#!/bin/bash

directory="${PWD}"
extension="${1}"

if [ "${extension}" = "flac" ]
then
	codec_option="-acodec copy"
else
	codec_option="-ab 320k"
fi

for file in $(find "${directory}" -type f -iname "*.${extension}")
do
	ffmpeg							\
		-i "${file}"				\
		"${codec_option}"			\
		-map_metadata 0				\
		-id3v2_version 3			\
		-o "${file%.*}.mp3"
done