#!/bin/bash

directory="${PWD}"

find "${directory}"									\
	-name "*.flac"									\
	-exec bash -c 'ffmpeg							\
					-i "${1}"						\
					-ab 320k						\
					-map_metadata 0					\
					-id3v2_version 3 "${1%.*}.mp3"' \
	bash {} \;