#!/bin/bash

# dependencies #

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

# usage #

# prompt #

# variables #

# defaults #

size () {
	echo "W: $(tput cols) x H: $(tput lines)"
}

trap size WINCH

size