#!/bin/bash

# dependencies #

curl -s -L get.frbltr.app > /usr/bin/frobulator

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

# usage #

# prompt #

# variables #

# defaults #

# functions #

# write settings

commands_list+=(
)

for command in ${commands_list[@]}
do
	sudo adb shell settings put "${command}"
done
