#!/bin/bash

# loaded by bash-functions from "${HOME}"/.local/bin - frobulator is already sourced there

# adb-set-environment ──────────────────────────────────────────────────────────

adb_set_environment () {

	if [[ $(command -v adb) ]]
	then
		export ANDROID_NO_USE_FWMARK=1

		if [ ! -d "${HOME}"/.adb ]
		then
			mkdir -p "${HOME}"/.adb
		fi

		export ADB_SERVER_SOCKET=localfilesystem:"${HOME}"/.adb/adb_server_socket
	fi
}
