#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# directory ────────────────────────────────────────────────────────────────────

directory () {

	frobulator.require mkdir

	mkdir -p "${1}"

	cd "${1}"
}
