#!/bin/bash

# loaded by bash-functions from "${HOME}"/.local/bin - frobulator is already sourced there

# adb-write ────────────────────────────────────────────────────────────────────

adb_write () {

	adb_download

	adb_set_environment

	hostname=$(adb ${device} shell getprop net.hostname)

	write_command"${@}"

	echo ${write_command@Q} | sed "s/ /%s/g" | xargs -0 adb "${device}" shell input text

	# enter

	adb_keycode 66

	# sleep for consecutive writes

	sleep 0.125
}
