#!/bin/bash

# loaded by bash-functions from "${HOME}"/.local/bin - frobulator is already sourced there

# adb-disable-phantom-killer ───────────────────────────────────────────────────

adb_disable_phantom_killer () {

	adb_download

	adb_set_environment

	adb	shell /system/bin/device_config set_sync_disabled_for_tests persistent
	adb shell /system/bin/device_config put activity_manager max_phantom_processes 2000000000
	adb shell /system/bin/settings get global device_config_sync_disabled
}
