#!/bin/bash

# logout ///////////////////////////////////////////////////////////////////////

if [ -n "${TERMUX_VERSION}" ]
then
	frobulator.fwd "Logging out..."
	echo

	frobulator.timeout
fi

# dextop ///////////////////////////////////////////////////////////////////////

if [ -n "${TERMUX_VERSION}" ]
then
	# automatic session stop

	if [[ $(cat "${HOME}"/.dextop/dextop-logout) = "logout" ]]
	then
		# audio

		if [[ $(pidof pulseaudio) ]]
		then
			pulseaudio --kill
		fi

		#framebuffer

		if [[ $(pidof Xvfb) ]]
		then
			container-session -x
		fi

		# vnc

		if [[ $(pidof x11vnc) ]]
		then
			container-session -x
		fi

		# x11

		if [[ $(pidof app_process / com.termux.x11.Loader) ]]
		then
			container-session -x
		fi

		if [[ $(pidof com.termux.x11) ]]
		then
			container-session -x
		fi
	fi
fi
