#!/bin/bash

# loaded by bash-functions from "${HOME}"/.local/bin - frobulator is already sourced there

# adb-settings-put ─────────────────────────────────────────────────────────────

adb_settings_put () {

	adb_download

	adb_set_environment

	setting="${1}"

	adb shell settings put "${setting}"
}
