#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# adb-remove-package ───────────────────────────────────────────────────────────

adb_remove_package () {

	local package

	adb_download

	adb_set_environment

	package="${1}"

	adb uninstall --user 0 "${package}"
}
