#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# list ─────────────────────────────────────────────────────────────────────────

list () {

	directory="${1}"

	if [ -z "${directory}" ]
	then
		directory="${PWD}"
	fi

	if [ ! -d "${directory}" ]
	then
		frobulator.err "Directory not found" "[ ${directory} ]"

		return 1
	fi

	ls								\
		-a							\
		-h							\
		-l							\
		--group-directories-first	\
									"${directory}"

	echo
	echo "$(find "${directory}" -type d | wc -l) directories"
	echo
	echo "$(find "${directory}" -type f | wc -l) files"
	echo
}
