#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# adb-write ────────────────────────────────────────────────────────────────────

adb_write () {

	adb_download

	adb_set_environment

	name_host=$(adb ${device} shell getprop net.name_host)

	text_write"${@}"

	echo ${text_write@Q} | sed "s/ /%s/g" | xargs -0 adb "${device}" shell input text

	# enter

	adb_keycode 66

	# sleep for consecutive writes

	sleep 0.125
}
