#!/bin/bash

# loaded by bash-functions from "${HOME}"/.local/bin - frobulator is already sourced there

# colors ───────────────────────────────────────────────────────────────────────

colors () {

	list=(
		tput
		printf
	)

	frobulator.require ${list[@]}

	list=()

	# print palette

	for foreground_color in {0..7}
	do
		set_foreground=$(tput setaf "${foreground_color}")

		for background_color in {0..7}
		do
			set_background=$(tput setab "${background_color}")

			echo -n "${set_background} ${set_foreground}"

			printf 'F:%s B:%s ' "${foreground_color}" "${background_color}"
		done

		# reset

		echo $(tput sgr0)
	done

	echo
}
