#!/bin/bash

# login ////////////////////////////////////////////////////////////////////////

if [ -n "${TERMUX_VERSION}" ]
then
	frobulator.fwd "Logging in..."
	echo
fi

# dextop ///////////////////////////////////////////////////////////////////////

if [ -n "${TERMUX_VERSION}" ]
then
	# session

	if [[ $(cat "${HOME}"/.dextop/dextop-environment) = xfce ]]
	then
		session_interface="XFCE"
	else
		session_interface="CONSOLE"
	fi

	if [ -f /etc/os-release ]
	then
		. /etc/os-release

		distribution_name="${NAME}"
	fi

	# settings

	if [ ! -f "${HOME}"/.dextop/dextop-settings-checkpoint ]
	then
		frobulator.fwd "Setting up..."
		echo

		dbus-launch "${HOME}"/.local/bin/container-settings

		frobulator.file "${HOME}"/.dextop dextop-settings-checkpoint

		frobulator.clear
	fi

	# update

	if [[ $(pidof proot) ]]
	then
		:
	else
		if [[ $(cat "${HOME}"/.dextop/dextop-update) = *update* ]]
		then
			if [[ $(cat "${HOME}"/.dextop/dextop-update) = *dextop* ]]
			then
				dextop -u dextop
			fi

			if [[ $(cat "${HOME}"/.dextop/dextop-update) = *shell* ]]
			then
				dextop -u shell
			fi

			if [[ $(cat "${HOME}"/.dextop/dextop-update) = *utility* ]]
			then
				dextop -u utility all
			fi

			if [[ $(cat "${HOME}"/.dextop/dextop-update) = *all* ]]
			then
				dextop -u all
			fi

			frobulator.clear
		fi
	fi

	# audio

	if [[ $(pidof proot) ]]
	then
		echo 'default-server = 127.0.0.1'   >  /etc/pulse/client.conf
		echo 'auto-connect-localhost = yes' >> /etc/pulse/client.conf
		echo 'autospawn = no'               >> /etc/pulse/client.conf
	else
		if [[ $(cat "${HOME}"/.dextop/dextop-audio) = "audio" ]]
		then
			if [[ $(command -v pulseaudio) ]]
			then
				if [[ $(pidof pulseaudio) ]]
				then
					:
				else
					# start pulseaudio and daemonize

					pulseaudio					\
						--start					\
						--daemonize=true		\
						--exit-idle-time=-1

					# initialize transmission control protocol

					pacmd								\
						load-module						\
							module-native-protocol-tcp	\
								auth-ip-acl=127.0.0.1	\
								auth-anonymous=1
				fi
			fi
		fi
	fi

	# automatic session start

	if [[ $(pidof x11vnc) ]]
	then
		:
	else
		if [[ $(cat "${HOME}"/.dextop/dextop-login) = "login" ]]
		then
			if [[ $(pidof proot) ]]
			then
				if [ -f "${HOME}"/.vnc/selection ]
				then
					echo $(cat "${HOME}"/.vnc/selection) | container-session -o
				else
					container-session -o
				fi
			else
				container-session -o

				termux_x11_activity="com.termux.x11/.MainActivity"

				display_activity="${termux_x11_activity}"

				# start termux:x11 intent

				unset intent_command

				intent_command+="am start"
				intent_command+=" --user 0"
				intent_command+=" -n ${display_activity}"

				frobulator.silence "${intent_command}"
			fi

		fi
	fi
fi
