#!/bin/bash

# loaded by bash-functions from "${HOME}"/.local/bin - frobulator is already sourced there

# duplicate ────────────────────────────────────────────────────────────────────

duplicate () {

	frobulator.require dd

	dd				\
		if="${1}"	\
		of="${2}"	\
		bs="${3}"	\
		status=progress
}
