#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [ -f "${HOME}"/.local/bin/frobulator ]
then
	rm -r -f "${HOME}"/.local/bin/frobulator
fi

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		SUDO_HOME=/root

		USER="${SUDO_USER}"

		HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${HOME}"/.local/bin ]
	then
		mkdir -p "${HOME}"/.local/bin
	fi

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${HOME}"/.local/bin/frobulator

# configuration ////////////////////////////////////////////////////////////////

if [ "${TERMUX_VERSION}" ]
then
	frobulator.fwd "Setting up..."
	echo
fi

# session //////////////////////////////////////////////////////////////////////

if [ -z "${PS1}" ]
then
	return
fi

# options //////////////////////////////////////////////////////////////////////

shopt -s checkwinsize
shopt -s histappend
shopt -s histverify

HISTCONTROL=ignoreboth
HISTSIZE=1000
HISTFILESIZE=2000

# completion ///////////////////////////////////////////////////////////////////

if [ ! $(shopt -oq posix) ]
then
	if [ -f "${PREFIX}"/share/bash-completion/bash_completion ]
	then
		. "${PREFIX}"/share/bash-completion/bash_completion

	elif [ -f /usr/share/bash-completion/bash_completion ]
	then
		. /usr/share/bash-completion/bash_completion

	elif [ -f /etc/bash_completion ]
	then
		. /etc/bash_completion
	fi
fi

# aliases //////////////////////////////////////////////////////////////////////

if [ -d "${HOME}"/.bash-aliases ]
then
	for alias in "${HOME}"/.bash-aliases/*
	do
		if [ -x "${alias}" ]
		then
			. "${alias}"
		fi
	done
fi

if [ -f "${HOME}"/.bash_aliases ]
then
	. "${HOME}"/.bash_aliases
fi

# functions ////////////////////////////////////////////////////////////////////

if [ -d "${HOME}"/.bash-functions ]
then
	for function in "${HOME}"/.bash-functions/*
	do
		if [ -x "${function}" ]
		then
			. "${function}"
		fi
	done
fi

if [ -f "${HOME}"/.bash_functions ]
then
	. "${HOME}"/.bash_functions
fi

# login ////////////////////////////////////////////////////////////////////////

if [ -f "${HOME}"/.bash_login ]
then
	. "${HOME}"/.bash_login
fi
