#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# record ───────────────────────────────────────────────────────────────────────

record () {

	list=(
		recordmydesktop
		wmctrl
	)

	(frobulator.require ${list[@]})

	list=()

	if [ -d "${HOME}"/Videos ]
	then
		directory_output="${HOME}"/Videos
	else
		directory_output="${HOME}"
	fi

	date_recording="$(date +"%m-%d-%Y-%H-%M-%S")"
	id_window="$(xwininfo | grep "Window id" | cut -d ' ' -f 4)"

	wmctrl		\
		-i		\
		-R		"${id_window}"

	frobulator.timeout 1

	recordmydesktop								\
		--no-cursor								\
		--no-wm-check							\
		--no-sound								\
		--overwrite								\
		--windowid "${id_window}"				\
		--output="${directory_output}"/clip-"${date_recording}".ogv
}
