#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# terminate ────────────────────────────────────────────────────────────────────

terminate () {

	process_name="${1}"

	if [[ $(command -v pgrep) ]] &&
	   [[ $(command -v pkill) ]]
	then
		while [[ $(pgrep -f "${process_name}") ]]
		do
			pkill -f "${process_name}"
		done
	fi
}
