#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# locate ───────────────────────────────────────────────────────────────────────

locate () {

	local command_find

	type_find="${1}"

	query="${2}"

	if [[ "${type_find}" =~ ^(d|dir|directory)$ ]]
	then
		type_find='d'

	elif [[ "${type_find}" =~ ^(f|file)$ ]]
	then
		type_find='f'
	else
		echo "unsupported type"
		echo

		return 1
	fi

	# 'find' path - empty if not installed

	command_find="$(command -v find)"

	if [ -n "${command_find}" ]
	then
		find								\
			"${PWD}"						\
				-type			"${type_find}"	\
				-iname 			"*${query}*"
	fi

}
