#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# when ─────────────────────────────────────────────────────────────────────────

when () {

	local time
	local date

	time=$(date '+%I:%M %p')
	date=$(date '+%A, %B %d %Y')

	echo

	echo "It is ${time} on ${date}"

	echo
}
