#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# adb-set-environment ──────────────────────────────────────────────────────────

adb_set_environment () {

	local command_adb

	# path of 'adb', empty when not installed

	command_adb="$(command -v adb)"

	if [ -n "${command_adb}" ]
	then
		export ANDROID_NO_USE_FWMARK=1

		if [ ! -d "${HOME}"/.adb ]
		then
			mkdir -p "${HOME}"/.adb
		fi

		export ADB_SERVER_SOCKET=localfilesystem:"${HOME}"/.adb/adb_server_socket
	fi
}
