#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# icons ────────────────────────────────────────────────────────────────────────

icons () {

	local list_directories_icons
	local directory_icons
	local directory_theme
	local name_theme

	frobulator.require gtk-update-icon-cache

	list_directories_icons=(
		"${HOME}"/.icons
		"${PREFIX}"/share/icons
		/usr/share/icons
	)

	for directory_icons in ${list_directories_icons[@]}
	do
		if [ -d "${directory_icons}" ]
		then
			cd "${directory_icons}"
		fi

		if [ -d "${directory_icons}" ]
		then
			find "${directory_icons}" -mindepth 1 -maxdepth 1 -type d | while read -r directory_theme
			do
				name_theme="${directory_theme##*/}"

				if [ -f "${directory_theme}"/index.theme ]
				then

					gtk-update-icon-cache -f -q "${directory_theme}"

					frobulator.scs "Cache update success" "[ ${name_theme} ]"
				else
					frobulator.wrn "Skipping" "[ ${name_theme} ]"
				fi
			done
		fi
	done
}
