#!/bin/bash

# dependencies ─────────────────────────────────────────────────────────────────

frobulator="${HOME}"/.local/bin/frobulator

source "${frobulator}"

# superuser ────────────────────────────────────────────────────────────────────

# script ───────────────────────────────────────────────────────────────────────

# version ──────────────────────────────────────────────────────────────────────

version="2026-09-20"

# defaults ─────────────────────────────────────────────────────────────────────

self="${BASH_SOURCE[0]}"

# usage ────────────────────────────────────────────────────────────────────────

# executed directly: install only

if [[ "${self}" = "${0}" ]]
then
	script="$(basename -- "${self}")"

	directory_install="${HOME}"/.local/bin

	while (($#))
	do
		case "${1}"
		in
			-i|--install)
				option="install"
			;;

			-h|--help)
				echo
				echo -e "Usage: ./${script} -i | -h"
				echo
				echo -e "Options:"
				echo
				echo -e "-i, --install    Run [i]nstallation of ${script} to ${directory_install}."
				echo
				echo -e "-h, --help       Show [h]elp and usage information."
				echo
				echo -e "'${script}'      [ Version // ${version} ]"
				echo

				exit
			;;

			"")
				# handle empty argument:
				# use default values specified in script

				:
			;;

			*)
				echo
				echo -e "Usage: ./${script} -i | -h"
				echo
				echo -e "Unknown option: '${script} ${1}':"
				echo -e "Type './${script} -h' for help and usage information."
				echo

				exit 1

			;;

			esac

		shift

	done

	# default to install

	if [ -z "${option}" ]
	then
		option="install"
	fi

	# install

	if [ "${option}" = "install" ]
	then
		file_script="$(realpath "${self}")"

		directory_script="$(dirname "${file_script}")"

		if [ "${directory_script}" -ef "${directory_install}" ]
		then
			frobulator.inf "Already installed" "[ ${directory_install}/${script} ]"
		else
			frobulator.copy "${directory_script}" "${directory_install}" "${script}"

			frobulator.permissions public execute "${directory_install}/${script}"

			frobulator.scs "Installed" "[ ${directory_install}/${script} ]"
		fi
	fi

	exit
fi

# adb ──────────────────────────────────────────────────────────────────────────

adb_download () {

	local directory_temporary
	local archive
	local path_extracted

	frobulator.temporary directory_temporary

	if [ -z "${directory_temporary}" ] || [ ! -d "${directory_temporary}" ]
	then
		frobulator.err "Unable to create temporary directory"

		exit 1
	fi

	archive="${directory_temporary}/platform-tools.zip"
	path_extracted="${directory_temporary}/platform-tools"

	frobulator.inf "Fetching latest" "[ Android Platform Tools ]"

	curl						\
		--silent				\
		--fail					\
		--location				\
		--output "${archive}"	\
								"${url_android_platform_tools}"

	if [ "${?}" -ne 0 ]
	then
		frobulator.delete "${directory_temporary}"

		frobulator.err "Unable to fetch" "[ Android Platform Tools ]"

		exit 1
	fi

	unzip -q "${archive}" -d "${directory_temporary}"

	if [ "${?}" -ne 0 ]
	then
		frobulator.delete "${directory_temporary}"

		frobulator.err "Unable to extract" "[ Android Platform Tools ]"

		exit 1
	fi

	if [ ! -x "${path_extracted}/adb" ] || [ ! -x "${path_extracted}/fastboot" ]
	then
		frobulator.delete "${directory_temporary}"

		frobulator.err "Invalid archive" "[ Android Platform Tools ]"

		exit 1
	fi

	frobulator.terminate "adb"

	frobulator.directory "${path_android}"

	frobulator.directory "${HOME}/.local/bin"

	frobulator.delete "${path_android_platform_tools}"

	mv "${path_extracted}" "${path_android_platform_tools}"

	list=(
		adb
		fastboot
	)

	for item in "${list[@]}"
	do
		frobulator.link "${path_android_platform_tools}" "${HOME}/.local/bin" "${item}"
	done

	list=()

	if [ "${USER}" != "root" ]
	then
		chown -R "${USER}:$(id -g "${USER}")" "${path_android}" "${HOME}/.local/bin/adb" "${HOME}/.local/bin/fastboot"
	fi

	frobulator.delete "${directory_temporary}"

	export PATH="${HOME}/.local/bin:${path_android_platform_tools}:${PATH}"

	hash -r

	frobulator.fwd "Utilities version: $(adb version | head -n 1)"

	frobulator.scs "Utilities deployment ready" "[ Android Platform Tools ]"

}

adb_set_environment () {

	if [[ $(command -v adb) ]]
	then
		export ANDROID_NO_USE_FWMARK=1

		if [ ! -d "${HOME}"/.adb ]
		then
			mkdir -p "${HOME}"/.adb
		fi

		export ADB_SERVER_SOCKET=localfilesystem:"${HOME}"/.adb/adb_server_socket
	fi
}

adb_screenshot () {

	adb_download

	adb_set_environment

	adb shell screencap -p /sdcard/"${screenshot}"

	adb pull /sdcard/"${screenshot}" screenshot/"${screenshot}"

	adb shell rm /sdcard/"${screenshot}"
}

adb_record () {

	adb_download

	adb_set_environment

	adb shell screenrecord /storage/emulated/0/Videos/"${recording}" &

	adb_record_PID=$!

	read -r -p 'Press enter to stop recording...'

	kill ${adb_record_PID} > "${sink}" 2>&1

	sleep 0.5

	adb pull /sdcard/"${recording}" screenrecord/"${recording}"

	adb shell rm /sdcard/"${recording}"
}

adb_pull_package () {

	adb_download

	adb_set_environment

	if [[ ! -d ./apk ]]
	then
		mkdir -p "${HOME}"/Android

		cd "${HOME}"/Android
	fi

	for package in $(adb shell pm list packages | sed -n 's/^package://p')
	do
		adb pull "$(adb shell pm path "${package}" | grep /data/app | sed -n "s/^package://p")"

		mv base.apk "${package}".apk
	done
}

adb_install_package () {

	adb_download

	adb_set_environment

	package="${1}"

	adb install "${package}"
}

adb_remove_package () {

	adb_download

	adb_set_environment

	package="${1}"

	adb uninstall --user 0 "${package}"
}

adb_settings_get () {

	adb_download

	adb_set_environment

	setting="${1}"

	adb shell settings get "${setting}"
}

adb_settings_put () {

	adb_download

	adb_set_environment

	setting="${1}"

	adb shell settings put "${setting}"
}

adb_disable_phantom_killer () {

	adb_download

	adb_set_environment

	adb	shell /system/bin/device_config set_sync_disabled_for_tests persistent
	adb shell /system/bin/device_config put activity_manager max_phantom_processes 2000000000
	adb shell /system/bin/settings get global device_config_sync_disabled
}

adb_vendor_ids () {

	adb_download

	adb_set_environment

	mkdir -p "${HOME}"/.android

	for id in {0..65535}
	do
		printf '0x%04x\n' "${id}"
	done >> "{HOME}"/.android/adb_usb.ini

	chmod -R 777 "${HOME}"/.android

	if [[ $(dpkg -l udev) ]]
	then
		while read -r vendor_id
		do
			echo SUBSYSTEM==\"usb\", SYSFS{idVendor}==\""${vendor_id:2}"\", MODE=\"0666\" \;

		done <<< $(cat "${HOME}"/.android/adb_usb.ini) >> /etc/udev/rules.d/51-android.rules
	fi
}

adb_keycode () {

	adb_download

	adb_set_environment

	adb "${device}" shell input keyevent "${1}"

	# https://developer.android.com/reference/android/view/KeyEvent.html

	#  0 - KEYCODE_0              # 49 - KEYCODE_U
	#  1 - KEYCODE_SOFT_LEFT      # 50 - KEYCODE_V
	#  2 - KEYCODE_SOFT_RIGHT     # 51 - KEYCODE_W
	#  3 - KEYCODE_HOME           # 52 - KEYCODE_X
	#  4 - KEYCODE_BACK           # 53 - KEYCODE_Y
	#  5 - KEYCODE_CALL           # 54 - KEYCODE_Z
	#  6 - KEYCODE_ENDCALL        # 55 - KEYCODE_COMMA
	#  7 - KEYCODE_0              # 56 - KEYCODE_PERIOD
	#  8 - KEYCODE_1              # 57 - KEYCODE_ALT_LEFT
	#  9 - KEYCODE_2              # 58 - KEYCODE_ALT_RIGHT
	# 10 - KEYCODE_3              # 59 - KEYCODE_SHIFT_LEFT
	# 11 - KEYCODE_4              # 60 - KEYCODE_SHIFT_RIGHT
	# 12 - KEYCODE_5              # 61 - KEYCODE_TAB
	# 13 - KEYCODE_6              # 62 - KEYCODE_SPACE
	# 14 - KEYCODE_7              # 63 - KEYCODE_SYM
	# 15 - KEYCODE_8              # 64 - KEYCODE_EXPLORER
	# 16 - KEYCODE_9              # 65 - KEYCODE_ENVELOPE
	# 17 - KEYCODE_STAR           # 66 - KEYCODE_ENTER
	# 18 - KEYCODE_POUND          # 67 - KEYCODE_DEL
	# 19 - KEYCODE_DPAD_UP        # 68 - KEYCODE_GRAVE
	# 20 - KEYCODE_DPAD_DOWN      # 69 - KEYCODE_MINUS
	# 21 - KEYCODE_DPAD_LEFT      # 70 - KEYCODE_EQUALS
	# 22 - KEYCODE_DPAD_RIGHT     # 71 - KEYCODE_LEFT_BRACKET
	# 23 - KEYCODE_DPAD_CENTER    # 72 - KEYCODE_RIGHT_BRACKET
	# 24 - KEYCODE_VOLUME_UP      # 73 - KEYCODE_BACKSLASH
	# 25 - KEYCODE_VOLUME_DOWN    # 74 - KEYCODE_SEMICOLON
	# 26 - KEYCODE_POWER          # 75 - KEYCODE_APOSTROPHE
	# 27 - KEYCODE_CAMERA         # 76 - KEYCODE_SLASH
	# 28 - KEYCODE_CLEAR          # 77 - KEYCODE_AT
	# 29 - KEYCODE_A              # 78 - KEYCODE_NUM
	# 30 - KEYCODE_B              # 79 - KEYCODE_HEADSETHOOK
	# 31 - KEYCODE_C              # 80 - KEYCODE_FOCUS
	# 32 - KEYCODE_D              # 81 - KEYCODE_PLUS
	# 33 - KEYCODE_E              # 82 - KEYCODE_MENU
	# 34 - KEYCODE_F              # 83 - KEYCODE_NOTIFICATION
	# 35 - KEYCODE_G              # 84 - KEYCODE_SEARCH
	# 36 - KEYCODE_H              # 85 - KEYCODE_MEDIA_PLAY_PAUSE
	# 37 - KEYCODE_I              # 86 - KEYCODE_MEDIA_STOP
	# 38 - KEYCODE_J              # 87 - KEYCODE_MEDIA_NEXT
	# 39 - KEYCODE_K              # 88 - KEYCODE_MEDIA_PREVIOUS
	# 40 - KEYCODE_L              # 89 - KEYCODE_MEDIA_REWIND
	# 41 - KEYCODE_M              # 90 - KEYCODE_MEDIA_FAST_FORWARD
	# 42 - KEYCODE_N              # 91 - KEYCODE_MUTE
	# 43 - KEYCODE_O              # 92 - KEYCODE_PAGE_UP
	# 44 - KEYCODE_P              # 93 - KEYCODE_PAGE_DOWN
	# 45 - KEYCODE_Q              # 94 - KEYCODE_PICTSYMBOLS
	# 46 - KEYCODE_R              # [ ... ]
	# 47 - KEYCODE_S              # 122  KEYCODE_MOVE_HOME
	# 48 - KEYCODE_T              # 123  KEYCODE_MOVE_END
}

adb_device () {

	adb_download

	adb_set_environment

	if [ $# -gt 1 ]
	then
		device="-s ${@:2}"

		adb connect ${@:2}

		sleep 2
	fi
}

adb_write () {

	adb_download

	adb_set_environment

	hostname=$(adb ${device} shell getprop net.hostname)

	write_command"${@}"

	echo ${write_command@Q} | sed "s/ /%s/g" | xargs -0 adb "${device}" shell input text

	# enter

	adb_keycode 66

	# sleep for consecutive writes

	sleep 0.125
}

adb_reset_apk () {

	adb_download

	adb_set_environment

	application="${1}"
	activity="${2}"

	adb "${device}" shell	\
		pm clear "${application}"

	adb "${device}" shell	\
		am start			\
			--user 0		\
			-n "${application}"/"${application}"."${activity}"
}

# address ──────────────────────────────────────────────────────────────────────

address () {

	frobulator.require curl

	url="ipinfo.io/ip"

	echo

	curl			\
		--silent	\
		--location	"${url}"

	echo

	unset url
}

# audio ────────────────────────────────────────────────────────────────────────

audio () {

	frobulator.require ffmpeg

	directory="${PWD}"
	extension="${1}"

	found=0

	# default conversion command

	convert_command () {

		ffmpeg					\
			-y					\
			-i "${file}"		\
			-f mp3				\
			-map_metadata 0		\
			-id3v2_version 3	"${file%.*}.mp3"
	}

	if [ "${extension}" = "flac" ]
	then
		# override for flac files with bitrate

		convert_command () {

			ffmpeg					\
				-y					\
				-i "${file}"		\
				-b:a 320k			\
				-map_metadata 0		\
				-id3v2_version 3	"${file%.*}.mp3"
		}
	fi

	# loop over all files

	for file in *
	do
		case "${file}" in
			*."${extension}")

				found=1

				convert_command

				rm					\
					--recursive		\
					--force			 "${file}"
				;;
		esac
	done

	# handle case where no matching files were found

	if [ "${found}" -eq 0 ]
	then
		frobulator.err "No files to convert with specified extension" "[ '${extension}' ]"

		return 1
	fi
}

play () {

	if [ -z "$(command -v mpv)" ]
	then
		frobulator.require mpv
	fi

	before="[${marker_spc}"
	after="${marker_spc}]"

	action="Playing"

	file="${1}"

	if [ $# -eq 2 ]
	then
		action="${1}"

		file="${2}"
	fi

	title="${file##*/}"


	# frobulator.pmt "${@}"

	# substitute standard input for function specific criteria:
	# [ ... ] action ───────────────────────────────────────────...─── [ title ]

	frobulator.pmt "${action}" "${title}"

	prompt="${prompt_string[@]}"

	ticker=(
		".  "
		".. "
		"..."
		" .."
		"  ."
		"   "
	)

	instance=0

	mpv					\
		--no-video		\
		--really-quiet	\
						"${file}" < "${sink}" > "${sink}" 2>&1 &

	PID=$!

	while [ -d /proc/"${PID}" ]
	do
		ticker_frame="${ticker[instance++%${#ticker[@]}]}"

		echo -n -e "\r${before}${ticker_frame}${after}${reset}${marker_spc}${prompt}\c"

		sleep 0.25
	done
}

# colors ───────────────────────────────────────────────────────────────────────

colors () {

	list=(
		tput
		printf
	)

	frobulator.require ${list[@]}

	list=()

	# print palette

	for foreground_color in {0..7}
	do
		set_foreground=$(tput setaf "${foreground_color}")

		for background_color in {0..7}
		do
			set_background=$(tput setab "${background_color}")

			echo -n "${set_background} ${set_foreground}"

			printf 'F:%s B:%s ' "${foreground_color}" "${background_color}"
		done

		# reset

		echo $(tput sgr0)
	done

	echo
}

hex () {

	# set IFS

	IFS=' '

	read r g b <<< "${@}"

	printf '%02x%02x%02x\n' ${r} ${g} ${b}

	# unset IFS

	IFS=''
}

rgb () {

	frobulator.require printf

	read hex <<< "${1}"

	[[ ${hex:0:1} = "#" ]] && hex=${hex:1:6}

	r=$((16#${hex:0:2}))
	g=$((16#${hex:2:2}))
	b=$((16#${hex:4:2}))

	printf '%03d %03d %03d\n' ${r} ${g} ${b}
}

# directory ────────────────────────────────────────────────────────────────────

directory () {

	frobulator.require mkdir

	mkdir -p "${1}"

	cd "${1}"
}

# duplicate ────────────────────────────────────────────────────────────────────

duplicate () {

	frobulator.require dd

	dd				\
		if="${1}"	\
		of="${2}"	\
		bs="${3}"	\
		status=progress
}

# extract ──────────────────────────────────────────────────────────────────────

extract () {

	list+=(
		7zip
		bunzip2
		gunzip
		tar
		unrar
		unzip
	)

	frobulator.require ${list[@]}

	# unset array

	list=()

	file="${1}"
	directory="${2}"
	extension="${3}"

	archive="${file##*/}"

	if [ -z "${directory}" ]
	then
		directory="${PWD}"
	fi

	if [ -z "${extension}" ]
	then
		extension="${file##*.}"
	fi

	if [ ! -d "${directory}" ]
	then
		mkdir -p "${directory}"
	fi

	case "${extension}"
	in
		tar.bz2|tbz2)
			tar								\
				--extract					\
				--bzip2						\
				--file="${file}" 			\
				--directory="${directory}"

				frobulator.inf "Extracting" "[ ${archive} ]"
		;;

		tar.gz|tgz)
			tar								\
				--extract					\
				--gzip						\
				--file="${file}" 			\
				--directory="${directory}"

				frobulator.inf "Extracting" "[ ${archive} ]"
		;;

		tar)
			tar								\
				--extract					\
				--file="${file}" 			\
				--directory="${directory}"

				frobulator.inf "Extracting" "[ ${archive} ]"

		;;

		7z)
			7z								\
				x "${file}" 				\
				-o							"${directory}"

				frobulator.inf "Extracting" "[ ${archive} ]"
		;;

		rar)
			unrar e "${file}" "${directory}"

				frobulator.inf "Extracting" "[ ${archive} ]"
		;;

		zip)
			unzip							\
				-o							\
				-qq "${file}"				\
				-d							"${directory}"

				frobulator.inf "Extracting" "[ ${archive} ]"
		;;

		*)
			frobulator.err "Unsupported archive type" "[ '${archive}' ]"

			exit 1
		;;

	esac
}

# icons ────────────────────────────────────────────────────────────────────────

icons () {

	frobulator.require gtk-update-icon-cache

	icons_directory_list=(
		"${HOME}"/.icons
		"${PREFIX}"/share/icons
		/usr/share/icons
	)

	for icons_directory in ${icons_directory_list[@]}
	do
		if [ -d "${icons_directory}" ]
		then
			cd "${icons_directory}"
		fi

		if [ -d "${icons_directory}" ]
		then
			find "${icons_directory}" -mindepth 1 -maxdepth 1 -type d | while read -r theme
			do
				if [ -f "${theme}"/index.theme ]
				then
					theme_name="${theme##*/}"

					gtk-update-icon-cache -f -q "${theme}"

					frobulator.scs "Cache update success" "[ ${theme_name} ]"
				else
					frobulator.wrn "Skipping" "[ ${theme_name} ]"
				fi
			done
		fi
	done
}

# inkscape ─────────────────────────────────────────────────────────────────────

vector-export () {

	frobulator.require inkscape

	export_type="${1}"

	if [ -z "${export_type}" ]
	then
		export_type="png"
	fi

	for file in *.svg
	do
		if [ -f "${file}" ]
		then
			file_name="${file%.*}"

			inkscape "${file}"						\
				--batch-process						\
				--export-width=4096					\
				--export-area-page					\
				--export-type="${export_type}"		\
				--export-filename="${file_name}"."${export_type}"
		fi
	done
}

# preview ──────────────────────────────────────────────────────────────────────

preview () {

	count="${1}"

	file="${2}"

	if [[ $(command -v cat) ]] &&
	   [[ $(command -v head) ]]
	then
		frobulator.inf "Previewing file" "[ ${count} lines // ${file} ]"

		frobulator.separate

		cat "${file}" | head -n "${count}"

		echo

		frobulator.separate

	fi
}

# record ───────────────────────────────────────────────────────────────────────

record () {

	list=(
		recordmydesktop
		wmctrl
	)

	(frobulator.require ${list[@]})

	list=()

	if [ -f "${HOME}"/Videos ]
	then
		path="${HOME}"/Videos
	else
		path="${HOME}"
	fi

	stamp="$(date +"%m-%d-%Y-%H-%M-%S")"
	window_id="$(xwininfo | grep "Window id" | cut -d ' ' -f 4)"

	wmctrl		\
		-i		\
		-R		"${window_id}"

	frobulator.wait 1

	recordmydesktop								\
		--no-cursor								\
		--no-wm-check							\
		--no-sound								\
		--overwrite								\
		--windowid "${window_id}"				\
		--output="${path}"/clip-"${stamp}".ogv
}

# list ─────────────────────────────────────────────────────────────────────────

list () {

	directory="${1}"

	if [ -z "${directory}" ]
	then
		directory="${PWD}"
	fi

	if [ ! -d "${directory}" ]
	then
		frobulator.err "Directory not found" "[ ${directory} ]"

		return 1
	fi

	ls								\
		-a							\
		-h							\
		-l							\
		--group-directories-first	\
									"${directory}"

	echo
	echo "$(find "${directory}" -type d | wc -l) directories"
	echo
	echo "$(find "${directory}" -type f | wc -l) files"
	echo
}

# size ─────────────────────────────────────────────────────────────────────────

dimensions () {

	columns=$(tput cols)
	lines=$(tput lines)

	echo "Terminal size:"
	echo "W: ${columns} x H: ${lines}"
}

# snippet ──────────────────────────────────────────────────────────────────────

snippet () {

	url="http://sprunge.us"

	if (($#))
	then
		curl -F 'sprunge=<-' "${url}" < "${1}"
	else
		curl -F 'sprunge=<-' "${url}"
	fi
}

# terminate ────────────────────────────────────────────────────────────────────

terminate () {

	process_name="${1}"

	if [[ $(command -v pgrep) ]] &&
	   [[ $(command -v pkill) ]]
	then
		while [[ $(pgrep -f "${process_name}") ]]
		do
			pkill -f "${process_name}"
		done
	fi
}

# weather ──────────────────────────────────────────────────────────────────────

weather () {

	url="wttr.in"

	echo

	curl -s "${url}" | head -n -2

	echo

	unset url

}

# media ────────────────────────────────────────────────────────────────────────

media () {

	local type="${1}"
	local source="${2}"
	local path="${3}"
	local directory_binary="${HOME}/.local/bin"
	local archive
	local file
	local files
	local directory
	local name_source
	local name_target
	local browser
	local duration_sleep
	local format
	local format_media
	local -a options_type=()
	local -a options_url=()
	local -a options_site=()

	if [ -z "${type}" ]
	then
		frobulator.err "No type specified" "[ audio | video ]"

		return 1
	fi

	if [ "${type}" != "audio" ] && [ "${type}" != "video" ]
	then
		frobulator.err "Invalid type" "[ ${type} ]"

		return 1
	fi

	if [ -z "${source}" ]
	then
		frobulator.err "No source specified"

		return 1
	fi

	if [ -z "${path}" ]
	then
		path="${PWD}"
	fi

	if [ ! -d "${path}" ]
	then
		path="${PWD}"
	fi

	if [ ! -f "${directory_binary}/yt-dlp" ]
	then
		frobulator.download "https://github.com/yt-dlp/yt-dlp/releases/latest/download" "${directory_binary}" "yt-dlp"
	else
		frobulator.silence "${directory_binary}/yt-dlp --update"
	fi

	if [ ! -x "${directory_binary}/yt-dlp" ]
	then
		frobulator.err "Downloader unavailable" "[ yt-dlp ]"

		return 1
	fi

	if [ ! -f "${directory_binary}/deno" ]
	then
		archive="deno-x86_64-unknown-linux-gnu.zip"

		frobulator.download "https://github.com/denoland/deno/releases/latest/download" "${directory_binary}" "${archive}"

		unzip -o -q "${directory_binary}/${archive}" -d "${directory_binary}"

		rm -f "${directory_binary}/${archive}"

		chmod +x "${directory_binary}/deno"
	else
		frobulator.silence "${directory_binary}/deno upgrade"
	fi

	if [ ! -x "${directory_binary}/deno" ]
	then
		frobulator.err "Solver unavailable" "[ deno ]"

		return 1
	fi

	if [ "${type}" = "audio" ]
	then
		format="bestaudio"
		format_media="mp3"

		options_type+=( --extract-audio )
		options_type+=( --audio-format "${format_media}" )
		options_type+=( --audio-quality best )
		options_type+=( --output '%(uploader)s - %(title)s.%(ext)s' )

	elif [ "${type}" = "video" ]
	then
		format="bestvideo+bestaudio"
		format_media="mp4"

		options_type+=( --merge-output-format "${format_media}" )
		options_type+=( --output '%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s' )
	fi

	if [ -f "${source}" ]
	then
		options_url+=( --batch-file )
	fi

	if [ "${source#*soundcloud.com}" = "${source}" ]
	then
		browser="$(xdg-settings get default-web-browser 2>"${sink}")"

		browser="${browser%.desktop}"

		if [[ "${browser}" = firefox* ]] ||
		[[ "${browser}" = librewolf*  ]] ||
		[[ "${browser}" = waterfox*   ]]
		then
			browser="firefox"

		elif [[ "${browser}" = chrome*       ]] ||
			[[ "${browser}" = google-chrome* ]] ||
			[[ "${browser}" = chromium*      ]] ||
			[[ "${browser}" = brave*         ]] ||
			[[ "${browser}" = vivaldi*       ]] ||
			[[ "${browser}" = opera*         ]]
		then
			browser="chrome"

		else
			frobulator.err "No compatible browser found on system"

			return 1
		fi

		options_site+=( --cookies-from-browser "${browser}" )
	fi

	cd "${path}"

	duration_sleep=$(( RANDOM % 5 + 1 ))

	"${directory_binary}/yt-dlp"									\
		--remote-components		"ejs:github"				\
		--js-runtimes			"deno:${directory_binary}/deno"	\
		--ffmpeg-location		"/usr/bin/ffmpeg"			\
		--quiet												\
		--no-update											\
		--ignore-errors										\
		--no-overwrites										\
		--sleep-requests		"${duration_sleep}"			\
		--yes-playlist										\
		--format				"${format}"					\
		"${options_site[@]}"								\
		"${options_type[@]}"								\
		"${options_url[@]}"									\
		"${source}" &

	frobulator.progress download

	files="$(find "${PWD}" -type f -iname "*.${format_media}")"

	IFS=$'\n'

	for file in ${files}
	do
		directory="${file%/*}"
		name_source="${file##*/}"

		name_target="${name_source// - Topic/}"

		if [ "${name_source}" != "${name_target}" ]
		then
			mv -- "${file}" "${directory}/${name_target}"
		fi
	done

	unset IFS
}

# find ─────────────────────────────────────────────────────────────────────────

locate () {

	type="${1}"

	query="${2}"

	if [[ "${type}" =~ ^(d|dir|directory)$ ]]
	then
		type='d'

	elif [[ "${type}" =~ ^(f|file)$ ]]
	then
		type='f'
	else
		echo "unsupported type"
		echo

		exit 1
	fi

	if [[ $(command -v find) ]]
	then
		find								\
			"${PWD}"						\
				-type			"${type}"	\
				-iname 			"*${query}*"
	fi

}

# secure shell ─────────────────────────────────────────────────────────────────

ssh () {

	# destination is always the last argument

	destination=${!#}

	echo -n -e "[  $(tput setaf 3)${destination}$(tput sgr 0)  ] >_ ? "

	read -r -s password

	echo

	sshpass					\
		-p "${password}"	\
							ssh -X "${@}"

	unset destination

	unset password

}

ssh-check () {

timeout="0.5"

lan="${1}"

if [ -z "${lan}" ]
then
    echo "Usage: ${0} <LAN_PREFIX> (e.g., ${0} 192.168.0 or 192.168.0.1)"
    echo

    exit 1
fi

# extract the first 3 octets from user input:
# sanitize to nnn.nnn.nnn.

lan=$(
		echo "${lan}" | grep -oE '^([0-9]{1,3}\.){2}[0-9]{1,3}' | awk -F. '{print $1"."$2"."$3"."}'
	)

	for i in {1..255}
	do
		ip="${lan}${i}"

		timeout "${timeout}" "${SHELL}" -c "echo > /dev/tcp/${ip}/22" 2> "${sink}"

		if [ ${?} -eq 0 ]
		then
			frobulator.scs "SSH open" "[ ${ip} ]"
		else
			frobulator.err "${ip}" &
		fi

	done | grep "open"

}

# music mirror ─────────────────────────────────────────────────────────────────

music-mirror () {

	# mirror external drive music to the phone, folder by folder, for the folders the phone keeps:
	# a folder's subfolders on the phone are each mirrored, or the folder itself when it has none
	# usage: music-mirror [utility-add-remove options: -e execute, -y skip confirmation]
	# without options every folder is a dry run

	local music_external="/media/${USER}/external/Music"
	local music_phone
	local music_utility
	local music_candidate
	local music_folder
	local music_subfolder
	local music_subfolders=()
	local music_relative
	local music_list=()
	local music_options=("${@}")

	# phone storage mounted by kde connect

	for music_candidate in /run/user/"$(id -u)"/*/storage/emulated/0/Music
	do
		if [ -d "${music_candidate}" ]
		then
			music_phone="${music_candidate}"

			break
		fi
	done

	if [ -z "${music_phone}" ]
	then
		frobulator.err "Phone music folder not mounted" "[ kde connect ]"
		frobulator.nul "Open the phone in dolphin or browse it through kde connect first."

		return 1
	fi

	if [ ! -d "${music_external}" ]
	then
		frobulator.err "External music folder not found" "[ ${music_external} ]"

		return 1
	fi

	music_utility="$(command -v utility-add-remove)"

	if [ -z "${music_utility}" ]
	then
		frobulator.download get.trmnl.me "${HOME}/.local/bin" utility-add-remove || return

		music_utility="${HOME}/.local/bin/utility-add-remove"
	fi

	# folder list: subfolders kept on the phone or the folder itself when it has none

	for music_folder in "${music_phone}"/*/
	do
		music_subfolders=("${music_folder}"*/)

		if [ -d "${music_subfolders[0]}" ]
		then
			for music_subfolder in "${music_subfolders[@]}"
			do
				music_list+=("$(basename -- "${music_folder}")/$(basename -- "${music_subfolder}")")
			done
		else
			music_list+=("$(basename -- "${music_folder}")")
		fi
	done

	# each folder mirrored on its own from the external drive

	for music_relative in "${music_list[@]}"
	do
		if [ ! -d "${music_external}/${music_relative}" ]
		then
			frobulator.wrn "Skipped - not on external drive" "[ '${music_relative}' ]"

			continue
		fi

		frobulator.fwd "Mirroring" "[ '${music_relative}' ]"

		bash "${music_utility}" -f "${music_external}/${music_relative}" -t "${music_phone}/${music_relative}" -m "${music_options[@]}"
	done
}

# audio control ────────────────────────────────────────────────────────────────

audio_combine_connect () {

	# connect a bluetooth device unless already connected - wait for each attempt:
	# speakers often answer only after a few page timeouts

	local bluetooth_address="${1}"
	local connect_attempt
	local connect_second

	for connect_attempt in {1..6}
	do
		if [[ "$(bluetoothctl info "${bluetooth_address}" 2> "${sink}")" = *"Connected: yes"* ]]
		then
			return 0
		fi

		bluetoothctl connect "${bluetooth_address}" > "${sink}" 2>&1

		for connect_second in {1..10}
		do
			if [[ "$(bluetoothctl info "${bluetooth_address}" 2> "${sink}")" = *"Connected: yes"* ]]
			then
				return 0
			fi

			sleep 1
		done
	done

	return 1
}

audio_combine_sink_wait () {

	# wait for a sink to appear

	local sink_name="${1}"
	local sink_timeout="${2:-15}"
	local sink_second

	for (( sink_second=0 ; sink_second<sink_timeout ; sink_second++ ))
	do
		if [[ "$(pactl list short sinks)" = *"	${sink_name}	"* ]]
		then
			return 0
		fi

		sleep 1
	done

	return 1
}

audio_combine_outputs () {

	# number of outputs the combined sink currently plays to

	local sink_input_line
	local sink_input_count=0

	while IFS= read -r sink_input_line
	do
		if [[ "${sink_input_line}" = *module-combine-sink* ]]
		then
			sink_input_count=$(( sink_input_count + 1 ))
		fi
	done < <(pactl list short sink-inputs)

	echo "${sink_input_count}"
}

audio_combine_load () {

	# (re)create the combined sink, make it default and move playing streams to it

	local sink_combined="${1}"
	local sink_slaves=("${@:2}")
	local sink_slave
	local sink_input_index
	local sink_input_sink
	local sink_input_client
	local sink_input_driver
	local slaves_joined

	audio_combine_unload "${sink_combined}"

	slaves_joined="${sink_slaves[*]}"

	# adjust_time=0: no rate adjustment timer - pulseaudio 16.1 aborts in its callback
	# ('u->time_event == e' in module-combine-sink time_callback), dropping both speakers

	pactl load-module module-combine-sink sink_name="${sink_combined}" slaves="${slaves_joined// /,}" adjust_time=0 > "${sink}" || return

	pactl set-default-sink "${sink_combined}"

	while IFS=$'\t' read -r sink_input_index sink_input_sink sink_input_client sink_input_driver
	do
		if [[ "${sink_input_driver}" != module-combine-sink* ]]
		then
			pactl move-sink-input "${sink_input_index}" "${sink_combined}" 2> "${sink}"
		fi
	done < <(pactl list short sink-inputs)

	for sink_slave in "${sink_slaves[@]}"
	do
		pactl set-sink-volume "${sink_slave}" 100%
	done

	pactl set-sink-volume "${sink_combined}" 75%
}

audio_combine_watch () {

	# background watcher: reconnect dropped speakers, rebuild the combined sink when they return

	local file_watch_pid="${1}"
	local sink_combined="${2}"
	local bluetooth_addresses=(${3})
	local sink_slaves=("${@:4}")

	(
		pactl subscribe | while IFS= read -r audio_event
		do
			if [[ "${audio_event}" = *"'remove' on sink"* ]]
			then
				# bluetooth still reports the device connected while it drops

				sleep 5

				for bluetooth_address in "${bluetooth_addresses[@]}"
				do
					audio_combine_connect "${bluetooth_address}" &
				done

			elif [[ "${audio_event}" = *"'new' on sink"* ]]
			then
				sleep 2

				sink_list="$(pactl list short sinks)"

				for sink_slave in "${sink_slaves[@]}"
				do
					if [[ "${sink_list}" != *"	${sink_slave}	"* ]]
					then
						continue 2
					fi
				done

				if [ "$(audio_combine_outputs)" -lt "${#sink_slaves[@]}" ]
				then
					audio_combine_load "${sink_combined}" "${sink_slaves[@]}"
				fi
			fi
		done
	) > "${sink}" 2>&1 &

	echo "${!}" > "${file_watch_pid}"

	disown
}

audio_combine_watch_stop () {

	# stop the background watcher

	local file_watch_pid="${1}"

	if [ -f "${file_watch_pid}" ]
	then
		pkill -P "$(< "${file_watch_pid}")" 2> "${sink}"
		kill "$(< "${file_watch_pid}")" 2> "${sink}"

		rm -f "${file_watch_pid}"
	fi
}

audio_combine_unload () {

	# remove the combined sink

	local sink_combined="${1}"
	local module_index
	local module_line

	while IFS=$'\t' read -r module_index module_line
	do
		if [[ "${module_line}" = module-combine-sink*"sink_name=${sink_combined}"* ]]
		then
			pactl unload-module "${module_index}"
		fi
	done < <(pactl list short modules)
}

audio-combine () {

	# combine two bluetooth speakers into one output, kept alive across dropouts
	# usage: audio-combine [stop]

	local sink_combined="bluez_sink_combined"
	local bluetooth_addresses=(
		"FC:E8:06:19:8E:9C"
		"FC:E8:06:19:77:00"
	)
	local bluetooth_address
	local sink_slaves=()
	local sink_slave
	local file_watch_pid="${XDG_RUNTIME_DIR:-/tmp}/audio-combine.pid"

	for bluetooth_address in "${bluetooth_addresses[@]}"
	do
		sink_slaves+=("bluez_sink.${bluetooth_address//:/_}.a2dp_sink")
	done

	if [ "${1}" = "stop" ]
	then
		audio_combine_watch_stop "${file_watch_pid}"
		audio_combine_unload "${sink_combined}"

		frobulator.inf "Combined audio stopped" "[ ${sink_combined} ]"

		return 0
	fi

	# connect bluetooth devices

	for bluetooth_address in "${bluetooth_addresses[@]}"
	do
		if ! audio_combine_connect "${bluetooth_address}"
		then
			frobulator.err "Unable to connect" "[ ${bluetooth_address} ]"
			frobulator.nul "Make sure the device is powered on, paired and trusted."

			return 1
		fi
	done

	for sink_slave in "${sink_slaves[@]}"
	do
		if ! audio_combine_sink_wait "${sink_slave}" 15
		then
			frobulator.err "Sink not found after connecting" "[ ${sink_slave} ]"
			frobulator.nul "Run 'pactl list short sinks' for details."

			return 1
		fi
	done

	audio_combine_load "${sink_combined}" "${sink_slaves[@]}" || return

	# one watcher at a time

	audio_combine_watch_stop "${file_watch_pid}"

	audio_combine_watch "${file_watch_pid}" "${sink_combined}" "${bluetooth_addresses[*]}" "${sink_slaves[@]}"

	frobulator.scs "Combined audio active" "[ ${sink_combined} ]"
}

# identification ───────────────────────────────────────────────────────────────

who () {

	echo

	echo "Current user: ${USER}"

	echo

}

where () {

	echo

	echo "You are in ${PWD}"

	echo

}

when () {

	time=$(date '+%I:%M %p')
	date=$(date '+%A, %B %d %Y')

	echo

	echo "It is ${time} on ${date}"

	echo
}

# commands ─────────────────────────────────────────────────────────────────────

pipx () {

	command pipx --global "$@"

}

countd () {

	echo "$(find "${PWD}" -maxdepth 1 -type d | wc -l) directories under ${PWD}"

}

countf () {

	echo "$(find . -type f | wc -l) files under ${PWD}"

}

# system ───────────────────────────────────────────────────────────────────────

temperature () {

	if [[ -d /sys/class/thermal ]]
	then
		acpitz_count=0
		cpu_label=""
		cpu_degrees=""
		lines=()
		max_length=0

		for zone in /sys/class/thermal/thermal_zone*
		do
			label=$(cat "${zone}"/type)

			if [ "${label}" = "acpitz" ]
			then
				acpitz_count=$(( acpitz_count + 1 ))

				label="System ${acpitz_count}"

			elif [[ "${label}" = pch_* ]]
			then
				label="Chipset"

			elif [[ "${label}" = iwlwifi_* ]]
			then
				label="WiFi"

			elif [ "${label}" = "x86_pkg_temp" ]
			then
				label="CPU"

			else
				label="${label//_/ }"
			fi

			degrees=$(cat "${zone}"/temp)
			degrees=$(( degrees / 1000 ))

			if [ "${#label}" -gt "${max_length}" ]
			then
				max_length="${#label}"
			fi

			if [ "${label}" = "CPU" ]
			then
				cpu_label="${label}"
				cpu_degrees="${degrees}"
			else
				lines+=("${label}|${degrees}")
			fi
		done

		pad=$(( max_length + 4 ))

		if [ -n "${cpu_label}" ]
		then
			printf "%-${pad}s%s°C\n" "${cpu_label}:" "${cpu_degrees}"
		fi

		printf '%s\n' "${lines[@]}" | sort |
		while IFS='|' read -r label degrees
		do
			printf "%-${pad}s%s°C\n" "${label}:" "${degrees}"
		done

		unset acpitz_count cpu_label cpu_degrees lines max_length pad
	fi

}

# llm ──────────────────────────────────────────────────────────────────────────

clo () {

	local command

	command="claude"

	if [[ -z $(command -v "${command}") ]]
	then
		frobulator.err "Command not found" "[ ${command} ]"

		return 1
	fi

	directory_projects="${HOME}/.${command}/projects"

	if [ ! -d "${directory_projects}" ]
	then
		frobulator.wrn "No session history found."

		return 1
	fi

	file_search=(find "${directory_projects}" -name '*.jsonl' -printf '%T@ %p\n')

	file_session=$("${file_search[@]}" 2>"${sink}" | sort -r -n | head -n 1 | cut -d ' ' -f 2-)

	if [ -z "${file_session}" ]
	then
		frobulator.wrn "No saved session(s) found."

		return 1
	fi

	echo

	id_session="$(basename "${file_session}" .jsonl)"

	frobulator.scs "Session found."

	frobulator.inf "Resuming session" "[ ${id_session} ]"

	claude --resume "${id_session}"

	unset command

}
