#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# adb-settings-get ─────────────────────────────────────────────────────────────

adb_settings_get () {

	adb_download

	adb_set_environment

	setting="${1}"

	adb shell settings get "${setting}"
}
