#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# hex ──────────────────────────────────────────────────────────────────────────

hex () {

	local value_red
	local value_green
	local value_blue

	# red green blue values - space separated - hexadecimal color code

	read -r value_red value_green value_blue <<< "${*}"

	printf '%02x%02x%02x\n' "${value_red}" "${value_green}" "${value_blue}"
}
