#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# dimensions ───────────────────────────────────────────────────────────────────

dimensions () {

	columns=$(tput cols)
	lines=$(tput lines)

	echo "Terminal size:"
	echo "W: ${columns} x H: ${lines}"
}
