#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# vector-export ────────────────────────────────────────────────────────────────

vector-export () {

	frobulator.require inkscape

	type_export="${1}"

	if [ -z "${type_export}" ]
	then
		type_export="png"
	fi

	for file in *.svg
	do
		if [ -f "${file}" ]
		then
			name_file="${file%.*}"

			inkscape "${file}"						\
				--batch-process						\
				--export-width=4096					\
				--export-area-page					\
				--export-type="${type_export}"		\
				--export-filename="${name_file}"."${type_export}"
		fi
	done
}
