#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# adb-device ───────────────────────────────────────────────────────────────────

adb_device () {

	adb_download

	adb_set_environment

	if [ $# -gt 1 ]
	then
		device="-s ${@:2}"

		adb connect ${@:2}

		sleep 2
	fi
}
