#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# adb-reset-apk ────────────────────────────────────────────────────────────────

adb_reset_apk () {

	adb_download

	adb_set_environment

	application="${1}"
	activity="${2}"

	adb "${device}" shell	\
		pm clear "${application}"

	adb "${device}" shell	\
		am start			\
			--user 0		\
			-n "${application}"/"${application}"."${activity}"
}
