#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# adb-screenshot ───────────────────────────────────────────────────────────────

adb_screenshot () {

	adb_download

	adb_set_environment

	adb shell screencap -p /sdcard/"${screenshot}"

	adb pull /sdcard/"${screenshot}" screenshot/"${screenshot}"

	adb shell rm /sdcard/"${screenshot}"
}
