#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# clo ──────────────────────────────────────────────────────────────────────────

clo () {

	local command_path
	local name_command
	local directory_projects
	local command_search
	local file_session
	local id_session

	name_command="claude"

	# ${name_command} command path - empty if not installed

	command_path="$(command -v "${name_command}")"

	if [ -z "${command_path}" ]
	then
		frobulator.err "Command not found" "[ ${name_command} ]"

		return 1
	fi

	directory_projects="${HOME}/.${name_command}/projects"

	if [ ! -d "${directory_projects}" ]
	then
		frobulator.wrn "No session history found."

		return 1
	fi

	command_search=(find "${directory_projects}" -name '*.jsonl' -printf '%T@ %p\n')

	file_session=$("${command_search[@]}" 2>"${sink}" | sort -r -n | head -n 1 | cut -d ' ' -f 2-)

	if [ -z "${file_session}" ]
	then
		frobulator.wrn "No saved session(s) found."

		return 1
	fi

	echo

	id_session="$(basename "${file_session}" .jsonl)"

	frobulator.scs "Session found."

	frobulator.inf "Resuming session" "[ ${id_session} ]"

	claude --dangerously-skip-permissions --resume "${id_session}"

	unset name_command

}
