#!/bin/bash

# dependencies ─────────────────────────────────────────────────────────────────

frobulator="${HOME}"/.local/bin/frobulator

source "${frobulator}"

# superuser ────────────────────────────────────────────────────────────────────

# script ───────────────────────────────────────────────────────────────────────

# version ──────────────────────────────────────────────────────────────────────

version="2026-09-20"

# defaults ─────────────────────────────────────────────────────────────────────

self="${BASH_SOURCE[0]}"

# usage ────────────────────────────────────────────────────────────────────────

# executed directly: install only

if [[ "${self}" = "${0}" ]]
then
	script="$(basename -- "${self}")"

	directory_install="${HOME}"/.local/bin

	while (( $# ))
	do
		case "${1}"
		in
			-i|--install)
				option="install"
			;;

			-h|--help)
				echo
				echo -e "Usage: ./${script} -i | -h"
				echo
				echo -e "Options:"
				echo
				echo -e "-i, --install    Run [i]nstallation of ${script} to ${directory_install}."
				echo
				echo -e "-h, --help       Show [h]elp and usage information."
				echo
				echo -e "'${script}'      [ Version // ${version} ]"
				echo

				exit
			;;

			"")
				# handle empty argument:
				# use default values specified in script

				:
			;;

			*)
				echo
				echo -e "Usage: ./${script} -i | -h"
				echo
				echo -e "Unknown option: '${script} ${1}':"
				echo -e "Type './${script} -h' for help and usage information."
				echo

				exit 1

			;;

			esac

		shift

	done

	# default to install

	if [ -z "${option}" ]
	then
		option="install"
	fi

	# install

	if [ "${option}" = "install" ]
	then
		file_script="$(realpath "${self}")"

		directory_script="$(dirname "${file_script}")"

		if [ "${directory_script}" -ef "${directory_install}" ]
		then
			frobulator.inf "Already installed" "[ ${directory_install}/${script} ]"
		else
			frobulator.copy "${directory_script}" "${directory_install}" "${script}"

			frobulator.permissions public execute "${directory_install}/${script}"

			frobulator.scs "Installed" "[ ${directory_install}/${script} ]"
		fi
	fi

	exit
fi

# bash ─────────────────────────────────────────────────────────────────────────

if [[ -f "${HOME}"/.bash_aliases ]]
then
	alias 'sa'='. "${HOME}"/.bash_aliases'
fi

if [[ -f "${HOME}"/.bash_funtions ]]
then
	alias 'sf'='. "${HOME}"/.bash_functions'
fi

if [[ -f "${HOME}"/.bashrc ]]
then
	alias 'sc'='. "${HOME}"/.bashrc'
fi

if [[ -f "${HOME}"/.bash_login ]]
then
	alias 'si'='. "${HOME}"/.bash_login'
fi

if [[ -f "${HOME}"/.bash_logout ]]
then
	alias 'so'='. "${HOME}"/.bash_logout'
fi

if [[ -f "${HOME}"/.bash_profile ]]
then
	alias 'sp'='. "${HOME}"/.bash_profile'
fi

# directories ──────────────────────────────────────────────────────────────────

# 'cd' path - empty if not installed

command_cd="$(command -v cd)"

if [ -n "${command_cd}" ]
then
	alias '..'='cd ..'
fi

unset command_cd

# folders present on this system - empty if absent

directory_home="$(ls -d "${HOME}" 2> "${sink}")"
directory_media="$(ls -d /media 2> "${sink}")"
directory_external="$(ls -d /media/[eE]xternal 2> "${sink}")"
directory_internal="$(ls -d /media/[iI]nternal 2> "${sink}")"
directory_files="$(ls -d /media/[fF]iles 2> "${sink}")"

if [ -n "${directory_home}" ]
then
	alias 'hd'='cd "${HOME}"'
fi

unset directory_home

if [ -n "${directory_media}" ]
then
	alias 'md'='cd /media'
fi

unset directory_media

if [ -n "${directory_external}" ]
then
	alias 'ex'='cd /media/[eE]xternal'
fi

unset directory_external

if [ -n "${directory_internal}" ]
then
	alias 'in'='cd /media/[iI]nternal'
fi

unset directory_internal

if [ -n "${directory_files}" ]
then
	alias 'fl'='cd /media/[fF]iles'
fi

unset directory_files

# git  ─────────────────────────────────────────────────────────────────────────

# 'git' path - empty if not installed

command_git="$(command -v git)"

if [ -n "${command_git}" ]
then
	alias 'gc'="git clone --depth 1"
	alias 'gi'='git init'
	alias 'gp'='git pull'
	alias 'ga'='git add *'
	alias 'gm'="git commit -a -m ${1}"
	alias 'gs'='git push'
	alias 'gu'='ga && gm "Code & Features Update" && gs'
	alias 'gn'='git ls-files | xargs cat | wc -l'
fi

unset command_git

# git folders - first one found is used - empty if absent

directory_git_home="$(ls -d "${HOME}"/[gG]it 2> "${sink}")"
directory_git_external="$(ls -d "${PREFIX}"/media/[eE]xternal/[gG]it 2> "${sink}")"
directory_git_internal="$(ls -d "${PREFIX}"/media/[iI]nternal/[gG]it 2> "${sink}")"

if [ -n "${directory_git_home}" ]
then
	alias 'gd'='cd "${HOME}"/[gG]it'

elif [ -n "${directory_git_external}" ]
then
	alias 'gd'='cd "${PREFIX}"/media/[eE]xternal/[gG]it'

elif [ -n "${directory_git_internal}" ]
then
	alias 'gd'='cd "${PREFIX}"/media/[iI]nternal/[gG]it'
fi

unset directory_git_home directory_git_external directory_git_internal

# packages ─────────────────────────────────────────────────────────────────────

# 'apt-get' path - empty if not installed

command_apt_get="$(command -v apt-get)"

if [ -n "${command_apt_get}" ]
then
	# 'sudo' path - empty if not installed

	command_sudo="$(command -v sudo)"

	if [ -n "${command_sudo}" ]
	then
		prefix_apt_get="sudo "
	else
		prefix_apt_get=""
	fi

	alias 'autoclean'="${prefix_apt_get}apt-get autoclean"
	alias 'autoremove'="${prefix_apt_get}apt-get autoremove"
	alias 'check'="${prefix_apt_get}apt-get check"
	alias 'clean'="${prefix_apt_get}apt-get clean"
	alias 'distribution-upgrade'="${prefix_apt_get}apt-get dist-upgrade"
	alias 'download'="${prefix_apt_get}apt-get download"
	alias 'install'="${prefix_apt_get}apt-get install --no-install-recommends --no-upgrade"
	alias 'purge'="${prefix_apt_get}apt-get purge"
	alias 'reinstall'="${prefix_apt_get}apt-get reinstall"
	alias 'repair'="${prefix_apt_get}apt-get -f install"
	alias 'remove'="${prefix_apt_get}apt-get remove"
	alias 'retrieve'="apt-get source"
	alias 'update'="${prefix_apt_get}apt-get update"
	alias 'upgrade'="${prefix_apt_get}apt-get dist-upgrade"
fi

unset command_apt_get

# 'apt-cache' path - empty if not installed

command_apt_cache="$(command -v apt-cache)"

if [ -n "${command_apt_cache}" ]
then
	# 'sudo' path - empty if not installed

	command_sudo="$(command -v sudo)"

	if [ -n "${command_sudo}" ]
	then
		prefix_apt_cache="sudo "
	else
		prefix_apt_cache=""
	fi

	alias 'depend'="${prefix_apt_cache}apt-cache depends"
	alias 'reverse'="${prefix_apt_cache}apt-cache rdepends"
	alias 'search'="${prefix_apt_cache}apt-cache search"
	alias 'status'="${prefix_apt_cache}apt-cache stats"
fi

unset command_apt_cache

# system ───────────────────────────────────────────────────────────────────────

# 'sudo' and 'systemctl' paths - empty if not installed

command_sudo="$(command -v sudo)"
command_systemctl="$(command -v systemctl)"

if [ -n "${command_sudo}" ] && [ -n "${command_systemctl}" ]
then
	alias 'start'='sudo systemctl start'
	alias 'stop'='sudo systemctl stop'
	alias 'enable'='sudo systemctl enable'
	alias 'disable'='sudo systemctl disable'
	alias 'status'='sudo systemctl status'
fi

unset command_systemctl

# filters ──────────────────────────────────────────────────────────────────────

# 'grep' path - empty if not installed

command_grep="$(command -v grep)"

if [ -n "${command_grep}" ]
then
	# 'env' path - empty if not installed

	command_env="$(command -v env)"

	if [ -n "${command_env}" ]
	then
		alias 'environment'='env | grep -i'
	fi

	# 'ls' path - empty if not installed

	command_ls="$(command -v ls)"

	if [ -n "${command_ls}" ]
	then
		alias 'files'='ls -a | grep -i'
	fi

	# 'ps' path - empty if not installed

	command_ps="$(command -v ps)"

	if [ -n "${command_ps}" ]
	then
		alias 'processes'='ps -a -u -x | grep -i'
	fi
fi

unset command_env command_grep

# session ──────────────────────────────────────────────────────────────────────

# 'exit' path - empty if not installed

command_exit="$(command -v exit)"

if [ -n "${command_exit}" ]
then
	alias 'exit'='exit > /dev/null 2>&1'
fi

unset command_exit

# 'logout' path - empty if not installed

command_logout="$(command -v logout)"

if [ -n "${command_logout}" ]
then
	alias 'logout'='logout > /dev/null 2>&1'
fi

unset command_logout

# commands ─────────────────────────────────────────────────────────────────────

# 'chgrp' path - empty if not installed

command_chgrp="$(command -v chgrp)"

if [ -n "${command_chgrp}" ]
then
	alias 'group'='chgrp --preserve-root'
fi

unset command_chgrp

# 'chmod' path - empty if not installed

command_chmod="$(command -v chmod)"

if [ -n "${command_chmod}" ]
then
	alias 'modify'='chmod --preserve-root'
fi

unset command_chmod

# 'chown' path - empty if not installed

command_chown="$(command -v chown)"

if [ -n "${command_chown}" ]
then
	alias 'own'='chown --preserve-root'
fi

unset command_chown

# 'command' path - empty if not installed

command_command="$(command -v command)"

if [ -n "${command_command}" ]
then
	alias 'which'='command -v'
fi

unset command_command

# 'curl' path - empty if not installed

command_curl="$(command -v curl)"

if [ -n "${command_curl}" ]
then
	alias 'header'='curl -I'
fi

# 'df' path - empty if not installed

command_df="$(command -v df)"

if [ -n "${command_df}" ]
then
	alias 'space'='df -H'
fi

unset command_df

# 'du' path - empty if not installed

command_du="$(command -v du)"

if [ -n "${command_du}" ]
then
	alias 'size'='du -a -c -h'
	alias 'usage'="du -a -d 1 -h -S --time 2> /dev/null | sed '/total/ [ Total ]/g"
fi

unset command_du

# 'htop' path - empty if not installed

command_htop="$(command -v htop)"

if [ -n "${command_htop}" ]
then
	alias 'top'='htop'
	alias 'process'='htop -s USER -t'
fi

unset command_htop

# 'ls' path - empty if not installed

command_ls="$(command -v ls)"

if [ -n "${command_ls}" ]
then
	alias last='echo ; ls -a -h -l -t | head -11 ; echo'
	fi

# 'mount' and 'column' paths - empty if not installed

command_mount="$(command -v mount)"
command_column="$(command -v column)"

if [ -n "${command_mount}" ] && [ -n "${command_column}" ]
then
	alias 'mounts'='mount | column -t'
fi

unset command_column command_ls command_mount

# 'nano' path - empty if not installed

command_nano="$(command -v nano)"

if [ -n "${command_nano}" ]
then
	alias 'edit'='nano -c -g -i -l -m -q -D -F -J 80 -T 4'
fi

unset command_nano

# 'ss' path - empty if not installed

command_ss="$(command -v ss)"

if [ -n "${command_ss}" ]
then
	alias 'ports'='ss -t -u -l -a -n -p'
fi

unset command_ss

# 'pgrep' path - empty if not installed

command_pgrep="$(command -v pgrep)"

if [ -n "${command_pgrep}" ]
then
	alias 'pgrep'='pgrep -f'
fi

unset command_pgrep

# 'pstree' path - empty if not installed

command_pstree="$(command -v pstree)"

if [ -n "${command_pstree}" ]
then
	alias 'ptree'='pstree -C age -p'
fi

unset command_pstree

# 'ping' path - empty if not installed

command_ping="$(command -v ping)"

if [ -n "${command_ping}" ]
then
	alias 'sonar'='ping -c 5'
fi

unset command_ping

# 'ps' path - empty if not installed

command_ps="$(command -v ps)"

if [ -n "${command_ps}" ]
then
	alias 'what'='ps -e'
	alias 'how'='ps -u'
fi

unset command_ps

# 'rm' path - empty if not installed

command_rm="$(command -v rm)"

if [ -n "${command_rm}" ]
then
	alias 'delete'='rm -r -f'
fi

unset command_rm

# 'rsync' path - empty if not installed

command_rsync="$(command -v rsync)"

if [ -n "${command_rsync}" ]
then
	alias 'archive'='rsync -a -r -q --progress -h'
fi

unset command_rsync

# 'cp' path - empty if not installed

command_cp="$(command -v cp)"

if [ -n "${command_cp}" ]
then
	alias 'copy'='cp -r -f'
fi

unset command_cp

# 'shutdown' path - empty if not installed

command_shutdown="$(command -v shutdown)"

if [ -n "${command_shutdown}" ]
then
	alias 'shutdown'='shutdown -h now'
fi

unset command_shutdown

# 'sudo' and 'tput' paths - empty if not installed

command_sudo="$(command -v sudo)"
command_tput="$(command -v tput)"

if [ -n "${command_sudo}" ] && [ -n "${command_tput}" ]
then
	# password prompt colors: user name in yellow - then back to normal

	color_user="$(tput setaf 3)"
	color_reset="$(tput sgr 0)"

	alias 'sudo'="sudo -p \"[ ${color_user}${USER}${color_reset} ] >_ ? \""
fi

unset color_user color_reset command_sudo command_tput

# 'wget' path - empty if not installed

command_wget="$(command -v wget)"

if [ -n "${command_wget}" ]
then
	alias 'get'='wget -c'
fi

unset command_wget

# 'tree' path - empty if not installed

command_tree="$(command -v tree)"

if [ -n "${command_tree}" ]
then
	alias 'treed'='tree -a -d -p -L'
	alias 'treef'='tree -a -p -L'
fi

unset command_tree

# 'journalctl' path - empty if not installed

command_journalctl="$(command -v journalctl)"

if [ -n "${command_journalctl}" ]
then
	alias 'logs'='journalctl -x -e'
fi

unset command_journalctl

# 'ip' path - empty if not installed

command_ip="$(command -v ip)"

if [ -n "${command_ip}" ]
then
	alias 'myip'='ip addr'
fi

unset command_ip

# 'curl' path - empty if not installed

command_curl="$(command -v curl)"

if [ -n "${command_curl}" ]
then
	alias 'publicip'='curl -s ifconfig.me'
fi

unset command_curl

# 'free' path - empty if not installed

command_free="$(command -v free)"

if [ -n "${command_free}" ]
then
	alias 'memory'='free -h'
fi

unset command_free

# 'lsblk' path - empty if not installed

command_lsblk="$(command -v lsblk)"

if [ -n "${command_lsblk}" ]
then
	alias 'disks'='lsblk -f'
fi

unset command_lsblk

# ai ───────────────────────────────────────────────────────────────────────────

# 'ollama' path - empty if not installed

command_ollama="$(command -v ollama)"

if [ -n "${command_ollama}" ]
then
	name_model_ollama=$(ollama list | tail -n 1 | cut -d ' ' -f 1)

	if [ -n "${name_model_ollama}" ]
	then
		alias 'ada'="ollama run ${name_model_ollama}"
	fi
fi

unset command_ollama

# dextop ───────────────────────────────────────────────────────────────────────

if [ -n "${TERMUX_VERSION}" ]
then
	# 'dextop' path - empty if not installed

	command_dextop="$(command -v dextop)"

	if [ -n "${command_dextop}" ]
	then
		alias 'daa'='bash dextop -u additions all'

		alias 'dda'='bash dextop -u all'

		alias 'ddu'='curl -s -L run.dxtp.app > "${HOME}"/.local/bin/dextop'

		alias 'dfa'='curl -s -L run.dxtp.app > "${HOME}"/.local/bin/dextop && bash dextop -u all'

		alias 'dpa'='bash dextop -u preferences all'

		alias 'dsa'='bash dextop -u shell all'

		alias 'dta'='bash dextop -u termux all'

		alias 'dua'='bash dextop -u utility all'
	fi

	# 'am' path - empty if not installed

	command_am="$(command -v am)"

	if [ -n "${command_am}" ]
	then
		alias {'dextop-mail','email','mail'}='am start --user 0 -a android.intent.action.VIEW -d mailto: > /dev/null 2>&1'

		alias {'dextop-browser','browser','link','web'}='am start --user 0 -a android.intent.action.VIEW -d https: > /dev/null 2>&1'

		alias {'dextop-message','message','text','sms'}='am start --user 0 -a android.intent.action.VIEW -d sms: > /dev/null 2>&1'

		alias {'dextop-files','file'}='am start --user 0 -a android.intent.action.VIEW -d file: > /dev/null 2>&1'
	fi
fi

unset command_am command_dextop
