#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# snippet ──────────────────────────────────────────────────────────────────────

snippet () {

	local url

	url="http://sprunge.us"

	if (( $# ))
	then
		curl -F 'sprunge=<-' "${url}" < "${1}"
	else
		curl -F 'sprunge=<-' "${url}"
	fi
}
