#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# temperature ──────────────────────────────────────────────────────────────────

temperature () {

	if [[ -d /sys/class/thermal ]]
	then
		count_acpitz=0
		label_cpu=""
		degrees_cpu=""
		list_lines=()
		length_label_longest=0

		for directory_zone in /sys/class/thermal/thermal_zone*
		do
			label=$(cat "${directory_zone}"/type)

			if [ "${label}" = "acpitz" ]
			then
				count_acpitz=$(( count_acpitz + 1 ))

				label="System ${count_acpitz}"

			elif [[ "${label}" = pch_* ]]
			then
				label="Chipset"

			elif [[ "${label}" = iwlwifi_* ]]
			then
				label="WiFi"

			elif [ "${label}" = "x86_pkg_temp" ]
			then
				label="CPU"

			else
				label="${label//_/ }"
			fi

			degrees=$(cat "${directory_zone}"/temp)
			degrees=$(( degrees / 1000 ))

			if [ "${#label}" -gt "${length_label_longest}" ]
			then
				length_label_longest="${#label}"
			fi

			if [ "${label}" = "CPU" ]
			then
				label_cpu="${label}"
				degrees_cpu="${degrees}"
			else
				list_lines+=("${label}|${degrees}")
			fi
		done

		width_label=$(( length_label_longest + 4 ))

		if [ -n "${label_cpu}" ]
		then
			printf "%-${width_label}s%s°C\n" "${label_cpu}:" "${degrees_cpu}"
		fi

		printf '%s\n' "${list_lines[@]}" | sort |
		while IFS='|' read -r label degrees
		do
			printf "%-${width_label}s%s°C\n" "${label}:" "${degrees}"
		done

		unset count_acpitz label_cpu degrees_cpu list_lines length_label_longest width_label
	fi

}
