#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# hex ──────────────────────────────────────────────────────────────────────────

hex () {

	# set IFS

	IFS=' '

	read r g b <<< "${@}"

	printf '%02x%02x%02x\n' ${r} ${g} ${b}

	# unset IFS

	IFS=''
}
