#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# adb-vendor-ids ───────────────────────────────────────────────────────────────

adb_vendor_ids () {

	local status_package_udev

	adb_download

	adb_set_environment

	mkdir -p "${HOME}"/.android

	for number_id in {0..65535}
	do
		printf '0x%04x\n' "${number_id}"
	done >> "${HOME}"/.android/adb_usb.ini

	chmod -R 777 "${HOME}"/.android

	# udev package listing - empty if not installed

	status_package_udev="$(dpkg -l udev)"

	if [ -n "${status_package_udev}" ]
	then
		while read -r id_vendor
		do
			echo SUBSYSTEM==\"usb\", SYSFS{idVendor}==\""${id_vendor:2}"\", MODE=\"0666\" \;

		done <<< $(cat "${HOME}"/.android/adb_usb.ini) >> /etc/udev/rules.d/51-android.rules
	fi
}
