#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# who ──────────────────────────────────────────────────────────────────────────

who () {

	echo

	echo "Current user: ${USER}"

	echo

}
