#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# media ────────────────────────────────────────────────────────────────────────

media () {

	local type_media="${1}"
	local source_media="${2}"
	local directory_output="${3}"
	local directory_binary="${HOME}/.local/bin"

	local file_archive_deno
	local path_file_media
	local list_files_media
	local directory_file
	local name_source
	local name_target
	local name_browser
	local duration_sleep
	local format_download
	local extension_media

	local -a list_options_type=()
	local -a list_options_url=()
	local -a list_options_site=()

	if [ -z "${type_media}" ]
	then
		frobulator.err "No type specified" "[ audio | video ]"

		return 1
	fi

	if [ "${type_media}" != "audio" ] && [ "${type_media}" != "video" ]
	then
		frobulator.err "Invalid type" "[ ${type_media} ]"

		return 1
	fi

	if [ -z "${source_media}" ]
	then
		frobulator.err "No source specified"

		return 1
	fi

	if [ -z "${directory_output}" ]
	then
		directory_output="${PWD}"
	fi

	if [ ! -d "${directory_output}" ]
	then
		directory_output="${PWD}"
	fi

	if [ ! -f "${directory_binary}/yt-dlp" ]
	then
		frobulator.download "https://github.com/yt-dlp/yt-dlp/releases/latest/download" "${directory_binary}" "yt-dlp"
	else
		frobulator.silence "${directory_binary}/yt-dlp --update"
	fi

	if [ ! -x "${directory_binary}/yt-dlp" ]
	then
		frobulator.err "Downloader unavailable" "[ yt-dlp ]"

		return 1
	fi

	if [ ! -f "${directory_binary}/deno" ]
	then
		file_archive_deno="deno-x86_64-unknown-linux-gnu.zip"

		frobulator.download "https://github.com/denoland/deno/releases/latest/download" "${directory_binary}" "${file_archive_deno}"

		unzip -o -q "${directory_binary}/${file_archive_deno}" -d "${directory_binary}"

		rm -f "${directory_binary}/${file_archive_deno}"

		chmod +x "${directory_binary}/deno"
	else
		frobulator.silence "${directory_binary}/deno upgrade"
	fi

	if [ ! -x "${directory_binary}/deno" ]
	then
		frobulator.err "Solver unavailable" "[ deno ]"

		return 1
	fi

	if [ "${type_media}" = "audio" ]
	then
		format_download="bestaudio"
		extension_media="mp3"

		list_options_type+=( --extract-audio )
		list_options_type+=( --audio-format "${extension_media}" )
		list_options_type+=( --audio-quality best )
		list_options_type+=( --output '%(uploader)s - %(title)s.%(ext)s' )

	elif [ "${type_media}" = "video" ]
	then
		format_download="bestvideo+bestaudio"
		extension_media="mp4"

		list_options_type+=( --merge-output-format "${extension_media}" )
		list_options_type+=( --output '%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s' )
	fi

	if [ -f "${source_media}" ]
	then
		list_options_url+=( --batch-file )
	fi

	if [ "${source_media#*soundcloud.com}" = "${source_media}" ]
	then
		name_browser="$(xdg-settings get default-web-browser 2>"${sink}")"

		name_browser="${name_browser%.desktop}"

		if [[ "${name_browser}" = firefox* ]] ||
		[[ "${name_browser}" = librewolf*  ]] ||
		[[ "${name_browser}" = waterfox*   ]]
		then
			name_browser="firefox"

		elif [[ "${name_browser}" = chrome*       ]] ||
			[[ "${name_browser}" = google-chrome* ]] ||
			[[ "${name_browser}" = chromium*      ]] ||
			[[ "${name_browser}" = brave*         ]] ||
			[[ "${name_browser}" = vivaldi*       ]] ||
			[[ "${name_browser}" = opera*         ]]
		then
			name_browser="chrome"

		else
			frobulator.err "No compatible browser found on system"

			return 1
		fi

		list_options_site+=( --cookies-from-browser "${name_browser}" )
	fi

	cd "${directory_output}"

	duration_sleep=$(( RANDOM % 5 + 1 ))

	"${directory_binary}/yt-dlp"									\
		--remote-components		"ejs:github"				\
		--js-runtimes			"deno:${directory_binary}/deno"	\
		--ffmpeg-location		"/usr/bin/ffmpeg"			\
		--quiet												\
		--no-update											\
		--ignore-errors										\
		--no-overwrites										\
		--sleep-requests		"${duration_sleep}"			\
		--yes-playlist										\
		--format				"${format_download}"					\
		"${list_options_site[@]}"								\
		"${list_options_type[@]}"								\
		"${list_options_url[@]}"									\
		"${source_media}" &

	frobulator.progress download

	list_files_media="$(find "${PWD}" -type f -iname "*.${extension_media}")"

	IFS=$'\n'

	for path_file_media in ${list_files_media}
	do
		directory_file="${path_file_media%/*}"
		name_source="${path_file_media##*/}"

		name_target="${name_source// - Topic/}"

		if [ "${name_source}" != "${name_target}" ]
		then
			mv -- "${path_file_media}" "${directory_file}/${name_target}"
		fi
	done

	unset IFS
}
