#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# colors ───────────────────────────────────────────────────────────────────────

colors () {

	local number_color_foreground
	local code_color_foreground
	local number_color_background
	local code_color_background

	list=(
		tput
		printf
	)

	frobulator.require ${list[@]}

	list=()

	# print palette

	for number_color_foreground in {0..7}
	do
		code_color_foreground=$(tput setaf "${number_color_foreground}")

		for number_color_background in {0..7}
		do
			code_color_background=$(tput setab "${number_color_background}")

			echo -n "${code_color_background} ${code_color_foreground}"

			printf 'F:%s B:%s ' "${number_color_foreground}" "${number_color_background}"
		done

		# reset

		echo $(tput sgr0)
	done

	echo
}
