#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# ssh ──────────────────────────────────────────────────────────────────────────

ssh () {

	local color_destination
	local color_reset

	# destination is always the last argument

	host_destination=${!#}

	# password prompt colors: destination in yellow - then back to normal

	color_destination="$(tput setaf 3)"
	color_reset="$(tput sgr 0)"

	echo -n -e "[  ${color_destination}${host_destination}${color_reset}  ] >_ ? "

	read -r -s password

	echo

	sshpass					\
		-p "${password}"	\
							ssh -X "${@}"

	unset host_destination

	unset password

}
