#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# adb-record ───────────────────────────────────────────────────────────────────

adb_record () {

	local date_recording
	local file_recording
	local id_process_record

	adb_download

	adb_set_environment

	# recording file - timestamped - recorded on the device then pulled here

	date_recording="$(date +"%m-%d-%Y-%H-%M-%S")"

	file_recording="recording-${date_recording}.mp4"

	adb shell screenrecord /sdcard/"${file_recording}" &

	id_process_record=$!

	read -r -p 'Press enter to stop recording...'

	kill "${id_process_record}" > "${sink}" 2>&1

	sleep 0.5

	mkdir -p screenrecord

	adb pull /sdcard/"${file_recording}" screenrecord/"${file_recording}"

	adb shell rm /sdcard/"${file_recording}"
}
