#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# vector-export ────────────────────────────────────────────────────────────────

vector-export () {

	frobulator.require inkscape

	export_type="${1}"

	if [ -z "${export_type}" ]
	then
		export_type="png"
	fi

	for file in *.svg
	do
		if [ -f "${file}" ]
		then
			file_name="${file%.*}"

			inkscape "${file}"						\
				--batch-process						\
				--export-width=4096					\
				--export-area-page					\
				--export-type="${export_type}"		\
				--export-filename="${file_name}"."${export_type}"
		fi
	done
}
