#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# locate ───────────────────────────────────────────────────────────────────────

locate () {

	local command_find

	type="${1}"

	query="${2}"

	if [[ "${type}" =~ ^(d|dir|directory)$ ]]
	then
		type='d'

	elif [[ "${type}" =~ ^(f|file)$ ]]
	then
		type='f'
	else
		echo "unsupported type"
		echo

		exit 1
	fi

	# path of 'find', empty when not installed

	command_find="$(command -v find)"

	if [ -n "${command_find}" ]
	then
		find								\
			"${PWD}"						\
				-type			"${type}"	\
				-iname 			"*${query}*"
	fi

}
