#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# rgb ──────────────────────────────────────────────────────────────────────────

rgb () {

	frobulator.require printf

	read code_hex <<< "${1}"

	[[ ${code_hex:0:1} = "#" ]] && code_hex=${code_hex:1:6}

	value_red=$(( 16#${code_hex:0:2} ))
	value_green=$(( 16#${code_hex:2:2} ))
	value_blue=$(( 16#${code_hex:4:2} ))

	printf '%03d %03d %03d\n' ${value_red} ${value_green} ${value_blue}
}
