#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# play ─────────────────────────────────────────────────────────────────────────

play () {

	local command_mpv
	local bracket_open
	local bracket_close
	local action
	local file_audio
	local title_audio
	local list_frames_ticker
	local index_frame
	local id_process_player
	local frame_ticker

	# 'mpv' path - empty if not installed

	command_mpv="$(command -v mpv)"

	if [ -z "${command_mpv}" ]
	then
		frobulator.require mpv
	fi

	bracket_open="[${marker_spc}"
	bracket_close="${marker_spc}]"

	action="Playing"

	file_audio="${1}"

	if [ $# -eq 2 ]
	then
		action="${1}"

		file_audio="${2}"
	fi

	title_audio="${file_audio##*/}"


	# frobulator.pmt "${@}"

	# substitute standard input for function specific criteria:
	# [ ... ] action ───────────────────────────────────────────...─── [ title_audio ]

	frobulator.pmt "${action}" "${title_audio}"

	prompt="${prompt_string[@]}"

	list_frames_ticker=(
		".  "
		".. "
		"..."
		" .."
		"  ."
		"   "
	)

	index_frame=0

	mpv					\
		--no-video		\
		--really-quiet	\
						"${file_audio}" < "${sink}" > "${sink}" 2>&1 &

	id_process_player=$!

	while [ -d /proc/"${id_process_player}" ]
	do
		frame_ticker="${list_frames_ticker[index_frame++%${#list_frames_ticker[@]}]}"

		echo -n -e "\r${bracket_open}${frame_ticker}${bracket_close}${reset}${marker_spc}${prompt}\c"

		sleep 0.25
	done
}
