#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# adb-download ─────────────────────────────────────────────────────────────────

adb_download () {

	local directory_temporary
	local file_archive
	local directory_extracted
	local item

	frobulator.temporary directory_temporary

	if [ -z "${directory_temporary}" ] || [ ! -d "${directory_temporary}" ]
	then
		frobulator.err "Unable to create temporary directory"

		return 1
	fi

	file_archive="${directory_temporary}/platform-tools.zip"
	directory_extracted="${directory_temporary}/platform-tools"

	frobulator.inf "Fetching latest" "[ Android Platform Tools ]"

	curl						\
		--silent				\
		--fail					\
		--location				\
		--output "${file_archive}"	\
								"${url_android_platform_tools}"

	if [ "${?}" -ne 0 ]
	then
		frobulator.delete "${directory_temporary}"

		frobulator.err "Unable to fetch" "[ Android Platform Tools ]"

		return 1
	fi

	unzip -q "${file_archive}" -d "${directory_temporary}"

	if [ "${?}" -ne 0 ]
	then
		frobulator.delete "${directory_temporary}"

		frobulator.err "Unable to extract" "[ Android Platform Tools ]"

		return 1
	fi

	if [ ! -x "${directory_extracted}/adb" ] || [ ! -x "${directory_extracted}/fastboot" ]
	then
		frobulator.delete "${directory_temporary}"

		frobulator.err "Invalid archive" "[ Android Platform Tools ]"

		return 1
	fi

	frobulator.terminate adb

	frobulator.directory "${directory_android}"

	frobulator.directory "${HOME}/.local/bin"

	frobulator.delete "${directory_platform_tools}"

	mv "${directory_extracted}" "${directory_platform_tools}"

	list=(
		adb
		fastboot
	)

	for item in "${list[@]}"
	do
		frobulator.link "${directory_platform_tools}" "${HOME}/.local/bin" "${item}"
	done

	list=()

	if [ "${USER}" != "root" ]
	then
		chown -R "${USER}:$(id -g "${USER}")" "${directory_android}" "${HOME}/.local/bin/adb" "${HOME}/.local/bin/fastboot"
	fi

	frobulator.delete "${directory_temporary}"

	export PATH="${HOME}/.local/bin:${directory_platform_tools}:${PATH}"

	hash -r

	frobulator.fwd "Utilities version: $(adb version | head -n 1)"

	frobulator.scs "Utilities deployment ready" "[ Android Platform Tools ]"

}
