#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# countf ───────────────────────────────────────────────────────────────────────

countf () {

	echo "$(find . -type f | wc -l) files under ${PWD}"

}
