#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# preview ──────────────────────────────────────────────────────────────────────

preview () {

	local command_cat
	local command_head

	count_lines="${1}"

	file="${2}"

	# 'cat' and 'head' paths - empty if not installed

	command_cat="$(command -v cat)"
	command_head="$(command -v head)"

	if [ -n "${command_cat}" ] &&
	   [ -n "${command_head}" ]
	then
		frobulator.inf "Previewing file" "[ ${count_lines} lines // ${file} ]"

		frobulator.separate

		cat "${file}" | head -n "${count_lines}"

		echo

		frobulator.separate

	fi
}
