#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# adb-install-package ──────────────────────────────────────────────────────────

adb_install_package () {

	local package

	adb_download

	adb_set_environment

	package="${1}"

	adb install "${package}"
}
