#!/bin/bash

# login ////////////////////////////////////////////////////////////////////////

if [ -n "${TERMUX_VERSION}" ]
then
	frobulator.fwd "Logging in..."
	echo
fi

# dextop ///////////////////////////////////////////////////////////////////////

if [ -n "${TERMUX_VERSION}" ]
then
	# session

	if [[ $(cat "${HOME}"/.dextop/dextop-environment) = xfce ]]
	then
		session_interface="XFCE"
	else
		session_interface="CONSOLE"
	fi

	if [ -f /etc/os-release ]
	then
		. /etc/os-release

		distribution_name="${NAME}"
	fi

	# settings

	if [ ! -f "${HOME}"/.dextop/dextop-settings-checkpoint ]
	then
		frobulator.fwd "Setting up..."
		echo

		dbus-launch "${HOME}"/.local/bin/container-settings

		frobulator.file "${HOME}"/.dextop dextop-settings-checkpoint

		frobulator.clear
	fi

	# update

	if [[ $(pgrep -f proot) ]]
	then
		:
	else
		if [[ $(cat "${HOME}"/.dextop/dextop-update) = *update* ]]
		then
			if [[ $(cat "${HOME}"/.dextop/dextop-update) = *dextop* ]]
			then
				dextop -u dextop
			fi

			if [[ $(cat "${HOME}"/.dextop/dextop-update) = *shell* ]]
			then
				dextop -u shell
			fi

			if [[ $(cat "${HOME}"/.dextop/dextop-update) = *utility* ]]
			then
				dextop -u utility all
			fi

			if [[ $(cat "${HOME}"/.dextop/dextop-update) = *all* ]]
			then
				dextop -u all
			fi

			frobulator.clear
		fi
	fi

	# audio

	if [[ $(pgrep -f proot) ]]
	then
		echo 'default-server = 127.0.0.1'   >  /etc/pulse/client.conf
		echo 'auto-connect-localhost = yes' >> /etc/pulse/client.conf
		echo 'autospawn = no'               >> /etc/pulse/client.conf
	else
		if [[ $(cat "${HOME}"/.dextop/dextop-audio) = "audio" ]]
		then
			if [[ $(command -v pulseaudio) ]]
			then
				if [[ $(pgrep -f pulseaudio) ]]
				then
					:
				else
					# start pulseaudio and daemonize

					pulseaudio					\
						--start					\
						--daemonize=true		\
						--exit-idle-time=-1

					# initialize transmission control protocol

					pacmd								\
						load-module						\
							module-native-protocol-tcp	\
								auth-ip-acl=127.0.0.1	\
								auth-anonymous=1
				fi
			fi
		fi
	fi

	# display

	if [ -n "${TERMUX_VERSION}" ]
	then
		TERMUX_X11_APPLICATION="com.termux.x11"
		TERMUX_X11_SERVER="termux-x11"
		TERMUX_X11_DRIVER="virpipe"
		TERMUX_X11_ACCELERATOR="virgl_test_server"

		export TERMUX_X11_SERVER="${TERMUX_X11_SERVER}"
		export TERMUX_X11_DRIVER="${TERMUX_X11_DRIVER}"
		export TERMUX_X11_ACCELERATOR="${TERMUX_X11_ACCELERATOR}"

		if [ -z "${DISPLAY}" ]
		then
			DISPLAY=":0"

			export DISPLAY="${DISPLAY}"
		fi

		if [[ $(pgrep -f "${TERMUX_X11_ACCELERATOR}") ]]
		then
			:
		else
			"${TERMUX_X11_ACCELERATOR}" &
		fi

		if [[ $(pgrep -f "${TERMUX_X11_APPLICATION}") ]]
		then
			:
		else
			"${TERMUX_X11_SERVER}" "${DISPLAY}" &
		fi
	fi

	# dextop

	if [ -n "${TERMUX_VERSION}" ]
	then
		# get session login count

		ticker=$(echo $(cat "${HOME}"/.dextop/dextop-ticker))

		# welcome

		if [[ $(cat "${HOME}"/.dextop/dextop-login) = "login" ]]
		then
			# load desktop environment

			container-session -o
		fi

		# load welcome message

		if [[ $(pgrep -f proot) ]]
		then
			frobulator.fwd "Welcome to Dextop" "[ ${distribution_name} ]"
			echo

			if [[ ${ticker} -eq 0 ]]
			then
				frobulator.wrn "This is your first login:"
				frobulator.wrn "Run 'container-session -o' to launch session [ ${session_interface} ]."
				echo
			fi
		fi

		frobulator.fwd "Welcome to Dextop" "[ Termux ]"
		echo

		frobulator.inf "Update utilities:"
		frobulator.nul "'dextop -u | dextop | shell [Shell Name | all] | utility [Utility Name | all] | all'"
		echo

		frobulator.inf "Launch session:"
		frobulator.nul "'container-session -o | -u [User Name] | -a [Application]'"
		echo

		# increment session login count

		ticker=$(( ${ticker} + 1 ))

		echo ${ticker} > "${HOME}"/.dextop/dextop-ticker

	fi

fi
