#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# adb-record ───────────────────────────────────────────────────────────────────

adb_record () {

	adb_download

	adb_set_environment

	adb shell screenrecord /storage/emulated/0/Videos/"${recording}" &

	id_process_record=$!

	read -r -p 'Press enter to stop recording...'

	kill ${id_process_record} > "${sink}" 2>&1

	sleep 0.5

	adb pull /sdcard/"${recording}" screenrecord/"${recording}"

	adb shell rm /sdcard/"${recording}"
}
