#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# preview ──────────────────────────────────────────────────────────────────────

preview () {

	count="${1}"

	file="${2}"

	if [[ $(command -v cat) ]] &&
	   [[ $(command -v head) ]]
	then
		frobulator.inf "Previewing file" "[ ${count} lines // ${file} ]"

		frobulator.separate

		cat "${file}" | head -n "${count}"

		echo

		frobulator.separate

	fi
}
