#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [[ $(id -u -n) = "root" ]]
then
	SUDO_HOME=/root

	USER="${SUDO_USER}"

	HOME=/home/"${USER}"
fi

if [[ -z $(command -v curl) ]]
then
	yes | apt-get install curl
fi

if [ ! -d "${HOME}"/.local/bin ]
then
	mkdir -p "${HOME}"/.local/bin
fi

frobulator="${HOME}"/.local/bin/frobulator

version_online=$(curl -s -L get.frbltr.app | grep 'version=' | cut -d '"' -f 2)

version_local=$(cat "${frobulator}" | grep 'version=' | cut -d '"' -f 2)

version_local="${version_local:-01-01-1970}"

date_online=$(date -d "${version_online:6:4}-${version_online:0:2}-${version_online:3:2}" +%s)

date_local=$(date -d "${version_local:6:4}-${version_local:0:2}-${version_local:3:2}" +%s)

if [ -f "${frobulator}" ] && [ "${date_online}" -gt "${date_local}" ]
then
	rm -r -f "${HOME}"/.local/bin/frobulator

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

if [ ! -f "${frobulator}" ]
then
	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${frobulator}"

# usage ////////////////////////////////////////////////////////////////////////

if [[ "${BASH_SOURCE[0]}" = "${0}" ]]
then
	# implement from local version

	if [ $# -eq 0 ]
	then
		source "${BASH_SOURCE[0]}"

		if return 0 2> "${sink}"
		then
			:
		else
			frobulator.scs "Implemented" "[ ${PWD}/${install_file} ]"
			echo
		fi
	fi

	while (($#))
	do
		case "${1}" in

			-i|--install)

				install_file="bash-logout"
				install_directory="${HOME}"/.local/bin

				source_file="${BASH_SOURCE[0]}"
				target_file="${install_directory}/${install_file}"

				if [ ! -d "${install_directory}" ]
				then
					mkdir -p "${install_directory}"
				fi

				if [ "${source_file}" != "${target_file}" ]
				then
					cp "${source_file}" "${target_file}"

					chmod a+rx "${target_file}"

					source "${target_file}"

					frobulator.scs "Installed" "[ ${target_file} ]"

					echo
				fi
			;;

			-h|--help)

				echo
				echo -e "Usage: ./${script} | [OPTION]"
				echo
				echo "Options:"
				echo
				echo "	-i, --install    Install BASH logout to ${install_directory}"
				echo "	-h, --help       Show this help menu"
				echo

				exit
			;;

			*)

				echo
				echo "${script}: Unknown option '${1}'"
				echo "Type './${script} --help' for help and usage information."
				echo

				exit 1
			;;

		esac

		shift

	done
fi

# logout ///////////////////////////////////////////////////////////////////////

if [ -n "${TERMUX_VERSION}" ]
then
	frobulator.fwd "Logging out..."
	echo

	frobulator.timeout
fi

# dextop ///////////////////////////////////////////////////////////////////////

if [ -n "${TERMUX_VERSION}" ]
then
	# automatic session stop

	if [[ $(cat "${HOME}"/.dextop/dextop-logout) = "logout" ]]
	then
		# audio

		if [[ $(pgrep -f pulseaudio) ]]
		then
			pulseaudio --kill
		fi

		# display

		if [[ $(pgrep -f com.termux.x11) ]]
		then
			container-session -x

			pkill -f com.termux.x11

			pkill -f virgl
		fi
	fi
fi
