#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# adb-settings-put ─────────────────────────────────────────────────────────────

adb_settings_put () {

	adb_download

	adb_set_environment

	setting="${1}"

	adb shell settings put "${setting}"
}
