#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# weather ──────────────────────────────────────────────────────────────────────

weather () {

	url="wttr.in"

	echo

	curl -s "${url}" | head -n -2

	echo

	unset url

}
