#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# list ─────────────────────────────────────────────────────────────────────────

list () {

	directory="${1}"

	local label_directory="directories"
	local label_file="files"

	if [ -z "${directory}" ]
	then
		directory="${PWD}"
	fi

	if [ ! -d "${directory}" ]
	then
		frobulator.err "Directory not found" "[ ${directory} ]"

		return 1
	fi

	ls								\
		-a							\
		-h							\
		-l							\
		--group-directories-first	\
									"${directory}"

	if [ "$(find "${directory}" -type d | wc -l)" -eq 1 ]
	then
		label_directory="directory"
	fi

	if [ "$(find "${directory}" -type f | wc -l) -eq 1 ]
	then
		label_directory="directory"
	fi

	echo
	echo "$(find "${directory}" -type d | wc -l) ${label_directory}"
	echo
	echo "$(find "${directory}" -type f | wc -l) ${label_file}"
	echo

	unset label_directory
	unset label_file
}
