#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# terminate ────────────────────────────────────────────────────────────────────

terminate () {

	local command_pgrep
	local command_pkill
	local process_found

	process_name="${1}"

	# 'pgrep' and 'pkill' paths - empty if not installed

	command_pgrep="$(command -v pgrep)"
	command_pkill="$(command -v pkill)"

	if [ -n "${command_pgrep}" ] &&
	   [ -n "${command_pkill}" ]
	then
		# process ids still matching the name - empty once all are gone

		process_found="$(pgrep -f "${process_name}")"

		while [ -n "${process_found}" ]
		do
			pkill -f "${process_name}"

			process_found="$(pgrep -f "${process_name}")"
		done
	fi
}
