#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# address ──────────────────────────────────────────────────────────────────────

address () {

	local url

	frobulator.require curl

	url="ipinfo.io/ip"

	echo

	curl			\
		--silent	\
		--location	"${url}"

	echo

	unset url
}
