#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# duplicate ────────────────────────────────────────────────────────────────────

duplicate () {

	frobulator.require dd

	dd				\
		if="${1}"	\
		of="${2}"	\
		bs="${3}"	\
		status=progress
}
