#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# countd ───────────────────────────────────────────────────────────────────────

countd () {

	echo "$(find "${PWD}" -maxdepth 1 -type d | wc -l) directories under ${PWD}"

}
