#!/bin/bash

# dextop ///////////////////////////////////////////////////////////////////////

if [ -f "${HOME}"/.dextop/dextop ]
then
	# automatic vnc session stop

	if [[ $(ps -A | grep -i -E *vnc*) ]]
	then
		container-session -x
	fi
fi
