#!/bin/bash

# loaded by "${HOME}"/.local/bin/bash-functions

# when ─────────────────────────────────────────────────────────────────────────

when () {

	local time_current
	local date_current

	time_current=$(date '+%I:%M %p')
	date_current=$(date '+%A, %B %d %Y')

	echo

	echo "It is ${time_current} on ${date_current}"

	echo
}
