#!/bin/bash

script=$(basename -- "${BASH_SOURCE[0]}")

colors="-nb '#000000' -nf '#FFFFFF' -sb '#666666' -sf '#000000'"
lines=15
prompt="OPEN DIRECTORY"

find "${HOME}" -type f -maxdepth 1 -printf "%f\n" | dmenu -i -l "${lines}" -p "${prompt}" "${colors}" | xargs -r st -e ranger --selectfile
