#!/bin/bash

path_selection="${HOME}"

history_file="${HOME}"/.local/bin/.dmenu-navigate-history
history_entry_count=3

open_command='xdg-open'
open_command_terminal='i3-sensible-terminal --working-directory'

lines=50
prompt="${path_selection}"

write_selection_to_history_file () {

    sed -i "\:${1}:d" "${history_file}"

    printf '%s\n' "$1" >> "${history_file}"

    printf '%s\n' "$(tail -n "${history_entry_count}" "${history_file}")" > "${history_file}"
}

selections=(
	'[ Open Terminal Here ]'
	'.'
	'..'
	"$(ls "${path_selection}")"
	"$(cat "${history_file}")"
)

while :
do
	dmenu_result="$(printf '%s\n' "${selections[@]}" | dmenu -i -l "${lines}" -p "${prompt}" -nb '#000000' -nf '#FFFFFF' -sb '#666666' -sf '#000000' "${@}")" || exit 1

	if [ "${dmenu_result}" == '[ Open Terminal Here ]' ]
	then
		"${open_command_terminal}" "${path_selection}"

		write_selection_to_history_file "${path_selection}"

		exit 0

	elif [[ "${dmenu_result}" == '/'* ]]
	then
		path_selection="${dmenu_result}"

	elif [[ "${dmenu_result}" =~ ^(https?|ftps): ]]
	then
		"${open_command}" "${dmenu_result}"

		write_selection_to_history_file "${dmenu_result}"

		exit 0
	else
		path_selection="$(realpath "${path_selection}/${dmenu_result}")"
	fi

	if [ -f "${path_selection}" ] || [ "${dmenu_result}" = '.' ]
	then
		"${open_command}" "${path_selection}"

		write_selection_to_history_file "${path_selection}"

		exit 0

	elif [ -d "${path_selection}" ]
	then
		selections=(
			'[ Open Terminal Here ]'
			'.'
			'..'
			"$(ls "${path_selection}")"
		)
	else
		path_selection="$(dirname "${path_selection}")"
	fi
done
