#!/bin/bash

script=$(basename -- "${BASH_SOURCE[0]}")

lines=15
prompt="SELECTION"

selections="1\n2\n\3\n4"

selection_menu=$(echo -e "${selections}" | dmenu -i -l "${lines}" -p "${prompt}" -nb '#000000' -nf '#FFFFFF' -sb '#666666' -sf '#000000')

case "${selection_menu}" in
	1)

	;;
	2)

	;;
	3)

	;;
	4)

	;;

	*)
		exit
	;;
esac
