#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [ -f "${HOME}"/.local/bin/frobulator ]
then
	rm -r -f "${HOME}"/.local/bin/frobulator
fi

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		SUDO_HOME=/root

		USER="${SUDO_USER}"

		HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${HOME}"/.local/bin ]
	then
		mkdir -p "${HOME}"/.local/bin
	fi

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${HOME}"/.local/bin/frobulator

# superuser ////////////////////////////////////////////////////////////////////

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="10-16-2023"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"

# variables ////////////////////////////////////////////////////////////////////

library_directory=$(pip show py-slvs | grep Location | cut -d ' ' -f 2)

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

list+=(
	system.cfg
	user.cfg
)

if [ -d /media/internal/Printer/freecad/configuration ]
then
	frobulator.inf "Linking configuration"
	echo

	for configuration in ${list[@]}
	do
		frobulator.link /media/internal/Printer/freecad/configuration "${HOME}"/.config/FreeCAD	"${configuration}"

		frobulator.link /media/internal/Printer/freecad/configuration "${HOME}"/.config/FreeCAD freecad.conf FreeCAD.conf
	done
fi

list=()

if [ -d /media/internal/Printer/freecad/macros ]
then
	frobulator.inf "Linking macros"
	echo

		frobulator.link /media/internal/Printer/freecad "${HOME}"/.config/FreeCAD macros
fi
