#!/bin/bash

script=$(basename -- "${BASH_SOURCE[0]}")

terminal="i3-sensible-terminal"
command_file_manager="ranger"

separator=" // "
name_font="Monospace"
size_font=10
font="${name_font}:size=${size_font}"

lines=15
prompt="OPEN DIRECTORY${separator}"

find "${HOME}" -maxdepth 1 -type d -printf "%f\n" | dmenu -i -l "${lines}" -p "${prompt}" -fn "${font}" -nb '#000000' -nf '#FFFFFF' -sb '#666666' -sf '#000000' | xargs -r "${terminal}" -e "${command_file_manager}"
