#!/bin/bash

terminal="i3-sensible-terminal"
file_manager="ranger"

if [[ $(command -v st) ]]
then
	"${terminal}" "${file_manager}"

elif [[ $(command -v gnome-terminal) ]] || \
     [[ $(command -v konsole)        ]] || \
     [[ $(command -v xfce4-terminal) ]]
then
	"${terminal}" -e "${file_manager}"
fi
