#!/bin/bash

script=$(basename -- "${BASH_SOURCE[0]}")

terminal="i3-sensible-terminal"
file_manager="ranger"

separator=" // "
font_name="Sans Regular"
font_size=10
font="${font_name}:size=${font_size}"

lines=15
prompt="OPEN FILE${separator}"

find "${HOME}" -maxdepth 1 -type f -printf "%f\n" | dmenu -i -l "${lines}" -p "${prompt}" -fn "${font}" -nb '#000000' -nf '#FFFFFF' -sb '#666666' -sf '#000000' | xargs -r "${terminal}" -e "${file_manager}" --selectfile
