#!/bin/bash

i3-dmenu-desktop						\
	--dmenu="							\
			dmenu						\
				-b						\
				-i						\
				-p 'LAUNCH //'			\
				-fn 'Monospace:size=10'	\
				-nb '#000000'			\
				-nf '#FFFFFF'			\
				-sb '#666666'			\
				-sf '#000000'			\
			"
