#!/bin/bash

script=$(basename -- "${BASH_SOURCE[0]}")

separator=" // "
name_font="Monospace"
size_font=10
font="${name_font}:size=${size_font}"

lines=15
prompt="LOOKUP${separator}"

dmenu_run -b -i -p  "${prompt}" -nb '#000000' -nf '#FFFFFF' -sb '#666666' -sf '#000000'
