#!/bin/bash

script=$(basename -- "${BASH_SOURCE[0]}")

terminal="i3-sensible-terminal"

separator=" // "
name_font="Monospace"
size_font=10
font="${name_font}:size=${size_font}"

lines=30
prompt="MANUALS${separator}"

man -k . | tr [:upper:] [:lower:] | sed 's/[)(]//g' | sed 's/[0-9]//g' | awk -F "- " '{printf "%-90s%s\n", $1,$2}' | dmenu -i -l "${lines}" -p "${prompt}" -fn "${font}" -nb '#000000' -nf '#FFFFFF' -sb '#666666' -sf '#000000' | xargs -r "${terminal}" -e man
