#!/usr/bin/bash

terminal="i3-sensible-terminal"
editor="i3-sensible-editor"

notes_directory="${HOME}"/.notes

if [[ ! -d "${notes_directory}" ]]
then
    mkdir -p "${notes_directory}"
fi

separator=" // "
font_name="Monospace"
font_size=10
font="${font_name}:size=${font_size}"

lines=15
prompt="NOTES${separator}"

list="$(find -L ${notes_directory} -maxdepth 1 -type f | sed 's|^"${notes_directory}/""||' | sort)"

selection="$(echo -e "${list}" | dmenu -i -l "${lines}" -p "${prompt}" -fn "${font}" -nb '#000000' -nf '#FFFFFF' -sb '#666666' -sf '#000000')"

note_slugger () {

echo ${@} | tr -d '[:punct:]'   \
        | sed -e "s/ /-/g"      \
              -e "s/[áàãâ]/a/g" \
              -e "s/[éê]/e/g"   \
              -e "s/[íÍ]/i/g"   \
              -e "s/[óõô]/o/g"  \
              -e "s/[úü]/u/g"   \
              -e "s/[ç]/c/g"
}

note_create () {

    extension="md"

    file_name="$(note_slugger "${1,,}")"

    file_name="${file_name}.${extension}"

    note="${notes_directory}/${file_name}"

    title="${1,,}"

    title=${title^^}

    echo -e "# ${title}\n\n" > "${note}"

    notify-send -i "Notes" "New note" "Note <b>$file_name.md</b> was created under '${notes_directory}'"
}

note_open () {

    note_selection="${notes_directory}/${selection}"

    if [[ ! -f "${note_selection}" ]]
    then
        note_create "${selection}"
    else
        note="${note_selection}"
    fi

    eval "$(${terminal} -T "Notes" -e "${editor} +$(wc -l ${note}) ${note}")"
}

if [[ ! -z "${selection}" ]]
then
    note_open
fi
