#!/bin/bash

path_selection="${HOME}"

lines=60
prompt="CURRENT DIRECTORY${separator}${path_selection}"
separator=" // "

history_entry_count=3
history_file="${HOME}"/.local/bin/.i3-navigate-history

file_manager="ranger"
terminal="i3-sensible-terminal"

list="ls -a"
read="cat"

handler_open () {

	xdg-open "${@}"
}

terminal_open () {

	"${terminal}" --working-directory="${@}"
}

terminal_open_visual () {

	"${terminal}" --command="${file_manager} ${@}"
}

history_write () {

	history_entry="${1}"

	sed -i "\:${history_entry}:d" "${history_file}"

	printf '%s\n' "${history_entry}" >> "${history_file}"

	printf '%s\n' "$(tail -n "${history_entry_count}" "${history_file}")" > "${history_file}"
}


selections_parse () {

	working_directory="${path_selection}"

	label_selections_empty=''
	label_selections_separator='////////////////////////////////////////////////////////////////////////////////'

	label_selections_working_directory="DIRECTORY${separator}${working_directory}"
	label_selections_history='[ History ]  ↴'
	label_selections_terminal='[ Open Terminal Here ]'
	label_selections_terminal_visual='[ Open Visual Terminal Here ]'

	selections=(
		"${label_selections_working_directory}"
		"${label_selections_empty}"
		"${label_selections_terminal}"
		"${label_selections_terminal_visual}"
		"${label_selections_empty}"
		"$(${list} "${path_selection}")"
		"${label_selections_empty}"
		"${label_selections_history}"
		"${label_selections_empty}"
		"$(${read} "${history_file}")"
	)

	IFS=$"\n"

	for selection in "${selections[@]}"
	do
		echo "${selection}"
	done

	IFS=""

	selections=()
}

while :
do
	navigation="$(selections_parse | dmenu -i -l "${lines}" -p "${prompt}" -nb '#000000' -nf '#FFFFFF' -sb '#666666' -sf '#000000' "${@}")" || exit 1

	if [ "${navigation}" == '[ Open Terminal Here ]' ]
	then
		terminal_open "${path_selection}"

		history_write "${path_selection}"

	elif [ "${navigation}" == '[ Open Visual Terminal Here ]' ]
	then
		terminal_open_visual "${path_selection}"

		history_write "${path_selection}"

	elif [[ "${navigation}" == '/'* ]]
	then
		path_selection="${navigation}"

	elif [[ "${navigation}" =~ ^(https?|ftps): ]]
	then
		handler_open "${navigation}"

		history_write "${navigation}"

	else
		path_selection="$(realpath "${path_selection}/${navigation}")"
	fi

	if [ -f "${path_selection}" ] || [ "${navigation}" = '.' ]
	then
		handler_open "${path_selection}"

		history_write "${path_selection}"

	elif [ -d "${path_selection}" ]
	then
		selections=(
			"${label_selections_working_directory}"
			"${label_selections_empty}"
			"${label_selections_terminal}"
			"${label_selections_terminal_visual}"
			"${label_selections_empty}"
			"$(${list} "${path_selection}")"
		)
	else
		path_selection="$(dirname "${path_selection}")"
	fi
done
