#!/usr/bin/bash

terminal="i3-sensible-terminal"
editor="i3-sensible-editor"

directory_notes="${HOME}"/.notes

if [[ ! -d "${directory_notes}" ]]
then
    mkdir -p "${directory_notes}"
fi

separator=" // "
name_font="Monospace"
size_font=10
font="${name_font}:size=${size_font}"

lines=15
prompt="NOTES${separator}"

list="$(find -L ${directory_notes} -maxdepth 1 -type f | sed 's|^"${directory_notes}/""||' | sort)"

selection="$(echo -e "${list}" | dmenu -i -l "${lines}" -p "${prompt}" -fn "${font}" -nb '#000000' -nf '#FFFFFF' -sb '#666666' -sf '#000000')"

note_slugger () {

echo ${@} | tr -d '[:punct:]'   \
        | sed -e "s/ /-/g"      \
              -e "s/[áàãâ]/a/g" \
              -e "s/[éê]/e/g"   \
              -e "s/[íÍ]/i/g"   \
              -e "s/[óõô]/o/g"  \
              -e "s/[úü]/u/g"   \
              -e "s/[ç]/c/g"
}

note_create () {

    extension="md"

    name_file_note="$(note_slugger "${1,,}")"

    name_file_note="${name_file_note}.${extension}"

    note="${directory_notes}/${name_file_note}"

    title="${1,,}"

    title=${title^^}

    echo -e "# ${title}\n\n" > "${note}"

    notify-send -i "Notes" "New note" "Note <b>$name_file_note.md</b> was created under '${directory_notes}'"
}

note_open () {

    file_note_selection="${directory_notes}/${selection}"

    if [[ ! -f "${file_note_selection}" ]]
    then
        note_create "${selection}"
    else
        note="${file_note_selection}"
    fi

    count_lines_note="$(wc -l < "${note}")"

    eval "$(${terminal} -T "Notes" -e "${editor} +${count_lines_note} ${note}")"
}

if [[ ! -z "${selection}" ]]
then
    note_open
fi
