#!/bin/bash

selection_navigation="${HOME}"

separator=" // "
name_font="Monospace"
size_font=10
font="${name_font}:size=${size_font}"

lines=60
prompt="NAVIGATION${separator}"

count_entries_history=3
file_history="${HOME}"/.local/bin/.i3-navigation-history

command_file_manager="ranger"
terminal="i3-sensible-terminal"

list="ls -a"
read="cat"

handler_open () {

	xdg-open "${@}"
}

terminal_open () {

	"${terminal}" -e "${@}"
}

terminal_open_visual () {

	"${terminal}" -e "${command_file_manager} ${@}"
}

history_write () {

	entry_history="${1}"

	sed -i "\:${entry_history}:d" "${file_history}"

	printf '%s\n' "${entry_history}" >> "${file_history}"

	printf '%s\n' "$(tail -n "${count_entries_history}" "${file_history}")" > "${file_history}"
}


selections_parse () {

	directory_working="${selection_navigation}"

	label_selections_empty=''
	label_selections_separator='////////////////////////////////////////////////////////////////////////////////'

	label_selections_working_directory="DIRECTORY${separator}${directory_working}"
	label_selections_history='[ History ]  ↴'
	label_selections_terminal='[ Open Terminal Here ]'
	label_selections_terminal_visual='[ Open Visual Terminal Here ]'

	selections=(
		"${label_selections_working_directory}"
		"${label_selections_empty}"
		"${label_selections_terminal}"
		"${label_selections_terminal_visual}"
		"${label_selections_empty}"
		"$(${list} "${selection_navigation}")"
		"${label_selections_empty}"
		"${label_selections_history}"
		"${label_selections_empty}"
		"$(${read} "${file_history}")"
	)

	IFS=$"\n"

	for selection in "${selections[@]}"
	do
		echo "${selection}"
	done

	IFS=""

	selections=()
}

while :
do
	selection="$(selections_parse | dmenu -i -l "${lines}" -p "${prompt}" -fn "${font}" -nb '#000000' -nf '#FFFFFF' -sb '#666666' -sf '#000000' "${@}")" || exit 1

	if [ "${selection}" == '[ Open Terminal Here ]' ]
	then
		terminal_open "${selection_navigation}"

		history_write "${selection_navigation}"

	elif [ "${selection}" == '[ Open Visual Terminal Here ]' ]
	then
		terminal_open_visual "${selection_navigation}"

		history_write "${selection_navigation}"

	elif [[ "${selection}" == '/'* ]]
	then
		selection_navigation="${selection}"

	elif [[ "${selection}" =~ ^(https?|ftps): ]]
	then
		handler_open "${selection}"

		history_write "${selection}"

	else
		selection_navigation="$(realpath "${selection_navigation}/${selection}")"
	fi

	if [ -f "${selection_navigation}" ] || [ "${selection}" = '.' ]
	then
		handler_open "${selection_navigation}"

		history_write "${selection_navigation}"

	elif [ -d "${selection_navigation}" ]
	then
		selections=(
			"${label_selections_working_directory}"
			"${label_selections_empty}"
			"${label_selections_terminal}"
			"${label_selections_terminal_visual}"
			"${label_selections_empty}"
			"$(${list} "${selection_navigation}")"
		)
	else
		selection_navigation="$(dirname "${selection_navigation}")"
	fi
done
