#!/usr/bin/bash

lines=30
separator=" // "
prompt="TYPE TO SEARCH - SELECT TO TERMINATE${separator}"

selection="$(ps all | dmenu -i -l "${lines}" -p "${prompt}" -nb '#000000' -nf '#FFFFFF' -sb '#666666' -sf '#000000' | awk '{print $1" "$4}')"

if [[ ! -z "${selection}" ]]
then
	prompt="SELECTION >>> ${selection} // TERMINATE?"

    answer="$(echo -e "NO\NYES" | dmenu -i -l "${lines}" -p "${prompt}" -nb '#000000' -nf '#FFFFFF' -sb '#666666' -sf '#000000')"

    if [[ "${answer}" == "YES" ]]
    then
        process_selection="$(awk '{print $1}' <<< "${selection}")"

        kill -9 "${process_selection}"
    fi
fi
