#!/usr/bin/bash

separator=" // "
name_font="Monospace"
size_font=10
font="${name_font}:size=${size_font}"

lines=30
prompt="TYPE TO SEARCH - SELECT TO TERMINATE${separator}"

selection="$(ps all | dmenu -i -l "${lines}" -p "${prompt}" -fn "${font}" -nb '#000000' -nf '#FFFFFF' -sb '#666666' -sf '#000000' | awk '{print $1" "$4}')"

if [[ ! -z "${selection}" ]]
then
	prompt="SELECTION >>> ${selection} // TERMINATE?"

    answer="$(echo -e "NO\NYES" | dmenu -i -l "${lines}" -p "${prompt}" -fn "${font}" -nb '#000000' -nf '#FFFFFF' -sb '#666666' -sf '#000000')"

    if [[ "${answer}" == "YES" ]]
    then
        id_process_selection="$(awk '{print $1}' <<< "${selection}")"

        kill -9 "${id_process_selection}"
    fi
fi
