#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		SUDO_HOME=/root

		USER="${SUDO_USER}"

		HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${HOME}"/.local/bin ]
	then
		mkdir -p "${HOME}"/.local/bin
	fi

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${HOME}"/.local/bin/frobulator

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="12-28-2024"

# usage ////////////////////////////////////////////////////////////////////////

# load interface files

interface_list+=(
	i3-configuration
	i3status-configuration
	i3-backgrounds
	i3-confirm
	i3-directory
	i3-exit
	i3-file
	i3-file-manager
	i3-launch
	i3-lookup
	i3-manuals
	i3-navigation
	i3-notes
	i3-shortcuts
	i3-status
	i3-template
	i3-terminate
)


frobulator.download get.trmnl.me "${HOME}"/.local/bin ${interface_list[@]}

# link configuration files

frobulator.link "${HOME}"/.local/bin "${HOME}"/.config/i3          i3-configuration          config
frobulator.link "${HOME}"/.local/bin "${HOME}"/.config/i3status    i3status-configuration    config

interface_list=()
