#!/bin/bash

indent="	"
separator=" // "
joiner=" > "

decimal_calculate () {

	value="${1}"
	factor_decimal="${2}"

	scale=$(bc <<< "scale=2; ${value} / ${factor_decimal}")

	echo "${scale}"

	unset value
}

memory_convert () {

	value="${1}"

	unit_from="${2}"
	unit_to="${3}"

	unit_memory="${unit_to}"

	case "${unit_from}"
	in
		KB)
			case "${unit_to}"
			in
				KB)
					echo "${value}"
				;;

				MB)
					echo "${value} / 1024" | bc
				;;

				GB)
					echo "${value} / 1024 / 1024" | bc
				;;

				TB)
					echo "${value} / 1024 / 1024 / 1024" | bc
				;;

				*)
					echo "Invalid unit_to: ${unit_to}"

					exit 1
				;;

			esac

			;;

		MB)
			case "${unit_to}"
			in
				KB)
					echo "${value} * 1024" | bc -l
				;;

				MB)
					echo "${value}"
				;;

				GB)
					echo "${value} / 1024" | bc -l
				;;

				TB)
					echo "${value} / 1024 / 1024" | bc -l
				;;

				*)
					echo "Invalid unit_to: ${unit_to}"

					exit 1
				;;

			esac

			;;

		GB)
			case "${unit_to}"
			in
				KB)
					echo "${value} * 1024 * 1024" | bc -l
				;;

				MB)
					echo "${value} * 1024" | bc -l
				;;

				GB)
					echo "${value}"
				;;

				TB)
					echo "${value} / 1024" | bc -l
				;;

				*)
					echo "Invalid unit_to: ${unit_to}"

					exit 1
				;;

			esac

			;;

		TB)
			case "${unit_to}"
			in
				KB)
					echo "${value} * 1024 * 1024 * 1024" | bc -l
				;;

				MB)
					echo "${value} * 1024 * 1024" | bc -l
				;;

				GB)
					echo "${value} * 1024" | bc -l
				;;

				TB)
					echo "${value}"
				;;

				*)
					echo "Invalid unit_to: ${unit_to}"

					exit 1
				;;

			esac

			;;

		*)
			echo "Invalid unit_from: ${unit_from}"

			exit 1
		;;

	esac

	unset value

}

uevent_parse () {

	name_uevent="${1}"
	directory_uevent="${2}"

	cat "${directory_uevent}" | grep -i "${name_uevent}=" | cut -d '=' -f 2

}

system_event_parse () {

	name_system_event="${1}"
	directory_system_event="${2}"

	cat "${directory_system_event}/${name_system_event}"

}

status_date () {

	#date_current=$(date +"%F")
	date_current=$(date +"%m-%d-%Y")

	status+="${date_current}${separator}"
}

status_time () {

	time_current=$(date +"%r")

	status+="${time_current}${separator}"
}

status_host () {

	if [ "$HOSTNAME" = "localhost" ]
	then
		HOSTNAME="Android"
	fi

	if [ -z "${USER}" ]
	then
		USER="termux"
	fi

	HOSTNAME="${HOSTNAME^^}"

	USER="${USER^^}"

	status+="${USER}${joiner}${HOSTNAME}${separator}"

}

status_battery () {

	# battery - system

	# capacity_battery=$(system_event_parse capacity /sys/class/power_supply/battery)
	# battery_charge_counter=$(system_event_parse charge_counter /sys/class/power_supply/battery)
	# battery_charge_counter_shadow=$(system_event_parse charge_counter_shadow /sys/class/power_supply/battery)
	# battery_charge_full=$(system_event_parse charge_full /sys/class/power_supply/battery)
	# battery_charge_full_design=$(system_event_parse charge_full_design /sys/class/power_supply/battery)
	# battery_charge_now=$(system_event_parse charge_now /sys/class/power_supply/battery)
	# battery_charge_type=$(system_event_parse charge_type /sys/class/power_supply/battery)
	# battery_charge_uno_control=$(system_event_parse charge_uno_control /sys/class/power_supply/battery)
	# battery_charge_utg_control=$(system_event_parse charge_utg_control /sys/class/power_supply/battery)
	# battery_current_average=$(system_event_parse current_avg /sys/class/power_supply/battery)
	# battery_current_now=$(system_event_parse current_now /sys/class/power_supply/battery)
	# health_battery=$(system_event_parse health /sys/class/power_supply/battery)
	# battery_power_average=$(system_event_parse power_avg /sys/class/power_supply/battery)
	# battery_power_now=$(system_event_parse power_now /sys/class/power_supply/battery)
	# battery_present=$(system_event_parse present /sys/class/power_supply/battery)
	# battery_present=$(system_event_parse present /sys/class/power_supply/battery)
	# battery_status=$(system_event_parse status /sys/class/power_supply/battery)
	# battery_technology=$(system_event_parse technology /sys/class/power_supply/battery)
	# temperature_battery=$(system_event_parse temp /sys/class/power_supply/battery)
	# battery_time_online=$(system_event_parse online /sys/class/power_supply/battery)
	# battery_time_to_full=$(system_event_parse time_to_full_now /sys/class/power_supply/battery)
	# battery_voltage=$(system_event_parse voltage /sys/class/power_supply/battery)
	# battery_voltage_average=$(system_event_parse voltage_avg /sys/class/power_supply/battery)
	# battery_voltage_now=$(system_event_parse voltage_now /sys/class/power_supply/battery)

	# battery - uevent

	# battery_capacity_uevent=$(uevent_parse capacity /sys/class/power_supply/battery/uevent)
	# battery_charge_counter_shadow_uevent=$(uevent_parse charge_counter_shadow /sys/class/power_supply/battery/uevent)
	# battery_charge_counter_uevent=$(uevent_parse charge_counter /sys/class/power_supply/battery/uevent)
	# battery_charge_full_design_uevent=$(uevent_parse charge_full_design /sys/class/power_supply/battery/uevent)
	# battery_charge_full_uevent=$(uevent_parse charge_full /sys/class/power_supply/battery/uevent)
	# battery_charge_now_uevent=$(uevent_parse charge_now /sys/class/power_supply/battery/uevent)
	# battery_charge_otg_control_uevent=$(uevent_parse charge_otg_control /sys/class/power_supply/battery/uevent)
	# battery_charge_type_uevent=$(uevent_parse charge_type /sys/class/power_supply/battery/uevent)
	# battery_charge_uno_control_uevent=$(uevent_parse charge_uno_control /sys/class/power_supply/battery/uevent)
	# battery_current_average_uevent=$(uevent_parse current_avg /sys/class/power_supply/battery/uevent)
	# battery_current_now_uevent=$(uevent_parse current_now /sys/class/power_supply/battery/uevent)
	# battery_health_uevent=$(uevent_parse health /sys/class/power_supply/battery/uevent)
	# battery_name_uevent=$(uevent_parse name /sys/class/power_supply/battery/uevent)
	# battery_online_uevent=$(uevent_parse online /sys/class/power_supply/battery/uevent)
	# battery_power_average_uevent=$(uevent_parse power_average /sys/class/power_supply/battery/uevent)
	# battery_power_now_uevent=$(uevent_parse power_now /sys/class/power_supply/battery/uevent)
	# battery_present_uevent=$(uevent_parse present /sys/class/power_supply/battery/uevent)
	# battery_status_uevent=$(uevent_parse status /sys/class/power_supply/battery/uevent)
	# battery_technology_uevent=$(uevent_parse technology /sys/class/power_supply/battery/uevent)
	# battery_temperature_ambient_uevent=$(uevent_parse temp_ambient /sys/class/power_supply/battery/uevent)
	# battery_temperature_uevent=$(uevent_parse temp /sys/class/power_supply/battery/uevent)
	# battery_time_to_full_uevent=$(uevent_parse time_to_full /sys/class/power_supply/battery/uevent)
	# battery_voltage_average_uevent=$(uevent_parse voltage_avg /sys/class/power_supply/battery/uevent)
	# battery_voltage_now_uevent=$(uevent_parse voltage_now /sys/class/power_supply/battery/uevent)

	if [[ -f /sys/class/power_supply/battery ]]
	then
		capacity_battery=$(system_event_parse capacity /sys/class/power_supply/battery)

		unit_capacity_battery="%"

		temperature_battery=$(system_event_parse temp /sys/class/power_supply/battery)
		temperature_battery=$(decimal_calculate "${temperature_battery}" 10)

		unit_temperature_battery="°C"

		status+="BATTERY ${capacity_battery}${unit_capacity_battery}${separator}"
		status+="TEMPERATURE ${temperature_battery}${unit_temperature_battery}${separator}"
	fi

}

status_cpu_temperature () {

	count_cpu=$(nproc)

	for (( i = 0 ; i < ${count_cpu} ; i ++ ))
	do
		path_temperature_cpu="/sys/class/thermal/thermal_zone${i}/temp"

		if [ -f "${path_temperature_cpu}" ]
		then
			temperature_cpu=$(cat "${path_temperature_cpu}")
			temperature_cpu=$(decimal_calculate "${temperature_cpu}" 1000)

			unit_temperature_cpu="°C"

			status+="CPU${i} ${temperature_cpu}${unit_temperature_cpu}${separator}"
		fi
	done

}

status_memory_information () {

	unit_memory="GB"

	memory_total=$(grep -i 'memtotal' /proc/meminfo | awk '{print $2}')
	memory_available=$(grep -i 'memavailable' /proc/meminfo | awk '{print $2}')

	memory_used=$(( ${memory_total} - ${memory_available} ))

	memory_total=$(memory_convert ${memory_total} KB "${unit_memory}")
	memory_available=$(memory_convert ${memory_available} KB "${unit_memory}")
	memory_used=$(memory_convert ${memory_used} KB "${unit_memory}")

	unit_memory="${unit_memory^^}"

	percentage_memory_available=$(echo "scale=2; (${memory_available} / ${memory_total}) * 100" | bc)
	percentage_memory_used=$(echo "scale=2; (${memory_used} / ${memory_total}) * 100" | bc)

	unit_percentage_memory="%"

	status+="MEMORY TOTAL ${memory_total}${unit_memory}${joiner}"
	status+="MEMORY USED ${memory_used}${unit_memory} [ ${percentage_memory_used}${unit_percentage_memory} ]${joiner}"
	status+="MEMORY AVAILABLE ${memory_available}${unit_memory} [ ${percentage_memory_available}${unit_percentage_memory} ]${separator}"

}


status_network_information () {

	route_default=$(ip route | grep 'default')

	if [[ -n "${route_default}" ]]
	then
		device_interface_network=$(ip route | grep '^default' | cut -d ' ' -f 5)
		gateway_interface_network=$(ip route | grep '^default' | cut -d ' ' -f 3)
		address_interface_network=$(ip route | grep '^default' | cut -d ' ' -f 9)

		device_interface_network="${device_interface_network^^}"

		status+="INTERFACE ${device_interface_network}${joiner}"
		status+="GATEWAY ${gateway_interface_network}${joiner}"
		status+="IP ${address_interface_network}${separator}"
	else
		status+="Network: Disconnected${separator}"
	fi
}

status_feed () {

	i3status | while :
	do
		status_host

		status_time

		status_date

		status_battery

		status_cpu_temperature

		status_memory_information

		status_network_information

		echo -e "${status}${indent}"

		unset status

		sleep 1

	done
}

status_feed
