#!/bin/bash

script=$(basename -- "${BASH_SOURCE[0]}")

shortcuts='
[ Modifier ]            Modifier                                                Alt-Left Key

[ Bar ]                 Show bar                                                Modifier

[ Launch ]              Open launcher                                           Modifier + Space

[ Lookup ]              Open file [l]ookup                                      Modifier + L

[ Shortcuts ]           Show shortcuts [i]nformation                            Modifier + Shift + I

[ Backgrounds ]         Change back[g]round image                               Modifier + G

[ Files ]               Open file manager                                       Modifier + M

[ Manuals ]             System manuals [q]uery                                  Modifier + Q

[ Navigation ]          N[a]vigate filesystem                                   Modifier + A

[ Notes ]               Open / take [n]otes                                     Modifier + N

[ Processes ]           Search / terminate proc[e]ss                            Modifier + E

[ Terminal ]            Open [t]erminal                                         Modifier + T

[ Terminate ]           Terminate focused application instance                  Modifier + X

[ Window Focus ]        Change focus [up]                                       Modifier + Up
                        Change focus [left]                                     Modifier + Left
                        Change focus [down]                                     Modifier + Down
                        Change focus [right]                                    Modifier + Right

[ Window Move]          Move focused window [up]                                Modifier + Shift + Up
                        Move focused window [left]                              Modifier + Shift + Left
                        Move focused window [down]                              Modifier + Shift + Down
                        Move focused window [right]                             Modifier + Shift + Right

[ Window Layout ]       Move floating window                                    Modifier + Mouse

                        Toggle [f]ullscreen windows                             Modifier + F
                        Toggle floating [w]indows                               Modifier + W
                        Change [w]indow focus - tiling / floating               Modifier + Shift + W

[ Container Layout ]    Change container layout  - [s]plit                      Modifier + S
                        Change container layout  - stac[k]                      Modifier + K
                        Change container layout  - ta[b]                        Modifier + B

                        Split container - [h]orizontal layout                   Modifier + H
                        Split container - [v]ertical layout                     Modifier + V

                        Focus [p]arent container                                Modifier + P
                        Focus [c]hild container                                 Modifier + C

                        Move floating container to [a]bsolute center            Modifier + Shift + A
                        Move container to current [m]ouse cursor position       Modifier + Shift + M

[ Workspaces ]          Switch to workspace [1]                                 Modifier + 1
                        Switch to workspace [2]                                 Modifier + 2
                        Switch to workspace [3]                                 Modifier + 3
                        Switch to workspace [4]                                 Modifier + 4
                        Switch to workspace [5]                                 Modifier + 5
                        Switch to workspace [6]                                 Modifier + 6
                        Switch to workspace [7]                                 Modifier + 7
                        Switch to workspace [8]                                 Modifier + 8

                        Move container to workspace [1]                         Modifier + Shift + 1
                        Move container to workspace [2]                         Modifier + Shift + 2
                        Move container to workspace [3]                         Modifier + Shift + 3
                        Move container to workspace [4]                         Modifier + Shift + 4
                        Move container to workspace [5]                         Modifier + Shift + 5
                        Move container to workspace [6]                         Modifier + Shift + 6
                        Move container to workspace [7]                         Modifier + Shift + 7
                        Move container to workspace [8]                         Modifier + Shift + 8

[ Gaps ]                Enter [g]aps management mode                            Modifier + Shift + G

[ Resize Mode ]         Enter tile resi[z]e mode                                Modifier + Z

                        Resize - reset window to configured size                Modifier + Shift + Z
                        Resize - shrink window height by 10 px                  Up
                        Resize - shrink window width by 10 px                   Left
                        Resize - grow window height by 10 px                    Down
                        Resize - grow window width by 10 px                     Right
                        Resize - Exit resi[z]e mode                             Modifier + Z

[ Session ]             [R]eload i3 configuration                               Modifier + R
                        [R]estart i3                                            Modifier + Shift + R
                        [E]xit i3                                               Modifier + Shift + E

'

separator=" // "
font_name="Monospace"
font_size=10
font="${font_name}:size=${font_size}"

lines=$(echo "${shortcuts}" | wc -l)
prompt="SHORTCUTS${separator}"

indent='                        '

shortcuts_parse () {

    while read line
    do
        if [[ ! "${line}" =~ ^\[ ]]
        then
            line="${indent}${line}"
        fi

        echo "${line}"

    done <<< "${shortcuts}"
}

shortcuts_parse | dmenu -i -l "${lines}" -p "${prompt}" -fn "${font}" -nb '#000000' -nf '#FFFFFF' -sb '#666666' -sf '#000000'
