#!/bin/bash

indent="    "
separator=" // "

timer_increment=0

calculate () {

	value="${1}"
	decimal="${2}"

	denominator=$(( 10 ** ${decimal} ))

	return=$(( ${value}/${denominator} ))
}

uevent_parse () {

	uevent="${1}"
	uevent_directory="${2}"

	cat "${uevent_directory}" | grep -i "${uevent}\=" | cut -d '=' -f 2

}

values () {

	timer=$(date +%s)
	timer_interval=$(( $timer - $timer_increment ))

	date=$(date +"%F")
	time=$(date +"%r")

	# battery - uevent

	battery_name_uevent=$(uevent_parse name /sys/class/power_supply/battery/uevent)
	battery_status_uevent=$(uevent_parse status /sys/class/power_supply/battery/uevent)
	battery_charge_type_uevent=$(uevent_parse charge_type /sys/class/power_supply/battery/uevent)
	battery_health_uevent=$(uevent_parse health /sys/class/power_supply/battery/uevent)
	battery_present_uevent=$(uevent_parse present /sys/class/power_supply/battery/uevent)
	battery_online_uevent=$(uevent_parse online /sys/class/power_supply/battery/uevent)
	battery_technology_uevent=$(uevent_parse technology /sys/class/power_supply/battery/uevent)
	battery_voltage_now_uevent=$(uevent_parse voltage_now /sys/class/power_supply/battery/uevent)
	battery_voltage_average_uevent=$(uevent_parse voltage_avg /sys/class/power_supply/battery/uevent)
	battery_current_now_uevent=$(uevent_parse current_now /sys/class/power_supply/battery/uevent)
	battery_current_average_uevent=$(uevent_parse current_avg /sys/class/power_supply/battery/uevent)
	battery_charge_full_design_uevent=$(uevent_parse charge_full_design /sys/class/power_supply/battery/uevent)
	battery_charge_full_uevent=$(uevent_parse charge_full /sys/class/power_supply/battery/uevent)
	battery_charge_now_uevent=$(uevent_parse charge_now /sys/class/power_supply/battery/uevent)
	battery_capacity_uevent=$(uevent_parse capacity /sys/class/power_supply/battery/uevent)
	battery_temperature_uevent=$(uevent_parse temp /sys/class/power_supply/battery/uevent)
	battery_temperature_ambient_uevent=$(uevent_parse temp_ambient /sys/class/power_supply/battery/uevent)
	battery_power_now_uevent=$(uevent_parse power_now /sys/class/power_supply/battery/uevent)
	battery_power_average=$(uevent_parse power_average /sys/class/power_supply/battery/uevent)



	# battery - system

	battery_charge_utg_control=$(cat /sys/class/power_supply/battery/charge_utg_control)
	battery_charge_uno_control=$(cat /sys/class/power_supply/battery/charge_uno_control)
	battery_charge_now=$(cat /sys/class/power_supply/battery/charge_now)
	battery_charge_full_design=$(cat /sys/class/power_supply/battery/charge_full_design)
	battery_charge_full=$(cat /sys/class/power_supply/battery/charge_full)
	battery_charge_counter=$(cat /sys/class/power_supply/battery/charge_counter)
	battery_charge_counter_shadow=$(cat /sys/class/power_supply/battery/charge_counter_shadow)
	battery_time_online=$(cat /sys/class/power_supply/battery/online)
	battery_time_to_full=$(cat /sys/class/power_supply/battery/time_to_full_now)
	battery_power_now=$(cat /sys/class/power_supply/battery/power_now)
	battery_power_average=$(cat /sys/class/power_supply/battery/power_avg)
	battery_current_now=$(cat /sys/class/power_supply/battery/current_now)
	battery_current_average=$(cat /sys/class/power_supply/battery/current_avg)
	battery_voltage_now=$(cat /sys/class/power_supply/battery/voltage_now)
	battery_voltage_average=$(cat /sys/class/power_supply/battery/voltage_avg)
	battery_present=$(cat /sys/class/power_supply/battery/present)
	battery_charge_type=$(cat /sys/class/power_supply/battery/charge_type)
	battery_capacity=$(cat /sys/class/power_supply/battery/capacity)
	battery_status=$(cat /sys/class/power_supply/battery/status)
	battery_health=$(cat /sys/class/power_supply/battery/health)
	battery_present=$(cat /sys/class/power_supply/battery/present)
	battery_voltage=$(cat /sys/class/power_supply/battery/voltage)
	battery_temperature=$(cat /sys/class/power_supply/battery/temp)
	battery_technology=$(cat /sys/class/power_supply/battery/technology)

	# parse values

	if [[ "${battery_present}" = "0" ]]
	then
		battery_present="no"

	elif [[ "${battery_present}" = "1" ]]
	then
		battery_present="yes"
	fi

	battery_temperature_unit="°C"
	battery_temperature=$(( ${battery_temperature} / 10 ))

	battery_charge_unit="Wh"
	battery_charge_counter=$(( ${battery_charge_counter} / 100000 ))

	# system

	if [ "$HOSTNAME" = "localhost" ]
	then
		HOSTANME="Android"
	fi

	if [ -z "${USER}" ]
	then
		USER="termux"
	fi

	# increment timer

	timer_increment=${timer}
}

# generate status feed

i3status | while :
do
	values

	echo -e "${time}${separator}${date}${separator}${battery_capacity_uevent}${indent}"
done
