#!/bin/bash

set -x

# dependencies /////////////////////////////////////////////////////////////////

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		SUDO_HOME=/root

		USER="${SUDO_USER}"

		HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${HOME}"/.local/bin ]
	then
		mkdir -p "${HOME}"/.local/bin
	fi

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${HOME}"/.local/bin/frobulator

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="01-03-2025"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"

# variables ////////////////////////////////////////////////////////////////////

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

i3_list+=(
	i3
	i3status
)

i3_addons_list+=(
	dmenu
	feh
	rofi
	stterm
)

# install #

install_list+=(
	${i3_list[@]}
	${i3_addons_list[@]}
)

frobulator.install ${install_list[@]}

install_list=()

# load interface files

interface_list+=(
	i3-configuration
	i3status-configuration
	i3-backgrounds
	i3-confirm
	i3-directory
	i3-exit
	i3-file
	i3-file-manager
	i3-launch
	i3-lookup
	i3-manuals
	i3-navigation
	i3-notes
	i3-processes
	i3-shortcuts
	i3-status
	i3-template
)

frobulator.download get.trmnl.me "${HOME}"/.local/bin ${interface_list[@]}

interface_list=()

# link configuration files

frobulator.link "${HOME}"/.local/bin "${HOME}"/.config/i3          i3-configuration          config
frobulator.link "${HOME}"/.local/bin "${HOME}"/.config/i3status    i3status-configuration    config

