#!/bin/bash

# dependencies #

[[ -z $(command -v frobulator) ]] && curl -s -L get.frbltr.app > "${PREFIX}"/bin/frobulator

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

# usage #

# prompt #

# variables #

# defaults

# update icon cache

icons_directory_list=(
	"${HOME}"/.icons
	"${PREFIX}"/share/icons
	/usr/share/icons
)

for icons_directory in ${icons_directory_list[@]}
do
	[ -d "${icons_directory}" ] && cd "${icons_directory}"

	if [ -d "${icons_directory}" ]
	then
		find "${icons_directory}" -mindepth 1 -maxdepth 1 -type d | while read -r theme
		do
			if [ -f "${theme}"/index.theme ]
			then
				theme_name="${theme##*/}"

				gtk-update-icon-cache -f -q "${theme}"

				frobulate.scs "Cache update success" "[ ${theme_name} ]"
				echo
			else
				frobulate.wrn "Skipping" "[ ${theme_name} ]"
				echo
			fi
		done
	fi
done
