#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

ticker () {

	echo

	for ticker in '>  ' '>> ' '>>>'
	do
		echo -n -e "\r[  ${ticker}  ] ${1^}..."

		sleep 0.5
	done

	echo

	echo

}

if [[ $(id -u -n) = "root" ]]
then
	USER="${SUDO_USER:-root}"

	if [ "${USER}" = "root" ]
	then
		HOME=/root
	else
		HOME="/home/${USER}"
	fi
fi

ticker checking

package_managers_list=(
	"apt-get --quiet --quiet update > /dev/null 2>&1; apt-get --quiet --quiet install --yes"
	"dnf --quiet install --assumeyes"
	"yum --quiet install --assumeyes"
	"apk add --quiet"
	"pacman --sync --refresh --noconfirm --noprogressbar"
	"zypper --quiet --non-interactive install"
)

package="curl"

if [[ -z $(command -v "${package}") ]]
then
	for package_manager in "${package_managers_list[@]}"
	do
		entry="${package_manager%% *}"

		if [[ -n $(command -v "${entry}") ]]
		then
			eval "${package_manager} ${package} > /dev/null 2>&1"

			break
		fi
	done

	if [[ -z $(command -v "${package}") ]]
	then
		echo "[  !  ] Unable to install or binary not found /////////////////////// [ '${package}' ]"
		echo

		exit 1
	fi
fi

mkdir -p "${HOME}"/.local/bin

frobulator="${HOME}"/.local/bin/frobulator

version_online=$(curl -s -L get.frbltr.app | grep -m 1 '^# version=' | cut -d '"' -f 2)
version_local=$(grep -m 1 '^# version=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)

version_local="${version_local:-1970-01-01}"

if [ ! -f "${frobulator}" ] || [[ "${version_online}" > "${version_local}" ]]
then
	curl -s -L get.frbltr.app > "${frobulator}"

	chmod +x "${frobulator}"
fi

ticker initializing

source "${frobulator}"

# script ///////////////////////////////////////////////////////////////////////

script="$(basename -- ${BASH_SOURCE[0]})"

# version //////////////////////////////////////////////////////////////////////

version="2026-08-02"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"

# variables ////////////////////////////////////////////////////////////////////

application="leocad"
source="https://github.com/leozide/leocad.git"

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

# update ///////////////////////////////////////////////////////////////////////

# frobulator.update

# frobulator.upgrade

# requirements /////////////////////////////////////////////////////////////////

list+=(
	git
	hub
	g++
	make
	zip
	zlib1g-dev
	leocad
	libqt5concurrent5
	libqt5opengl5
	libqt5opengl5-dev
	libqt5printsupport5
	libqt5xml5
	qtbase5-dev
	qttools5-dev
	qttools5-dev-tools
)

frobulator.require ${list[@]}

list=()

# configuration ////////////////////////////////////////////////////////////////

frobulator.temporary build_directory

frobulator.complete

frobulator.trap "${build_directory}"

frobulator.complete

# get source code

command_clone="git clone --quiet"

frobulator.silence "${command_clone} ${source} ${build_directory}" &

frobulator.progress "clone"

frobulator.complete

cd "${build_directory}"

# compile project

frobulator.silence "qmake ${application}.pro"

# compile binary

command_build="make -j$(nproc)"

frobulator.log "${command_build}" &

frobulator.progress "build"

frobulator.complete

# update binary

frobulator.copy "${build_directory}"/build/release /usr/bin "${application}"

frobulator.complete

# generate launcher

cat <<- 'FILE' > /usr/share/applications/leocad.desktop
[Desktop Entry]
Name=LeoCAD
Comment=LDraw model editor
Exec=leocad %f
Terminal=false
Type=Application
Icon=leocad
MimeType=application/vnd.leocad;application/x-ldraw;application/x-multi-part-ldraw;application/x-multipart-ldraw;application/x-ldlite;
Categories=Graphics;3DGraphics;
Keywords=CAD;LEGO;LDraw;
FILE

frobulator.result "${script}"
