#!/bin/bash

# superuser ////////////////////////////////////////////////////////////////////

if [[ $(id -u -n) = "root" ]]
then
    if [ -z "${SUDO:-$HOME}" ]
    then
        SUDO_HOME=/root
    else
        SUDO_HOME="${SUDO:-$HOME}"
    fi

	USER="${SUDO_USER}"
	USER_HOME=/home/"${USER}"
else
    # restart as superuser

    exec sudo bash "${0}" "${@}"
fi

# dependencies /////////////////////////////////////////////////////////////////

if [[ -z $(command -v frobulator) ]]
then
    if [[ -z $(command -v curl) ]]
    then
        yes | apt-get install curl
    fi

    curl -s -L get.frbltr.app > /usr/bin/frobulator

    chmod +x /usr/bin/frobulator
fi

. /usr/bin/frobulator

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="12-24-2021"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"
echo

# variables ////////////////////////////////////////////////////////////////////

TEMPORARY=$(mktemp -d -t TEMPORARY.XXXXXX)

trap 'rm -rf "${TEMPORARY}"' EXIT

download_directory="${TEMPORARY}"

application="leocad"
architecture="arm64"

archive=$(curl -s -L https://api.github.com/repos/leozide/leocad/releases/latest | grep -o [aA0-zZ9-]*${architecture}.zip | head -n 1)

archive_url="https://github.com/leozide/leocad/releases/download/continuous/${archive}"

extract_command=$(unzip -qq -d /usr/bin -o "${download_directory}"/*.zip)

# defaults /////////////////////////////////////////////////////////////////////

install_list=(
	curl
	zip
	unzip
)

frobulator.install ${install_list[@]}

# functions ////////////////////////////////////////////////////////////////////

frobulator.download "${archive_url}" "${download_directory}"

# extract #

frobulator.silence "${extract_command}" &

frobulator.progress "Extracting..."

frobulator.scs "Done."
