#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [ -f "${HOME}"/.local/bin/frobulator ]
then
	rm -r -f "${HOME}"/.local/bin/frobulator
fi

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		SUDO_HOME=/root

		USER="${SUDO_USER}"

		HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${HOME}"/.local/bin ]
	then
		mkdir -p "${HOME}"/.local/bin
	fi

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${HOME}"/.local/bin/frobulator

# superuser ////////////////////////////////////////////////////////////////////

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="03-03-2022"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"

# variables ////////////////////////////////////////////////////////////////////

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

directories_list=(
	[aA]ndroid
	[iI]nternal
)

matches=()

for directory in ${directories_list[@]}
do
	match=$(ls /media 2>/dev/null | grep -i "^${directory}$" | head -n 1)

	if [ -n "$match" ]
	then
		matches+=("${match}")
	fi
done

for directory in ${matches[@]}
do
	subdirectory=$(ls "/media/${directory}" 2>/dev/null | grep -i "^lego$" | head -n 1)

	if [ -n "${subdirectory}" ] && [ -d "/media/${directory}/${subdirectory}" ]
	then
		if [ -f "/media/${directory}/${subdirectory}/leocad/leocad.conf" ]
		then
			frobulator.inf "Linking configuration"
			echo

			frobulator.link "/media/${directory}/${subdirectory}/leocad" "${HOME}/.config/LeoCAD Software" leocad.conf LeoCAD.conf

			sed															\
				-i														\
				-e	"s|/media/\([^/]*\)/\([^/]*\)|/media/${directory}/${subdirectory}|g"	\
																		"/media/${directory}/${subdirectory}/leocad/leocad.conf"
		fi
	fi
done

frobulator.scs "Done"
echo
