#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [ -z "${TERMUX_VERSION}" ]
then
	PREFIX="/usr"
fi

if [[ -z $(command -v frobulator) ]]
then
	curl -s -L get.frbltr.app > "${PREFIX}"/bin/frobulator
fi

. "${PREFIX}"/bin/frobulator

if [[ $(id -u -n) = "root" ]]
then
	USER="${SUDO_USER}"
	HOME=/home/"${USER}"
fi

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version=""

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

# variables ////////////////////////////////////////////////////////////////////

# defaults /////////////////////////////////////////////////////////////////////

install_list=(
	wmctrl
)

frobulator.install ${install_list[@]}

# functions ////////////////////////////////////////////////////////////////////

# set position

wmctrl -r "New Model.ldr — LeoCAD" -e 0,0000,0000,1660,1080
wmctrl -r "Colors — LeoCAD"        -e 0,1660,0000,0450,0350
wmctrl -r "Preview — LeoCAD"       -e 0,1660,0000,0450,0350
wmctrl -r "Properties — LeoCAD"    -e 0,1660,0350,0450,0370
wmctrl -r "Parts — LeoCAD"         -e 0,1660,0720,0900,0360
wmctrl -r "Timeline — LeoCAD"      -e 0,2110,0000,0450,0720
