#!/bin/bash

# superuser ////////////////////////////////////////////////////////////////////

if [[ $(id -u -n) = "root" ]]
then
    if [ -z "${SUDO:-$HOME}" ]
    then
        SUDO_HOME=/root
    else
        SUDO_HOME="${SUDO:-$HOME}"
    fi

	USER="${SUDO_USER}"
	USER_HOME=/home/"${USER}"
else
    # restart as superuser

    exec sudo bash "${0}" "${@}"
fi

# dependencies /////////////////////////////////////////////////////////////////

if [[ -z $(command -v frobulator) ]]
then
    if [[ -z $(command -v curl) ]]
    then
        yes | apt-get install curl
    fi

    curl -s -L get.frbltr.app > /usr/bin/frobulator

    chmod +x /usr/bin/frobulator
fi

. /usr/bin/frobulator

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="09-23-2022"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

# variables ////////////////////////////////////////////////////////////////////

# defaults /////////////////////////////////////////////////////////////////////

install_list=(
	wmctrl
)

frobulator.install ${install_list[@]}

# functions ////////////////////////////////////////////////////////////////////

# set position

wmctrl -r "New Model.ldr — LeoCAD" -e 0,0000,0000,1660,1080
wmctrl -r "Colors — LeoCAD"        -e 0,1660,0000,0450,0350
wmctrl -r "Preview — LeoCAD"       -e 0,1660,0000,0450,0350
wmctrl -r "Properties — LeoCAD"    -e 0,1660,0350,0450,0370
wmctrl -r "Parts — LeoCAD"         -e 0,1660,0720,0900,0360
wmctrl -r "Timeline — LeoCAD"      -e 0,2110,0000,0450,0720
