#!/bin/bash

# dependencies #

curl -s -L get.frbltr.app > "${PREFIX}"/bin/frobulator

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="12-24-2021"

# usage #

# prompt #

frobulate.script "Setting up ${script#*-}"
echo

# variables #

# defaults #

# link configuration

frobulate.inf "Linking configuration."
echo

if [ -f /media/internal/Lego/leocad/leocad.conf ]
then
	frobulate.directory "${HOME}"/.config/"LeoCAD Software"

	ln -s -f											\
	/media/internal/Lego/leocad/leocad.conf				\
	"${HOME}"/.config/"LeoCAD Software"/LeoCAD.conf
fi
