#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [[ -z $(command -v frobulator) ]]
then
	curl -s -L get.frbltr.app > "${PREFIX}"/bin/frobulator
fi

. "${PREFIX}"/bin/frobulator

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version=""

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulate.script "Setting up ${script#*-}"
echo

# variables ////////////////////////////////////////////////////////////////////

TEMPORARY=$(mktemp -d -t TEMPORARY.XXXXXX)

trap 'rm -rf "${TEMPORARY}"' EXIT

build_directory="${TEMPORARY}"

application="leocad"
source="https://github.com/leozide/leocad.git"# variables ////////////////////////////////////////////////////////////////////

# defaults /////////////////////////////////////////////////////////////////////

install_list=(
	git
	hub
	g++
	make
	zip
	zlib1g-dev
	libqt5concurrent5
	libqt5opengl5
	libqt5opengl5-dev
	libqt5printsupport5
	libqt5xml5
	qt5-default
	qtbase5-dev
	qttools5-dev
	qttools5-dev-tools
)

frobulate.install ${install_list[@]}

# functions ////////////////////////////////////////////////////////////////////

# get source code

command_clone="git clone --quiet"

frobulate.log "${command_clone} ${source} ${build_directory}" &

frobulate.progress "Cloning..."

cd "${build_directory}"

# compile project

qmake "${application}".pro

# compile binary

command_build="make -j$(nproc)"

frobulate.log "${command_build}" &

frobulate.progress "Building..."

# update binary

cp "${build_directory}"/build/release/"${application}" /usr/bin/"${application}"

# generate launcher

cat <<- 'FILE' > /usr/share/applications/leocad.desktop
[Desktop Entry]
Encoding=UTF-8
Name=LeoCAD
GenericName=LDraw Model Editor
Comment=LDraw Model Editor
Exec=/usr/bin/leocad
Icon=leocad
Terminal=false
Type=Application
MimeType=application/x-ldraw;application/x-multipart-ldraw;
Categories=Graphics;2DGraphics;3DGraphics;Editor;
FILE
