#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [[ $(id -u -n) = "root" ]]
then
	SUDO_HOME=/root

	USER="${SUDO_USER:-root}"

	if [ "${USER}" = "root" ]
	then
		HOME=/root
	else
		HOME="/home/${USER}"
	fi
fi

echo "[  -  ] Checking..."
echo

if [[ -z $(command -v curl) ]]
then
	if [[ -n $(command -v apt-get) ]]
	then
		apt-get -q -q update > /dev/null 2>&1
		apt-get -q -q install -y curl > /dev/null 2>&1

	elif [[ -n $(command -v dnf) ]]
	then
		dnf -q install -y curl > /dev/null 2>&1

	elif [[ -n $(command -v yum) ]]
	then
		yum -q install -y curl > /dev/null 2>&1

	elif [[ -n $(command -v apk) ]]
	then
		apk add --quiet curl > /dev/null 2>&1

	elif [[ -n $(command -v pacman) ]]
	then
		pacman -S -y --noconfirm --noprogressbar curl > /dev/null 2>&1

	elif [[ -n $(command -v zypper) ]]
	then
		zypper --quiet --non-interactive install curl > /dev/null 2>&1
	fi
fi

if [[ -z $(command -v curl) ]]
then
	echo "[  !  ] Unable to install or binary not found ////////////////////// [ 'curl'  ]"
	echo

	exit 1
fi

mkdir -p "${HOME}"/.local/bin

frobulator="${HOME}"/.local/bin/frobulator

version_online=$(	curl -s -L get.frbltr.app | grep -m 1 '^# version=' | cut -d '"' -f 2)

version_local=$(grep -m 1 '^# version=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)

version_local="${version_local:-01-01-1970}"

date_online="${version_online:6:4}${version_online:0:2}${version_online:3:2}"
date_local="${version_local:6:4}${version_local:0:2}${version_local:3:2}"

if [ ! -f "${frobulator}" ] ||
   [[ "${date_online}" > "${date_local}" ]]
then
	curl -s -L get.frbltr.app > "${frobulator}"

	chmod +x "${frobulator}"
fi

echo "[  >  ] Implementing..."
echo

source "${frobulator}"

# superuser ////////////////////////////////////////////////////////////////////

export self_arguments="${@}"

frobulator.escalate

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="07-12-2026"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"

# variables ////////////////////////////////////////////////////////////////////

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

# update ///////////////////////////////////////////////////////////////////////

# frobulator.update

# frobulator.upgrade

# requirements /////////////////////////////////////////////////////////////////

list=(

)

frobulator.require ${list[@]}

list=()

# configuration ////////////////////////////////////////////////////////////////

if [[ $(command -v lpub3d24) ]]
then
    frobulator.link /usr/bin /usr/bin lpub3d24 lpub3d
fi

if [ -d /media/[iI]nternal/[lL]ego ]
then
	if [ -d /media/[iI]nternal/[lL]ego/lpub3d ]
	then
		if [ -f /media/[iI]nternal/[lL]ego/lpub3d/lpub3d.conf ]
		then
			frobulator.inf "Linking configuration"
			echo

			frobulator.directory "${HOME}" .config/"LPub3D Software"

			frobulator.link /media/[iI]nternal/[lL]ego/lpub3d "${HOME}"/.config/"LPub3D Software" lpub3d.conf
		fi

		if [ -f /media/[iI]nternal/[lL]ego/ldraw.zip ]
		then
			frobulator.inf "Generating library setup"
			echo

			frobulator.directory "${HOME}"/.local/share/"LPub3D Software" lpub3d/libraries

			# official parts archive

			frobulator.extract /media/[iI]nternal/[lL]ego/ldraw.zip "${HOME}"/.local/share/"LPub3D Software"/lpub3d

			frobulator.link /media/[iI]nternal/[lL]ego "${HOME}"/.local/share/"LPub3D Software"/lpub3d/libraries ldraw.zip complete.zip

			# unofficial parts archive

			frobulator.extract /media/[iI]nternal/[lL]ego/ldrawunf.zip "${HOME}"/.local/share/"LPub3D Software"/lpub3d/ldraw

			frobulator.link /media/[iI]nternal/[lL]ego "${HOME}"/.local/share/"LPub3D Software"/lpub3d/libraries ldrawunf.zip lpub3dldrawunf.zip

			chmod -R 777 "${HOME}"/.local/share/"LPub3D Software"
		fi

	fi
fi

# generate launcher

cat <<- 'FILE' > /usr/share/applications/lpub3d.desktop
[Desktop Entry]
Version=1.0
Name=LPub3D
GenericName=LDraw Editor
Comment=An LDraw Building Instruction Editor
Exec=lpub3d %f
Terminal=false
Type=Application
Icon=lpub3d
MimeType=application/x-ldraw;application/x-multi-part-ldraw;application/x-multipart-ldraw;
Categories=Graphics;3DGraphics;Publishing;Engineering;
Keywords=;Building;CAD;CAI;Editor;Education;Instructions;LDraw;LEGO;Publishing;Renderer;Viewer;
FILE

frobulator.scs "Done"
echo
