#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		SUDO_HOME=/root

		USER="${SUDO_USER}"

		HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${HOME}"/.local/bin ]
	then
		mkdir -p "${HOME}"/.local/bin
	fi

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${HOME}"/.local/bin/frobulator

# superuser ////////////////////////////////////////////////////////////////////

# frobulator.escalate

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="09-23-2022"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"
echo

# variables ////////////////////////////////////////////////////////////////////

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

if [ -d /media/internal/Lego ]
then
	if [ -d /media/internal/Lego/lpub3d ]
	then
		if [ -f /media/internal/Lego/lpub3d/lpub3d.conf ]
		then
			frobulator.inf "Linking configuration."
			echo

			frobulator.directory "${HOME}"/.config/"LPub3D Software"

			frobulator.link /media/internal/Lego/lpub3d "${HOME}"/.config/"LPub3D Software" lpub3d.conf lpub3d24.conf
		fi

		if [ -f /media/internal/Lego/ldraw.zip ]
		then
			frobulator.inf "Generating library setup."
			echo

			frobulator.directory "${HOME}"/.local/share/"LPub3D Software" lpub3d24/libraries

			# official parts archive

			unzip		\
				-qq 	\
				-o		\
				-d 		\
						"${HOME}"/.local/share/"LPub3D Software"/lpub3d24			\
																					/media/internal/Lego/ldraw.zip

			frobulator.link /media/internal/Lego "${HOME}"/.local/share/"LPub3D Software"/lpub3d24/libraries ldraw.zip complete.zip

			# unofficial parts archive

			unzip		\
				-qq		\
				-o		\
				-d 		\
						"${HOME}"/.local/share/"LPub3D Software"/lpub3d24/ldraw		\
																					/media/internal/Lego/ldrawunf.zip

			frobulator.link /media/internal/Lego "${HOME}"/.local/share/"LPub3D Software"/lpub3d24/libraries ldrawunf.zip lpub3dldrawunf.zip
		fi

	fi
fi
