#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

USER_HOME="${HOME}"

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		if [ -z "${SUDO:-$HOME}" ]
		then
			SUDO_HOME=/root
		else
			SUDO_HOME="${SUDO:-$HOME}"
		fi

		USER="${SUDO_USER}"
		USER_HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${USER_HOME}"/.local/bin ]
	then
		mkdir -p "${USER_HOME}"/.local/bin/frobulator
	fi

	curl -s -L get.frbltr.app > "${USER_HOME}"/.local/bin/frobulator

	chmod +x "${USER_HOME}"/.local/bin/frobulator
fi

. "${USER_HOME}"/.local/bin/frobulator

# superuser ////////////////////////////////////////////////////////////////////

frobulator.escalate

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="09-23-2022"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"
echo

# variables ////////////////////////////////////////////////////////////////////

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

frobulator.inf "Linking configuration."
echo

if [ -f /media/internal/Lego/lpub3d/lpub3d.conf ]
then
	frobulator.directory "${HOME}"/.config/"LPub3D Software"

	frobulator.link /media/internal/Lego/lpub3d "${HOME}"/.config/"LPub3D Software" lpub3d.conf lpub3d24.conf
fi

frobulator.inf "Linking library archives."
echo

if [ -d /media/internal/Lego ]
then
	frobulator.directory "${HOME}"/.local/share/"LPub3D Software"/lpub3d24/libraries/

	# official parts archive

	frobulator.link /media/internal/Lego "${HOME}"/.local/share/"LPub3D Software"/lpub3d24/libraries complete.zip complete.zip

	# unofficial parts archive

	frobulator.link /media/internal/Lego "${HOME}"/.local/share/"LPub3D Software"/lpub3d24/libraries ldrawunf.zip lpub3dldrawunf.zip
fi
