#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# skeleton #

# script --------------------------------------------------------------------- #

script=$(basename -- "${BASH_SOURCE[0]}")

# version -------------------------------------------------------------------- #

version="MM-DD-YYYY"

# variables ------------------------------------------------------------------ #

# enable quiet package install

export DEBIAN_FRONTEND=noninteractive

# INSERT VARIABLES HERE

# defaults ------------------------------------------------------------------- #

option=default

# usage ---------------------------------------------------------------------- #

while (($#))
do
	case "$1" in
		-a|--option-a)
			option=a
			;;
		-b|--option-b)
			option=b
			;;
		-h|--help)
			echo -e "Usage:"
			echo -e "./$script [OPTION]"
			echo -e "Utility options:"
			echo -e "-a, --option-a \t Runs using option a."
			echo -e "-b, --option-b \t Runs using option b."
			echo -e ""
			echo -e "-h, --help \t\t Show help options."
			echo -e "-v, --version \t\t Print version."
			exit
			;;
		-v|--version)
			echo -e "$script $version"
			exit
			;;
		*)
			echo -e ""
			echo -e "$script: Unknown option $1"
			echo -e "Defaulting to option $option"
			echo -e "Try '$script --help' for options information."
			echo -e ""
			;;
		esac
	shift
done

# functions ------------------------------------------------------------------ #

console.spinner () {
	# catch PID of last command

	PID=$!

	# spinner string content

	before="[ "
	spinner="/—\|"
	after="]"
	message="$1"

	i=1

	echo

	while [ -d /proc/$PID ]
	do
		echo -ne "\r${before} \b${spinner:i++%${#spinner}:1} ${after} ${message}\c "
		sleep 0.125
	done

	echo
}

# dependencies --------------------------------------------------------------- #

binaries_list=(
	console
)

if [[ "$(which $binary)" == "" ]]
then

	for binary in ${binaries_list[@]}
	do
		binary_url=bin-dex.ntttn.me/"$binary"

		# get binaries from repository

		curl -sL ${binary_url} > "$binary_directory/$binary" &

		console.spinner "Downloading binary [ $binary ]."
		echo

		# set execution mode for binary

		chmod +x "$binary_directory/$binary"
	done

	source "$binary_directory/$binary"
fi

# initial prompt clear ------------------------------------------------------- #

clear

# configuration -------------------------------------------------------------- #

# INSERT SCRIPT CONTENT HERE

# complete ------------------------------------------------------------------- #

console.success "Done."
echo