#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

script="$(basename -- ${BASH_SOURCE[0]})"

if [[ "${frobulator_loaded}" != "true" ]]
then
	echo

	ticker () {

		for ticker in '>  ' '>> ' '>>>'
		do
			echo -n -e "\r[  ${ticker}  ] ${1^}..."

			sleep 0.5
		done

		echo

		echo

	}

	if [[ $(id -u -n) = "root" ]]
	then
		USER="${SUDO_USER:-root}"

		if [ "${USER}" = "root" ]
		then
			HOME=/root
		else
			HOME="/home/${USER}"
		fi
	fi

	ticker checking

	package_managers_list=(
		"apt-get --quiet --quiet update > /dev/null 2>&1; apt-get --quiet --quiet install --yes"
		"dnf --quiet install --assumeyes"
		"yum --quiet install --assumeyes"
		"apk add --quiet"
		"pacman --sync --refresh --noconfirm --noprogressbar"
		"zypper --quiet --non-interactive install"
	)

	package="curl"

	if [[ -z $(command -v "${package}") ]]
	then
		for package_manager in "${package_managers_list[@]}"
		do
			entry="${package_manager%% *}"

			if [[ -n $(command -v "${entry}") ]]
			then
				eval "${package_manager} ${package} > /dev/null 2>&1"

				break
			fi
		done

		if [[ -z $(command -v "${package}") ]]
		then
			echo "[  !  ] Unable to install or binary not found /////////////////////// [ '${package}' ]"
			echo

			exit 1
		fi
	fi

	mkdir -p "${HOME}"/.local/bin

	frobulator="${HOME}"/.local/bin/frobulator

	version_online=$(curl -s -L get.frbltr.app | grep -m 1 '^update=' | cut -d '"' -f 2)

	version_local=$(grep -m 1 '^update=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)

	version_local="${version_local:-1970-01-01}"

	if [ ! -f "${frobulator}" ] || [[ "${version_online}" > "${version_local}" ]]
	then
		curl -s -L get.frbltr.app > "${frobulator}"

		chmod +x "${frobulator}"
	fi

	ticker initializing

	source "${frobulator}"

	# script arguments for 'frobulator.escalate': kept as an array - restored
	# exactly (spaces, quotes, empty arguments) when restarting as superuser

	self_arguments=("${@}")
fi

# superuser ////////////////////////////////////////////////////////////////////

frobulator.escalate

# script ///////////////////////////////////////////////////////////////////////

frobulator.script

# version //////////////////////////////////////////////////////////////////////

version="YYYY-MM-DD"

# usage ////////////////////////////////////////////////////////////////////////

while (($#))
do
	case "${1}"
	in
		-i|--install)
			option="install"
		;;

		-h|--help)
			echo
			echo -e "Usage: ./${script} -i | -h"
			echo
			echo -e "Options:"
			echo
			echo -e "-i, --install    Run [i]nstallation of ${script} to ${HOME}/.local/bin."
			echo
			echo -e "-h, --help       Show [h]elp and usage information."
			echo
			echo -e "'${script}'      [ Version // ${version} ]"
			echo

			exit
		;;

		"")
			# handle empty argument:
			# use default values specified in script

			:
		;;

		*)
			echo
			echo -e "Usage: ./${script} -i | -h"
			echo
			echo -e "Unknown option: '${script} ${1}':"
			echo -e "Type './${script} -h' for help and usage information."
			echo

			exit 1

		;;

		esac

	shift

done

# variables ////////////////////////////////////////////////////////////////////

directory_install="${HOME}"/.local/bin

# defaults /////////////////////////////////////////////////////////////////////

if [ -z "${option}" ]
then
	option="install"
fi

# functions ////////////////////////////////////////////////////////////////////

# update ///////////////////////////////////////////////////////////////////////

# frobulator.update

# frobulator.upgrade

# requirements /////////////////////////////////////////////////////////////////

list=(

)

frobulator.require ${list[@]}

list=()

# configuration ////////////////////////////////////////////////////////////////

# install

if [ "${option}" = "install" ]
then
	file_script="$(realpath "${BASH_SOURCE[0]}")"

	directory_script="$(dirname "${file_script}")"

	if [ "${directory_script}" -ef "${directory_install}" ]
	then
		frobulator.inf "Already installed" "[ ${directory_install}/${script} ]"
		echo
	else
		frobulator.copy "${directory_script}" "${directory_install}" "${script}"

		frobulator.permissions public execute "${directory_install}/${script}"

		frobulator.scs "Installed" "[ ${directory_install}/${script} ]"
		echo
	fi
fi

frobulator.result "${script}"

frobulator.scs "Done"
echo
