#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [[ $(id -u -n) = "root" ]]
then
	SUDO_HOME=/root

	USER="${SUDO_USER}"

	HOME=/home/"${USER}"
fi

if [[ -z $(command -v curl) ]]
then
	yes | apt-get install curl
fi

if [ ! -d "${HOME}"/.local/bin ]
then
	mkdir -p "${HOME}"/.local/bin
fi

frobulator="${HOME}"/.local/bin/frobulator

version_online=$(curl -s -L get.frbltr.app | grep 'version=' | cut -d '"' -f 2)

version_local=$(cat "${frobulator}" | grep 'version=' | cut -d '"' -f 2)

version_local="${version_local:-01-01-1970}"

date_online=$(date -d "${version_online:6:4}-${version_online:0:2}-${version_online:3:2}" +%s)

date_local=$(date -d "${version_local:6:4}-${version_local:0:2}-${version_local:3:2}" +%s)

if [ -f "${frobulator}" ] && [ "${date_online}" -gt "${date_local}" ]
then
	rm -r -f "${HOME}"/.local/bin/frobulator

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

if [ ! -f "${frobulator}" ]
then
	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${frobulator}"

# superuser ////////////////////////////////////////////////////////////////////

export self_arguments="${@}"

# frobulator.escalate

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="MM-DD-YYYY"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"

# variables ////////////////////////////////////////////////////////////////////

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

# requirements /////////////////////////////////////////////////////////////////
