#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [[ -z $(command -v frobulator) ]]
then
    if [[ -z $(command -v curl) ]]
    then
        yes | apt-get install curl
    fi

    curl -s -L get.frbltr.app > /usr/bin/frobulator
fi

. /usr/bin/frobulator

if [[ $(id -u -n) = "root" ]]
then
    if [ -z "${SUDO:-$HOME}" ]
    then
        SUDO_HOME=/root
    else
        SUDO_HOME="${SUDO:-$HOME}"
    fi

	USER="${SUDO_USER}"
	USER_HOME=/home/"${USER}"
fi

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="08-12-2022"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"
echo

# variables ////////////////////////////////////////////////////////////////////

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

# storage //////////////////////////////////////////////////////////////////////

storage_list=(
    external
    internal
)

for storage in ${storage_list[@]}
do
    if [ -d /media/"${storage}" ]
    then
        chmod -R 777 /media/"${storage}"
        chmod -R 777 /media/"${storage}"/*
    fi
done

storage_list=()

# git //////////////////////////////////////////////////////////////////////////

frobulator.inf "Setting up" "[ git ]"
echo

storage_list=(
    internal
)
for storage in ${storage_list[@]}
do
    if [ -d  /media/"${storage}" ]
    then
    	storage=/media/internal
    fi
done

storage_list=()

frobulator.link "${storage}"/Git "${HOME}" git-configuration .gitconfig
frobulator.link "${storage}"/Git "${HOME}" git-credentials   .git-credentials

chown "${USER}":"${USER}" "${storage}"/Git/git-configuration
chown "${USER}":"${USER}" "${storage}"/Git/git-credentials

# shell ////////////////////////////////////////////////////////////////////////

frobulator.inf "Setting up" "[ shell ]"
echo

files_list+=(
	bash-aliases
	bash-configuration
	bash-functions
	bash-login
	bash-logout
	bash-profile
)

frobulator.download get.trmnl.me /usr/bin ${files_list[@]}

frobulator.link /usr/bin "${HOME}"      bash-aliases       .bash_aliases
frobulator.link /usr/bin "${HOME}"      bash-configuration .bashrc
frobulator.link /usr/bin "${HOME}"      bash-configuration .bash_configuration
frobulator.link /usr/bin "${HOME}"      bash-functions     .bash_functions
frobulator.link /usr/bin "${HOME}"      bash-login         .bash_login
frobulator.link /usr/bin "${HOME}"      bash-logout        .bash_logout
frobulator.link /usr/bin "${HOME}"      bash-profile       .bash_profile

frobulator.link /usr/bin "${SUDO_HOME}" bash-aliases       .bash_aliases
frobulator.link /usr/bin "${SUDO_HOME}" bash-configuration .bashrc
frobulator.link /usr/bin "${SUDO_HOME}" bash-configuration .bash_configuration
frobulator.link /usr/bin "${SUDO_HOME}" bash-functions     .bash_functions
frobulator.link /usr/bin "${SUDO_HOME}" bash-login         .bash_login
frobulator.link /usr/bin "${SUDO_HOME}" bash-logout        .bash_logout
frobulator.link /usr/bin "${SUDO_HOME}" bash-profile       .bash_profile

files_list=()
