#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [[ $(id -u -n) = "root" ]]
then
	SUDO_HOME=/root

	USER="${SUDO_USER:-root}"

	if [ "${USER}" = "root" ]
	then
		HOME=/root
	else
		HOME="/home/${USER}"
	fi
fi

echo "[  -  ] Checking..."
echo

if [[ -z $(command -v curl) ]]
then
	if [[ -n $(command -v apt-get) ]]
	then
		apt-get -q -q update > /dev/null 2>&1
		apt-get -q -q install -y curl > /dev/null 2>&1

	elif [[ -n $(command -v dnf) ]]
	then
		dnf -q install -y curl > /dev/null 2>&1

	elif [[ -n $(command -v yum) ]]
	then
		yum -q install -y curl > /dev/null 2>&1

	elif [[ -n $(command -v apk) ]]
	then
		apk add --quiet curl > /dev/null 2>&1

	elif [[ -n $(command -v pacman) ]]
	then
		pacman -S -y --noconfirm --noprogressbar curl > /dev/null 2>&1

	elif [[ -n $(command -v zypper) ]]
	then
		zypper --quiet --non-interactive install curl > /dev/null 2>&1
	fi
fi

if [[ -z $(command -v curl) ]]
then
	echo "[  !  ] Unable to install or binary not found ////////////////////// [ 'curl'  ]"
	echo

	exit 1
fi

mkdir -p "${HOME}"/.local/bin

frobulator="${HOME}"/.local/bin/frobulator

version_online=$(	curl -s -L get.frbltr.app | grep -m 1 '^# version=' | cut -d '"' -f 2)

version_local=$(grep -m 1 '^# version=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)

version_local="${version_local:-01-01-1970}"

date_online="${version_online:6:4}${version_online:0:2}${version_online:3:2}"
date_local="${version_local:6:4}${version_local:0:2}${version_local:3:2}"

if [ ! -f "${frobulator}" ] ||
   [[ "${date_online}" > "${date_local}" ]]
then
	curl -s -L get.frbltr.app > "${frobulator}"

	chmod +x "${frobulator}"
fi

echo "[  >  ] Implementing..."
echo

source "${frobulator}"

# superuser ////////////////////////////////////////////////////////////////////

export self_arguments="${@}"

# frobulator.escalate

# script ///////////////////////////////////////////////////////////////////////

script="${BASH_SOURCE[0]}"

# version //////////////////////////////////////////////////////////////////////

version="07-12-2026"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"
echo

# variables ////////////////////////////////////////////////////////////////////

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

settings_intent () {

	# reload termux settings

	settings_command=()

	settings_command+=(am broadcast)
	settings_command+=(--user 0)
	settings_command+=(-a com.termux.app.reload_style)
	settings_command+=(com.termux)

	frobulator.silence "${settings_command[@]}"
}

# update ///////////////////////////////////////////////////////////////////////

# frobulator.update

# frobulator.upgrade

# requirements /////////////////////////////////////////////////////////////////

list=(

)

frobulator.require ${list[@]}

list=()

# configuration ////////////////////////////////////////////////////////////////

# termux

frobulator.inf "Setting up" "[ termux ]"
echo

list+=(
	termux-colors
	termux-font
	termux-properties
)

frobulator.download get.trmx.app "${HOME}"/.local/bin ${list[@]}

frobulator.link "${HOME}"/.local/bin "${HOME}"/.termux termux-colors     colors.properties
frobulator.link "${HOME}"/.local/bin "${HOME}"/.termux termux-font       font.ttf
frobulator.link "${HOME}"/.local/bin "${HOME}"/.termux termux-properties termux.properties

settings_intent

list=()

# git

frobulator.inf "Setting up" "[ git ]"
echo

if [ -z "${TERMUX_VERSION}" ]
then
	storage=/media/internal
else
	if [ -d "${PREFIX}"/media/internal ]
	then
		storage="${PREFIX}"/media/internal
	else
		storage=/storage/emulated/0
	fi
fi

frobulator.link "${storage}"/Git "${HOME}" git-configuration .gitconfig
frobulator.link "${storage}"/Git "${HOME}" git-credentials   .git-credentials

# shell

frobulator.inf "Setting up" "[ shell ]"
echo

list+=(
	bash-aliases
	bash-configuration
	bash-functions
	bash-login
	bash-logout
	bash-profile
)

frobulator.download get.trmnl.me "${HOME}"/.local/bin ${list[@]}

frobulator.link "${HOME}"/.local/bin "${HOME}" bash-aliases       .bash_aliases
frobulator.link "${HOME}"/.local/bin "${HOME}" bash-configuration .bashrc
frobulator.link "${HOME}"/.local/bin "${HOME}" bash-configuration .bash_configuration
frobulator.link "${HOME}"/.local/bin "${HOME}" bash-functions     .bash_functions
frobulator.link "${HOME}"/.local/bin "${HOME}" bash-login         .bash_login
frobulator.link "${HOME}"/.local/bin "${HOME}" bash-logout        .bash_logout
frobulator.link "${HOME}"/.local/bin "${HOME}" bash-profile       .bash_profile

list=()

# adb

frobulator.inf "Setting up" "[ adb ]"
echo

list+=(
	adb
	fastboot
	e2fsdroid
	f2fs_sload
	make_f2fs
)

frobulator.download get.trmnl.me/android "${HOME}"/.local/bin ${list[@]}

list=()

# geany


frobulator.inf "Setting up" "[ geany ]"
echo

frobulator.directory "${HOME}"/.config/geany

frobulator.link "${PREFIX}"/media/internal/Git/terminal "${HOME}"/.config/geany geany-configuration geany.conf
frobulator.link "${PREFIX}"/media/internal/Git/terminal "${HOME}"/.config/geany geany-keybindings   keybindings.conf
frobulator.link "${PREFIX}"/media/internal/Git/terminal "${HOME}"/.config/geany geany-toolbar       ui_toolbar.xml

