#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

ticker () {

	echo

	for ticker in '>  ' '>> ' '>>>'
	do
		echo -n -e "\r[  ${ticker}  ] ${1^}..."

		sleep 0.5
	done

	echo

	echo

}

if [[ $(id -u -n) = "root" ]]
then
	USER="${SUDO_USER:-root}"

	if [ "${USER}" = "root" ]
	then
		HOME=/root
	else
		HOME="/home/${USER}"
	fi
fi

ticker checking

package_managers_list=(
	"apt-get --quiet --quiet update > /dev/null 2>&1; apt-get --quiet --quiet install --yes"
	"dnf --quiet install --assumeyes"
	"yum --quiet install --assumeyes"
	"apk add --quiet"
	"pacman --sync --refresh --noconfirm --noprogressbar"
	"zypper --quiet --non-interactive install"
)

package="curl"

if [[ -z $(command -v "${package}") ]]
then
	for package_manager in "${package_managers_list[@]}"
	do
		entry="${package_manager%% *}"

		if [[ -n $(command -v "${entry}") ]]
		then
			eval "${package_manager} ${package} > /dev/null 2>&1"

			break
		fi
	done

	if [[ -z $(command -v "${package}") ]]
	then
		echo "[  !  ] Unable to install or binary not found /////////////////////// [ '${package}' ]"
		echo

		exit 1
	fi
fi

mkdir -p "${HOME}"/.local/bin

frobulator="${HOME}"/.local/bin/frobulator

version_online=$(curl -s -L get.frbltr.app | grep -m 1 '^# version=' | cut -d '"' -f 2)
version_local=$(grep -m 1 '^# version=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)

version_local="${version_local:-1970-01-01}"

if [ ! -f "${frobulator}" ] || [[ "${version_online}" > "${version_local}" ]]
then
	curl -s -L get.frbltr.app > "${frobulator}"

	chmod +x "${frobulator}"
fi

ticker initializing

source "${frobulator}"

# script ///////////////////////////////////////////////////////////////////////

script="$(basename -- ${BASH_SOURCE[0]})"

# version //////////////////////////////////////////////////////////////////////

version="2026-07-12"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"
echo

# variables ////////////////////////////////////////////////////////////////////

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

settings_intent () {

	# reload termux settings

	settings_command=()

	settings_command+=(am broadcast)
	settings_command+=(--user 0)
	settings_command+=(-a com.termux.app.reload_style)
	settings_command+=(com.termux)

	frobulator.silence "${settings_command[@]}"
}

# update ///////////////////////////////////////////////////////////////////////

# frobulator.update

# frobulator.upgrade

# requirements /////////////////////////////////////////////////////////////////

list=(

)

frobulator.require ${list[@]}

list=()

# configuration ////////////////////////////////////////////////////////////////

# termux

frobulator.inf "Setting up" "[ termux ]"
echo

list+=(
	termux-colors
	termux-font
	termux-properties
)

frobulator.download get.trmx.app "${HOME}"/.local/bin ${list[@]}

frobulator.link "${HOME}"/.local/bin "${HOME}"/.termux termux-colors     colors.properties
frobulator.link "${HOME}"/.local/bin "${HOME}"/.termux termux-font       font.ttf
frobulator.link "${HOME}"/.local/bin "${HOME}"/.termux termux-properties termux.properties

settings_intent

list=()

# git

frobulator.inf "Setting up" "[ git ]"
echo

if [ -z "${TERMUX_VERSION}" ]
then
	storage=/media/internal
else
	if [ -d "${PREFIX}"/media/internal ]
	then
		storage="${PREFIX}"/media/internal
	else
		storage=/storage/emulated/0
	fi
fi

frobulator.link "${storage}"/Git "${HOME}" git-configuration .gitconfig
frobulator.link "${storage}"/Git "${HOME}" git-credentials   .git-credentials

# shell

frobulator.inf "Setting up" "[ shell ]"
echo

list+=(
	bash-aliases
	bash-configuration
	bash-functions
	bash-login
	bash-logout
	bash-profile
)

frobulator.download get.trmnl.me "${HOME}"/.local/bin ${list[@]}

frobulator.link "${HOME}"/.local/bin "${HOME}" bash-aliases       .bash_aliases
frobulator.link "${HOME}"/.local/bin "${HOME}" bash-configuration .bashrc
frobulator.link "${HOME}"/.local/bin "${HOME}" bash-configuration .bash_configuration
frobulator.link "${HOME}"/.local/bin "${HOME}" bash-functions     .bash_functions
frobulator.link "${HOME}"/.local/bin "${HOME}" bash-login         .bash_login
frobulator.link "${HOME}"/.local/bin "${HOME}" bash-logout        .bash_logout
frobulator.link "${HOME}"/.local/bin "${HOME}" bash-profile       .bash_profile

list=()

# adb

frobulator.inf "Setting up" "[ adb ]"
echo

list+=(
	adb
	fastboot
	e2fsdroid
	f2fs_sload
	make_f2fs
)

frobulator.download get.trmnl.me/android "${HOME}"/.local/bin ${list[@]}

list=()

# geany


frobulator.inf "Setting up" "[ geany ]"
echo

frobulator.directory "${HOME}"/.config/geany

frobulator.link "${PREFIX}"/media/internal/Git/terminal "${HOME}"/.config/geany geany-configuration geany.conf
frobulator.link "${PREFIX}"/media/internal/Git/terminal "${HOME}"/.config/geany geany-keybindings   keybindings.conf
frobulator.link "${PREFIX}"/media/internal/Git/terminal "${HOME}"/.config/geany geany-toolbar       ui_toolbar.xml

