#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [[ $(id -u -n) = "root" ]]
then
	SUDO_HOME=/root

	USER="${SUDO_USER:-root}"

	if [ "${USER}" = "root" ]
	then
		HOME=/root
	else
		HOME="/home/${USER}"
	fi
fi

echo

echo "[  -  ] Checking..."
echo

if [[ -z $(command -v curl) ]]
then
	if [[ -n $(command -v apt-get) ]]
	then
		apt-get -q -q update > /dev/null 2>&1
		apt-get -q -q install -y curl > /dev/null 2>&1

	elif [[ -n $(command -v dnf) ]]
	then
		dnf -q install -y curl > /dev/null 2>&1

	elif [[ -n $(command -v yum) ]]
	then
		yum -q install -y curl > /dev/null 2>&1

	elif [[ -n $(command -v apk) ]]
	then
		apk add --quiet curl > /dev/null 2>&1

	elif [[ -n $(command -v pacman) ]]
	then
		pacman -S -y --noconfirm --noprogressbar curl > /dev/null 2>&1

	elif [[ -n $(command -v zypper) ]]
	then
		zypper --quiet --non-interactive install curl > /dev/null 2>&1
	fi
fi

if [[ -z $(command -v curl) ]]
then
	echo "[  !  ] Unable to install or binary not found /////////////////////// [ 'curl' ]"
	echo

	exit 1
fi

mkdir -p "${HOME}"/.local/bin

frobulator="${HOME}"/.local/bin/frobulator

version_online=$(	curl -s -L get.frbltr.app | grep -m 1 '^# version=' | cut -d '"' -f 2)

version_local=$(grep -m 1 '^# version=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)

version_local="${version_local:-01-01-1970}"

date_online="${version_online:6:4}${version_online:0:2}${version_online:3:2}"

date_local="${version_local:6:4}${version_local:0:2}${version_local:3:2}"

if [ ! -f "${frobulator}" ] ||
   [[ "${date_online}" > "${date_local}" ]]
then
	curl -s -L get.frbltr.app > "${frobulator}"

	chmod +x "${frobulator}"
fi

echo "[  >  ] Implementing..."
echo

source "${frobulator}"

# superuser ////////////////////////////////////////////////////////////////////

export self_arguments="${@}"

# frobulator.escalate

# script ///////////////////////////////////////////////////////////////////////

script="${BASH_SOURCE[0]}"

# version //////////////////////////////////////////////////////////////////////

version="07-12-2026"

# usage ////////////////////////////////////////////////////////////////////////

while (($#))
do
	case "${1}"
	in
		-a|--activity)
			option="activity"
			activity_option="${2}"

			shift
		;;

		-n|--handle)
			option="handle"
			handle_option="${2}"

			shift
		;;

		-h|--help)
			echo
			echo -e "Usage: ${script} -a [Activity] | -n [Handle] | [OPTION]"
			echo
			echo -e "Options"
			echo
			echo -e "-a, --activity        Run native Android activities via Dextop environement defaults."
			echo
			echo -e "                      [ google-chrome ] | [ chrome ]"
			echo -e "                      [ google-mail ]   | [ gmail ]"
			echo -e "                      [ terminal ]"
			echo
			echo -e "-n, --handle          Run desktop environment handles through native Android applications."
			echo
			echo -e "                      [ email ]   | [ mail ]"
			echo -e "                      [ browser ] | [ link ] | [ web ]"
			echo -e "                      [ message ] | [ text ] | [ sms ]"
			echo
			echo -e "-h, --help            Show help and usage information."
			echo
			echo -e "'${script}' [ Version // ${version} ]"
			echo

			exit
		;;

		"")
			# handle empty argument:
			# use default values specified in script

			:
		;;

		*)
			echo
			echo -e "Usage: ${script} -a [Activity] | -n [Handle] | [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1

		;;

		esac

	shift

done

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"
echo

# variables ////////////////////////////////////////////////////////////////////

# activities

google_chrome="com.android.chrome/com.google.android.apps.chrome.Main"
google_chrome_beta="com.chrome.beta/com.google.android.apps.chrome.Main"
google_mail="com.google.android.gm/.GmailActivity"
terminal="com.termux/com.termux.app.TermuxActivity"

# defaults /////////////////////////////////////////////////////////////////////

email="mailto:"
link="https:"
message="sms:"

# functions ////////////////////////////////////////////////////////////////////

activity_intent () {

	activity="${1}"

	am start							\
		-n "${activity}"				> "${sink}" 2>&1
	}

handle_intent () {

	handle="${1}"

	am start							\
		-a android.intent.action.VIEW	\
		-d "${handle}"					> "${sink}" 2>&1
}

# requirements /////////////////////////////////////////////////////////////////

# configuration ////////////////////////////////////////////////////////////////

if [[ "${option}" = [aA][cC][tT][iI][vV][iI][tT][yY] ]]
then
	if [[ "${activity_option}" = "google-chrome" ]] || \
	   [[ "${activity_option}" = "chrome"        ]]
	then
		activity="${google_chrome}"

	elif [[ "${activity_option}" = "google-mail" ]] || \
		[[ "${activity_option}" = "gmail"        ]]
	then
		activity="${google_mail}"

	elif [[ "${activity_option}" = "terminal"    ]]
	then
		activity="${terminal}"

	else
		frobulator.err "Unrecognized activity option" "[ ${activity_option} ]"
		echo

		exit 1
	fi

	activity_intent "${activity}"

elif [[ "${option}" = [hH][aA][nN][dD][lL][eE] ]]
then
	if [[ "${handle_option}" = "email"     ]] || \
	   [[ "${handle_option}" = "mail"      ]]
	then
		handle="${email}"

	elif [[ "${handle_option}" = "browser" ]] || \
		[[ "${handle_option}" = "link"     ]] || \
		[[ "${handle_option}" = "web"      ]]
	then
		handle="${link}"

	elif [[ "${handle_option}" = "message" ]] || \
	     [[ "${handle_option}" = "text"    ]] || \
	     [[ "${handle_option}" = "sms"     ]]
	then
		handle="${message}"

	else
		frobulator.err "Unrecognized handle option" "[ ${handle_option} ]"
		echo

		exit 1
	fi

	handle_intent "${handle}"
fi
