#!/bin/bash

script=$(basename -- "${BASH_SOURCE[0]}")

if [[ $(uname -o) =~ [aA][nN][dD][rR][oO][iI][dD] ]] && [[ "${TERMUX_VERSION}"]]
then
	cat <<- 'FILE' > "${PREFIX}"/bin/"${script}"
	#!/bin/bash

	am start							\
		-a android.intent.action.VIEW	\
		-d "sms:" > /dev/null 2>&1
	FILE
fi
