#!/bin/bash

# superuser ////////////////////////////////////////////////////////////////////

if [[ $(id -u -n) = "root" ]]
then
    if [ -z "${SUDO:-$HOME}" ]
    then
        SUDO_HOME=/root
    else
        SUDO_HOME="${SUDO:-$HOME}"
    fi

	USER="${SUDO_USER}"
	USER_HOME=/home/"${USER}"
else
    # restart as superuser

    exec sudo bash "${0}" "${@}"
fi

# dependencies /////////////////////////////////////////////////////////////////

if [[ -z $(command -v frobulator) ]]
then
    if [[ -z $(command -v curl) ]]
    then
        yes | apt-get install curl
    fi

    curl -s -L get.frbltr.app > /usr/bin/frobulator

    chmod +x /usr/bin/frobulator
fi

. /usr/bin/frobulator

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="09-23-2022"

# usage ////////////////////////////////////////////////////////////////////////

# variables ////////////////////////////////////////////////////////////////////

stamp=$(date +"%m-%d-%Y-%H-%M-%S")

# defaults /////////////////////////////////////////////////////////////////////

list=(
	conky
	convert
	zenity
)

frobulator.require ${list[@]}

# functions ////////////////////////////////////////////////////////////////////

alignment="top_left"
font_size="8"
gap_x="10"
gap_y="10"
size_x="512"
size_y="512"
width="$size_x"

if [ ! -d "${HOME}"/.config/conky-picture-frame ]
then
	mkdir -p "${HOME}"/.config/conky-picture-frame
fi

cat <<- FILE > "${HOME}"/.config/conky-picture-frame/conky-picture-framerc
# conky picture frame #

alignment $alignment
background yes
default_color CCCCCC
double_buffer yes
gap_x $gap_x
gap_y $gap_y
imlib_cache_size 0
maximum_width 0
minimum_size $size_x $size_y
no_buffers no
override_utf8_locale yes
own_window yes
own_window_argb_value 255
own_window_argb_visual no
own_window_colour grey
own_window_hints below,skip_pager,skip_taskbar,sticky,undecorated
own_window_transparent no
own_window_type normal
total_run_times 0
uppercase no
use_xft yes
xftalpha 1.0
xftfont Sans:size=$font_size:normal

TEXT
\${image .picture.png}
FILE

chmod -R 777 "${HOME}"/.config/conky-picture-frame

# generate launcher

cat <<- 'FILE' > /usr/share/applications/conky-picture-frame.desktop
[Desktop Entry]
Name=Conky Picture Frame
Comment=Highly configurable system monitor
Exec=sh -c "conky -c /home/${SUDO_USER:-$USER}/.config/conky-picture-frame/conky-picture-framerc"
Icon=conky
Terminal=false
Type=Application
StartupNotify=true
Categories=Utility;
FILE
