#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

ticker () {

	echo

	for ticker in '>  ' '>> ' '>>>'
	do
		echo -n -e "\r[  ${ticker}  ] ${1^}..."

		sleep 0.5
	done

	echo

	echo

}

if [[ $(id -u -n) = "root" ]]
then
	USER="${SUDO_USER:-root}"

	if [ "${USER}" = "root" ]
	then
		HOME=/root
	else
		HOME="/home/${USER}"
	fi
fi

ticker checking

package_managers_list=(
	"apt-get --quiet --quiet update > /dev/null 2>&1; apt-get --quiet --quiet install --yes"
	"dnf --quiet install --assumeyes"
	"yum --quiet install --assumeyes"
	"apk add --quiet"
	"pacman --sync --refresh --noconfirm --noprogressbar"
	"zypper --quiet --non-interactive install"
)

package="curl"

if [[ -z $(command -v "${package}") ]]
then
	for package_manager in "${package_managers_list[@]}"
	do
		entry="${package_manager%% *}"

		if [[ -n $(command -v "${entry}") ]]
		then
			eval "${package_manager} ${package} > /dev/null 2>&1"

			break
		fi
	done

	if [[ -z $(command -v "${package}") ]]
	then
		echo "[  !  ] Unable to install or binary not found /////////////////////// [ '${package}' ]"
		echo

		exit 1
	fi
fi

mkdir -p "${HOME}"/.local/bin

frobulator="${HOME}"/.local/bin/frobulator

version_online=$(curl -s -L get.frbltr.app | grep -m 1 '^# version=' | cut -d '"' -f 2)
version_local=$(grep -m 1 '^# version=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)

version_local="${version_local:-1970-01-01}"

if [ ! -f "${frobulator}" ] || [[ "${version_online}" > "${version_local}" ]]
then
	curl -s -L get.frbltr.app > "${frobulator}"

	chmod +x "${frobulator}"
fi

ticker initializing

source "${frobulator}"

# script ///////////////////////////////////////////////////////////////////////

script="$(basename -- ${BASH_SOURCE[0]})"

# version //////////////////////////////////////////////////////////////////////

version="2026-07-13"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"

# variables ////////////////////////////////////////////////////////////////////

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

# update ///////////////////////////////////////////////////////////////////////

# frobulator.update

# frobulator.upgrade

# requirements /////////////////////////////////////////////////////////////////

list=(

)

frobulator.require ${list[@]}

list=()

# configuration ////////////////////////////////////////////////////////////////

# user

deluser --remove-home ubuntu
groupdel -f ubuntu

chpasswd <<< root:09018610

# hostname

echo pi > /etc/hostname

hostnamectl set-hostname pi

# ssh

cat << 'FILE' > /boot/firmware/ssh
FILE

# network

cat << 'FILE' > /etc/netplan/01-wlan0-config.yaml
network:
    version: 2

    ethernets:
      eth0:
        dhcp4: no
        dhcp6: no

    wifis:
      wlan0:
        dhcp4: no
        dhcp6: no

        addresses:
          - 192.168.86.21/24

        nameservers:
          addresses:
            - 8.8.8.8
            - 1.1.1.1

        routes:
            - to: default
              via: 192.168.86.1

        access-points:
          "WiFi":
            password: "y5cE?z>6&juDEm"
FILE

netplan generate
netplan apply

# configuration

cat << 'FILE' > /boot/firmware/config.txt
[pi4]
max_framebuffers=2

[all]
arm_64bit=1
disable_splash=1
kernel=vmlinuz
cmdline=cmdline.txt
initramfs initrd.img followkernel
loglevel=1
dtoverlay=vc4-kms-v3d,noaudio
dtparam=audio=on
dtparam=i2c_arm=on
dtparam=spi=on
enable_uart=1

disable_overscan=1
hdmi_force_hotplug=1

over_voltage=8
arm_freq=2000
FILE

# packages

apt --assume-yes update
apt --assume-yes purge snap thin-provisioning-tools
apt --assume-yes upgrade

# restart

reboot
