#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

script="$(basename -- ${BASH_SOURCE[0]})"

if [[ "${frobulator_loaded}" != "true" ]]
then
	echo

	ticker () {

		for ticker in '>  ' '>> ' '>>>'
		do
			echo -n -e "\r[  ${ticker}  ] ${1^}..."

			sleep 0.5
		done

		echo

		echo

	}

	if [[ $(id -u -n) = "root" ]]
	then
		USER="${SUDO_USER:-root}"

		if [ "${USER}" = "root" ]
		then
			HOME=/root
		else
			HOME="/home/${USER}"
		fi
	fi

	ticker checking

	package_managers_list=(
		"apt-get --quiet --quiet update > /dev/null 2>&1; apt-get --quiet --quiet install --yes"
		"dnf --quiet install --assumeyes"
		"yum --quiet install --assumeyes"
		"apk add --quiet"
		"pacman --sync --refresh --noconfirm --noprogressbar"
		"zypper --quiet --non-interactive install"
	)

	package="curl"

	if [[ -z $(command -v "${package}") ]]
	then
		for package_manager in "${package_managers_list[@]}"
		do
			entry="${package_manager%% *}"

			if [[ -n $(command -v "${entry}") ]]
			then
				eval "${package_manager} ${package} > /dev/null 2>&1"

				break
			fi
		done

		if [[ -z $(command -v "${package}") ]]
		then
			echo "[  !  ] Unable to install or binary not found /////////////////////// [ '${package}' ]"
			echo

			exit 1
		fi
	fi

	mkdir -p "${HOME}"/.local/bin

	frobulator="${HOME}"/.local/bin/frobulator

	version_online=$(curl -s -L get.frbltr.app | grep -m 1 '^# version=' | cut -d '"' -f 2)

	version_local=$(grep -m 1 '^# version=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)

	version_local="${version_local:-1970-01-01}"

	if [ ! -f "${frobulator}" ] || [[ "${version_online}" > "${version_local}" ]]
	then
		curl -s -L get.frbltr.app > "${frobulator}"

		chmod +x "${frobulator}"
	fi

	ticker initializing

	source "${frobulator}"

	export self_arguments="${@}"
fi

# superuser ////////////////////////////////////////////////////////////////////

frobulator.escalate

# script ///////////////////////////////////////////////////////////////////////

frobulator.script

# version //////////////////////////////////////////////////////////////////////

version="2026-09-20"

# usage ////////////////////////////////////////////////////////////////////////

sites_list=()

while (($#))
do
	case "${1}"
	in
		-s|--site)
			sites_list+=("${2}")

			shift
		;;

		-h|--help)
			echo
			echo -e "Usage: ${script} -s [Site] [-s [Site] ...] | -h"
			echo
			echo -e "Options:"
			echo
			echo -e "-s, --site          Site to configure - repeatable for multiple sites."
			echo
			echo -e "                    [ mechablocks ]    [ Default ]"
			echo
			echo -e "-h, --help          Show help and usage information."
			echo
			echo -e "'${script}' [ Version // ${version} ]"
			echo

			exit
		;;

		"")
			:
		;;

		*)
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;

	esac

	shift

done

# variables ////////////////////////////////////////////////////////////////////

web_development_directory=/var/www

process="apache2"
service="${process}.service"

web="www"
hostname="${HOSTNAME}"

ip=$(hostname -I)
ip="${ip%% *}"

sites_list=("${sites_list[@]:-mechablocks}")

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

# update ///////////////////////////////////////////////////////////////////////

# frobulator.update

# frobulator.upgrade

# requirements /////////////////////////////////////////////////////////////////

list=(
	apache2
)

frobulator.require ${list[@]}

frobulator.complete

list=()

# configuration ////////////////////////////////////////////////////////////////

# sites

for item in "${sites_list[@]}"
do
	frobulator.directory "${web_development_directory}" "${item}"

	frobulator.complete

	vhost_content=$(cat <<- FILE
	<VirtualHost *:80>
		ServerName ${item}.local
		DocumentRoot /var/www/${item}/

		<Directory "/var/www/${item}/">
			Options None
			AllowOverride None
			Order allow,deny
			Allow from all
		</Directory>

		ErrorLog /var/log/${item}-error.log
		CustomLog /var/log/${item}-access.log combined
	</VirtualHost>
	FILE
	)

	frobulator.write "write" "${vhost_content}" /etc/apache2/sites-available "${item}.conf"

	frobulator.complete

	if [[ $(a2ensite "${item}".conf | grep -e "enabled") ]]
	then
		frobulator.scs "Configuration validation success" "[ ${item} ]"
		echo
	elif [[ $(a2ensite "${item}".conf | grep -e "error") ]]
	then
		frobulator.err "Configuration validation failed" "[ ${item} ]"
		echo

		exit 1
	fi

	if [[ -z $(grep -F "${item}.local" /etc/hosts) ]]
	then
		frobulator.write "append" "127.0.0.1$(printf '\t\t')${item}.local" /etc hosts

		frobulator.complete
	fi

	frobulator.inf "Setting ownership"
	echo

	chmod -R 755 "${web_development_directory}"/"${item}"

	frobulator.complete

	chown -R "${USER}":"${USER}" "${web_development_directory}"/"${item}"

	frobulator.complete

done

# service activation

frobulator.service activate "${service}"

if [ "${?}" -ne 0 ]
then
	exit 1
fi

frobulator.complete

frobulator.result "${script}"

frobulator.scs "Done"
echo
