#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [ -f "${HOME}"/.local/bin/frobulator ]
then
	rm -r -f "${HOME}"/.local/bin/frobulator
fi

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		SUDO_HOME=/root

		USER="${SUDO_USER}"

		HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${HOME}"/.local/bin ]
	then
		mkdir -p "${HOME}"/.local/bin
	fi

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${HOME}"/.local/bin/frobulator

# superuser ////////////////////////////////////////////////////////////////////

export self_arguments="${@}"

frobulator.escalate

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="06-27-2026"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"

# variables ////////////////////////////////////////////////////////////////////

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

android_debug_bridge () {

	sudo adb shell pm "${@}"

}

packages_list_malware=(
	ai.tanka.app.team
	aiphotogenerator.aivideogenerator.artgenerator.texttoimage
	all.documentreader.filereader.office.viewer
	alldocumentreader.officepdfwordexcel.hidoc
	allpdfreader.pdfviewer.editfilepdf
	allrecovery.recoverdeletedphotovideo.ezrecovery
	and.brainworks.nummatch
	and.lihuhu.machingtriple
	and.lihuhu.mahjongtriple3d
	and.lihuhu.woober
	app.parkusher.ticket911
	app.quiet.cleanmanager
	ball.sort.color.sorting.puzzle.games
	ball.sort.color.water.puzzle.games
	ball.sort.water.puzzle
	beats.color.sing.star.rush
	beetles.puzzle.solitaire
	bloodpressure.bloodpressureapp.bloodpressuretracker
	calendar.agenda.calendarplanner.agendaplanner
	calendar.agenda.schedule.event
	cc.cube.crush
	com.Avenza
	com.GMA.Ball.Sort.Puzzle
	com.Hadiz.Yogaflex
	com.Neurononfire.SupremeDuelist
	com.SuperVision.maneeea
	com.aaaudi.wordmaker
	com.accurate.weather.forecast.live.radar
	com.adobe.reader
	com.adobe.scan.android
	com.adolfodeveloper.deepcleaner
	com.aho.live.livescoreapp
	com.airmin.showdown
	com.aisecurity
	com.all.document.reader.doc.pdf.reader
	com.alldocument.focus
	com.alldocumentexplor.ade
	com.allrestore.photos.videos.recovery
	com.alphacleaner.app
	com.altnero.powersync.voltvaultfilesandreader
	com.anti.cleaner.phoener
	com.antivirus
	com.apollo.tap.master
	com.applovin.array.apphub.samsung
	com.appone.pdf.pdfreader.alldocumentreader
	com.apponemedia.filerecovery.photorecovery.alldatarecovery
	com.appswing.qr.barcodescanner.barcodereader
	com.appswing.qrcodereader.barcodescanner.qrscanner
	com.ardrawing.drawingsketch.easydraw.trace
	com.arumcomm.appstoreshortcut
	com.ast.grandmondial
	com.auraclean.clean
	com.avast.android.cleaner
	com.avenir.cycle.pinkcalendar
	com.bahiaprincipe.bahiaprincipehotels
	com.biddl.biddl
	com.bigc.numlink.number.match
	com.bigduckgames.flowfitsudoku
	com.bigduckgames.flowfitwords
	com.bitmango.go.bubblepop
	com.bitmango.go.jewelsmagicmysterymatch3
	com.block.juggle
	com.blood.sugar.health.diabetes.tool
	com.bloodapppro904b.com
	com.bravestars.savethedog.drawgame
	com.bright.flashlight.torch.led.light
	com.btinew.stickynoteabc
	com.calendar2019.hindicalendar
	com.callapp.contacts
	com.camscanner.documentscanner.pdfscanner.textscanner.photos.scanner
	com.cardgame.solitaireclassic.playrelax
	com.chating.messages.chat.fun
	com.classplash.flutemaster
	com.clean.fast.launcher
	com.clean.sweep.quick.flash
	com.clean.sweep.taipot
	com.cleaner.goal
	com.cleanertool.box
	com.cleanfix.fixplus
	com.cleansweep.junk.fadftope
	com.cleansweep.plus
	com.cleanswift.pro
	com.clear.junk.xiape
	com.cliffs.pro.cell.building.crazy.clever.craft
	com.contactsbackup.contactstransfer.sevenapp
	com.crypt.gram.puzz
	com.customuse.customuse
	com.cyber.clean
	com.daily.sunster.baught
	com.defianttech.diskdigger
	com.dhgate.buyermob
	com.dialpade.caller
	com.diamondlife.slots.vegas.free
	com.dmobileapps.barcodescanner
	com.document.reader.viewer.officepdfwordexcel
	com.document.tools.all
	com.document.viewer.doc.reader
	com.document.viewer.fileviewer.fileeditor
	com.documentreader.documentviewer.office
	com.documentreader.free.viewer.all
	com.documentreader.pdfviewer.readallfile.app
	com.docxreader.documentreader.wordoffice
	com.doprotectme
	com.doubleugames.DoubleUCasino
	com.draw.sketch.ardrawing.paint.anime
	com.dreamgames.royalmatch
	com.dts.freefiremax
	com.duangmobi.pdf
	com.easybrain.number.puzzle.game
	com.easybrain.sudoku.android
	com.easyfile.recoveryfile.eafire
	com.easyfun.solitaire
	com.easyrecovery.photorecovery.filerecover.restoredata
	com.econogames.wordsearch.gp
	com.eds.qcleanss
	com.eduspot.antivirus.clean
	com.egg.hunt.easter.egg.sort.ball.sort
	com.entertaininglogixapps.gps.navigation.direction.find.route.map.guide.pro
	com.eu.eusds
	com.eugeneadeli.ion.cleaner
	com.evergreen.games.card.solitaire.free
	com.ezetop.world
	com.ezt.pdfreader.pdfviewer
	com.fasthelperk.mogine
	com.fbd.appstore.nb
	com.ffr.filefastrecovery.recoveryfast
	com.fftools.photorecovery
	com.file.photo.recovery.deleted.restore
	com.file.recoveryultra.filerecovey
	com.file.respho.mar
	com.fileclean.manager.easy
	com.filemaster.cleaner.cachae
	com.filerecovery.allrecovery.mate
	com.filerecovery.plus
	com.filerecovery.recoverphoto.restoreimage
	com.filerestore.datarecovery.photorecovery
	com.files.restore.recovery.tool.deleted.document.photo.video.app
	com.files.restore.recovery.tool.deleted.document.photo.video.audio.app.mobile.scan.utility
	com.fingerlab.words.block
	com.fiogonia.hearts
	com.flashlight.lucky.dog
	com.footballtv.easycircle
	com.footballworldcup.fsc.livestreamfootballgame
	com.free.spider.solitaire.card.game
	com.fugo.wow
	com.gallery.albums.photomanager
	com.galleryphotoandvideomanager.picturegalleryapp
	com.gam.voicetranslater.cameratranslator.translate
	com.gamma.scan
	com.gamovation.mahjongclub
	com.gamovation.sudoku
	com.gamovation.tileclub
	com.gangster.mafia.crime.game
	com.gd.pdf.reader.pdfviewer
	com.gismart.guitar
	com.glimzoid.froobly.mad
	com.gnostic.proxy.wuhoo
	com.gogo.photo.recover
	com.google.android.apps.adwords
	com.gps.routfinder.maps.navigation.directions.free.app
	com.gpscamera.timestamp.photolocation.geotag.gpsmapcamera
	com.gpsnavigation.routeplanner.livemaproad.routefinder
	com.gpsroutefinder.mobile.location.tracker.gps.maps.locator.route.finder
	com.gpsroutefinder.routemap.gpsnavigation.maps
	com.grandcashslots.free.gp
	com.grandegames.slots.dafu.casino
	com.gratis.docviewer
	com.greyfun.block.puzzle.sudoku
	com.guavapay.mobile
	com.heartpulse.healthycompanion.tracker
	com.hidden.object.find.beauty.search.games.free
	com.hide.applock.protect.vaultg.fingerlock.free
	com.higgs.slotsmash
	com.hoaduong.filerecovery.photorecovery.alldatarecovery
	com.homa.free.solitaire.card.game
	com.htroutine2023.planapp
	com.huty.cozy.weather
	com.igg.android.lordsmobile
	com.ikame.pdf.pdfreader.pdfviewer.editor
	com.ikeyboard.theme.neon.love
	com.inscode.autoclicker
	com.inspiredsquare.jupiter1
	com.iosgalleryigallery.iphonegallery
	com.jisunk.photo.data.recovry
	com.jjqq.easy.cleaner
	com.jogjateam.easy.junk.clean
	com.joistapp.android.joist
	com.junk.security.files.scanner.killer.stcleaner
	com.junkeraser.max
	com.junkfiles.buster.eraperivp
	com.jvstudios.gpstracker
	com.kdanmobile.android.pdfreader.google.pad
	com.keep.recovery.keeprecovery
	com.king.candycrushsaga
	com.king.candycrushsodasaga
	com.kiwifun.game.android.numbermaster.puzzles
	com.labour.video.fast.hd.downloader.secure.player
	com.ledlight.flashalert.ledtorchlight.ledtext
	com.lff.jungle.dozer.coin.story.google
	com.lhd.drawbackflip
	com.lhd.drawmonowheel3d
	com.live.earthview.maps.gpsfinder.globalsatellite.apps
	com.live.score.football.app
	com.live.street.view.streetview.maps.gps.navigation.route.finder.gpsnav
	com.lmtopx.recoverjtph
	com.logic.puzzle.games.number.match
	com.lordix.addonsforminecraftpe
	com.lordix.masterforminecraft
	com.magical.smart.alban
	com.maps.gps.places.location.address.routefinder.nearby.gpsmapslocationandnearby
	com.maps.voice.navigation.traffic.gps.location.route.driving.directions
	com.marriott.mrt
	com.masterappstudio.qrcodereader
	com.mediamushroom.copymydata
	com.menstrual.health.manage
	com.merge.puzzle.games.block.link
	com.merik.translator
	com.messagerecovery.deletedmessagesrecovery.filerecovery
	com.messenger.sms.messages.text.messaging.chat
	com.microsoft.office.word
	com.mnogogames.triviascapes
	com.mobile.cleaner.sfopsye
	com.mobile.pdf.reader.document.vt09v
	com.mobilityware.CastleSolitaire
	com.mobilityware.solitaire
	com.modesens.androidapp
	com.mods.mcpe.skins.master
	com.mouhameadfms.instantclean
	com.mwm.sampler
	com.myhomescreen.messenger.home.emoji.lite
	com.netmarble.kofafk
	com.newpubco.klondikesolitaire
	com.nexus.pdfreader.pdfviewer.editor
	com.nimbusapps.qrcodescanner
	com.ninijia.snake
	com.ntfileapp.fierecovery
	com.oakever.tiletrip
	com.officeapp.pdf.readerapp
	com.officedocument.word.docx.document.viewer
	com.officepdf.pdfeditor.pdfreader
	com.onecwireless.mahjong3.google.free
	com.open.web.ai.browser
	com.openmygame.games.android.sudokumaster
	com.opgames.mahjongtile.gp
	com.otto.recovery.photorecovery
	com.otto.restore.restorephoto
	com.papegames.lysk.en
	com.partner.filespeed.panpa
	com.pdf.document.reader
	com.pdf.document.viewer.reader.word.excel.office
	com.pdf.edit.read.pdfreader
	com.pdf.editor.reader.larrybrook.app
	com.pdf.editor.viewer.pdfreader.pdfviewer
	com.pdf.note.reader
	com.pdf.pdfreader.pdfviewer.editor
	com.pdf.read.view.editor.pdfreader.pdfviewer
	com.pdf.reader.document.viewer
	com.pdf.reader.pdfviewer.pdfbookreader.readpdf
	com.pdf.reader.pdfviewer.pdfeditor.forandroid
	com.pdf.viewer.good
	com.pdfapp.ezpdf
	com.pdfapp.pdfreader.pdfeditor.pdfscanner
	com.pdffile.reader.pdffr
	com.pdffileeditor.pro
	com.pdfreader.document.manager.viewer.file
	com.pdfreader.free.viewer.documentreader
	com.pdfreader.pdfeditor.scandocu.pro.app.amb
	com.pdfreader.pdfpoint
	com.pdfreader.zone
	com.pdfview.allapp
	com.pdfview.finder
	com.pdfviewer.prodoc
	com.pdfviewer.readpdf
	com.pdfviewer.scanner
	com.peacock.flashlight
	com.pelmorex.WeatherEyeAndroid
	com.penguin.escape.dash
	com.peoplefun.wordcross
	com.phone.cleaner.junk.files.use.android
	com.phone.cleaner.kityraect
	com.phone.cleaner.shineapps
	com.phonecleaner.storagecleaner.junkcleaner.cleanphone
	com.phonerecovery.filerecovery.pfr
	com.phonestorage.cleanup
	com.photogalleryapp.album.gallery
	com.photorecovery.filerecovery.recoverall
	com.photorecovery.filerecovery.restorefile
	com.photorestore.filerecovery.videorecovery
	com.photovault.photoalbumgallery
	com.pinterest
	com.piriform.ccleaner
	com.pixel.art.coloring.color.number
	com.platinumplayer.word.addict
	com.playojo.www
	com.playrix.gardenscapes
	com.playtika.wsop.gp
	com.playvalve.solitaire
	com.playvalve.watersort
	com.playwing.acu.huawei
	com.plusphoto.recovery.co
	com.poshmark.app
	com.powerful.flashlight.launcher.max
	com.prd.pdf.document
	com.prequelapp.hula
	com.procleaner.clean
	com.proxypics.app
	com.pulseal.qrlarcs
	com.purplekiwii.vegaskeno
	com.purplekiwii.vegaslive
	com.pvoercase.recover
	com.qdcv.clime.weather
	com.qr.code.reader.scanner.qrscan.android
	com.qrcodeai.smartscanner
	com.qrcodescanner.barcodereader.scanbarcode
	com.qrx2.barcodescanner.qrcodereader
	com.qrzoom.cnchzj
	com.quickdoc.pdfreader
	com.ratrodstudio.skateparty3lite
	com.readall.docspdf.reader
	com.recoverall.allrecoverphotos.allrecoverfiles
	com.recoverdeletedphotos.photorecovery.filerecovery.video
	com.recoverfile.restorephoto
	com.recovery.restore.filerecovery.photos.videos.data
	com.recoveryphotos.videos.allfiles
	com.rescue.psoeprs.solf
	com.restoreimages.photorecovery
	com.revive.gptwne.copro
	com.rover.android
	com.rsupport.rs.activity.rsupport.aas2
	com.rvlife.rvlife
	com.sanvga.security.pejur
	com.sauceapp.solitaire.lite.klondike
	com.scan.qrcode.tool.scanner
	com.scannerreader.qrcode.creatorfree
	com.scanqrcode.barcodereader.qrcodegenerator.qrcode.aiqrgenerate
	com.scopely.m3samsung
	com.sd.arabickeyboard
	com.sec.android.app.popupcalculator
	com.security.fileguard
	com.senssc.sensclean
	com.sephora
	com.severex.cross.word.puzzle.logic
	com.severex.trivia.quiz.brain.puzzle
	com.sezane.android
	com.sherwin.diy
	com.shotsy.app
	com.skype.raider
	com.sli.photo.findrec
	com.slots.free.vegas.casino.jackpotland
	com.smart.clean.spacebiaqre
	com.smart.recover.photorecovery
	com.smartmanager.storagespace
	com.smartpdf.viewer
	com.smilerlee.klondike
	com.snap.intelligence.musics
	com.softowelgames.casual.free.word.puzzle.game.connect.letters.paradise
	com.softtowelgames.cwp.android
	com.solara.filerecovery
	com.solara.qrcodescanner
	com.solusimediainformasi.mobilerecover
	com.space.reclaimer.sr
	com.spacegame.basic3
	com.starplay.spider.fighter.openworld
	com.step.fight
	com.storage.clean.nietsnie
	com.storage.junk.sparkclean.new
	com.suk.phonedata.filerecover.photo.videorecovery
	com.surpax.ledflashlight.panel
	com.symantec.mobilesecurity
	com.symantec.securewifi
	com.taymay.magnifying.glass
	com.taymay.pdf.reader
	com.teacapps.barcodescanner
	com.tenmatch.numberpair
	com.text.call.textunlimited.free
	com.text.messages.sms.emoji
	com.thehomedepotca
	com.thermometer.room.temperature.checker
	com.topultragame.slotlasvega
	com.translate.all.languages.translator.free.voice.translation
	com.trashrecovery.recoverdata
	com.triangular.bootyslam
	com.tripledot.solitaire
	com.tripledot.tile.dynasty
	com.trivia.star.android
	com.trusted.pdfeditor.pdfreader
	com.trustedapp.pdfreaderpdfviewer
	com.trythecolors.paintmyhouse
	com.tw.tycoon.casino
	com.utilitiesandtool.pdfreader
	com.vegasgames.tdactylskillpoker
	com.video.data.photorecovery.filerecovery.deletedrestore
	com.video.x.file.image.recovery
	com.vidmate.video.downloader.hd.mp4.saver
	com.vitastudio.mahjong
	com.vitec.easelifeEn
	com.vngtx.filerecovery.photorecovery.datarecovery
	com.voicetexttranslate.voicetranslator
	com.vox.pdf.taopao
	com.vrbo.android
	com.whizwhiz.clean
	com.wilds.craft.mysticland.explore
	com.wonderful.mahjong
	com.wonderpeople.megahitpoker.global
	com.wordgame.wordconnect.fr
	com.wp.clean.sep
	com.xdev.docxreader.docx.docxviewer.document.doc.office.viewer.reader.word
	com.xiyou.puzzle.card.solitaire.classic
	com.xmonetize.quizzland
	com.xtra.video.hd.downloader
	com.yaohuo.xingyu
	com.yardi.systems.rentcafe.resident
	com.yolo.hiddenobjects
	com.yousician.yousician
	com.yukongoldonline
	com.yur.pdf.reader
	com.zhiliaoapp.musically
	com.zip.archiver.rar.es.expert
	com.zm.crossmath
	com.zm.watersort
	com.zoovex.pro.zoom
	com.zorinos.zorin_connect
	com.zte.nubrowser
	com.zynga.hititrich
	com.zynga.words3
	com.zzkko
	core.readpdf.com
	daily.number.match.free.puzzle
	de.fastic.app
	documentreader.officeviewer.filereader.all.doc
	duy.pdf.reader
	easy.magnifier.em
	easy.sudoku.puzzle.solver.free
	fast.documentreader.pdfviewer.pdfreader
	fasteasy.dailyburn.fastingtracker
	file.recovery.photo.video.audio.document.restore.findback
	filerecovery.photosrecovery.allrecovery
	flipboard.boxer.app
	footballscore.footballlivematch.liveupdate.livematch.charan
	free.video.downloader.freevideodownloader2021.video.saver.videosaverlite
	gallery.photogallery.memory.photoeditor.vault.album
	gallery.photogallery.pictures.vault.album
	games.conifer.card.solitaire.klondike.free
	geolocationmapcamera.locationstamp.gpsphotocamera
	ic.island.conquest
	in.playsimple.tripcross
	io.supercent.linkedcubic
	io.voodoo.holeio
	io.voodoo.paper2
	jb.jump.buddy
	jewels.pdf.reader.viewer
	jewels.qrcode.scanner
	jp.co.goodroid.hyper.hexaaway
	jp.drsv.SkateSpace
	kidultlovin.word.zen
	linkdesks.classic.solitaire.klondike
	mahjong.solitaire.card.games.free.senior.match.puzzle
	mahjongsolitaire.mahjong.solitaire.free.offline.game
	master.pdfviewerreader.com
	math.crossmath.game.puzzle.free.easyfun.number.sudoku.match
	math.puzzle.games.crossmath.number.puzzles.free
	me.zepeto.main
	mica.recov.dlaq.phoqem
	mmapps.mobile.magnifier
	my.tasks.mtt
	net.doo.snap
	net.supertreat.solitaire
	net.wordbit.enfr
	no.nrk.yr
	number.games.match.numbers.ten.puzzle.free
	nut.sort.color.puzzle.offline.games
	org.chromium.webapk.a603fd7fa6b08567c_v2
	org.chromium.webapk.aa157a4769e41a5c9_v2
	org.chromium.webapk.aff81623bf56c4c50_v2
	org.zwanoo.android.speedtest
	pdf.office.reader.viewer.editor
	pdf.pdfreader.pdfeditor.pdfmaker.pdfscanner
	pdf.pdfreader.pdfviewer.reader.officelens
	pdf.pdfreader.viewer.editor.free
	pdf.reader.pdf.viewer.all.document.reader.office.viewer
	pdf.reader.pdfreader.pdfviewer.pdfreaderfree
	pdf.reader.pdfviewer.pdfeditor
	pdfreader.pdfviewer.allofficedocumentreader.pdfgo
	pdfreader.pdfviewer.free.officetool
	pdfreader.pdfviewer.officetool.pdfscanner
	pdfreader.pdfviewer.pdf.editor
	pdfreader.pdfviewer.pdfeditor.pdfscanner.pdf.document.pdf
	pdfreader.proeditor.freepdfviewer
	pdfscanner.scan.pdf.scanner.free
	pedometer.steptracker.calorieburner.stepcounter
	photo.manager.private.photogallery
	photo.photovault.hidepictures.gallery.lockgallery
	photo.video.allrecovery.aiapp.recovery
	photorecovery.datarecovery.allrecovery
	photos.gallery.album.imagelock.photovault
	playxo.video.player
	pocket.calc.pcc
	pro.viewpdf.com
	qrcodereader.barcodescanner.scan.qrscanner
	qrcodescanner.barcodescanner.qrscanner.qrcodereader
	recover.deleted.messages.business.messagerecovery
	restore.deleted.messages.recoveryapp
	roblox.clothes.skin.maker.editor
	slots.pcg.casino.games.free.android
	smash.pdf.reader.viewer
	solitaire.classicgame.klondike.solitaire.freecard
	sort.ball.color.puzzle.sorting.tube.game
	spider.classic.solitaire.card.pgmaker
	stepcounter.pedometer.stepstracker
	storage.manager.ora
	sudoku.puzzle.brain.games.number.puzzles.free
	sudoku.puzzle.free.game.brain
	swiftflyers.homeworkout.chair.floor.bed.exercise.forlazy
	tb.tappy.ball
	tc.tc.scsm.phonegap
	teskin.jewels.planet
	video.player.videoplayer
	video.save.downloader.saver.hd.download.any
	water.minder.wmx
	wht.phot.house.recov
	wiac.gpak.nvqe.allrecovery
	word.connect.free
	words.puzzle.wordgame.free.connect
)

packages_list_amazon=(
	com.amazon.mShop.android.shopping
	com.amazon.appmanager
)

packages_list_android=(

)

packages_list_carrier=(
	com.telus.myaccount
	com.telus.checkup
)

packages_list_facebook=(
	com.facebook.appmanager
	com.facebook.services
	com.facebook.system
)

packages_list_google=(

)

packages_list_microsoft=(
	com.microsoft.appmanager
	com.microsoft.office.outlook
	com.microsoft.rdc.androidx
	com.microsoft.skydrive
	com.samsung.android.mdx
	com.microsoft.android.mdx
)

packages_list_onyx=(
	com.android.theme.font.notoserifsource

	# com.onyx
	# com.onyx.android.ksync
	# com.onyx.android.note
	# com.onyx.android.onyxotaservice
	# com.onyx.floatingbutton
	# com.onyx.gallery
	com.onyx.igetshop
	# com.onyx.kreader
	# com.onyx.tscalibration

	com.onyx.aiassistant
	com.onyx.android.production.test
	com.onyx.appmarket
	com.onyx.calculator
	com.onyx.clock
	com.onyx.dict
	com.onyx.easytransfer
	com.onyx.kime
	com.onyx.latinime
	com.onyx.mail
	com.onyx.musicplayer
	com.onyx.voicerecorder
	org.chromium.chrome
)

packages_list_samsung=(
	com.samsung.android.kidsinstaller
)

packages_list=(
	${packages_list_amazon[@]}
	${packages_list_carrier[@]}
	${packages_list_microsoft[@]}
	${packages_list_onyx[@]}
	${packages_list_samsung[@]}
	${packages_list_malware[@]}
)

for application in "${packages_list[@]}"
do
	if [[ $(android_debug_bridge list packages | grep -F -x "package:${application}") ]]
	then
		frobulator.inf "Package on device" "[ ${application} ]"
		echo

		frobulator.wrn "Removing package" "[ ${application} ]"
		echo

		android_debug_bridge uninstall -k --user 0 "${application}"
	else
		frobulator.fwd "Not on device" "[ ${application} ]"
		echo
	fi
done

frobulator.scs 'Done'
echo
