#!/bin/bash

# superuser ////////////////////////////////////////////////////////////////////

if [[ $(id -u -n) = "root" ]]
then
    if [ -z "${SUDO:-$HOME}" ]
    then
        SUDO_HOME=/root
    else
        SUDO_HOME="${SUDO:-$HOME}"
    fi

	USER="${SUDO_USER}"
	USER_HOME=/home/"${USER}"
else
    # restart as superuser

    exec sudo bash "${0}" "${@}"
fi

# dependencies /////////////////////////////////////////////////////////////////

if [[ -z $(command -v frobulator) ]]
then
    if [[ -z $(command -v curl) ]]
    then
        yes | apt-get install curl
    fi

    curl -s -L get.frbltr.app > /usr/bin/frobulator

    chmod +x /usr/bin/frobulator
fi

. /usr/bin/frobulator

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version=""

# usage ////////////////////////////////////////////////////////////////////////

# variables ////////////////////////////////////////////////////////////////////

stamp=$(date +"%m-%d-%Y-%H-%M-%S")

# defaults /////////////////////////////////////////////////////////////////////

list=(
	gsettings
)

frobulator.require ${list[@]}

# functions ////////////////////////////////////////////////////////////////////

cat <<- 'FILE' > /usr/bin/background-cycler
#!/bin/bash

# background cycler #

directory=$(zenity --file-selection --separator=$'\n' --title="Select a Directory") 2> /dev/null

gsettings set org.gnome.desktop.background picture-options "zoom"

while true
do
	picture="$(ls $directory | sort -R | head -n 1)"

	gsettings set org.gnome.desktop.background picture-uri "file://${picture}"

	sleep 60
done
FILE

# set permissions

sudo chmod +x /usr/bin/background-cycler

# write launcher

cat <<- FILE > /usr/share/applications/background-cycler.desktop
[Desktop Entry]
Name=Background Cycler
Comment=Enable timed background cycling
Exec=/usr/bin/background-cycler
Icon=background
Terminal=false
Type=Application
StartupNotify=true
Categories=Utility;
FILE
