#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

script="$(basename -- ${BASH_SOURCE[0]})"

if [[ "${frobulator_loaded}" != "true" ]]
then
	echo

	ticker () {

		for ticker in '>  ' '>> ' '>>>'
		do
			echo -n -e "\r[  ${ticker}  ] ${1^}..."

			sleep 0.5
		done

		echo

		echo

	}

	if [[ $(id -u -n) = "root" ]]
	then
		USER="${SUDO_USER:-root}"

		if [ "${USER}" = "root" ]
		then
			HOME=/root
		else
			HOME="/home/${USER}"
		fi
	fi

	ticker checking

	package_managers_list=(
		"apt-get --quiet --quiet update > /dev/null 2>&1; apt-get --quiet --quiet install --yes"
		"dnf --quiet install --assumeyes"
		"yum --quiet install --assumeyes"
		"apk add --quiet"
		"pacman --sync --refresh --noconfirm --noprogressbar"
		"zypper --quiet --non-interactive install"
	)

	package="curl"

	if [[ -z $(command -v "${package}") ]]
	then
		for package_manager in "${package_managers_list[@]}"
		do
			entry="${package_manager%% *}"

			if [[ -n $(command -v "${entry}") ]]
			then
				eval "${package_manager} ${package} > /dev/null 2>&1"

				break
			fi
		done

		if [[ -z $(command -v "${package}") ]]
		then
			echo "[  !  ] Unable to install or binary not found /////////////////////// [ '${package}' ]"
			echo

			exit 1
		fi
	fi

	mkdir -p "${HOME}"/.local/bin

	frobulator="${HOME}"/.local/bin/frobulator

	version_online=$(curl -s -L get.frbltr.app | grep -m 1 '^# version=' | cut -d '"' -f 2)

	version_local=$(grep -m 1 '^# version=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)

	version_local="${version_local:-1970-01-01}"

	if [ ! -f "${frobulator}" ] || [[ "${version_online}" > "${version_local}" ]]
	then
		curl -s -L get.frbltr.app > "${frobulator}"

		chmod +x "${frobulator}"
	fi

	ticker initializing

	source "${frobulator}"

	export self_arguments="${@}"
fi

# superuser ////////////////////////////////////////////////////////////////////

frobulator.escalate

# script ///////////////////////////////////////////////////////////////////////

frobulator.script

# version //////////////////////////////////////////////////////////////////////

version="07-13-2026"

# usage ////////////////////////////////////////////////////////////////////////

# variables ////////////////////////////////////////////////////////////////////

process="rclone-google-drive"
service="${process}.service"
tracker="${HOME}"/.local/bin/rclone-google-drive-run-count

cloud_service="google drive"

cloud_server_directory="drive:"
local_server_directory="/media/internal"

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

# update ///////////////////////////////////////////////////////////////////////

# frobulator.update

# frobulator.upgrade

# requirements /////////////////////////////////////////////////////////////////

list=(
	inotify-tools
)

frobulator.require ${list[@]}

list=()

# configuration ////////////////////////////////////////////////////////////////

list=(
	rclone
	rclone-browser
)

frobulator.require "${list[@]}"

frobulator.complete

list=()

if [ -d /media/[iI]nternal/[rR][cC]lone ]
then
	if [ -f /media/[iI]nternal/[rR][cC]lone/rclone.conf ]
	then
		frobulator.inf "Linking configuration"
		echo

		frobulator.directory "${HOME}" .config/rclone

		frobulator.link /media/[iI]nternal/[rR][cC]lone/ "${HOME}"/.config/rclone rclone.conf

		frobulator.complete
	fi
fi

# script

cat <<- FILE > "${HOME}"/.local/bin/"${process}"
#!/bin/bash

# variables ////////////////////////////////////////////////////////////////////

cloud_server_directory="drive:"
local_server_directory="/media/internal"

run_count_tracker="\${HOME}"/.local/bin/rclone-google-drive-run-count

# functions ////////////////////////////////////////////////////////////////////

rclone_transfer () {

${TAB}rclone=/usr/bin/rclone

${TAB}checkers="64"
${TAB}max_lock="120"
${TAB}modify_window="1"
${TAB}streams="16"
${TAB}transfers="32"
${TAB}log_file="${HOME}/.config/rclone/rclone.log"

${TAB}synchronization_option="\${1}"

${TAB}source="\${2}"
${TAB}destination="\${3}"

${TAB}shift 3

${TAB}extra_arguments=("\${@}")

${TAB}transfer_command=()

${TAB}transfer_command+=(\${rclone})
${TAB}transfer_command+=(\${synchronization_option})
${TAB}transfer_command+=(\${source})
${TAB}transfer_command+=(\${destination})
${TAB}transfer_command+=(--compare size,modtime,checksum)
${TAB}transfer_command+=(--checkers \${checkers})
${TAB}transfer_command+=(--create-empty-src-dirs)
${TAB}transfer_command+=(--drive-acknowledge-abuse)
${TAB}transfer_command+=(--drive-skip-dangling-shortcuts)
${TAB}transfer_command+=(--drive-skip-gdocs)
${TAB}transfer_command+=(--drive-skip-shortcuts)
${TAB}transfer_command+=(--fix-case)
${TAB}transfer_command+=(--max-lock \${max_lock}s)
${TAB}transfer_command+=(--metadata)
${TAB}transfer_command+=(--exclude '.Trash-*/**')
${TAB}transfer_command+=(--modify-window \${modify_window}s)
${TAB}transfer_command+=(--multi-thread-streams \${streams})
${TAB}transfer_command+=(--recover)
${TAB}transfer_command+=(--track-renames)
${TAB}transfer_command+=(--transfers \${transfers})
${TAB}if (( run_count == 0 || run_count % 10 == 0 ))
${TAB}then
${TAB}${TAB}echo "Resync triggered - count \${run_count}"
${TAB}${TAB}echo

${TAB}${TAB}transfer_command+=(--resync)
${TAB}${TAB}transfer_command+=(--resync-mode newer)
${TAB}fi

${TAB}transfer_command+=(--progress)
${TAB}transfer_command+=(--verbose)
${TAB}transfer_command+=(--log-file \${log_file})

${TAB}transfer_command+=("\${extra_arguments[@]}")

${TAB}eval \${transfer_command[@]}
}

# batch directory management

# set IFS

synchronize () {

${TAB}if [ -e "\${run_count_tracker}" ]
${TAB}then
${TAB}${TAB}run_count=\$(cat "\${run_count_tracker}")
${TAB}else
${TAB}${TAB}run_count=0
${TAB}fi

${TAB}echo "\${run_count}" > "\${run_count_tracker}"

${TAB}echo
${TAB}echo "Run start - count: \${run_count}"
${TAB}echo

${TAB}IFS=\$'\n'

${TAB}server_directories_list=(
${TAB}${TAB}\$(find "\${local_server_directory}"	\\
${TAB}${TAB}${TAB}-mindepth 1						\\
${TAB}${TAB}${TAB}-maxdepth 1						\\
${TAB}${TAB}${TAB}-type d							\\
${TAB}${TAB}${TAB}! -iname "*.Trash*"				\\
${TAB}${TAB})
${TAB})

${TAB}IFS=''

${TAB}rclone_transfer bisync "\${cloud_server_directory}/" "\${local_server_directory}/" --max-depth 1

${TAB}for server_directory in "\${server_directories_list[@]}"
${TAB}do
${TAB}${TAB}server_directory=\${server_directory##*/}

${TAB}${TAB}rclone_transfer bisync "\${cloud_server_directory}/\${server_directory}" "\${local_server_directory}/\${server_directory}"

${TAB}${TAB}sleep 1
${TAB}done

${TAB}run_count=\$((run_count + 1))

${TAB}echo "\${run_count}" > "\${run_count_tracker}"

${TAB}echo
${TAB}echo "Run end - count: \${run_count}"
${TAB}echo
}

# unset directory list

server_directories_list=()

# initial sync, then event-driven for local changes, periodic for cloud-side changes

synchronize

periodic_interval="600"

(
${TAB}while true
${TAB}do
${TAB}${TAB}sleep "\${periodic_interval}"

${TAB}${TAB}synchronize
${TAB}done
) &

inotifywait																\\
${TAB}--monitor															\\
${TAB}--recursive														\\
${TAB}--event modify,create,delete,move,attrib							\\
${TAB}--exclude '(\.?Trash.*|\.?Git.*/)'								\\
${TAB}																	"\${local_server_directory}" |
while read -r inotify_directory inotify_event inotify_file
do
${TAB}debounce_pending=true

${TAB}while \${debounce_pending}
${TAB}do
${TAB}${TAB}read -t 2 -r inotify_directory inotify_event inotify_file 2> "\${sink}"
${TAB}${TAB}read_status="\${?}"

${TAB}${TAB}if [ "\${read_status}" -ge 128 ] || [ "\${read_status}" -eq 1 ]
${TAB}${TAB}then
${TAB}${TAB}${TAB}debounce_pending=false
${TAB}${TAB}fi
${TAB}done

${TAB}synchronize
done
FILE

frobulator.complete

# permissions

chmod +x "${HOME}"/.local/bin/"${process}"

frobulator.complete

# service

frobulator.directory /etc/systemd system

frobulator.complete

# service desciptor

cat <<- FILE > /etc/systemd/system/"${service}"
[Unit]
Description=Synchronize Google Drive using RClone
After=network-online.target
Wants=network-online.target

[Service]
User=${USER}
Group=${USER}
Environment=HOME=${HOME}
ExecStart=${SHELL} ${HOME}/.local/bin/${process}
Restart=always
RestartSec=1s
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
FILE

frobulator.complete

# prepare

frobulator.delete "$(dirname "${tracker}")" "$(basename "${tracker}")"

frobulator.delete "${HOME}"/.cache rclone

frobulator.complete

# service activation

frobulator.service activate "${service}"

frobulator.complete

frobulator.result "${script}"

frobulator.scs "Done"
echo
