#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

ticker () {

	echo

	for ticker in '>  ' '>> ' '>>>'
	do
		echo -n -e "\r[  ${ticker}  ] ${1^}..."

		sleep 0.5
	done

	echo

	echo

}

if [[ $(id -u -n) = "root" ]]
then
	USER="${SUDO_USER:-root}"

	if [ "${USER}" = "root" ]
	then
		HOME=/root
	else
		HOME="/home/${USER}"
	fi
fi

ticker checking

package_managers_list=(
	"apt-get --quiet --quiet update > /dev/null 2>&1; apt-get --quiet --quiet install --yes"
	"dnf --quiet install --assumeyes"
	"yum --quiet install --assumeyes"
	"apk add --quiet"
	"pacman --sync --refresh --noconfirm --noprogressbar"
	"zypper --quiet --non-interactive install"
)

package="curl"

if [[ -z $(command -v "${package}") ]]
then
	for package_manager in "${package_managers_list[@]}"
	do
		entry="${package_manager%% *}"

		if [[ -n $(command -v "${entry}") ]]
		then
			eval "${package_manager} ${package} > /dev/null 2>&1"

			break
		fi
	done

	if [[ -z $(command -v "${package}") ]]
	then
		echo "[  !  ] Unable to install or binary not found /////////////////////// [ '${package}' ]"
		echo

		exit 1
	fi
fi

mkdir -p "${HOME}"/.local/bin

frobulator="${HOME}"/.local/bin/frobulator

version_online=$(curl -s -L get.frbltr.app | grep -m 1 '^# version=' | cut -d '"' -f 2)
version_local=$(grep -m 1 '^# version=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)

version_local="${version_local:-1970-01-01}"

if [ ! -f "${frobulator}" ] || [[ "${version_online}" > "${version_local}" ]]
then
	curl -s -L get.frbltr.app > "${frobulator}"

	chmod +x "${frobulator}"
fi

ticker initializing

source "${frobulator}"

# script ///////////////////////////////////////////////////////////////////////

script="$(basename -- ${BASH_SOURCE[0]})"

# version //////////////////////////////////////////////////////////////////////

version="2023-01-10"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

# variables ////////////////////////////////////////////////////////////////////

docker_image_name="pihole"
docker_image_address="192.168.86.13"
docker_image_base="/var"
docker_image_container="docker"
docker_image_directory="${docker_image_base}"/"${docker_image_container}"/"${docker_image_name}"
docker_image_password=$(docker logs "${docker_image_name}" 2> /dev/null | grep 'password:' | cut -d ':' -f 2 | sed 's/^ //')
docker_image_source="${docker_image_name}"/"${docker_image_name}:latest"
docker_image_id=$(docker container ls --all --quiet --filter "name=${docker_image_name}")

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

# update ///////////////////////////////////////////////////////////////////////

# frobulator.update

# frobulator.upgrade

# requirements /////////////////////////////////////////////////////////////////

list=(
	docker
	docker-clean
	docker-compose
	docker-registry
	docker.io
)

frobulator.require ${list[@]}

list=()

# configuration ////////////////////////////////////////////////////////////////

if [[ ! -d "${docker_image_directory}" ]]
then
	frobulator.directory "${docker_image_base}/${docker_image_container}" "${docker_image_name}"
else
	frobulator.log "docker stop ${docker_image_name}"
	frobulator.log "docker rm -f ${docker_image_name}"

	frobulator.delete "${docker_image_base}/${docker_image_container}" "${docker_image_name}"

	wait

	frobulator.directory "${docker_image_base}/${docker_image_container}" "${docker_image_name}"
fi

frobulator.inf "Deploying" "[ ${docker_image_name} ]"
echo

frobulator.fwd "Deploying..."
echo

docker run																					\
	--detach																				\
	--name "${docker_image_name}"															\
	--dns=127.0.0.1																			\
	--dns=1.1.1.1																			\
	--restart=unless-stopped																\
	--hostname "${docker_image_name}"														\
	-p 53:53/tcp																			\
	-p 53:53/udp																			\
	-p 80:80																				\
	-v "${docker_image_directory}/etc-${docker_image_name}:/etc/${docker_image_name}"		\
	-v "${docker_image_directory}/etc-dnsmasq.d:/etc/dnsmasq.d"								\
	-e tz="america/toronto"																	\
	-e virtual_host="${docker_image_name}"													\
	-e proxy_location="${docker_image_name}"												\
	-e ftlconf_local_ipv4="${docker_image_address}"											\
																							"${docker_image_source}" > /dev/null 2>&1

wait

frobulator.write "${docker_image_password}" "${docker_image_directory}" password

frobulator.inf "Image ID" "[ ${docker_image_id} ]"
echo

frobulator.inf "Password" "[ ${docker_image_password} ]"
echo

frobulator.scs "Done."
