#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [ -f "${HOME}"/.local/bin/frobulator ]
then
	. "${HOME}"/.local/bin/frobulator

	frobulator.fwd 'Updating...'
	echo

	rm -r -f "${HOME}"/.local/bin/frobulator
else
	echo -n -e '[ ▷ ] Updating...'
	echo
fi

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = 'root' ]]
	then
		SUDO_HOME=/root

		USER="${SUDO_USER}"

		HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${HOME}"/.local/bin ]
	then
		mkdir -p "${HOME}"/.local/bin
	fi

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${HOME}"/.local/bin/frobulator

# superuser ////////////////////////////////////////////////////////////////////

export self_arguments="${@}"

frobulator.escalate

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version='05-21-2026'

# variables ////////////////////////////////////////////////////////////////////

input_user=''

input_file=''

download_directory='tracks'

duration_minimum=120

duration_maximum=780

search_count='1'

sleep_minimum=1

sleep_maximum=5

solver='deno'

runtime_javascript="${solver}:$(command -v ${solver})"

extension_track='mp3'

# usage ////////////////////////////////////////////////////////////////////////

usage () {

	echo
	echo "usage: ${script} [option]"
	echo
	echo 'input:'
	echo '  -i, --input <track>     search/download a single track'
	echo '  -f, --file <file>       search/download tracks from file'
	echo
	echo 'options:'
	echo '  -h, --help              show this help'
	echo
}

# arguments ////////////////////////////////////////////////////////////////////

while [ "${#}" -gt 0 ]
do
	case "${1}" in

		-i|--input)
			if [ -n "${input_user}" ] ||
			   [ -n "${input_file}" ]
			then
				frobulator.err 'Only one input source may be used'

				usage

				exit 1
			fi

			input_user="${2}"

			shift 2
		;;

		-f|--file)
			if [ -n "${input_user}" ] ||
			   [ -n "${input_file}" ]
			then
				frobulator.err 'Only one input source may be used'

				usage

				exit 1
			fi

			input_file="${2}"

			shift 2
		;;

		-h|--help)
			usage

			exit 0
		;;

		*)
			frobulator.err "Unknown argument: ${1}"

			usage

			exit 1
		;;

	esac
done

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Processing ${script#*-}"

# functions ////////////////////////////////////////////////////////////////////

browser_identify () {

	local browser

	browser=$(
		xdg-settings get default-web-browser 2>"${sink}"
	)

	browser=${browser%.desktop}

	case "${browser}" in

		firefox*		|
		librewolf*		|
		waterfox*		)
						browser='firefox'
		;;

		chrome*			|
		google-chrome*	|
		chromium*		|
		brave*			|
		vivaldi*		|
		opera*			)
						browser='chrome'
		;;

		*)
			frobulator.err 'Unsupported browser'

			exit 1
		;;

	esac

	echo "${browser}"
}

normalize () {

	echo "${1}"						|

		tr '[:upper:]' '[:lower:]'	|

		tr '/:' '--'				|

		sed								\
			-e 's/[^a-z0-9._ -]//g'		\
			-e 's/[[:space:]]\+/ /g'	\
			-e 's/^ *//g'				\
			-e 's/ *$//g'
}

sleep_randomize () {

	duration_sleep=$(( RANDOM % ( sleep_maximum - sleep_minimum + 1 ) + sleep_minimum ))

	frobulator.fwd "Sleeping ${duration_sleep} seconds"

	sleep "${duration_sleep}"
}

youtube_search () {

	local track="${1}"

	sleep_randomize

	yt-dlp										\
		--cookies-from-browser "${browser}"		\
		--js-runtimes "${runtime_javascript}"	\
		--sleep-requests "${duration_sleep}"	\
		--flat-playlist							\
		--dump-json								\
												"ytsearch${search_count}:${track}" 2>"${sink}"
}

youtube_download () {

	local url="${1}"

	local artist="${2}"

	local title="${3}"

	local filename="${4}"

	audio_quality="0"

	audio_format='bestaudio/best'

	sleep_randomize

	yt-dlp														\
		--ignore-errors											\
		--js-runtimes "${runtime_javascript}"					\
		--cookies-from-browser "${browser}"						\
		--sleep-requests "${duration_sleep}"					\
		--extract-audio											\
		--audio-format "${extension_track}"						\
		--audio-quality "${audio_quality}"						\
		--format "${audio_format}"								\
		--embed-metadata										\
		--no-playlist											\
		--replace-in-metadata title '^.*$' "${title}"			\
		--replace-in-metadata artist '^.*$' "${artist}"			\
		--output "${download_directory}/${filename}.%(ext)s"	\
																"${url}"
}

# requirements /////////////////////////////////////////////////////////////////

list=(
	ffmpeg
	jq
	nodejs
	pip
	xdg-settings
)

frobulator.require "${list[@]}"

unset list

list=(
	yt-dlp
	yt-dlp-ejs
	deno
)

for item in "${list[@]}"
do
	pip install "${item}"
done

list=()


# defaults /////////////////////////////////////////////////////////////////////

if [ -z "${input_user}" ] &&
   [ -z "${input_file}" ]
then
	frobulator.err 'Missing input source'

	usage

	exit 1
fi

if [ -n "${input_file}"   ] &&
   [ ! -f "${input_file}" ]
then
	frobulator.err "Missing input file: ${input_file}"

	exit 1
fi

tracks_input=()

if [ -n "${input_user}" ]
then
	tracks_input+=("${input_user}")
fi

if [ -n "${input_file}" ]
then
	while IFS= read -r track
	do
		tracks_input+=("${track}")

	done < "${input_file}"

	unset IFS
fi

# initialize ///////////////////////////////////////////////////////////////////

frobulator.directory "${download_directory}"

# browser //////////////////////////////////////////////////////////////////////

browser=$(
	browser_identify
)

# existing downloads

tracks_existing_files=()

while IFS= read -r track_existing_file
do
	tracks_existing_files+=( "${track_existing_file}" )

done < <(
	find "${download_directory}"		\
		-type f							\
		-iname "*.${extension_track}"	\
		-printf '%f\n'
)

unset IFS

tracks_existing=()

for track_existing in "${tracks_existing_files[@]}"
do
	track_existing=${track_existing%."${extension_track}"}

	track_existing=$(normalize "${track_existing}")

	tracks_existing+=("${track_existing}")

done

# pending downloads

tracks_pending=()

echo

frobulator.fwd 'Comparing track list against existing downloads'

echo

for track in "${tracks_input[@]}"
do
	# skip empty lines

	if [ -z "${track}" ]
	then
		continue
	fi

	# skip comments

	if [[ ${track} = \#* ]]
	then
		continue
	fi

	# normalize filename for comparisons

	filename_normalized=$(normalize "${track}")

	# preserve original filename for output

	filename=$(echo "${track}" | tr '/:' '--')

	found='false'

	# compare against existing downloads

	for track_existing in "${tracks_existing[@]}"
	do
		if [ "${track_existing}" = "${filename_normalized}" ]
		then
			found='true'

			break
		fi
	done

	# append only missing tracks

	if [ "${found}" = 'false' ]
	then
		frobulator.fwd "Adding ${track}"

		tracks_pending+=("${track}")
	else
		frobulator.scs "Skipping ${track}"
	fi

done

# summary //////////////////////////////////////////////////////////////////////

echo

frobulator.fwd "${#tracks_pending[@]} tracks pending"

# download

search_file=$(mktemp)

for track in "${tracks_pending[@]}"
do
	echo

	frobulator.fwd "Searching ${track}"

	# parse artist

	artist=${track%% - *}

	# parse title

	title=${track#* - }

	# normalize filename for comparisons

	filename_normalized=$(normalize "${track}")

	# preserve original filename for output

	filename=$(echo "${track}" | tr '/:' '--')

	url=''

	# retrieve candidates

	youtube_search "${track}" > "${search_file}" &

	frobulator.process "Searching" "[ ${track} ]"

	results=$(cat "${search_file}")

	# select first reasonable duration

	while IFS= read -r result
	do
		duration_track=$(echo "${result}" | jq -r '.duration')

		# skip invalid duration

		if [ "${duration_track}" = 'null' ]
		then
			continue
		fi

		# accept only valid duration

		if [ "${duration_track}" -ge "${duration_minimum}" ] &&
		   [ "${duration_track}" -le "${duration_maximum}" ]
		then
			url=$(echo "${result}" | jq -r '.webpage_url')

			break
		fi

	done <<< "${results}"

	unset IFS

	# validate

	if [ -z "${url}" ]
	then
		frobulator.err "No valid track duration result" "[ ${track} ]"
		echo

		continue
	fi

	frobulator.scs "${url}"

	# download

	youtube_download	\
		"${url}"		\
		"${artist}"		\
		"${title}"		\
						"${filename}" &

	frobulator.process "Downloading" "[ ${track} ]"

	echo

	frobulator.scs "${download_directory}/${filename}.${extension_track}"
	echo

done

frobulator.delete "${search_file}"

unset IFS

# done //////////////////////////////////////////////////////////////////////////

echo

frobulator.scs "Downloads saved to ${download_directory}"
echo
