#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

script="$(basename -- ${BASH_SOURCE[0]})"

if [[ "${frobulator_loaded}" != "true" ]]
then
	echo

	ticker () {

		for ticker in '>  ' '>> ' '>>>'
		do
			echo -n -e "\r[  ${ticker}  ] ${1^}..."

			sleep 0.5
		done

		echo

		echo

	}

	if [[ $(id -u -n) = "root" ]]
	then
		USER="${SUDO_USER:-root}"

		if [ "${USER}" = "root" ]
		then
			HOME=/root
		else
			HOME="/home/${USER}"
		fi
	fi

	ticker checking

	package_managers_list=(
		"apt-get --quiet --quiet update > /dev/null 2>&1; apt-get --quiet --quiet install --yes"
		"dnf --quiet install --assumeyes"
		"yum --quiet install --assumeyes"
		"apk add --quiet"
		"pacman --sync --refresh --noconfirm --noprogressbar"
		"zypper --quiet --non-interactive install"
	)

	package="curl"

	if [[ -z $(command -v "${package}") ]]
	then
		for package_manager in "${package_managers_list[@]}"
		do
			entry="${package_manager%% *}"

			if [[ -n $(command -v "${entry}") ]]
			then
				eval "${package_manager} ${package} > /dev/null 2>&1"

				break
			fi
		done

		if [[ -z $(command -v "${package}") ]]
		then
			echo "[  !  ] Unable to install or binary not found /////////////////////// [ '${package}' ]"
			echo

			exit 1
		fi
	fi

	mkdir -p "${HOME}"/.local/bin

	frobulator="${HOME}"/.local/bin/frobulator

	version_online=$(curl -s -L get.frbltr.app | grep -m 1 '^# version=' | cut -d '"' -f 2)

	version_local=$(grep -m 1 '^# version=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)

	version_local="${version_local:-1970-01-01}"

	if [ ! -f "${frobulator}" ] || [[ "${version_online}" > "${version_local}" ]]
	then
		curl -s -L get.frbltr.app > "${frobulator}"

		chmod +x "${frobulator}"
	fi

	ticker initializing

	source "${frobulator}"

	export self_arguments="${@}"
fi

# superuser ////////////////////////////////////////////////////////////////////

frobulator.escalate

# script ///////////////////////////////////////////////////////////////////////

frobulator.script

# version //////////////////////////////////////////////////////////////////////

version="2026-07-13"

# usage ////////////////////////////////////////////////////////////////////////

while (($#))
do
	case "${1}"
	in
		-i|--interface)
			interface="${2}"

			shift
		;;

		-b|--bridge)
			bridge_name="${2}"

			shift
		;;

		-h|--help)
			echo
			echo -e "Usage: ${script} -i [Interface] -b [Bridge] | -h"
			echo
			echo -e "Options:"
			echo
			echo -e "-i, --interface     Physical ethernet interface to bridge."
			echo
			echo -e "                    [ enp2s0 ]    [ Default ]"
			echo
			echo -e "-b, --bridge        Name for the created bridge device."
			echo
			echo -e "                    [ bridge0 ]    [ Default ]"
			echo
			echo -e "-h, --help          Show help and usage information."
			echo
			echo -e "'${script}' [ Version // ${version} ]"
			echo

			exit
		;;

		"")
			:
		;;

		*)
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;

	esac

	shift

done

# variables ////////////////////////////////////////////////////////////////////

interface="${interface:-enp2s0}"
bridge_name="${bridge_name:-bridge0}"

stamp=$(date +"%m-%d-%Y-%H-%M-%S")

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

# update ///////////////////////////////////////////////////////////////////////

# frobulator.update

# frobulator.upgrade

# requirements /////////////////////////////////////////////////////////////////

list=(
	aqemu
	guestfs-tools
	libosinfo-bin
	libvirt-daemon-system
	ovmf
	qemu-system-x86
	qemu-utils
	swtpm
	tuned
	tuned-utils
	virt-manager
	virt-viewer
	virtinst
)

frobulator.require ${list[@]}

frobulator.complete

list=()


# configuration ////////////////////////////////////////////////////////////////

frobulator.inf "Enabling libvirt"
echo

frobulator.service enable libvirtd.service

frobulator.complete

frobulator.inf "Validating host"
echo

virt-host-validate qemu

frobulator.complete

frobulator.inf "Enabling tuned"
echo

frobulator.service enable tuned

frobulator.complete

tuned-adm active

frobulator.complete

tuned-adm profile virtual-host

frobulator.complete

# bridge

frobulator.inf "Creating network bridge"
echo

nmcli device status

frobulator.complete

nmcli														\
		connection add type bridge 						\
		con-name ${bridge_name} 									\
		ifname ${bridge_name}

frobulator.complete

nmcli														\
		connection add type ethernet 						\
		slave-type bridge 									\
		con-name 'Bridge Connection' 						\
		ifname ${interface} 										\
		master ${bridge_name}

frobulator.complete

nmcli														\
		connection up ${bridge_name}

frobulator.complete

nmcli														\
		connection modify ${bridge_name} 							\
		connection.autoconnect-slaves 1

frobulator.complete

nmcli														\
		connection up ${bridge_name}

frobulator.complete

nmcli														\
		device status

frobulator.complete

# network

frobulator.inf "Defining libvirt network"
echo

frobulator.temporary directory_temporary

frobulator.complete

frobulator.trap "${directory_temporary}"

frobulator.complete

file_temporary="${directory_temporary}"/bridge.xml

cat > "${file_temporary}" << FILE
<network>
<name>bridge</name>
<forward mode='bridge'/>
<bridge name='${bridge_name}'/>
</network>
FILE

virsh net-define "${file_temporary}"

frobulator.complete

virsh net-start bridge

frobulator.complete

virsh net-autostart bridge

frobulator.complete

# permissions

frobulator.inf "Configuring permissions"
echo

usermod 									\
	--append								\
	--groups libvirt						\
											"${USER}"

frobulator.complete

frobulator.write "append" "export LIBVIRT_DEFAULT_URI='qemu:///system'" "${HOME}" .bashrc

frobulator.complete

setfacl 									\
	--recursive								\
	--remove-all							/var/lib/libvirt/images

frobulator.complete

setfacl										\
	--recursive								\
	--modify u:"${USER}":rwX				/var/lib/libvirt/images

frobulator.complete

setfacl										\
	--modify d:u:"${USER}":rwx				/var/lib/libvirt/images

frobulator.complete

frobulator.result "${script}"

frobulator.scs "KVM host ready"
echo
