#!/bin/bash

set -x

# dependencies /////////////////////////////////////////////////////////////////

if [ -f "${HOME}"/.local/bin/frobulator ]
then
	rm -r -f "${HOME}"/.local/bin/frobulator
fi

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		SUDO_HOME=/root

		USER="${SUDO_USER}"

		HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${HOME}"/.local/bin ]
	then
		mkdir -p "${HOME}"/.local/bin
	fi

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${HOME}"/.local/bin/frobulator

# superuser ////////////////////////////////////////////////////////////////////

export self_arguments="${@}"

frobulator.escalate

# variables ////////////////////////////////////////////////////////////////////

android_media="${HOME}"/.local/share/waydroid/data/media/0

host_media=/media

id="${SUDO_UID}"

seconds="60"

android_directories_list=(
	Drive
	Music
)

host_directories_list=(
	internal
	"/${USER}/Samsung T7/music"
)

waydroid show-full-ui &

waydroid_process=$!

sleep "${seconds}"

sudo chown -R "${id}":"${id}" "$android_media"/

sudo chmod -R 777 "$android_media"/

for i in ${!android_directories_list[@]}
do
	if ! sudo mountpoint -q "$android_media/${android_directories_list[$i]}"
	then
		mkdir -p ${android_media}/${android_directories_list[$i]}

		mount --bind -o uid="${id}",gid="${id}" ${host_media}/${host_directories_list[$i]} ${android_media}/${android_directories_list[$i]}

	fi

done

wait "${waydroid_process}"

for i in ${!android_directories_list[@]}
do
	while sudo umount ${android_media}/${android_directories_list[$i]} 2> "${sink}"
	do
		echo -n "x"
	done
done
