#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [[ $(id -u -n) = "root" ]]
then
	SUDO_HOME=/root

	USER="${SUDO_USER:-root}"

	if [ "${USER}" = "root" ]
	then
		HOME=/root
	else
		HOME="/home/${USER}"
	fi
fi


echo

echo "[  -  ] Checking..."
echo

if [[ -z $(command -v curl) ]]
then
	if [[ -n $(command -v apt-get) ]]
	then
		apt-get -q -q update > /dev/null 2>&1
		apt-get -q -q install -y curl > /dev/null 2>&1

	elif [[ -n $(command -v dnf) ]]
	then
		dnf -q install -y curl > /dev/null 2>&1

	elif [[ -n $(command -v yum) ]]
	then
		yum -q install -y curl > /dev/null 2>&1

	elif [[ -n $(command -v apk) ]]
	then
		apk add --quiet curl > /dev/null 2>&1

	elif [[ -n $(command -v pacman) ]]
	then
		pacman -S -y --noconfirm --noprogressbar curl > /dev/null 2>&1

	elif [[ -n $(command -v zypper) ]]
	then
		zypper --quiet --non-interactive install curl > /dev/null 2>&1
	fi
fi

if [[ -z $(command -v curl) ]]
then
	echo "[  !  ] Unable to install or binary not found ////////////////////// [ 'curl'  ]"
	echo

	exit 1
fi

mkdir -p "${HOME}"/.local/bin

frobulator="${HOME}"/.local/bin/frobulator

version_online=$(	curl -s -L get.frbltr.app | grep -m 1 '^# version=' | cut -d '"' -f 2)

version_local=$(grep -m 1 '^# version=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)

version_local="${version_local:-01-01-1970}"

date_online="${version_online:6:4}${version_online:0:2}${version_online:3:2}"
date_local="${version_local:6:4}${version_local:0:2}${version_local:3:2}"

if [ ! -f "${frobulator}" ] ||
   [[ "${date_online}" > "${date_local}" ]]
then
	curl -s -L get.frbltr.app > "${frobulator}"

	chmod +x "${frobulator}"
fi

echo "[  >  ] Implementing..."
echo

source "${frobulator}"

# superuser ////////////////////////////////////////////////////////////////////

export self_arguments="${@}"

frobulator.escalate

# script ///////////////////////////////////////////////////////////////////////

script="${BASH_SOURCE[0]}"

# version //////////////////////////////////////////////////////////////////////

version="07-13-2026"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"

# variables ////////////////////////////////////////////////////////////////////

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

# update ///////////////////////////////////////////////////////////////////////

# frobulator.update

# frobulator.upgrade

# requirements /////////////////////////////////////////////////////////////////

list=(
	openssh*
)

frobulator.require ${list[@]}

list=()

# configuration ////////////////////////////////////////////////////////////////

frobulator.silence "service ssh restart" &

frobulator.process "Starting service"

# authorized keys file check

frobulator.fwd "Copying keys..."
echo

if [ -f "${PREFIX}"/media/internal/.ssh/authorized_keys ]
then
	:
else
	frobulator.file "${PREFIX}"/media/internal/.ssh authorized_keys
fi

if [ -f "${PREFIX}"/media/internal/.ssh/sshd_config ]
then
	cp "${PREFIX}"/media/internal/.ssh/sshd_config "${PREFIX}"/etc/ssh/sshd_config
fi

if [ -d "${HOME}"/.ssh ]
then
	rm						\
			--recursive		\
			--force 		"${HOME}"/.ssh

	cp 						\
			--recursive		\
			--force			"${PREFIX}"/media/internal/.ssh "${HOME}"/.ssh

else
	cp 						\
			--recursive		\
			--force			"${PREFIX}"/media/internal/.ssh "${HOME}"/.ssh
fi

# set permissions

frobulator.fwd "Setting permissions..."
echo

list=(
	"${HOME}"/.ssh
	"${PREFIX}"/media/internal/.ssh
)

for directory in ${directories_list[@]}
do
	# ownership

	sudo chown "${USER}" "${directory}"
	sudo chown "${USER}" "${directory}"/*
	sudo chown "${USER}" "${directory}"/.keys/
	sudo chown "${USER}" "${directory}"/.keys/*

	# permissions

	sudo chmod 700 "${directory}"
	sudo chmod 755 "${directory}"/known_hosts
	sudo chmod 400 "${directory}"/.keys/*
	sudo chmod 600 "${directory}"/config
	sudo chmod 600 "${directory}"/authorized_keys
done

list=()
