#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

ticker () {

	echo

	for ticker in '>  ' '>> ' '>>>'
	do
		echo -n -e "\r[  ${ticker}  ] ${1^}..."

		sleep 0.5
	done

	echo

	echo

}

if [[ $(id -u -n) = "root" ]]
then
	USER="${SUDO_USER:-root}"

	if [ "${USER}" = "root" ]
	then
		HOME=/root
	else
		HOME="/home/${USER}"
	fi
fi

ticker checking

package_managers_list=(
	"apt-get --quiet --quiet update > /dev/null 2>&1; apt-get --quiet --quiet install --yes"
	"dnf --quiet install --assumeyes"
	"yum --quiet install --assumeyes"
	"apk add --quiet"
	"pacman --sync --refresh --noconfirm --noprogressbar"
	"zypper --quiet --non-interactive install"
)

package="curl"

if [[ -z $(command -v "${package}") ]]
then
	for package_manager in "${package_managers_list[@]}"
	do
		entry="${package_manager%% *}"

		if [[ -n $(command -v "${entry}") ]]
		then
			eval "${package_manager} ${package} > /dev/null 2>&1"

			break
		fi
	done

	if [[ -z $(command -v "${package}") ]]
	then
		echo "[  !  ] Unable to install or binary not found /////////////////////// [ '${package}' ]"
		echo

		exit 1
	fi
fi

mkdir -p "${HOME}"/.local/bin

frobulator="${HOME}"/.local/bin/frobulator

version_online=$(curl -s -L get.frbltr.app | grep -m 1 '^# version=' | cut -d '"' -f 2)
version_local=$(grep -m 1 '^# version=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)

version_local="${version_local:-1970-01-01}"

if [ ! -f "${frobulator}" ] || [[ "${version_online}" > "${version_local}" ]]
then
	curl -s -L get.frbltr.app > "${frobulator}"

	chmod +x "${frobulator}"
fi

ticker initializing

source "${frobulator}"

# script ///////////////////////////////////////////////////////////////////////

script="$(basename -- ${BASH_SOURCE[0]})"

# version //////////////////////////////////////////////////////////////////////

version="2026-05-09"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"

# variables ////////////////////////////////////////////////////////////////////

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

ssh_check () {

	seconds="5"
	timeout="0.125"
	lan="${1}"

	if [ -z "${lan}" ]
	then
		echo "Usage:"
		echo
		echo "${script} <LAN PREFIX>"
		echo
		echo "LAN Prefix	XXX.XXX.XXX"
		echo

		return 1
	fi

	# extract and validate first 3 octets

	lan=$(
		echo "${lan}"									| \
			grep -E -o '^([0-9]{1,3}\.){2}[0-9]{1,3}'	| \
				awk -F'.' '
					$1 <= 255 && $2 <= 255 && $3 <= 255 {
						printf("%d.%d.%d.", $1, $2, $3)
					}'
	)

	if [ -z "${lan}" ]
	then
		frobulator.err "Invalid IP address format."

		return 1
	fi

	# split ip into individual octets

	IFS='.' read -r octet_01 octet_02 octet_03 <<< "${lan%?}"

	for octet_host in {1..255}
	do
		# ip used for networking

		ip_network="${octet_01}.${octet_02}.${octet_03}.${octet_host}"

		# ip used for informational display

		ip_display=$(printf "%03d.%03d.%03d.%03d" "${octet_01}" "${octet_02}" "${octet_03}" "${octet_host}")

		timeout "${timeout}" "${SHELL}" -c "echo > /dev/tcp/${ip_network}/22" 2> "${sink}"

		if [ $? -eq 0 ]
		then
			list_port_open+=("${ip_display}")

			# secure shell

			ssh_output=$(
				ssh								\
					-oBatchMode=yes				\
					-oStrictHostKeyChecking=no	\
					-oConnectTimeout="${seconds}"\
					-oUserKnownHostsFile="${sink}"\
													"${ip_network}" exit 2>&1
			)

			if echo "${ssh_output}" | grep -q -i -e "permission denied" -e "welcome" -e "last login"
			then
				list_ssh_open+=("${ip_display}")
			fi

			# secure file transfer

			sftp_output=$(
				sftp								\
					-oBatchMode=yes					\
					-oStrictHostKeyChecking=no		\
					-oConnectTimeout="${seconds}"	\
					-oUserKnownHostsFile="${sink}"	\
													"${ip_network}" 2>&1
			)

			if echo "${sftp_output}" | grep -q -i -e "sftp>" -e "permission denied"
			then
				list_sftp_open+=("${ip_display}")
			fi

		fi

	done

	# unset IFS

	IFS=''

	frobulator.plo 3

	# port

	if [ ${#list_port_open[@]} -gt 0 ]
	then
		if [ ${#list_port_open[@]} -eq 1 ]
		then
			message="Address"

		elif [ ${#list_port_open[@]} -ge 2 ]
		then
			message="Addresses"
		fi

		frobulator.inf "${message} with open port found at:"
		echo

		for address in "${list_port_open[@]}"
		do
			frobulator.ind "${address}"
			echo
		done

	else
		frobulator.wrn "No open port addresse(s) found"
		echo
	fi

	# shell

	if [ ${#list_ssh_open[@]} -gt 0 ]
	then
		if [ ${#list_ssh_open[@]} -eq 1 ]
		then
			message="Address"

		elif [ ${#list_ssh_open[@]} -ge 2 ]
		then
			message="Addresses"
		fi

		frobulator.inf "${message} with available ssh found at:"
		echo

		for address in "${list_ssh_open[@]}"
		do
			frobulator.ind "${address}"
			echo
		done

	else
		frobulator.wrn "No available ssh addresse(s) found"
		echo
	fi

	# file transfer

	if [ ${#list_sftp_open[@]} -gt 0 ]
	then
		if [ ${#list_sftp_open[@]} -eq 1 ]
		then
			message="Address"

		elif [ ${#list_sftp_open[@]} -ge 2 ]
		then
			message="Addresses"
		fi

		frobulator.inf "${message} with available sftp found at:"
		echo

		for address in "${list_sftp_open[@]}"
		do
			frobulator.ind "${address}"
			echo
		done

	else
		frobulator.wrn "No available sftp addresse(s) found"
		echo
	fi

}

# update ///////////////////////////////////////////////////////////////////////

# frobulator.update

# frobulator.upgrade

# requirements /////////////////////////////////////////////////////////////////

list=(
	ssh*
)

frobulator.require ${list[@]}

list=()

# configuration ////////////////////////////////////////////////////////////////

ssh_check "${@}" &

frobulator.progress scan
