#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

ticker () {

	echo

	for ticker in '>  ' '>> ' '>>>'
	do
		echo -n -e "\r[  ${ticker}  ] ${1^}..."

		sleep 0.5
	done

	echo

	echo

}

if [[ $(id -u -n) = "root" ]]
then
	USER="${SUDO_USER:-root}"

	if [ "${USER}" = "root" ]
	then
		HOME=/root
	else
		HOME="/home/${USER}"
	fi
fi

ticker checking

package_managers_list=(
	"apt-get --quiet --quiet update > /dev/null 2>&1; apt-get --quiet --quiet install --yes"
	"dnf --quiet install --assumeyes"
	"yum --quiet install --assumeyes"
	"apk add --quiet"
	"pacman --sync --refresh --noconfirm --noprogressbar"
	"zypper --quiet --non-interactive install"
)

package="curl"

if [[ -z $(command -v "${package}") ]]
then
	for package_manager in "${package_managers_list[@]}"
	do
		entry="${package_manager%% *}"

		if [[ -n $(command -v "${entry}") ]]
		then
			eval "${package_manager} ${package} > /dev/null 2>&1"

			break
		fi
	done

	if [[ -z $(command -v "${package}") ]]
	then
		echo "[  !  ] Unable to install or binary not found /////////////////////// [ '${package}' ]"
		echo

		exit 1
	fi
fi

mkdir -p "${HOME}"/.local/bin

frobulator="${HOME}"/.local/bin/frobulator

version_online=$(curl -s -L get.frbltr.app | grep -m 1 '^# version=' | cut -d '"' -f 2)
version_local=$(grep -m 1 '^# version=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)

version_local="${version_local:-1970-01-01}"

if [ ! -f "${frobulator}" ] || [[ "${version_online}" > "${version_local}" ]]
then
	curl -s -L get.frbltr.app > "${frobulator}"

	chmod +x "${frobulator}"
fi

ticker initializing

source "${frobulator}"

# script ///////////////////////////////////////////////////////////////////////

script="$(basename -- ${BASH_SOURCE[0]})"

# version //////////////////////////////////////////////////////////////////////

version="2025-04-26"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

# variables ////////////////////////////////////////////////////////////////////

if [ ! -d /media/internal/ ]
then
	configuration_directory="${HOME}"
else
	configuration_directory=/media/internal
fi

configuration=.dns-dynamic

use=$(cat "${configuration_directory}"/"${configuration}" | sed -n 1p)
protocol=$(cat "${configuration_directory}"/"${configuration}" | sed -n 2p)
server=$(cat "${configuration_directory}"/"${configuration}" | sed -n 3p)

login=$(cat "${configuration_directory}"/"${configuration}" | sed -n 4p)
password=$(cat "${configuration_directory}"/"${configuration}" | sed -n 5p)

process="ddclient"
service="${process}.service"

web="www"

# defaults /////////////////////////////////////////////////////////////////////

hostname="${HOSTNAME}"

# functions ////////////////////////////////////////////////////////////////////

# update ///////////////////////////////////////////////////////////////////////

# frobulator.update

# frobulator.upgrade

# requirements /////////////////////////////////////////////////////////////////

list=(
	ddclient
)

frobulator.require ${list[@]}

list=()

# configuration ////////////////////////////////////////////////////////////////

if [ ! -e "${configuration_directory}"/"${configuration}" ]
then
	frobulator.err "Configuration file not found" "[ ${configuration} ]"
	echo

	frobulator.fwd "Aborting"
	echo

	exit 1
fi

# write ddclient configuration

cat <<- FILE > /etc/"${process}".conf
# ddclient #

daemon=300                                  # check every 5 minutes
syslog=yes                                  # log update messages to syslog
mail-failure=root                           # mail failed updates to user
pid=/var/run/ddclient.pid                   # record PID to file
ssl=yes                                     # use ssl
cache=/var/cache/ddclient/ddclient.cache    # set cache file

use=${use}
protocol=${protocol}
server=${server}

login=${login}
password=${password}

${web}
${hostname}
FILE

# reconfigure prccess handlers

sed -i -e 's|\PIDFile|#PIDFile|g' /usr/lib/systemd/system/"${process}".service

# purge service cache file

if [ -d /var/cache/"${process}" ]
then
	rm					\
		--recursive		\
		--force			 /var/cache/"${process}"/"${process}".cache
fi

# service activation

if [[ $(systemctl status "${service}" | grep -e "active.*running") ]]
then
	frobulator.wrn "Service running" " [ ${service} ]"
	echo

	service_actions_list=(
		disable
		stop
	)
fi

service_actions_list+=(
	enable
	start
)

for service_action in ${service_actions_list[@]}
do
	systemctl "${service_action}" "${service}" > "${sink}" 2>&1 &

	frobulator.process "Service ${service_action}" "[ ${service} ]"

	sleep 1

	systemctl daemon-reload > "${sink}" 2>&1 &

	frobulator.process "Reloading"

	sleep 1
done

service_actions_list=()

# service process verification

if [[ $(systemctl status "${service}" | grep -e "active.*running") ]]
then
	frobulator.scs "Service activation success" "[ ${service} ]"
	echo

elif [[ $(systemctl status "${service}" | grep -e "inactive.*") ]]
then
	frobulator.err "Service activation failed" "[ ${service} ]"
	echo

	exit 1
fi

frobulator.scs "Done"
