#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

ticker () {

	echo

	for ticker in '>  ' '>> ' '>>>'
	do
		echo -n -e "\r[  ${ticker}  ] ${1^}..."

		sleep 0.5
	done

	echo

	echo

}

if [[ $(id -u -n) = "root" ]]
then
	USER="${SUDO_USER:-root}"

	if [ "${USER}" = "root" ]
	then
		HOME=/root
	else
		HOME="/home/${USER}"
	fi
fi

ticker checking

package_managers_list=(
	"apt-get --quiet --quiet update > /dev/null 2>&1; apt-get --quiet --quiet install --yes"
	"dnf --quiet install --assumeyes"
	"yum --quiet install --assumeyes"
	"apk add --quiet"
	"pacman --sync --refresh --noconfirm --noprogressbar"
	"zypper --quiet --non-interactive install"
)

package="curl"

if [[ -z $(command -v "${package}") ]]
then
	for package_manager in "${package_managers_list[@]}"
	do
		entry="${package_manager%% *}"

		if [[ -n $(command -v "${entry}") ]]
		then
			eval "${package_manager} ${package} > /dev/null 2>&1"

			break
		fi
	done

	if [[ -z $(command -v "${package}") ]]
	then
		echo "[  !  ] Unable to install or binary not found /////////////////////// [ '${package}' ]"
		echo

		exit 1
	fi
fi

mkdir -p "${HOME}"/.local/bin

frobulator="${HOME}"/.local/bin/frobulator

version_online=$(curl -s -L get.frbltr.app | grep -m 1 '^# version=' | cut -d '"' -f 2)
version_local=$(grep -m 1 '^# version=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)

version_local="${version_local:-1970-01-01}"

if [ ! -f "${frobulator}" ] || [[ "${version_online}" > "${version_local}" ]]
then
	curl -s -L get.frbltr.app > "${frobulator}"

	chmod +x "${frobulator}"
fi

ticker initializing

source "${frobulator}"

# script ///////////////////////////////////////////////////////////////////////

script="$(basename -- ${BASH_SOURCE[0]})"

# version //////////////////////////////////////////////////////////////////////

version="2026-07-13"

# usage ////////////////////////////////////////////////////////////////////////

# variables ////////////////////////////////////////////////////////////////////

stamp=$(date +"%m-%d-%Y-%H-%M-%S")

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

# update ///////////////////////////////////////////////////////////////////////

# frobulator.update

# frobulator.upgrade

# requirements /////////////////////////////////////////////////////////////////

list=(
	conky
	convert
	zenity
)

frobulator.require ${list[@]}

list=()

# configuration ////////////////////////////////////////////////////////////////

cat <<- 'FILE' > /usr/bin/conky-color-selector
#!/bin/bash

# conky color selector #

rgb_to_hex () {

	IFS='(,)'

	read _ r g b <<< "${1}"

	printf '%02x%02x%02x\n' ${r} ${g} ${b}
}

hex_to_rgb () {

	read hex <<< "${1}"

	[[ ${hex:0:1} = "#" ]] && hex=${hex:1:6}

	r=$((16#${hex:0:2}))
	g=$((16#${hex:2:2}))
	b=$((16#${hex:4:2}))

	printf '%03d %03d %03d\n' ${r} ${g} ${b}
}

default_color="cccccc"
color_input="$(zenity --color-selection --color="#cccccc" --show-palette)"
color_selection=$(rgb_to_hex "${color_input}")

if [[ "$color_input" != "" ]]
then
	color="$color_selection"
else
	color="$default_color"
fi

find "${HOME}" -type f -name *conkyrc -exec \
	sed -i \
	-e "s|default_color.*|default_color $color|g" \
	-e "s|default_shade_color.*|default_shade_color $color|g" {} +
FILE

sudo chmod +x /usr/bin/conky-color-selector

# generate launcher

cat <<- 'FILE' > /usr/share/applications/conky-color-selector.desktop
[Desktop Entry]
Name=Conky Color Selector
Comment=Color selector for Conky
Exec=/usr/bin/conky-color-selector
Icon=conky
Terminal=false
Type=Application
StartupNotify=true
Categories=Utility;
FILE
