#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

ticker () {

	echo

	for ticker in '>  ' '>> ' '>>>'
	do
		echo -n -e "\r[  ${ticker}  ] ${1^}..."

		sleep 0.5
	done

	echo

	echo

}

if [[ $(id -u -n) = "root" ]]
then
	USER="${SUDO_USER:-root}"

	if [ "${USER}" = "root" ]
	then
		HOME=/root
	else
		HOME="/home/${USER}"
	fi
fi

ticker checking

package_managers_list=(
	"apt-get --quiet --quiet update > /dev/null 2>&1; apt-get --quiet --quiet install --yes"
	"dnf --quiet install --assumeyes"
	"yum --quiet install --assumeyes"
	"apk add --quiet"
	"pacman --sync --refresh --noconfirm --noprogressbar"
	"zypper --quiet --non-interactive install"
)

package="curl"

if [[ -z $(command -v "${package}") ]]
then
	for package_manager in "${package_managers_list[@]}"
	do
		entry="${package_manager%% *}"

		if [[ -n $(command -v "${entry}") ]]
		then
			eval "${package_manager} ${package} > /dev/null 2>&1"

			break
		fi
	done

	if [[ -z $(command -v "${package}") ]]
	then
		echo "[  !  ] Unable to install or binary not found /////////////////////// [ '${package}' ]"
		echo

		exit 1
	fi
fi

mkdir -p "${HOME}"/.local/bin

frobulator="${HOME}"/.local/bin/frobulator

version_online=$(curl -s -L get.frbltr.app | grep -m 1 '^# version=' | cut -d '"' -f 2)
version_local=$(grep -m 1 '^# version=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)

version_local="${version_local:-1970-01-01}"

if [ ! -f "${frobulator}" ] || [[ "${version_online}" > "${version_local}" ]]
then
	curl -s -L get.frbltr.app > "${frobulator}"

	chmod +x "${frobulator}"
fi

ticker initializing

source "${frobulator}"

# script ///////////////////////////////////////////////////////////////////////

script="$(basename -- ${BASH_SOURCE[0]})"

# version //////////////////////////////////////////////////////////////////////

version="2025-05-03"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"

# variables ////////////////////////////////////////////////////////////////////

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

# update ///////////////////////////////////////////////////////////////////////

frobulator.update

frobulator.upgrade

# requirements /////////////////////////////////////////////////////////////////

list=(

)

frobulator.require ${list[@]}

list=()

# configuration ////////////////////////////////////////////////////////////////

if [ -e /sys/firmware/efi ]
then

	# install

	list=(
		refind
	)

	frobulator.install ${list[@]}

	list=()

	refind-install --yes 1> "${sink}"

	# purge

	apt purge grub* > "${sink}" 2>&1

	list=(
		grub
	)

	frobulator.delete /boot ${list[@]}

	list=()

	# remove

	list=(
		refind.conf
	)

	frobulator.delete /boot/efi/EFI/refind	${list[@]}

	frobulator.download get.trmnl.me refind-configuration /boot/efi/EFI/refind refind.conf

	frobulator.download get.trmnl.me /boot/efi/EFI/refind/themes archive-refind-theme.tar.gz

	frobulator.extract /boot/efi/EFI/refind/themes/archive-refind-theme.tar.gz /boot/efi/EFI/refind/themes

	frobulator.delete /boot/efi/EFI/refind/themes archive-refind-theme.tar.gz

fi
