#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [[ $(id -u -n) = "root" ]]
then
	SUDO_HOME=/root

	USER="${SUDO_USER:-root}"

	if [ "${USER}" = "root" ]
	then
		HOME=/root
	else
		HOME="/home/${USER}"
	fi
fi

echo

echo "[  -  ] Checking..."
echo

if [[ -z $(command -v curl) ]]
then
	if [[ -n $(command -v apt-get) ]]
	then
		apt-get -q -q update > /dev/null 2>&1
		apt-get -q -q install -y curl > /dev/null 2>&1

	elif [[ -n $(command -v dnf) ]]
	then
		dnf -q install -y curl > /dev/null 2>&1

	elif [[ -n $(command -v yum) ]]
	then
		yum -q install -y curl > /dev/null 2>&1

	elif [[ -n $(command -v apk) ]]
	then
		apk add --quiet curl > /dev/null 2>&1

	elif [[ -n $(command -v pacman) ]]
	then
		pacman -S -y --noconfirm --noprogressbar curl > /dev/null 2>&1

	elif [[ -n $(command -v zypper) ]]
	then
		zypper --quiet --non-interactive install curl > /dev/null 2>&1
	fi
fi

if [[ -z $(command -v curl) ]]
then
	echo "[  !  ] Unable to install or binary not found ////////////////////// [ 'curl'  ]"
	echo

	exit 1
fi

mkdir -p "${HOME}"/.local/bin

frobulator="${HOME}"/.local/bin/frobulator

version_online=$(	curl -s -L get.frbltr.app | grep -m 1 '^# version=' | cut -d '"' -f 2)

version_local=$(grep -m 1 '^# version=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)

version_local="${version_local:-01-01-1970}"

date_online="${version_online:6:4}${version_online:0:2}${version_online:3:2}"
date_local="${version_local:6:4}${version_local:0:2}${version_local:3:2}"

if [ ! -f "${frobulator}" ] ||
   [[ "${date_online}" > "${date_local}" ]]
then
	curl -s -L get.frbltr.app > "${frobulator}"

	chmod +x "${frobulator}"
fi

echo "[  >  ] Implementing..."
echo

source "${frobulator}"

# superuser ////////////////////////////////////////////////////////////////////

export self_arguments="${@}"

frobulator.escalate

# script ///////////////////////////////////////////////////////////////////////

script="${BASH_SOURCE[0]}"

# version //////////////////////////////////////////////////////////////////////

version="07-18-2026"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"

# variables ////////////////////////////////////////////////////////////////////

blacklist_directory="/etc/modprobe.d"

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

# update ///////////////////////////////////////////////////////////////////////

# frobulator.update

# frobulator.upgrade

# requirements /////////////////////////////////////////////////////////////////

list=(
	awk
	grep
	lsmod
	update-initramfs
)

frobulator.require ${list[@]}

list=()

# configuration ////////////////////////////////////////////////////////////////

# extract loaded watchdog module

module=$(

	lsmod |
	awk '
		tolower($1) ~ /(wdt$|tco$|^softdog$|watchdog)/ &&
		tolower($1) != "watchdog" {
			print $1
			exit
		}
	'

)

# validate module

if [ -z "${module}" ]
then
	frobulator.err "No watchdog module found." "[ ${module_label} ]"
	echo

	exit 1
fi

module_label="${module,,}"

module_label="${module_label//_/-}"

blacklist_file="${module_label}-blacklist.conf"

blacklist_entry="${blacklist_directory}/${blacklist_file}"

# display the detected module

frobulator.inf "Watchdog module" "[ ${module_label} ]"
echo

# avoid duplicate blacklist entries

if [ -n "$(grep -F -x "blacklist ${module}" "${blacklist_entry}" 2> "${sink}")" ]
then
	frobulator.fwd "Module already blacklisted" "[ ${module_label} ]"
	echo

	exit 0
fi

# blacklist module

echo "blacklist ${module}" > "${blacklist_entry}"

frobulator.inf "Module blacklisted" "[ ${module_label} ]"
echo

# rebuild the initramfs

frobulator.silence "update-initramfs -u" &

frobulator.progress rebuild "[ initramfs ]"

if [ "$?" -ne 0 ]
then
	frobulator.err "Failed to rebuild initramfs."
	echo

	exit 1
fi

frobulator.inf "Watchdog disabled."
echo

frobulator.wrn "Change takes effect after next reboot."
echo

frobulator.scs "Done."
