#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [ -f "${HOME}"/.local/bin/frobulator ]
then
	rm -r -f "${HOME}"/.local/bin/frobulator
fi

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		SUDO_HOME=/root

		USER="${SUDO_USER}"

		HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${HOME}"/.local/bin ]
	then
		mkdir -p "${HOME}"/.local/bin
	fi

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${HOME}"/.local/bin/frobulator

# superuser ////////////////////////////////////////////////////////////////////

export self_arguments="${@}"

frobulator.escalate

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="06-25-2026"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"

# variables ////////////////////////////////////////////////////////////////////

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

android_debug_bridge () {

	sudo adb shell pm -k --user 0

}

applications_list_android=(

)

applications_list_carrier=(
	com.telus.myaccount
	com.telus.checkup
)

applications_list_google=(

)

applications_list_microsoft=(
	com.microsoft.appmanager
	com.microsoft.office.outlook
	com.microsoft.rdc.androidx
	com.microsoft.skydrive
)

applications_list_onyx=(
	com.android.theme.font.notoserifsource

	org.chromium.chrome

	com.onyx.clock
	com.onyx.calculator
	com.onyx.aiassistant
	com.onyx.android.production.test
	com.onyx.appmarket
	com.onyx.mail
	com.onyx.kime
	com.onyx.dict
	com.onyx.musicplayer
	com.onyx.voicerecorder
	# com.onyx
	# com.onyx.android.ksync
	# com.onyx.android.note
	# com.onyx.android.onyxotaservice
	# com.onyx.easytransfer
	# com.onyx.floatingbutton
	# com.onyx.gallery
	# com.onyx.igetshop
	# com.onyx.kreader
	# com.onyx.latinime
	# com.onyx.tscalibration
)

applications_list_samsung=(
	com.samsung.android.kidsinstaller
)

list=(
	${applications_list_carrier[@]}
	${applications_list_microsoft[@]}
	${applications_list_onyx[@]}
	${applications_list_samsung[@]}
)

for application in ${list}
do
	if [ $(android_debug_bridge list packages | grep -q "${application}" ]
	then
		frobulator.inf "Application package not on device" "[ ${application} ]"
		echo

		frobulator.wrn "Removing application package" "[ ${application} ]"
		echo

		android_debug_bridge uninstall "${application}"
	else
		frobulator.error "Application package not present on device" "[ ${application} ]"
		echo
	fi
done

frobulator.scs 'Done'
echo
