#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

ticker () {

	echo

	for ticker in '>  ' '>> ' '>>>'
	do
		echo -n -e "\r[  ${ticker}  ] ${1^}..."

		sleep 0.5
	done

	echo

	echo

}

if [[ $(id -u -n) = "root" ]]
then
	USER="${SUDO_USER:-root}"

	if [ "${USER}" = "root" ]
	then
		HOME=/root
	else
		HOME="/home/${USER}"
	fi
fi

ticker checking

package_managers_list=(
	"apt-get --quiet --quiet update > /dev/null 2>&1; apt-get --quiet --quiet install --yes"
	"dnf --quiet install --assumeyes"
	"yum --quiet install --assumeyes"
	"apk add --quiet"
	"pacman --sync --refresh --noconfirm --noprogressbar"
	"zypper --quiet --non-interactive install"
)

package="curl"

if [[ -z $(command -v "${package}") ]]
then
	for package_manager in "${package_managers_list[@]}"
	do
		entry="${package_manager%% *}"

		if [[ -n $(command -v "${entry}") ]]
		then
			eval "${package_manager} ${package} > /dev/null 2>&1"

			break
		fi
	done

	if [[ -z $(command -v "${package}") ]]
	then
		echo "[  !  ] Unable to install or binary not found /////////////////////// [ '${package}' ]"
		echo

		exit 1
	fi
fi

mkdir -p "${HOME}"/.local/bin

frobulator="${HOME}"/.local/bin/frobulator

version_online=$(curl -s -L get.frbltr.app | grep -m 1 '^# version=' | cut -d '"' -f 2)
version_local=$(grep -m 1 '^# version=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)

version_local="${version_local:-1970-01-01}"

if [ ! -f "${frobulator}" ] || [[ "${version_online}" > "${version_local}" ]]
then
	curl -s -L get.frbltr.app > "${frobulator}"

	chmod +x "${frobulator}"
fi

ticker initializing

source "${frobulator}"

# script ///////////////////////////////////////////////////////////////////////

script="$(basename -- ${BASH_SOURCE[0]})"

# version //////////////////////////////////////////////////////////////////////

version="2026-07-18"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"

# variables ////////////////////////////////////////////////////////////////////

blacklist_directory="/etc/modprobe.d"

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

# update ///////////////////////////////////////////////////////////////////////

# frobulator.update

# frobulator.upgrade

# requirements /////////////////////////////////////////////////////////////////

list=(
	awk
	grep
	lsmod
	update-initramfs
)

frobulator.require ${list[@]}

list=()

# configuration ////////////////////////////////////////////////////////////////

# extract loaded watchdog module

module=$(

	lsmod |
	awk '
		tolower($1) ~ /(wdt$|tco$|^softdog$|watchdog)/ &&
		tolower($1) != "watchdog" {
			print $1
			exit
		}
	'

)

# validate module

if [ -z "${module}" ]
then
	frobulator.err "No watchdog module found." "[ ${module_label} ]"
	echo

	exit 1
fi

module_label="${module,,}"

module_label="${module_label//_/-}"

blacklist_file="${module_label}-blacklist.conf"

blacklist_entry="${blacklist_directory}/${blacklist_file}"

# display the detected module

frobulator.inf "Watchdog module" "[ ${module_label} ]"
echo

# avoid duplicate blacklist entries

if [ -n "$(grep -F -x "blacklist ${module}" "${blacklist_entry}" 2> "${sink}")" ]
then
	frobulator.fwd "Module already blacklisted" "[ ${module_label} ]"
	echo

	exit 0
fi

# blacklist module

echo "blacklist ${module}" > "${blacklist_entry}"

frobulator.inf "Module blacklisted" "[ ${module_label} ]"
echo

# rebuild the initramfs

frobulator.silence "update-initramfs -u" &

frobulator.progress rebuild "[ initramfs ]"

if [ "$?" -ne 0 ]
then
	frobulator.err "Failed to rebuild initramfs."
	echo

	exit 1
fi

frobulator.inf "Watchdog disabled."
echo

frobulator.wrn "Change takes effect after next reboot."
echo

frobulator.scs "Done."
