#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [ -f "${HOME}"/.local/bin/frobulator ]
then
	rm -r -f "${HOME}"/.local/bin/frobulator
fi

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		SUDO_HOME=/root

		USER="${SUDO_USER}"

		HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${HOME}"/.local/bin ]
	then
		mkdir -p "${HOME}"/.local/bin
	fi

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${HOME}"/.local/bin/frobulator

# superuser ////////////////////////////////////////////////////////////////////

frobulator.escalate

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="11-30-2023"

# usage ////////////////////////////////////////////////////////////////////////

# variables ////////////////////////////////////////////////////////////////////

stamp=$(date +"%m-%d-%Y-%H-%M-%S")

# defaults /////////////////////////////////////////////////////////////////////

list=(

list=(
	aqemu
	guestfs-tools
	libosinfo-bin
	libvirt-daemon-system
	ovmf
	qemu-system-x86
	qemu-utils
	swtpm
	tuned
	tuned-utils
	virt-manager
	virt-viewer
	virtinst
	)

frobulator.install ${list[@]}

list=()

sudo systemctl enable libvirtd.service

sudo nmcli connection add type bridge con-name bridge0 ifname bridge0

sudo nmcli															\
		connection add type ethernet slave-type bridge 				\
		con-name 'Bridge Connection' ifname enp2s0 master bridge0

sudo nmcli 	\
		connection up bridge0

sudo nmcli 	\
		connection modify bridge0 connection.autoconnect-slaves 1

sudo nmcli 	\
		connection up bridge0

# sudo nmcli device status

sudo virsh net-define << NETWORK
<network>
<name>nwbridge</name>
<forward mode='bridge'/>
<bridge name='bridge0'/>
</network>
NETWORK

sudo virsh net-start nwbridge

sudo virsh net-autostart nwbridge

sudo usermod -aG libvirt $USER

echo "export LIBVIRT_DEFAULT_URI='qemu:///system'" >> ~/.bashrc

sudo setfacl -R -b /var/lib/libvirt/images
sudo setfacl -R -m u:$USER:rwX /var/lib/libvirt/images
sudo setfacl -m d:u:$USER:rwx /var/lib/libvirt/images
