#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

script="$(basename -- ${BASH_SOURCE[0]})"

if [[ "${frobulator_loaded}" != "true" ]]
then
	echo

	ticker () {

		for ticker in '>  ' '>> ' '>>>'
		do
			echo -n -e "\r[  ${ticker}  ] ${1^}..."

			sleep 0.5
		done

		echo

		echo

	}

	if [[ $(id -u -n) = "root" ]]
	then
		USER="${SUDO_USER:-root}"

		if [ "${USER}" = "root" ]
		then
			HOME=/root
		else
			HOME="/home/${USER}"
		fi
	fi

	ticker checking

	package_managers_list=(
		"apt-get --quiet --quiet update > /dev/null 2>&1; apt-get --quiet --quiet install --yes"
		"dnf --quiet install --assumeyes"
		"yum --quiet install --assumeyes"
		"apk add --quiet"
		"pacman --sync --refresh --noconfirm --noprogressbar"
		"zypper --quiet --non-interactive install"
	)

	package="curl"

	if [[ -z $(command -v "${package}") ]]
	then
		for package_manager in "${package_managers_list[@]}"
		do
			entry="${package_manager%% *}"

			if [[ -n $(command -v "${entry}") ]]
			then
				eval "${package_manager} ${package} > /dev/null 2>&1"

				break
			fi
		done

		if [[ -z $(command -v "${package}") ]]
		then
			echo "[  !  ] Unable to install or binary not found /////////////////////// [ '${package}' ]"
			echo

			exit 1
		fi
	fi

	mkdir -p "${HOME}"/.local/bin

	frobulator="${HOME}"/.local/bin/frobulator

	version_online=$(curl -s -L get.frbltr.app | grep -m 1 '^# version=' | cut -d '"' -f 2)

	version_local=$(grep -m 1 '^# version=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)

	version_local="${version_local:-1970-01-01}"

	if [ ! -f "${frobulator}" ] || [[ "${version_online}" > "${version_local}" ]]
	then
		curl -s -L get.frbltr.app > "${frobulator}"

		chmod +x "${frobulator}"
	fi

	ticker initializing

	source "${frobulator}"

	export self_arguments="${@}"
fi

# superuser ////////////////////////////////////////////////////////////////////

frobulator.escalate

# script ///////////////////////////////////////////////////////////////////////

frobulator.script

# version //////////////////////////////////////////////////////////////////////

version="2026-07-13"

# usage ////////////////////////////////////////////////////////////////////////

while (($#))
do
	case "${1}"
	in
		-p|--platform)
			platform="${2}"

			shift
		;;

		-h|--help)
			echo
			echo -e "Usage: ${script} -p [Platform] | -h"
			echo
			echo -e "Options:"
			echo
			echo -e "-p, --platform      Target platform to pull and repackage images for."
			echo
			echo -e "                    [ linux/amd64 ]"
			echo -e "                    [ linux/aarch64 ]    [ Default ]"
			echo
			echo -e "-h, --help          Show help and usage information."
			echo
			echo -e "'${script}' [ Version // ${version} ]"
			echo

			exit
		;;

		"")
			:
		;;

		*)
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;

	esac

	shift

done

# variables ////////////////////////////////////////////////////////////////////

platform="${platform:-linux/aarch64}"

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

# update ///////////////////////////////////////////////////////////////////////

# frobulator.update

# frobulator.upgrade

# requirements /////////////////////////////////////////////////////////////////

list=(
	docker
	docker-clean
	docker-compose
	docker-registry
	docker.io
	7zip
	bunzip2
	gunzip
	tar
	unrar
	unzip
)

frobulator.require ${list[@]}

frobulator.complete

list=()

# configuration ////////////////////////////////////////////////////////////////

directory_origin="${PWD}"

frobulator.temporary directory_temporary

if [ -d "${directory_temporary}" ]
then
	cd "${directory_temporary}"

	frobulator.complete
else
	frobulator.err "Directory not found" "[ ${directory_temporary} ]"
	echo

	exit 1
fi

declare -A distributions_list=(
	[ubuntu]="18.04 20.04 22.04 24.04"
	[debian]="10 11 12 13"
	[fedora]="38 39 40 41"
)

for distribution in "${!distributions_list[@]}"
do
	for distribution_version in ${distributions_list[${distribution}]}
	do
		docker pull --quiet --platform="${platform}" "${distribution}:${distribution_version}"

		frobulator.complete

		docker image save "${distribution}:${distribution_version}" | xz > "${distribution}-${distribution_version}-container.tar.xz"

		frobulator.complete

		for archive_input in *container.tar.xz
		do
			archive_output="${archive_input/-container.tar.xz/.tar.xz}"

			frobulator.temporary directory_extraction

			frobulator.complete

			frobulator.fwd "Extracting .."

			tar										\
				--extract							\
					--file="${archive_input}"   	\
					--xz                        	\
					--directory="${directory_extraction}"

			frobulator.complete

			archive_layer=$(find "${directory_extraction}" -name "layer.tar")

			if [ -f "${archive_layer}" ]
			then
				xz -c "${archive_layer}" > "${archive_output}"

				mv "${archive_output}" "${directory_origin}"/"${archive_output}"

				frobulator.scs "Repackaged" "[ ${archive_output} ]"
				echo
			else
				frobulator.err "'layer.tar' not found in extracted content" "[ ${archive_input} ]"
				echo
			fi

			rm -r -f "${directory_extraction}"

			rm -r -f "${archive_input}"
		done
	done
done

if [ -d "${directory_origin}" ]
then
	cd "${directory_origin}"

	frobulator.complete
else
	frobulator.err "Directory not found" "[ ${directory_origin} ]"
	echo

	exit 1
fi

rm -r -f "${directory_temporary}"

frobulator.complete

frobulator.result "${script}"

frobulator.scs "Repackaging complete" "[ ${platform} ]"
echo
