#!/bin/bash

# dependencies #

curl -s -L get.frbltr.app > "${PREFIX}"/bin/frobulator

# variables #

configuration_directory="${HOME}"/.config

# configuration #

cat <<- 'FILE' > /usr/bin/conky-color-selector
#!/bin/bash

rgb_to_hex () {
	IFS='(,)'
	read _ r g b <<< "$1"
	printf '%02x%02x%02x\n' $r $g $b
}

default_color="cccccc"
color_input="$(zenity --color-selection --color="#cccccc" --show-palette)"
color_selection=$(rgb_to_hex "$color_input")

[[ $(id -u -n) = "root" ]] && home=/home/"${SUDO_USER:-$USER}" || home=/home/"${USER}"

cd "$home" || exit

if [[ "$color_input" != "" ]]
then
	color="$color_selection"
else
	color="$default_color"
fi

find . -type f -name *conkyrc -exec \
	sed -i \
	-e "s|default_color.*|default_color $color|g" \
	-e "s|default_shade_color.*|default_shade_color $color|g" {} +
FILE

sudo chmod +x /usr/bin/conky-color-selector

# generate launcher

cat <<- 'FILE' > /usr/share/applications/conky-color-selector.desktop
[Desktop Entry]
Name=Conky Color Selector
Comment=Color selector for Conky
Exec=/usr/bin/conky-color-selector
Icon=conky
Terminal=false
Type=Application
StartupNotify=true
Categories=Utility;
FILE
