#!/bin/bash

# dependencies ─────────────────────────────────────────────────────────────────

script="$(basename -- "${BASH_SOURCE[0]}")"

# script arguments for escalation

self_arguments=("${@}")

if [ "${frobulator_loaded}" != "true" ]
then
	echo
	echo "[  >  ] Checking..."
	echo

	# root through sudo keeps using the user's frobulator

	if [ -n "${SUDO_USER}" ]
	then
		USER="${SUDO_USER}"
		HOME="$(getent passwd "${SUDO_USER}" | cut -d ':' -f 6)"
	fi

	frobulator="${HOME}/.local/bin/frobulator"
	frobulator_download="$(mktemp)"

	mkdir -p "${HOME}/.local/bin"

	# latest release - curl or wget - local copy replaced only by a newer one

	curl -s -L -o "${frobulator_download}" get.frbltr.app 2> /dev/null ||
	wget -q -O "${frobulator_download}" get.frbltr.app 2> /dev/null

	version_online="$(grep -m 1 '^update=' "${frobulator_download}")"
	version_local="$(grep -m 1 '^update=' "${frobulator}" 2> /dev/null)"

	if [[ "${version_online}" > "${version_local}" ]]
	then
		mv -f "${frobulator_download}" "${frobulator}"

		chmod +x "${frobulator}"
	fi

	rm -f "${frobulator_download}"

	if [ ! -f "${frobulator}" ]
	then
		echo "[  !  ] Unable to fetch frobulator ── [ get.frbltr.app ]"
		echo

		exit 1
	fi

	source "${frobulator}"
fi

# superuser ────────────────────────────────────────────────────────────────────

frobulator.escalate

# script ───────────────────────────────────────────────────────────────────────

frobulator.script

# version ──────────────────────────────────────────────────────────────────────

version="2026-10-04"

# usage ────────────────────────────────────────────────────────────────────────

while (( $# ))
do
	case "${1}"
	in
		-h|--help)
			echo
			echo -e "Usage: ./${script} -h"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help    Show [h]elp and usage information."
			echo
			echo -e "'${script}'   [ Version // ${version} ]"
			echo

			exit
		;;

		"")
			# handle empty argument:
			# use default values specified in script

			:
		;;

		*)
			echo
			echo -e "Usage: ./${script} -h"
			echo
			echo -e "Unknown option: '${script} ${1}':"
			echo -e "Type './${script} -h' for help and usage information."
			echo

			exit 1

		;;

		esac

	shift

done

# variables ────────────────────────────────────────────────────────────────────

stamp=$(date +"%m-%d-%Y-%H-%M-%S")

# defaults ─────────────────────────────────────────────────────────────────────

# functions ────────────────────────────────────────────────────────────────────

# update ───────────────────────────────────────────────────────────────────────

# frobulator.update

# frobulator.upgrade

# requirements ─────────────────────────────────────────────────────────────────

list=(
	conky
)

frobulator.require ${list[@]}

list=()

# configuration ────────────────────────────────────────────────────────────────

alignment="top_right"
size_font="8"

gap_x="10"
gap_y="10"
offset="10"
size_x="0"
size_y="0"
width="210"

if [ ! -d "${HOME}"/.config/conky ]
then
	mkdir -p "${HOME}"/.config/conky
fi

cat << HEADER > "${HOME}"/.config/conky/conkyrc
# conky #

alignment $alignment
background yes
border_inner_margin 0
border_outer_margin 0
cpu_avg_samples 2
default_color F9F9F9
default_shade_color CCCCCC
double_buffer yes
draw_borders no
draw_graph_borders yes
draw_outline no
draw_shades no
gap_x $gap_x
gap_y $gap_y
if_up_strictness address
maximum_width $size_x
minimum_size $size_x $size_y
net_avg_samples 2
no_buffers no
override_utf8_locale yes
own_window yes
own_window_argb_value 255
own_window_argb_visual yes
own_window_hints below,skip_pager,skip_taskbar,sticky,undecorated
own_window_transparent yes
own_window_type desktop
short_units yes
temperature_unit celsius
text_buffer_size 2048
total_run_times 0
update_interval 2
uppercase no
use_xft yes
xftalpha 1.0
xftfont Sans:size=$size_font:normal

TEXT

HEADER

cat << 'MAIN' > /usr/bin/write-conky
#!/bin/bash

# write conky #

# user running the script

name_user="$(id -u -n)"

if [ "${name_user}" = "root" ]
then
	directory_home=/home/"${SUDO_USER:-$USER}"
else
	directory_home=/home/"${USER}"
fi

text_unavailable="[ × ]"

sed -i -e '/^TEXT$/q' "${HOME}"/.config/conky/conkyrc
sed -i -e '$G' "${HOME}"/.config/conky/conkyrc

name_kernel=$(uname -s)
name_machine=$(uname -m)
name_host=$(uname -n)
name_processor=$(uname -p)

name_os=$(cat /etc/os-release | awk -F '=' '{if (NR==1) print $2}')
version_os=$(cat /etc/os-release | awk -F '=' '{if (NR==4) print $2}')

cat <<- FILE >> "${HOME}"/.config/conky/conkyrc
SYSTEM\${alignr}[ $name_kernel ][ $name_host ]
OS\${alignr}[ $name_os $version_os ][ $name_machine ]
\${voffset -2}\${hr 1}
UPTIME\${alignr}[ D ][ H ][ M ][ S ]
\${voffset -2}\${hr 1}
TIME\${alignr}\${uptime}
\${voffset -2}\${hr 1}
FILE

for path_supply in /sys/class/power_supply/BAT[0-9]*
do
	cat <<- FILE >> "${HOME}"/.config/conky/conkyrc
	\${if_existing $path_supply/present 1}\\
	BATTERY\${alignr}[ TECH ][ STATUS ][ % ]
	\${voffset -2}\${hr 1}
	[ \${exec cat $path_supply/technology} ][ \${exec cat $path_supply/status} ]\${alignr}\${battery_percent}
	\${battery_bar 2}\\
	\${else}\\
	\${voffset -2}\${hr 1}\${endif}
	FILE
done

cat <<- FILE >> "${HOME}"/.config/conky/conkyrc
CPU\${alignr}[ CORE ][ FREQ ][ MODE ][ % ]
\${voffset -2}\${hr 1}
FILE

count_cpu=$(grep -c processor /proc/cpuinfo)

for (( index_core = 0 ; index_core < count_cpu ; index_core ++ ))
do
	number_core=$(( index_core + 1 ))

	cat <<- FILE >> "${HOME}"/.config/conky/conkyrc
	CORE $index_core \${freq_g $number_core} \\
	\${if_existing /sys/devices/system/cpu/cpu$index_core/cpufreq/scaling_governor powersave}◼◼◻◻◻◻◻◻◻◻\${endif}\\
	\${if_existing /sys/devices/system/cpu/cpu$index_core/cpufreq/scaling_governor conservative}◼◼◼◼◻◻◻◻◻◻\${endif}\\
	\${if_existing /sys/devices/system/cpu/cpu$index_core/cpufreq/scaling_governor ondemand}◼◼◼◼◼◼◻◻◻◻\${endif}\\
	\${if_existing /sys/devices/system/cpu/cpu$index_core/cpufreq/scaling_governor performance}◼◼◼◼◼◼◼◼◻◻\${endif}\\
	\${if_existing /sys/devices/system/cpu/cpu$index_core/cpufreq/scaling_governor userspace}◻◻◻◻◻◻◻◻◼◼\${endif}\\
	\${if_existing /sys/devices/system/cpu/cpu$index_core/cpufreq/scaling_governor ""}$text_unavailable\${endif}\\
	\${alignr} \${cpu cpu$number_core}
	\${cpubar cpu$number_core 2}
	\${cpugraph cpu$number_core 10}
	FILE
done

command_memory_available="free -h | awk 'NR==2{print \$7}'"
command_memory_cache="free -h | awk 'NR==2{print \$6}'"
command_memory_shared="free -h | awk 'NR==2{print \$5}'"
command_memory_free="free -h | awk 'NR==2{print \$4}'"
command_memory_used="free -h | awk 'NR==2{print \$3}'"
command_memory_total="free -h | awk 'NR==2{print \$2}'"

cat <<- FILE >> "${HOME}"/.config/conky/conkyrc
MEMORY\${alignr}[ % ]
\${voffset -2}\${hr 1}
CAPACITY\${alignr}\${memperc}
\${membar 2}
USAGE\${alignr}[ M ][ G ]
\${voffset -2}\${hr 1}
[ Used ][ Free ]\${goto 125}\${exec $command_memory_used}\${alignr}\${exec $command_memory_free}
[ Shared ][ Cache ]\${goto 125}\${exec $command_memory_shared}\${alignr}\${exec $command_memory_cache}
[ Available ][ Total ]\${goto 125}\${exec $command_memory_available}\${alignr}\${exec $command_memory_total}
\${voffset -2}\${hr 1}
PROCESS\${alignr}[ CPU ][RAM ][ % ]
\${voffset -2}\${hr 1}
FILE

for (( index_process = 1 ; index_process <= 4 ; index_process ++ ))
do
	cat <<- FILE >> "${HOME}"/.config/conky/conkyrc
	\${top name $index_process}\${goto 120}\${top cpu $index_process}\${alignr}\${top mem $index_process}
	FILE
done

if list_files_sensor=(/sys/class/hwmon/hwmon[0-9]*/temp*) && [[ -e "$list_files_sensor" ]]
then
	cat <<- FILE >> "${HOME}"/.config/conky/conkyrc
	\${voffset -2}\${hr 1}
	TEMPERATURE\${alignr}[ T° ][ MAX ][ °C ]
	\${voffset -2}\${hr 1}
	FILE

	for path_input in /sys/class/hwmon/hwmon[0-9]*/*_input
	do
		IFS='/' read -r _ _ _ _ name_hwmon name_probe <<< "$path_input"

		if [[ "$path_input" = *fan* ]]
		then
			continue
		fi

		path_hwmon="${path_input%/*}"
		path_probe="$path_input"
		name_probe="${path_input##*/}"

		if [[ -e ${path_input%_input}_label ]]
		then
			path_label="${path_input%_input}_label"
		else
			path_label="$path_hwmon"/name
		fi

		if [[ -e ${path_input%_input}_max ]]
		then
			path_max="${path_input%_input}_max"
		elif [[ -e ${path_input%_input}_crit ]]
		then
			path_max="${path_input%_input}_crit"
		else
			path_max="$text_unavailable"
		fi

		name_label="${path_label##*/}"
		name_max="${path_max##*/}"

		name_hwmon_display=$(echo "$name_hwmon" | sed 's/.$/ &/')
		name_probe_display=$(echo "$name_probe" | sed 's/_.*//' | sed 's/.$/ &/')

		cat <<- FILE >> "${HOME}"/.config/conky/conkyrc
		\${if_existing ${path_hwmon}}\\
		\${if_existing $path_probe}\${exec cat $path_label | sed 's/[^_-]*/\U&/g;s/_/ /g'}\${else}\${endif}\${goto 140}\${$name_hwmon_display $name_probe_display}\${alignr}\${if_existing $path_max}\${exec cat $path_max | sed 's/...$//'}\${else}$text_unavailable\${endif}\${endif}
		FILE
	done
fi

if list_files_sensor=(/sys/class/hwmon/hwmon[0-9]*/fan*) && [[ -e "$list_files_sensor" ]]
then
	cat <<- FILE >> "${HOME}"/.config/conky/conkyrc
	\${voffset -2}\${hr 1}
	FAN\${alignr}[ RPM ]
	\${voffset -2}\${hr 1}
	FILE

	for path_input in /sys/class/hwmon/hwmon[0-9]*/*_input
	do
		IFS='/' read -r _ _ _ _ name_hwmon name_probe <<< "$path_input"

		if [[ "$path_input" = *temp* ]]
		then
			continue
		fi

		path_hwmon="${path_input%/*}"
		path_probe="$path_input"
		name_probe="${path_input##*/}"

		if [[ -e ${path_input%_input}_label ]]
		then
			path_label="${path_input%_input}_label"
		else
			path_label="$path_hwmon"/name
		fi

		name_label="${path_label##*/}"

		name_hwmon_display=$(echo "$name_hwmon" | sed 's/.$/ &/')
		name_probe_display=$(echo "$name_probe" | sed 's/_.*//' | sed 's/.$/ &/')

		cat <<- FILE >> "${HOME}"/.config/conky/conkyrc
		\${if_existing ${path_hwmon}}\\
		\${if_existing $path_probe}\${exec cat $path_label | sed 's/[^_-]*/\U&/g;s/_/ /g'}\${else}\${endif}\${alignr}\${$name_hwmon_display $name_probe_display}\${alignr}\${else}$text_unavailable\${endif}
		FILE
	done
fi

cat <<- FILE >> "${HOME}"/.config/conky/conkyrc
\${voffset -2}\${hr 1}
DRIVES\${alignr}[ USED ][ TOTAL ][ G ]
\${voffset -2}\${hr 1}
FILE

for path_device in /dev/sd[a-z][1-9]*
do
	name_block=$(df -H "$path_device" | awk 'END{print $1}')
	command_free="df -H "$path_device" | awk 'END{print \$4}'"
	label_device=$(blkid -s LABEL -o value "$path_device")
	path_mount=$(df -H "$path_device" | awk 'END{print $6}')
	command_percent="df -H "$path_device" | awk 'END{print \$5}'"
	command_size="df -H "$path_device" | awk 'END{print \$2}'"
	type_filesystem=$(blkid -s TYPE -o value "$path_device")
	command_used="df -H "$path_device" | awk 'END{print \$3}'"

	if [[ "$name_block" = "devtmpfs" ]] || [[ "$name_block" = "udev" ]] || [[ "$type_filesystem" = "vfat" ]]
	then
		: # pass
	else
		cat <<- FILE >> "${HOME}"/.config/conky/conkyrc
		\${if_mounted $path_mount}\\
		[ $name_block ] $label_device\${goto 135}\${exec $command_used}\${alignr}\${exec $command_size}
		\${fs_bar 2 $path_mount}\${endif}
		FILE
	fi
done

interface_wireless=$(netstat -in | awk '/^w[l][ap][0-9]/{print $1}') # Main
interface_ethernet=$(netstat -in | awk '/^e/{print $1}') # Secondary
interface_virtual=$(netstat -in | awk '/^v[i][r][b][r][0-9]/{print $1}') # Fallback
interface_loopback=$(netstat -in | awk '/^lo/{print $1}') # Local

url_address_external="https://api.ipify.org"

if [[ ! -z "$interface_virtual" ]]
then
	interface_virtual="$interface_virtual"
else
	interface_virtual="$interface_loopback"
fi

if [[ ! -z "$interface_wireless" ]]
then
	interface_wireless="$interface_wireless"
else
	interface_wireless="$interface_virtual"
fi

if [[ ! -z "$interface_ethernet" ]]
then
	interface_ethernet="$interface_ethernet"
else
	interface_ethernet="$interface_virtual"
fi

cat <<- FILE >> "${HOME}"/.config/conky/conkyrc
NETWORK\${alignr}[ IP ][ IFACE ]\\
\${if_up $interface_wireless}\\
\${alignr}[ $interface_wireless ]\${endif}\\
\${if_up $interface_ethernet}\\
\${alignr}[ $interface_ethernet ]\${endif}
\${voffset -2}\${hr 1}
\${if_up $interface_wireless}\\
Gateway    \${alignr}\${gw_ip} [ $interface_wireless ]\${endif}\\
\${if_up $interface_ethernet}\\
Gateway    \${alignr}\${gw_ip} [ $interface_ethernet ]\${endif}
\${if_up $interface_wireless}\\
External    \${alignr}\${exec curl $url_address_external} [ $interface_wireless ]\${endif}\${if_up $interface_ethernet}
External    \${alignr}\${exec curl $url_address_external} [ $interface_ethernet ]\${endif}
\${if_up $interface_wireless}\\
Local    \${alignr}\${addr $interface_wireless} [ $interface_wireless ]\${endif}\${if_up $interface_ethernet}
Local    \${alignr}\${addr $interface_ethernet} [ $interface_ethernet ]\${endif}
\${if_up $interface_wireless}\\
\${voffset -2}\${hr 1}
LINK\${alignr}[ % ]
\${voffset -2}\${hr 1}
Signal\${alignr}\${wireless_link_qual_perc $interface_wireless}
\${wireless_link_bar 2 $interface_wireless}\\
\${else}\\
\${voffset -2}\${hr 1}\${endif}
THROUGHPUT\${alignr}[ M ][ G ][ kbps ]
\${voffset -2}\${hr 1}
\${if_up $interface_wireless}\\
[ ▼ ] \${totaldown $interface_wireless}\${alignr}\${downspeedf $interface_wireless}
\${voffset 4}\${downspeedgraph $interface_wireless 10}
[ ▲ ] \${totalup $interface_wireless}\${alignr}\${upspeedf $interface_wireless}
\${voffset 4}\${upspeedgraph $interface_wireless 10}\${endif}
\${if_up $interface_ethernet}\\
[ ▼ ] \${totaldown $interface_ethernet}\${alignr}\${downspeedf $interface_ethernet}
\${voffset 4}\${downspeedgraph $interface_ethernet 10}
[ ▲ ] \${totalup $interface_ethernet}\${alignr}\${upspeedf $interface_ethernet}
\${voffset 4}\${upspeedgraph $interface_ethernet 10}\${endif}
FILE
MAIN

sudo chmod +x /usr/bin/write-conky

sudo chmod -R 777 "${HOME}"/.config/conky

write-conky

# generate launcher

cat <<- 'FILE' > /usr/share/applications/conky.desktop
[Desktop Entry]
Name=Conky
Comment=Highly configurable system monitor
Exec=sh -c "write-conky && conky -c /home/${SUDO_USER:-$USER}/.config/conky/conkyrc"
Icon=conky
Terminal=false
Type=Application
StartupNotify=true
Categories=Utility;
FILE
