#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [ -f "${HOME}"/.local/bin/frobulator ]
then
	. "${HOME}"/.local/bin/frobulator

	frobulator.fwd 'Updating...'
	echo

	rm -r -f "${HOME}"/.local/bin/frobulator
else
	echo -n -e '[  ▷  ] Updating...'
	echo
fi

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = 'root' ]]
	then
		SUDO_HOME=/root

		USER="${SUDO_USER}"

		HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${HOME}"/.local/bin ]
	then
		mkdir -p "${HOME}"/.local/bin
	fi

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${HOME}"/.local/bin/frobulator

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version='07-03-2026'

# variables ////////////////////////////////////////////////////////////////////

execute=false

temporary="$(mktemp -d)"

list_device="${temporary}/device.list"
list_local="${temporary}/local.list"
list_delete="${temporary}/delete.list"

# usage ////////////////////////////////////////////////////////////////////////

while (($#))
do
	case "${1}"
	in
		-d|--device)
			device="${2}"

			shift
		;;

		-l|--local)
			local="${2}"

			shift
		;;

		-e|--execute)
			execute=true
		;;

		-h|--help)
			echo
			echo "Usage:"
			echo
			echo "Dry run:"
			echo
			echo "${script} -d /path/to/device/files -l /path/to/local/files"
			echo
			echo "Execute:"
			echo
			echo "${script} -d /path/to/device/files -l /path/to/local/files -e"
			echo
			echo "Options:"
			echo
			echo "-d, --device     Set device directoryreference."
			echo "-l, --local      Set local directory reference."
			echo "-e, --execute    Delete files from local directory."
			echo "-h, --help       Show help and usage information."
			echo

			exit
		;;

		"")
			:
		;;

		*)
			echo
			echo "Usage: ${script} -d [Device Directory] -l [Local Directory] | -e"
			echo
			echo "${script}: Unknown option '${1}'"
			echo "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;

	esac

	shift

done

# defaults /////////////////////////////////////////////////////////////////////

# validate arguments

if [ -z "${device}" ]
then
	frobulator.err "Missing device directory."
	echo

	exit 1

elif [ -z "${local}" ]
then
	frobulator.err "Missing local directory."
	echo

	exit 1
fi

# validate directories

if [ ! -d "${device}" ]
then
	frobulator.err "Device directory does not exist" "[ ${device} ]"
	echo

	exit 1

elif [ ! -d "${local}" ]
then
	frobulator.err "Local directory does not exist" "[ ${local} ]"
	echo

	exit 1
fi

# functions ////////////////////////////////////////////////////////////////////

index () {

	source="${1}"
	destination="${2}"

	cd "${source}" || exit 1

	find . -type f | sed 's|^\./||' | sort > "${destination}"

}

# index libraries

index "${device}" "${list_device}" &

frobulator.progress index "[ device ]"

index "${local}" "${list_local}" &

frobulator.progress index "[ local ]"

# determine files missing from the device

comm -1 -3 "${list_device}" "${list_local}" > "${list_delete}"

# display results

if [ -s "${list_delete}" ]
then
	count_delete=$(echo $(wc -l < "${list_delete}"))

	frobulator.wrn "Files to be removed from device" "[ ${count_delete} ]"
	echo

	cat "${list_delete}"

	echo

	# execute changes

	if [ "${execute}" = true ] && [ ${count_delete} -gt 0 ]
	then
		frobulator.fwd "Pruning..."
		echo

		while IFS= read -r file
		do
			rm -v -- "${local}/${file}"

		done < "${list_delete}"

		echo

		# remove empty directories

		find "${local}" -type d -empty -delete

		frobulator.inf "Local library pruned."
		echo
	else
		frobulator.wrn "Dry run only:"
		frobulator.nul "Run ${script} again with 'execute' argument to delete reported files from the local directory."
		echo
	fi

else

	frobulator.inf "No files to be removed."
	echo
fi

# cleanup

frobulator.delete "${temporary}"
