#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [[ $(id -u -n) = "root" ]]
then
	SUDO_HOME=/root

	USER="${SUDO_USER}"

	HOME=/home/"${USER}"
fi

if [[ -z $(command -v curl) ]]
then
	yes | apt-get install curl
fi

if [ ! -d "${HOME}"/.local/bin ]
then
	mkdir -p "${HOME}"/.local/bin
fi

frobulator="${HOME}"/.local/bin/frobulator

version_online=$(curl -s -L get.frbltr.app | grep 'version=' | cut -d '"' -f 2)

version_local=$(cat "${frobulator}" | grep 'version=' | cut -d '"' -f 2)

version_local="${version_local:-01-01-1970}"

date_online=$(date -d "${version_online:6:4}-${version_online:0:2}-${version_online:3:2}" +%s)

date_local=$(date -d "${version_local:6:4}-${version_local:0:2}-${version_local:3:2}" +%s)

if [ -f "${frobulator}" ] && [ "${date_online}" -gt "${date_local}" ]
then
	rm -r -f "${HOME}"/.local/bin/frobulator

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

if [ ! -f "${frobulator}" ]
then
	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${frobulator}"

# superuser ////////////////////////////////////////////////////////////////////

export self_arguments="${@}"

# frobulator.escalate

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="07-13-2026"

# usage ////////////////////////////////////////////////////////////////////////

while (($#))
do
	case "${1}"
	in
		-r|--read)
			read="${2}"

			shift
		;;

		-m|--remove)
			remove="${2}"

			shift
		;;

		-e|--execute)
			execute=true
		;;

		-h|--help)
			echo
			echo "Usage:"
			echo
			echo "Dry run:"
			echo
			echo "${script} -r /path/to/read/files -m /path/to/remove/files"
			echo
			echo "Execute:"
			echo
			echo "${script} -r /path/to/read/files -m /path/to/remove/files -e"
			echo
			echo "Options:"
			echo
			echo "-r, --read       Set [r]ead directory reference."
			echo "-m, --remove     Set re[m]ove directory reference."
			echo "-e, --execute    Ex[e]cute file removal from specified 'remove' directory."
			echo "-h, --help       Show [h]elp and usage information."
			echo

			exit
		;;

		"")
			:
		;;

		*)
			echo
			echo "Usage: ${script} -r [Read Directory] -m [Remove Directory] | -e"
			echo
			echo "${script}: Unknown option '${1}'"
			echo "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;

	esac

	shift

done

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"

# variables ////////////////////////////////////////////////////////////////////

execute=false

temporary="$(mktemp -d)"

list_read="${temporary}/read.list"
list_remove="${temporary}/remove.list"
list_delete="${temporary}/delete.list"

# defaults /////////////////////////////////////////////////////////////////////

# validate arguments

if [ -z "${read}" ]
then
	frobulator.err "Missing read directory."
	echo

	exit 1

elif [ -z "${remove}" ]
then
	frobulator.err "Missing remove directory."
	echo

	exit 1
fi

# validate directories

if [ ! -d "${read}" ]
then
	frobulator.err "Read directory not found" "[ ${read} ]"
	echo

	exit 1

elif [ ! -d "${remove}" ]
then
	frobulator.err "Remove directory not found" "[ ${remove} ]"
	echo

	exit 1
fi

# functions ////////////////////////////////////////////////////////////////////

index () {

	source="${1}"
	destination="${2}"

	cd "${source}" || exit 1

	find . -type f | sed 's|^\./||' | sort > "${destination}"

}

# update ///////////////////////////////////////////////////////////////////////

# frobulator.update

# frobulator.upgrade

# requirements /////////////////////////////////////////////////////////////////

list=(

)

frobulator.require ${list[@]}

list=()

# configuration ////////////////////////////////////////////////////////////////


# index libraries

index "${read}" "${list_read}" &

frobulator.progress index "[ read ]"

index "${remove}" "${list_remove}" &

frobulator.progress index "[ remove ]"

# determine files missing from the read directory

comm -1 -3 "${list_read}" "${list_remove}" > "${list_delete}"

# display results

if [ -s "${list_delete}" ]
then
	count_delete=$(echo $(wc -l < "${list_delete}"))

	frobulator.wrn "Files to be removed from remove directory" "[ ${count_delete} ]"
	echo

	cat "${list_delete}"

	echo

	# execute changes

	if [ "${execute}" = true ] && [ ${count_delete} -gt 0 ]
	then
		frobulator.fwd "Removing..."
		echo

		while IFS= read -r file
		do
			rm -- "${remove}/${file}"

			frobulator.wrn "Removing" "[ ${file} ]"
			echo

		done < "${list_delete}"

		echo

		# remove empty directories

		find "${remove}" -type d -empty -delete

		frobulator.inf "Files removed from remove directory" "[ ${count_delete} ]"
		echo
	else
		frobulator.wrn "Dry run only: indexed ${count_delete} files to be removed."
		frobulator.nul "Run ${script} again with 'execute' argument to delete indexed files from the 'remove' directory."
		echo
	fi

else

	frobulator.inf "No files to be removed."
	echo
fi

# cleanup

frobulator.delete "${temporary}"
