#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

ticker () {

	echo

	for ticker in '>  ' '>> ' '>>>'
	do
		echo -n -e "\r[  ${ticker}  ] ${1^}..."

		sleep 0.5
	done

	echo

	echo

}

if [[ $(id -u -n) = "root" ]]
then
	USER="${SUDO_USER:-root}"

	if [ "${USER}" = "root" ]
	then
		HOME=/root
	else
		HOME="/home/${USER}"
	fi
fi

ticker checking

package_managers_list=(
	"apt-get --quiet --quiet update > /dev/null 2>&1; apt-get --quiet --quiet install --yes"
	"dnf --quiet install --assumeyes"
	"yum --quiet install --assumeyes"
	"apk add --quiet"
	"pacman --sync --refresh --noconfirm --noprogressbar"
	"zypper --quiet --non-interactive install"
)

package="curl"

if [[ -z $(command -v "${package}") ]]
then
	for package_manager in "${package_managers_list[@]}"
	do
		entry="${package_manager%% *}"

		if [[ -n $(command -v "${entry}") ]]
		then
			eval "${package_manager} ${package} > /dev/null 2>&1"

			break
		fi
	done

	if [[ -z $(command -v "${package}") ]]
	then
		echo "[  !  ] Unable to install or binary not found /////////////////////// [ '${package}' ]"
		echo

		exit 1
	fi
fi

mkdir -p "${HOME}"/.local/bin

frobulator="${HOME}"/.local/bin/frobulator

version_online=$(curl -s -L get.frbltr.app | grep -m 1 '^# version=' | cut -d '"' -f 2)
version_local=$(grep -m 1 '^# version=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)

version_local="${version_local:-1970-01-01}"

if [ ! -f "${frobulator}" ] || [[ "${version_online}" > "${version_local}" ]]
then
	curl -s -L get.frbltr.app > "${frobulator}"

	chmod +x "${frobulator}"
fi

ticker initializing

source "${frobulator}"

# script ///////////////////////////////////////////////////////////////////////

script="$(basename -- ${BASH_SOURCE[0]})"

# version //////////////////////////////////////////////////////////////////////

version="2026-07-12"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"

# variables ////////////////////////////////////////////////////////////////////

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

# update ///////////////////////////////////////////////////////////////////////

# frobulator.update

# frobulator.upgrade

# requirements /////////////////////////////////////////////////////////////////

list=(
	cpufreq-set
)

frobulator.require ${install_list[@]}

# configuration ////////////////////////////////////////////////////////////////

# set governor aliases

governors_list=(
	$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors)
)

for governor in "${!governors_list[@]}"
do
	cat <<- FILE >> /etc/bash.bashrc

	# governor - ${governors_list[governor]} #

	${governors_list[governor]}() {
		for (( n=0 ; n<$(grep -c processor /proc/cpuinfo) ; n++ ))
	do
			sudo cpufreq-set -c "\$n" -g ${governors_list[governor]}
		done
	}
	FILE

	cat <<- FILE > /usr/bin/${governors_list[governor]}
	#!/bin/bash

	# cpu governor (${governors_list[governor]}) #

	if [[ $(grep -c processor /proc/cpuinfo) ]]
	then
		cpu="$(grep -c processor /proc/cpuinfo)"
	fi

	for (( count=0; count<cpu; count++ ))
	do
		sudo cpufreq-set	\
			-c "\${count}"	\
			-g ${governors_list[governor]}
	done

	if [[ $(command -v notify-send) ]]
	then
		notify-send						\
			-i gnome-system-monitor		\
			"CPU governor set to ${governors_list[governor]}"
	FILE

	sudo chmod +x /usr/bin/${governors_list[governor]}
done

# write switch

cat <<- 'FILE' > /usr/bin/cpu-switch
#!/bin/bash

# cpu-switch #

cpu_count="$(grep -c processor /proc/cpuinfo)"

cpu_status="$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)"

case "${governor}"
in
	powersave)
		governor="conservative"
	;;

	conservative)
		governor="ondemand"
	;;

	ondemand)
		governor="performance"
	;;

	performance)
		governor="powersave"
	;;
esac

for (( count=0 ; count<cpu_count ; count++ ))
do
	sudo cpufreq-set	\
		-c "${count}"	\
		-g "${governor}"
done

if [[ $(command -v notify-send) ]]
then
	notify-send						\
		-i gnome-system-monitor		\
		"CPU governor set to ${governors_list[governor]}"
FILE

# set permissions

sudo chmod +x /usr/bin/cpu-switch
