#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [ -f "${HOME}"/.local/bin/frobulator ]
then
	rm -r -f "${HOME}"/.local/bin/frobulator
fi

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		SUDO_HOME=/root

		USER="${SUDO_USER}"

		HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${HOME}"/.local/bin ]
	then
		mkdir -p "${HOME}"/.local/bin
	fi

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${HOME}"/.local/bin/frobulator

# superuser ////////////////////////////////////////////////////////////////////

export self_arguments="${@}"

frobulator.escalate

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="04-26-2025"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

# variables ////////////////////////////////////////////////////////////////////

configuration=/media/internal/.ddclient
hostname="${HOSTNAME}"
login=$(cat /media/internal/.ddclient | sed -n 1p)
password=$(cat /media/internal/.ddclient | sed -n 2p)

# defaults /////////////////////////////////////////////////////////////////////

list=(
	ddclient
)

frobulator.require ${list[@]}

list=()

# functions ////////////////////////////////////////////////////////////////////

if [ ! -e "${configuration}" ]
then
	frobulator.err "Configuration file not found" "[ ${configuration} ]"
	echo

	frobulator.fwd "Aborting"
	echo

	exit 1
fi

# write ddclient configuration

cat <<- FILE > /etc/ddclient.conf
# ddclient #

daemon=300                                  # check every 5 minutes
syslog=yes                                  # log update messages to syslog
mail-failure=root                           # mail failed updates to user
pid=/var/run/ddclient.pid                   # record PID to file
ssl=yes                                     # use ssl
cache=/var/cache/ddclient/ddclient.cache    # set cache file

use=web, web=dynamicdns.park-your-domain.com/getip
protocol=namecheap
server=dynamicdns.park-your-domain.com

login=${login}
password=${password}
www
${hostname}
FILE

# stop service

service ddclient stop

# reconfigure prccess handlers

sed -i -e 's|\PIDFile|#PIDFile|g' /usr/lib/systemd/system/ddclient.service

# purge service cache file

if [ -d /var/cache/ddclient ]
then
	rm					\
		--recursive		\
		--force			 /var/cache/ddclient/ddclient.cache
fi

# restart service

service ddclient start

# reload service units

systemctl daemon-reload
