#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		if [ -z "${SUDO:-$HOME}" ]
		then
			SUDO_HOME=/root
		else
			SUDO_HOME="${SUDO:-$HOME}"
		fi

		USER="${SUDO_USER}"
		USER_HOME=/home/"${USER}"
	else
		USER_HOME="${HOME}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${USER_HOME}"/.local/bin ]
	then
		mkdir -p "${USER_HOME}"/.local/bin/frobulator
	fi

	curl -s -L get.frbltr.app > "${USER_HOME}"/.local/bin/frobulator

	chmod +x "${USER_HOME}"/.local/bin/frobulator
fi

. "${USER_HOME}"/.local/bin/frobulator

# superuser ////////////////////////////////////////////////////////////////////

frobulator.escalate

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="09-23-2022"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

# variables ////////////////////////////////////////////////////////////////////

# defaults /////////////////////////////////////////////////////////////////////

list=(
	ddclient
)

frobulator.require ${list[@]}

# functions ////////////////////////////////////////////////////////////////////

# write ddclient configuration

cat <<- FILE > /etc/ddclient.conf
# ddclient #

daemon=600                               # check every 10 minutes
syslog=yes                               # log update messages to syslog
mail-failure=root                        # mail failed updates to user
pid=/var/run/ddclient.pid                # record PID to file
ssl=yes                                  # use ssl
cache=/var/cache/ddclient/ddclient.cache # set cache file

use=web, web=dynamicdns.park-your-domain.com/getip

protocol=protocol_name
server=protocol_server_address
wildcard=no
login=login
password=password # protocol dynamic dns password
$HOSTNAME
FILE

# stop service

service ddclient stop

# reconfigure prccess handlers

sed -i -e 's|\PIDFile|#PIDFile|g' /usr/lib/systemd/system/ddclient.service

# purge service cache file

if [ -d /var/cache/ddclient ]
then
	rm -rf /var/cache/ddclient/ddclient.cache
fi

# restart service

service ddclient start

# reload service units

systemctl daemon-reload
