#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [[ $(id -u -n) = "root" ]]
then
	SUDO_HOME=/root

	USER="${SUDO_USER:-root}"

	if [ "${USER}" = "root" ]
	then
		HOME=/root
	else
		HOME="/home/${USER}"
	fi
fi

echo

for ticker in '>  ' '>> ' '>>>'
do
	echo -n -e "\r[  ${ticker}  ] Checking..."

	sleep 0.5
done

echo

if [[ -z $(command -v curl) ]]
then
	if [[ -n $(command -v apt-get) ]]
	then
		apt-get -q -q update > /dev/null 2>&1
		apt-get -q -q install -y curl > /dev/null 2>&1

	elif [[ -n $(command -v dnf) ]]
	then
		dnf -q install -y curl > /dev/null 2>&1

	elif [[ -n $(command -v yum) ]]
	then
		yum -q install -y curl > /dev/null 2>&1

	elif [[ -n $(command -v apk) ]]
	then
		apk add --quiet curl > /dev/null 2>&1

	elif [[ -n $(command -v pacman) ]]
	then
		pacman -S -y --noconfirm --noprogressbar curl > /dev/null 2>&1

	elif [[ -n $(command -v zypper) ]]
	then
		zypper --quiet --non-interactive install curl > /dev/null 2>&1
	fi
fi

if [[ -z $(command -v curl) ]]
then
	echo "[  !  ] Unable to install or binary not found /////////////////////// [ 'curl' ]"
	echo

	exit 1
fi

mkdir -p "${HOME}"/.local/bin

frobulator="${HOME}"/.local/bin/frobulator

version_online=$(	curl -s -L get.frbltr.app | grep -m 1 '^# version=' | cut -d '"' -f 2)

version_local=$(grep -m 1 '^# version=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)

version_local="${version_local:-01-01-1970}"

date_online="${version_online:6:4}${version_online:0:2}${version_online:3:2}"

date_local="${version_local:6:4}${version_local:0:2}${version_local:3:2}"

if [ ! -f "${frobulator}" ] || [[ "${date_online}" > "${date_local}" ]]
then
	curl -s -L get.frbltr.app > "${frobulator}"

	chmod +x "${frobulator}"
fi

for ticker in '>  ' '>> ' '>>>'
do
	echo -n -e "\r[  ${ticker}  ] Initializing..."

	sleep 0.5
done

echo

source "${frobulator}"

# superuser ////////////////////////////////////////////////////////////////////

export self_arguments="${@}"

# frobulator.escalate

# script ///////////////////////////////////////////////////////////////////////

script="$(basename -- ${BASH_SOURCE[0]})"

# version //////////////////////////////////////////////////////////////////////

version="07-13-2026"

# usage ////////////////////////////////////////////////////////////////////////

# variables ////////////////////////////////////////////////////////////////////

stamp=$(date +"%m-%d-%Y-%H-%M-%S")

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

# update ///////////////////////////////////////////////////////////////////////

# frobulator.update

# frobulator.upgrade

# requirements /////////////////////////////////////////////////////////////////

list=(
	conky
	convert
	zenity
)

frobulator.require ${list[@]}

list=()

# configuration ////////////////////////////////////////////////////////////////

alignment="top_left"
font_size="8"
gap_x="10"
gap_y="10"
size_x="512"
size_y="512"
width="$size_x"

if [ ! -d "${HOME}"/.config/conky-picture-frame ]
then
	mkdir -p "${HOME}"/.config/conky-picture-frame
fi

cat <<- FILE > "${HOME}"/.config/conky-picture-frame/conky-picture-framerc
# conky picture frame #

alignment $alignment
background yes
default_color CCCCCC
double_buffer yes
gap_x $gap_x
gap_y $gap_y
imlib_cache_size 0
maximum_width 0
minimum_size $size_x $size_y
no_buffers no
override_utf8_locale yes
own_window yes
own_window_argb_value 255
own_window_argb_visual no
own_window_colour grey
own_window_hints below,skip_pager,skip_taskbar,sticky,undecorated
own_window_transparent no
own_window_type normal
total_run_times 0
uppercase no
use_xft yes
xftalpha 1.0
xftfont Sans:size=$font_size:normal

TEXT
\${image .picture.png}
FILE

chmod -R 777 "${HOME}"/.config/conky-picture-frame

# generate launcher

cat <<- 'FILE' > /usr/share/applications/conky-picture-frame.desktop
[Desktop Entry]
Name=Conky Picture Frame
Comment=Highly configurable system monitor
Exec=sh -c "conky -c /home/${SUDO_USER:-$USER}/.config/conky-picture-frame/conky-picture-framerc"
Icon=conky
Terminal=false
Type=Application
StartupNotify=true
Categories=Utility;
FILE
