#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

script="$(basename -- ${BASH_SOURCE[0]})"

if [[ "${frobulator_loaded}" != "true" ]]
then
	echo

	ticker () {

		for ticker in '>  ' '>> ' '>>>'
		do
			echo -n -e "\r[  ${ticker}  ] ${1^}..."

			sleep 0.5
		done

		echo

		echo

	}

	if [[ $(id -u -n) = "root" ]]
	then
		USER="${SUDO_USER:-root}"

		if [ "${USER}" = "root" ]
		then
			HOME=/root
		else
			HOME="/home/${USER}"
		fi
	fi

	ticker checking

	package_managers_list=(
		"apt-get --quiet --quiet update > /dev/null 2>&1; apt-get --quiet --quiet install --yes"
		"dnf --quiet install --assumeyes"
		"yum --quiet install --assumeyes"
		"apk add --quiet"
		"pacman --sync --refresh --noconfirm --noprogressbar"
		"zypper --quiet --non-interactive install"
	)

	package="curl"

	if [[ -z $(command -v "${package}") ]]
	then
		for package_manager in "${package_managers_list[@]}"
		do
			entry="${package_manager%% *}"

			if [[ -n $(command -v "${entry}") ]]
			then
				eval "${package_manager} ${package} > /dev/null 2>&1"

				break
			fi
		done

		if [[ -z $(command -v "${package}") ]]
		then
			echo "[  !  ] Unable to install or binary not found /////////////////////// [ '${package}' ]"
			echo

			exit 1
		fi
	fi

	mkdir -p "${HOME}"/.local/bin

	frobulator="${HOME}"/.local/bin/frobulator

	version_online=$(curl -s -L get.frbltr.app | grep -m 1 '^# version=' | cut -d '"' -f 2)

	version_local=$(grep -m 1 '^# version=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)

	version_local="${version_local:-1970-01-01}"

	if [ ! -f "${frobulator}" ] || [[ "${version_online}" > "${version_local}" ]]
	then
		curl -s -L get.frbltr.app > "${frobulator}"

		chmod +x "${frobulator}"
	fi

	ticker initializing

	source "${frobulator}"

	export self_arguments="${@}"
fi

# superuser ////////////////////////////////////////////////////////////////////

frobulator.escalate

# script ///////////////////////////////////////////////////////////////////////

frobulator.script

# version //////////////////////////////////////////////////////////////////////

version="2026-07-12"

# usage ////////////////////////////////////////////////////////////////////////

while (($#))
do
	case "${1}"
	in
		-i|--installer)
			installer="${2}"

			shift
		;;

		-h|--help)
			echo
			echo -e "Usage: ${script} -i [Installer] | -h"
			echo
			echo -e "Options:"
			echo
			echo -e "-i, --installer     Path to the SOLIDWORKS setup.exe."
			echo
			echo -e "                    [ /path/to/setup.exe ]"
			echo
			echo -e "-h, --help          Show help and usage information."
			echo
			echo -e "'${script}' [ Version // ${version} ]"
			echo

			exit
		;;

		"")
			:
		;;

		*)
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;

	esac

	shift

done

# variables ////////////////////////////////////////////////////////////////////

wine_prefix="${HOME}"/.wine
wine_drive="${wine_prefix}"/drive_c

WINEPREFIX="${wine_prefix}"

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

# update ///////////////////////////////////////////////////////////////////////

# frobulator.update

# frobulator.upgrade

# requirements /////////////////////////////////////////////////////////////////

list=(
	cabextract
	curl
	p7zip
	p7zip-full
	p7zip-rar
	rfkill
	wget
	winbind
)

frobulator.require ${list[@]}

frobulator.complete

list=()

# configuration ////////////////////////////////////////////////////////////////

frobulator.inf "Updating system"
echo

apt-get update

apt-get --assume-yes upgrade

frobulator.complete

frobulator.inf "Adding i386 architecture"
echo

dpkg --add-architecture i386

frobulator.complete

frobulator.inf "Adding WineHQ repository"
echo

wget -qO - https://dl.winehq.org/wine-builds/winehq.key | apt-key add -

add-apt-repository --yes 'deb https://dl.winehq.org/wine-builds/debian/ bookworm main'

apt-get update

apt-get --assume-yes upgrade

frobulator.complete

frobulator.inf "Installing WineHQ" "[ staging ]"
echo

apt-get --assume-yes install --install-recommends winehq-staging

frobulator.complete

# gecko

frobulator.download "https://dl.winehq.org/wine/wine-gecko/2.47.3/wine-gecko-2.47.3-x86.msi" "${HOME}/Downloads" wine-gecko.msi

frobulator.complete

WINEPREFIX="${wine_prefix}" msiexec /i "${HOME}"/Downloads/wine-gecko.msi /qn

frobulator.complete

# mono

frobulator.download "https://dl.winehq.org/wine/wine-mono/7.4.0/wine-mono-7.4.0-x86.msi" "${HOME}/Downloads" wine-mono.msi

frobulator.complete

WINEPREFIX="${wine_prefix}" msiexec /i "${HOME}"/Downloads/wine-mono.msi /qn

frobulator.complete

# winetricks

frobulator.download "https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks" "${HOME}/.local/bin" winetricks

frobulator.complete

winetricks_list=(
	win10
	allfonts
	dxvk
	vcrun2019
	dotnet48
	msxml6
	msxml4
	msxml3
	ie8
)

for winetricks_verb in "${winetricks_list[@]}"
do
	frobulator.inf "Winetricks" "[ ${winetricks_verb} ]"
	echo

	WINEPREFIX="${wine_prefix}" "${SHELL}" "${HOME}"/.local/bin/winetricks -q "${winetricks_verb}"

	frobulator.complete
done

# vba 7.1

frobulator.download "https://github.com/cryinkfly/SOLIDWORKS-Linux-Wine-Version-/raw/main/files/VBA/vba7.1.zip" "${HOME}/Downloads" vba7.1.zip

frobulator.complete

unzip -q "${HOME}"/Downloads/vba7.1.zip -d "${HOME}"/Downloads

frobulator.complete

cp -r "${HOME}"/Downloads/vba7.1/* "${wine_drive}"

frobulator.complete

# vba 7.1 patch

frobulator.download "https://github.com/cryinkfly/SOLIDWORKS-Linux-Wine-Version-/raw/main/files/VBA/vba71-kb2783832-x64.msp" "${HOME}/Downloads" vba-patch.msp

frobulator.complete

WINEPREFIX="${wine_prefix}" msiexec /p "${HOME}"/Downloads/vba-patch.msp REINSTALL=ALL REINSTALLMODE=omus /qn

frobulator.complete

# solidworks

if [ -z "${installer}" ]
then
	frobulator.err "No installer specified"
	echo

	exit 1
fi

if [ ! -f "${installer}" ]
then
	frobulator.err "Installer not found" "[ ${installer} ]"
	echo

	exit 1
fi

frobulator.inf "Launching SOLIDWORKS installer"
echo

WINEPREFIX="${wine_prefix}" wine "${installer}"

frobulator.complete

frobulator.result "${script}"

frobulator.scs "Setup complete"
echo
