#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [ -f "${HOME}"/.local/bin/frobulator ]
then
	rm -r -f "${HOME}"/.local/bin/frobulator
fi

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		SUDO_HOME=/root

		USER="${SUDO_USER}"

		HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${HOME}"/.local/bin ]
	then
		mkdir -p "${HOME}"/.local/bin
	fi

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${HOME}"/.local/bin/frobulator

# superuser ////////////////////////////////////////////////////////////////////

# frobulator.escalate

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="03-09-2023"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"
echo

# variables ////////////////////////////////////////////////////////////////////

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

install_list+=(
	apache2
	cura
	ffmpeg
	samba
)

purge_list+=(
	apport*
	firefox
	info
	kerneloops
	memtest86+
	snapd
	vlc
	xterm
)

gnome_list+=(

)

kde_list+=(
	kaffeine
	kfind
	krename
	ktorrent
)

pip_list=(
	trimesh
	puddletag
	scdl
)

frobulator.purge ${purge_list[@]}

frobulator.install ${install_list[@]}

if [ -d /media/internal/Linux/applications ]
then
	cd /media/internal/Linux/applications

	for package in *.deb
	do
		frobulator.install "${package}"
	done
fi

for package in ${pip_list[@]}
do
	pip install "${package}"
done

if [[ "${DESKTOP_SESSION}" = "plasma" ]]
then
	frobulator.install ${kde_list[@]}
fi

if [[ "${DESKTOP_SESSION}" = "gnome" ]]
then
	frobulator.install ${gnome_list[@]}
fi
