#!/bin/bash

# usage #

if [[ $# -gt 2 ]]
then
	echo "Usage: ${0} print <color number [0..255]>"
	exit 1
fi

# name		value		HEX		RGB

# black		0		#000000		000,000,000
# red		1		#ff0000		255,000,000
# green		2		#00ff00		000,255,000
# yellow	3		#ffff00		255,255,000
# blue		4		#000000		000,000,255
# magenta	5		#ff00ff		255,000,255
# cyan		6		#00ffff		000,255,255
# white		7		#ffffff		255,255,255

# variables #

color_option=$"{1}"
color_number=$"{2}"

print_color(){
	for color_number
	do
		printf '\e[48;5;%dm%03d' $color_number $color_number
	done

	printf '\e[0m \n'
}

if [[ "$color_option" = "print" ]]
then
	# set IFS

	IFS=$' \t\n'

	# print basic colors 000 >>> 015

	print_color {0..15}

	# print color range 016 >>> 231

	for ((i=0;i<6;i++))
	do
		print_color $(seq $((i*36+16)) $((i*36+51)))
	done

	# print monochromatic colors 232 >>> 255

	print_color {232..255}
fi
