#!/bin/bash

# dependencies #

curl -sL get.trmnl.me/frobulate.console > "${PREFIX}"/bin/console && . "${PREFIX}"/bin/console

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

# usage #

# prompt #

# variables #

# defaults #

# governor aliases #

governors_list=(
	conservative
	ondemand
	powersave
	performance
)

for governor in "${!governors_list[@]}"
do
cat << FILE >> /etc/bash.bashrc

# cpu ${governors_list[governor]} #

${governors_list[governor]}() {
	for ((n=0; n<$(grep -c processor /proc/cpuinfo); n++))
do
		sudo cpufreq-set -c "\$n" -g ${governors_list[governor]}
	done
}
FILE
done

# source new shell content

. /etc/bash.bashrc

# add cpu governor binary entries

for i in "${!governors_list[@]}"
do
	cat <<- FILE > "$binary_directory/${governors_list[governor]}"
	#!/bin/bash

	# cpu governor (${governors_list[governor]}) #

	cpu="$(grep -c processor /proc/cpuinfo)"

	for ((n=0; n<cpu; n++))
	do
		sudo cpufreq-set -c "\$n" -g ${governors_list[governor]}
	done

	[[ $(command -v notify-send) ]] && notify-send -i gnome-system-monitor "CPU governor set to ${governors_list[governor]}"
	FILE
done

for governor in "${!governors_list[@]}"
do
	sudo chmod +x /usr/bin/"$governors_list"
done

# write switch

cat << 'FILE' > /usr/bin/cpu-switch
#!/bin/bash

# cpu-switch #

cpu_count="$(grep -c processor /proc/cpuinfo)"

cpu_status="$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)"

case "${governor}"
in
	powersave)
		governor="conservative"
	;;

	conservative)
		governor="ondemand"
	;;

	ondemand)
		governor="performance"
	;;

	performance)
		governor="powersave"
	;;
esac

for ((n=0; n<cpu_count; n++))
do
	sudo cpufreq-set -c "$n" -g "${governor}";
done

[[ $(command -v notify-send) ]] && notify-send -i gnome-system-monitor "CPU governor set to ${cpu_status}"
FILE

# set permissions

sudo chmod +x /usr/bin/cpu-switch

# write launcher

cat <<- FILE > /usr/share/applications/cpu-switch.desktop
[Desktop Entry]
Name=Background Cycler
Comment=Enable timed background cycling
Exec=/usr/bin/cpu-switch
Icon=background
Terminal=false
Type=Application
StartupNotify=true
Categories=Utility;
FILE
