#!/bin/bash

# dependencies #

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

# usage #

if [[ -z "$#" ]]
then
	echo "Usage: ${0} <first last [name]> <uid> <gid>"
	exit 1
fi

# prompt #

# variables #

first_name=${1}
last_name=${2}
uid=${3}
gid=${4}

user_name=${first_name,,}
full_name="$first_name $last_name"

sudo_gid=$(getent group sudo | cut -d : -f 3)

# defaults

if [ -z "$sudo_gid" ]
then
	sudo_gid=27
fi

# create user

# equivalent - useradd -m -s "${SHELL}" -p ${password} ${user_name}

echo "${user_name}:x:${uid}:${gid}:${full_name},,,:/home/${user_name}:$SHELL" >> /etc/passwd
echo "${user_name}:x:${uid}:" >> /etc/group

# set sudo privileges for user #

# equivalent - usermod -a -G sudo ${user_name}

echo "sudo:x:27:${user_name}" >> /etc/group

echo "${user_name} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/${user_name}

# create home directory for user

mkdir -p /home/${user_name}

# set ownership

chown -R root:root /usr
chown ${uid}:${gid} -R /home/${user_name}
chmod 4755 /usr/bin/sudo
chmod 0440 /etc/sudoers.d/${user_name}