#!/bin/bash

# dependencies #

curl -sL get.trmnl.me/console/console > "${PREFIX}"/bin/console && . "${PREFIX}"/bin/console

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

# usage #

# prompt #

# variables #

# defaults

# update icon cache

icons_directory_list=(
	"${HOME}"/.icons
	"${PREFIX}"/share/icons
	/usr/share/icons
)

for icons_directory in ${icons_directory_list[@]}
do
	[ -d "${icons_directory}" ] && cd "${icons_directory}"

	find "${icons_directory}" -mindepth 1 -maxdepth 1 -type d | while read -r theme
	do
		if [ -f "${theme}"/index.theme ]
		then
			theme_name="${theme##*/}"

			gtk-update-icon-cache -f -q "${theme}"

			console.scs "Cache update success" "[ ${theme_name} ]"
			echo
		else
			console.inf "${theme_name}"
			echo
		fi
	done
done
