#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# password #

# dependencies #

curl -sL dep.dxtp.app/console > /usr/bin/console && source /usr/bin/console

# variables #

password_file="/.password"

# passsword file check/generate

if [[ -e "$password_file" ]]
then
	# password files exists - continue
	:
else
	# password file not found - enter new password to generate

	read -p "Password: " -s password

	echo "$(echo "$password" | base64)" >> "$password_file"
fi
