#!/bin/bash

# dependencies #

curl -sL get.trmnl.me/console//console > /usr/bin/console && . /usr/bin/console

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

# usage #

# prompt #

# variables #

home="/home/${SUDO_USER:-$USER}"

# defaults #

# write binary

cat << 'FILE' > /usr/bin/wacom-touch-toggle
#!/bin/bash

# wacom-touch-toggle #

device_name=$(xinput list --name-only | grep [wW]acom)
device_input_type=$(xinput list --name-only | grep [fF]inger)
device_id=$(xinput list --id-only "$device_input_type")
device_enabled_status=$(xinput list-props  "$device_id" | grep  "Device Enabled")
device_status=${device_enabled_status: -1}

if [[ "$device_name" =~ [wW]acom ]]
then
	if [[ "$device_status" == "0" ]]
	then
		status="on"
			xinput set-prop "$device_id" "Device Enabled" 1

	elif [[ "$device_status" == "1" ]]
	then
		status="off"
		xinput set-prop "$device_id" "Device Enabled" 0
	else
		exit
	fi
else
	notify-send -i input-tablet "Wacom tablet not detected or connected."

	exit
fi

notify-send -i input-tablet "$device_input_type touch is $status"
FILE

# set permissions

chmod +x /usr/bin/wacom-touch-toggle

# write launcher

cat <<- FILE > /usr/share/applications/wacom-touch-toggle.desktop
[Desktop Entry]
Name=Touch Toggle
Comment=Touch input toggle
Exec=/usr/bin/wacom-touch-toggle
Terminal=false
Type=Application
Icon=input-tablet
Categories=Application;Settings;System;
FILE