#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# wireless power control #

# dependencies #

curl -sL dep.dxtp.app/console > /usr/bin/console && source /usr/bin/console

# variables #

home="/home/${SUDO_USER:-$USER}"

# configuration #

# disable wifi powersave #

cat << 'FILE' > /etc/NetworkManager/conf.d/default-wifi-powersave-on.conf
[connection]
wifi.powersave = 2

[device]
wifi.scan-rand-mac-address=false
FILE

# binary #

cat << 'FILE' > /usr/bin/wireless-power-control
#!/bin/bash
wlan=$(netstat -in | awk '/^w[l][ap][0-9]/{print $1}')
iwconfig "$wlan" power off
notify-send -i preferences-system-power "Power control for wireless interface $wlan is turned off"
FILE

sudo chmod +x /usr/bin/wireless-power-control

# launcher #

cat << FILE > /usr/share/applications/wireless-power-control.desktop
[Desktop Entry]
Name=Wireless Power Control
Comment=Disable wireless power management
Exec=sh -c "sudo /usr/bin/wireless-power-control"
Icon=preferences-system-power
Terminal=false
Type=Application
StartupNotify=true
Categories=Utility;
NoDisplay=true
FILE
