#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="04-13-2021"

# usage #

settings_file="${1}"

if [[ $# -lt 1 ]]
then
	echo "Usage: ${script} [SEtTINGS FILE] | [OPTION]"
	exit 1
fi

# variables #

settings_file="${1}"

# read settings

console.inf "Reading settings file."
echo

xfconf-query -l | sed -r -e '/Channels:/d' | while read channel
do
	if [ "$channel" = "xfce4-session" ]
	then
		# skip xfce4-session channel:
		# problems with failsafe state reload from settings file

		:
	else
		xfconf-query -lv -c "${channel}" | sed -r -e "s/^/${channel} /"
	fi

done > "${settings_file}"

# strip unsupported data lines

sed -i -e '/UNSUPPORTED/d' "${settings_file}"
