#!/bin/bash

# dependencies #

curl -sL get.trmnl.me/console/console > "${PREFIX}"/bin/console && . "${PREFIX}"/bin/console

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="01-06-2022"

# usage #

settings_file="${1}"

if [[ $# -lt 1 ]]
then
	echo "Usage: ${script} [SETTINGS FILE] | [OPTION]"
	exit 1
fi

# variables #

settings_file="${1}"

# defaults #

# read settings

console.inf "Generating" ""
echo

xfconf-query -l | sed '/Channel.*/d' | while read channel
do
	xfconf-query -l -v -c "${channel}" | while read property setting
	do
		# provide data type:
		# needs to be researched before making a new .xfconf file
		# “bool”   - boolean value: either “true” or “false”
		# “int”    - 32-bit signed integer value, in the range from -2·147·483·648 through 2·147·483·647
		# “uint”   - 32-bit unsigned integer value, in the range from 0 through 4·294·967·295
		# “int64”  - 64-bit signed integer value, in the range from -9·223·372·036·854·775·808 through 9·223·372·036·854·775·807
		# “uint64” - 64-bit unsigned integer value, in the range from 0 through 18·446·744·073·709·551·615
		# “double” - presumably a double-precision floating-point value, even though it will be stored as a fixed-point value instead, with six decimal places following the decimal point
		# “string” - character string

	# parse data types : FIX ME

	#	if [[ ${setting} = "true" ]] || [[ ${setting} = "false" ]]
	#	then
	#		type=bool
	#
	#	elif [[ ${setting} -lt 2147438647 ]] || [[ ${setting} -gt -2147438647 ]]
	#	then
	#		type=int
	#
	#	elif [[ ${setting} -lt 4294967295 ]] || [[ ${setting} -gt 0 ]]
	#	then
	#		type=uint
	#
	#	elif [[ ${setting} -lt 9223372036854775807 ]] || [[ ${setting} -gt -9223372036854775807 ]]
	#	then
	#		type=int64
	#
	#	elif [[ ${setting} -lt 18446744073709551615 ]] || [[ ${setting} -gt 0 ]]
	#	then
	#		type=uint64
	#
	#	elif [[ ${setting} =~ ^[-+]?[0-9]+\.[0-9]*$ ]]
	#	then
	#		type=double
	#
	#	else
	#		type=string
	#	fi

		if [[ ${setting} = "true" ]] || [[ ${setting} = "false" ]]
		then
			type=bool
		else
			type=string
		fi

		if [[ ${setting} = *UNSUPPORTED* ]] || [[ ${channel} = "xfce4-session" ]] || [[ ${channel} = "xfce4-settings-editor" ]] || [[ ${channel} = "displays" ]]
		then
			:
		else
			echo "xfconf-query --create -c ${channel} -p ${property} -t ${type} -s ${setting}"
		fi
	done

done > "${settings_file}"

echo "xfwm4 --replace &" >> "${settings_file}"

