#!/bin/bash

# dependencies #

curl -sL get.trmnl.me/console/console > "${PREFIX}"/bin/console && . "${PREFIX}"/bin/console

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

# usage #

settings_file="${1}"

if [[ $# -lt 1 ]]
then
	echo "Usage: ${script} [SETTINGS FILE] | [OPTION]"
	exit 1
fi

# variables #

settings_file="${1}"

# defaults #

# read settings

console.inf "Reading settings file."
echo

xfconf-query -l | sed '/Channel.*/d' | while read channel
do
	if [ "$channel" = "xfce4-session" ]
	then
		# skip xfce4-session channel:
		# problems with failsafe state reload from settings file

		:
	else
		xfconf-query -l -v -c "${channel}" | while read property setting
		do
			echo "xfconf-query --create -c ${channel} -p ${property} -t TYPE -s ${setting}"
		done
	fi

done > "${settings_file}"

# strip unsupported data lines

sed -i -e '/UNSUPPORTED/d' "${settings_file}"
