#!/bin/bash

# dependencies #

curl -sL get.trmnl.me/console/console > "${PREFIX}"/bin/console && . "${PREFIX}"/bin/console

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="01-06-2022"

# usage #

settings_file="${1}"

if [[ $# -lt 1 ]]
then
	echo "Usage: ${script} [SETTINGS FILE] | [OPTION]"
	exit 1
fi

# variables #

settings_file="${1}"

# defaults #

# read settings

console.inf "Reading settings file."
echo

xfconf-query -l | sed '/Channel.*/d' | while read channel
do
	xfconf-query -l -v -c "${channel}" | while read property setting
	do
		if [[ ${setting} = "true" ]] || [[ ${setting} = "false" ]]
		then
			type="bool"
		else
			type="string"
		fi

		if [[ ${setting} = *UNSUPPORTED* ]] || [[ ${channel} = "xfce4-session" ]] || [[ ${channel} = "xfce4-settings-editor" ]] || [[ ${channel} = "displays" ]]
		then
			:
		else
			echo "xfconf-query --create -c ${channel} -p ${property} -t ${type} -s ${setting}"
		fi
	done

done > "${settings_file}"

