#!/bin/bash

# dependencies #

curl -sL get.trmnl.me/console/console > "${PREFIX}"/bin/console && . "${PREFIX}"/bin/console

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="01-06-2022"

# usage #

settings_file="${1}"

if [[ $# -lt 1 ]]
then
	echo
	echo "Usage: ${script} [SETTINGS FILE] | [OPTION]"
	echo

	exit 1
fi

# variables #

stamp=$(date +"%m-%d-%Y-%H-%M-%S")

# defaults #

# read settings

console.inf "Generating" "[ ${settings_file} ]"
echo

xfconf-query -l | sed '/Channel.*/d' | while read channel
do
	xfconf-query -l -v -c "${channel}" | while read property setting
	do
		# provide data type:
		# needs to be researched before making a new .xfconf file
		# “bool”   - boolean value: either 'true'or 'false'
		# “int”    - 32-bit signed integer value, in the range from -2·147·483·648 through 2·147·483·647
		# “uint”   - 32-bit unsigned integer value, in the range from 0 through 4·294·967·295
		# “int64”  - 64-bit signed integer value, in the range from -9·223·372·036·854·775·808 through 9·223·372·036·854·775·807
		# “uint64” - 64-bit unsigned integer value, in the range from 0 through 18·446·744·073·709·551·615
		# “double” - presumably a double-precision floating-point value, even though it will be stored as a fixed-point value instead, with six decimal places following the decimal point
		# “string” - character string

		# parse data types

		if [[ ${setting} = true ]] || [[ ${setting} = false ]]
		then
			type=bool

		elif [[ ${setting} =~ ^[-+]?[0-9]+\.[0-9]*$ ]]
		then
			type=double

		elif [[ ${setting} =~ ^[0-9]+$ ]]
		then
			type=int

		else
			type=string
		fi

		if [[ ${channel} = "displays" ]] || [[ ${channel} = "xfce4-panel" ]] || [[ ${channel} = "xfce4-session" ]] || [[ ${channel} = "xfce4-settings-editor" ]] || [[ ${channel} = "xfce4-settings-manager" ]] || [[ ${setting} = *UNSUPPORTED* ]]
		then
			:
		else
			echo "xfconf-query --create -c '${channel}' -p '${property}' -t ${type} -s '${setting}'"
		fi
	done

done > "${settings_file}"

echo "xfconf-query --create -c 'xfce4-desktop' -p '/backdrop/screen0/monitorVNC-0/workspace0/rgba1' -t double -t double -t double -t double -s 1.0 -s 1.0 -s 1.0 -s 1.0" >> "${settings_file}"
echo "xfconf-query --create -c 'xfce4-desktop' -p '/backdrop/screen0/monitorVNC-0/workspace0/rgba2' -t double -t double -t double -t double -s 1.0 -s 1.0 -s 1.0 -s 1.0" >> "${settings_file}"

echo "bash -c 'xfwm4 --replace & > /dev/null 2>&1'" >> "${settings_file}"

console.scs "Done."
echo

console.msg "Use newly generated settings file as follows:"
console.msg "'bash <settings_file>'"
echo
