#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# icon cache update #

# dependencies #

# dependencies #  curl -sL dep.dxtp.app/console > /usr/bin/console && source /usr/bin/console

# variables #

home="/home/${SUDO_USER:-$USER}"
local_icons_directory="$home/.icons"
system_icons_directory="/usr/share/icons"

icons_directory_list=(
	"$local_icons_directory"
	"$system_icons_directory"
)

# configuration #

for icons_directory in ${icons_directory_list[@]}
do
	cd "$icons_directory" || exit

	console.inf "Forcing icon cache update..."

	find "$icons_directory" -mindepth 1 -maxdepth 1 -type d | while read -r theme
	do
		if [ -f "$theme/index.theme" ]
		then
			theme_name="${theme##*/}"

			echo "Refreshing (${theme_name})..."
			echo

			gtk-update-icon-cache -f "$theme" || echo "${red}$theme_name"
			echo ""
		fi
	done
done
