#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# password #

# dependencies #

source ./console

# variables #

password_file="/.password"

# configuration #

console.info "Acquiring password for setup..."

if [[ -e "$password_file" ]]
then
	echo "${green}Password file exists. Proceeding..."
else
	echo "${red}Password file not found."
	console.warning "Choose a password to use during setup..."

	read -s password

	echo "$(echo "$password" | base64)" >> "$password_file"
fi
