#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# wacom touch toggle #

# dependencies #

source ./console

# variables #

binary_directory="/usr/bin"

home="/home/${SUDO_USER:-$USER}"
local_applications_directory="$home/.local/share/applications"
system_applications_directory="/usr/share/applications"

# binary #

console.info "Adding Wacom tablet touch toggle binary (/usr/bin) ..."

cat << 'FILE' > "$binary_directory"/wacom-touch-toggle
#!/bin/bash

# wacom-touch-toggle #

device_name=$(xinput list --name-only | grep [wW]acom)
device_input_type=$(xinput list --name-only | grep [fF]inger)
device_id=$(xinput list --id-only "$device_input_type")
device_enabled_status=$(xinput list-props  "$device_id" | grep  "Device Enabled")
device_status=${device_enabled_status: -1}

if [[ "$device_name" =~ [wW]acom ]]
then
	if [[ "$device_status" == "0" ]]
	then
		status="on"
			xinput set-prop "$device_id" "Device Enabled" 1

	elif [[ "$device_status" == "1" ]]
	then
		status="off"
		xinput set-prop "$device_id" "Device Enabled" 0
	else
		exit
	fi
else
	notify-send -i input-tablet "Wacom tablet not detected or connected."

	exit
fi

notify-send -i input-tablet "$device_input_type touch is $status"
FILE

# permissions #

chmod +x "$binary_directory"/wacom-touch-toggle

# launcher #

cat <<- FILE > "$system_applications_directory"/wacom-touch-toggle.desktop
[Desktop Entry]
Name=Touch Toggle
Comment=Touch input toggle
Exec=/usr/bin/wacom-touch-toggle
Terminal=false
Type=Application
Icon=input-tablet
Categories=Application;Settings;System;
FILE