#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# administration #

# dependencies #

source ./console

# configuration #

console.info "Granting administration privileges (/etc/sudoers)..."

echo "${SUDO_USER:-$USER} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/${SUDO_USER:-$USER}
