#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# git #

# dependencies #

source ./console

# variables #

home="/home/${SUDO_USER:-$USER}"
git_configuration="$home/.gitconfig"

# configuration #

console.info "Writing configuration (git)..."

cat << FILE > "$git_configuration"
[user]
email = nathanel.titane@gmail.com
name = nathaneltitane
[credential]
helper = store
FILE
