#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# git #

# dependencies #

source ./console

# variables #

home="/home/${SUDO_USER:-$USER}"
git_configuration="$home/.gitconfig"

# configuration #

console.info "Writing configuration (git)..."

cat <<- FILE > "$git_configuration"
[user]
        name = nathaneltitane
        email = nathanel.titane@gmail.com
[color]
        ui = auto
[core]
        editor = /usr/bin/nano -c
[hub]
        protocol = https
[credential]
  helper = store
FILE
