#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# install local #

# dependencies #

source ./console

# variables #

# Enable quiet package install

export DEBIAN_FRONTEND=noninteractive

# configuration #

console.info "Installing local packages..."

if [ -d ./deb ]
then
	for package in ./deb/*.deb
	do
		yes | apt install "${package}"
	done
else
	console.warning "No local packages to install. Continuing..."
fi