#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# setup #

# dependencies #

source ./console

# variables #

# configuration #

console.info "Configuring system..."

scripts_list=(
	colors
	storage-link
	purge
	upgrade
	install
	install-local
	administration
	aliases
	android
	ddclient
	git
	ssh
	files
)

for script in ${scripts_list[@]}
do
	bash ${script}
done

console.success "Setup complete."
echo
