#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# storage link #

# dependencies #

source ./console

# configuration #

console.info "Linking storage devices..."

if [ $(echo $(cat /proc/version | grep -o microsoft)) = microsoft ]
then
  ln -s -f /mnt/d/MEGA /media/MEGA
else
  ln -s -f /media/${SUDO_USER:-$USER}/SD/MEGA /media/MEGA
fi

