#!/bin/bash

# adb install apk #

# dependencies #

# dependencies #  curl -sL dep.dxtp.app/console > /usr/bin/console && source /usr/bin/console

# install #

if [ -e ./apk ]
then
	for package in ./apk/*.apk
	do
		adb install "${package}"
	done
else
	console.error "No local packages to install."
	echo
	console.fwd "Continuing."
	echo
fi
