#!/bin/bash

# adb pull data apps #

# create directory #

if [[ ! -e ./apk ]]
then
	mkdir apk
	cd apk
else
	cd ./apk || exit
fi

# pull #

for package in $(adb shell pm list packages | sed -n 's/^package://p')
do
	adb pull "$(adb shell pm path "${package}" | grep /data/app | sed -n "s/^package://p")"
	mv base.apk "${package}".apk
done
