#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# ddclient #

# dependencies #

curl -sL dep.dxtp.app/console > /usr/bin/console && source /usr/bin/console

# variables #

# configuration #

console.inf "Writing configuration."

cat << FILE > /etc/ddclient.conf
# ddclient #

daemon=600
syslog=yes
mail-failure=root
pid=/var/run/ddclient.pid
ssl=yes
cache=/var/cache/ddclient/ddclient.cache

use=web, web=dynamicdns.park-your-domain.com/getip

protocol=namecheap
server=dynamicdns.park-your-domain.com
wildcard=no
login=nathaneltitane.com
password=PASSWORD
HOSTNAME
FILE

console.wrn "Stopping service."

service ddclient stop

console.inf "Reconfiguring process handlers."

sed -i -e 's|\PIDFile|#PIDFile|g' /usr/lib/systemd/system/ddclient.service

if [ -d /var/cache/ddclient ]
then
	console.wrn "Purging service cache."

	rm -rf /var/cache/ddclient/ddclient.cache
fi

console.wrn "Restarting service."

service ddclient start

console.wrn "Reloading service units."

systemctl daemon-reload
