#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# git #

# dependencies #

# variables #

# configuration #

console.inf "Writing configuration [ git ]."

cat <<- FILE >> "${HOME}"/.gitconfig
[user]
	name = nathaneltitane
	email = nathanel.titane@gmail.com
[color]
	ui = auto
[core]
	editor = /usr/bin/nano -c
[hub]
	protocol = https
[credential]
	helper = store
FILE
