#!/bin/bash

# dependencies #

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

# usage #

# prompt #

# variables #

# defaults #

[ -z "${USER}" ] && USER="termux"

unset PS1

PS1+='\[$(tput sc)'
PS1+='$(tput ed)'
PS1+='$(tput cup 0 0)'
PS1+='$(tput setaf 0)'
PS1+='$(tput setab 7)'
PS1+='$(tput el)'
PS1+=' ( HOSTNAME: )'
PS1+=' ( USER: \u )'
PS1+=' ( TIME: )'
PS1+=' ( BATT. % )'
PS1+=' ( NET: $(getprop wifi.interface) )'
PS1+="$(tput sgr 0)$(tput rc)\]"
PS1+="[ ${USER} ] >_ $ '
