#!/bin/bash

# dependencies #

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

# usage #

# prompt #

# variables #

# defaults #

for foreground_color in {0..7}
do
	set_foreground=$(tput setaf $foreground_color)
	
	for background_color in {0..7}
	do
		set_background=$(tput setab $background_color)
		
		echo -n $set_background$set_foreground
		
		printf ' F:%s B:%s ' $foreground_color $background_color
	done
	
	echo $(tput sgr0)
	
done