#!/bin/bash

# dependencies #

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

# usage #

# prompt #

# variables #

query="${1}"

# defaults #

# query types:

# health
# percentage
# plugged
# status
# temperature
# current

termux-battery-status | jq -r | grep "${query}" | cut -d ':' -f 2 | sed 's/[^aA0-zZ9]//g ; s/_/ /g'