#!/bin/bash

# change wallpaper #

ln -sf "$(find /media/Internal/Pictures/ -type f | xargs -r0 | dmenu -l 15 -p 'Change Wallpaper')" ~/Pictures/Wallpaper.png && feh --bg-fill ~/Pictures/Wallpaper.png