#!/bin/bash

while [ "$selection" != "CANCEL" -a "$selection" != "LOGOUT" -a "$selection" != "POWEROFF" -a "$selection" != "REBOOT" ]
do
	selection=$(echo -e 'CANCEL\nLOGOUT\nPOWEROFF\nREBOOT' | dmenu -i -l 15 -p "Exit session?")

	[ -z "$selection" ] && exit
done

[ "$selection" = "CANCEL" ] && exit
[ "$selection" = "LOGOUT" ] && i3-msg exit