#!/bin/bash

line_count=15

prompt="${1}"
execute="${2}"

selection_menu=$(echo -e "NO\NYES" | dmenu -i -l "$line_count" -p "${prompt}")

[ "${selection_menu}" == "YES" ] && "${execute}"

# use with i3wm binding as follows:
# bindsym $modifier+key exec --no-startup-id /usr/bin/dmenu-confirm "Prompt?" "usr/bin/script-to-execute"