#!/bin/bash

line_count=15
prompt="CHANGE BACKGROUND"

background_directory="${HOME}/Pictures"
background_file="${background_directory}/.background.png"

ln -sf "$(find "${background_directory}" -type f | xargs -r0 | dmenu -i -l "${line_count}" -p "${prompt}")" "${background_file}" && feh --bg-fill "${background_file}"