#!/bin/bash

# dependencies #

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

# usage #

# prompt #

# variables #

lines=15
prompt="OPEN DIRECTORY"

# defaults #

find $HOME -type f -maxdepth 1 -printf "%f\n" | dmenu -i -l "${lines}" -p "${prompt}" -nb '#000000' -nf '#FFFFFF' -sb '#666666' -sf '#000000' | xargs -r st -e ranger --selectfile