#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# administration #

# dependencies #

curl -sL get.cnsl.app/console> /usr/bin/console && . /usr/bin/console

# write admin privilege

echo "${SUDO_USER:-$USER} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers/"${SUDO_USER:-$USER}"
