#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# administration #

# dependencies #

curl -sL dep.dxtp.app/console > /usr/bin/console && source /usr/bin/console

#configuration #

console.inf "Granting administration privileges (/etc/sudoers)..."

echo "${SUDO_USER:-$USER} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers/"${SUDO_USER:-$USER}"
