#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# aliases #

# dependencies #

source ./console

# variables #

home=(
	"/root"
	"/home/${SUDO_USER:-$USER}"
)

for path in ${home[@]}
do
	console.info "Adding command line aliases ($path/.bash_aliases)..."

	cat <<- 'FILE' > "$path"/.bash_aliases
	# aliases #


	FILE
done
