#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com - Copyright 2016

# applications #

# dependencies #

curl -sL dep.dxtp.app/console > /usr/bin/console && source /usr/bin/console

# variables #

home="/home/${SUDO_USER:-$USER}"



# launcher #

if [ -e /usr/share/applications/launcher.desktop ]
then
	console.inf "Creating applcition launcher (launcher_name)..."

	cat <<- FILE >> /usr/share/applications/launcher.desktop
	[Desktop Entry]
	Name=Name
	Comment=Description
	Exec=/usr/bin/commmand
	Terminal=false
	Type=Application
	Icon=icon
	Categories=Application;Settings;System;
	Actions=Action_Name;Action_Name;Action_Name;

	[Desktop Action Action_Name]
	Name=Name
	Exec=command

	[Desktop Action Action_Name]
	Name=Name
	Exec=command

	[Desktop Action Action_Name]
	Name=Name
	Exec=command
	FILE
else
	console.error "Launcher not present or application not installed..."
	console.error "Skipping."
fi
