#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# autostart #

# dependencies #

source ./console

# variables #

home="/home/${SUDO_USER:-$USER}"
local_autostart_directory="$home/.config/autostart"
system_autostart_directory="/etc/xdg/autostart"
local_applications_directory="$home/.local/share/applications"
system_applications_directory="/usr/share/applications"

# autostart enable #

if [ ! -d "$local_autostart_directory" ]
then
	mkdir "$local_autostart_directory"
fi

console.info "Generating startup items..."

cd "$system_applications_directory" || exit

autostart_enable_list=(
	launcher.desktop
	launcher.desktop
	launcher.desktop
)

if (( ${#autostart_enable_list[@]} ))
then
	for launcher in ${autostart_enable_list[@]}
	do
		if [[ -e "$launcher" ]]
		then
			cp "$system_applications_directory/$launcher" "$local_autostart_directory/$launcher"
		else
			: #pass
		fi
	done
fi

# permissions #

sudo chmod -R 777 "$local_autostart_directory"

cd "$local_autostart_directory" || exit

chmod +x *.desktop

# autostart disable #

console.info "Disabling startup items..."

cd "$system_autostart_directory" || exit

autostart_disable_list=(
	launcher.desktop
	launcher.desktop
	launcher.desktop
)

if (( ${#autostart_disable_list[@]} ))
then
	for launcher in ${autostart_disable_list[@]}
	do
		rm -rf "$launcher"
	done
fi
