#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# blacklist modules #

# dependencies #

curl -sL get.cnsl.app/console> /usr/bin/console && . /usr/bin/console

# variables #

# blacklist modules

if [[ "$HOSTNAME" == [hH]ostname || "$HOSTNAME" == [hH]ostname ]]
then
	modules_list=(
		"module_name"
		"module_name"
		"module_name"
	)

elif [[ "$HOSTNAME" == [hH]ostname ]]
then
	modules_list=(
		"module_name"
		"module_name"
		"module_name"
	)
fi

for module in ${modules_list[@]}
do
	cat << FILE >> /etc/modprobe.d/blacklist-"${module}".conf
	blacklist "$module"
	FILE
done