#!/bin/bash

# dependencies #

curl -sL get.trmnl.me/frobulate.console > "${PREFIX}"/bin/console && . "${PREFIX}"/bin/console

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

# usage #

# prompt #

# variables #

# defaults #

if [ -d /etc ]
then
	cat <<- 'FILE' > /etc/hosts
	# localhosts #

	::1			localhost6
	::1			localhost6.localdomain6
	127.0.0.1	localhost
	127.0.0.1	localhost.localdomain
	127.0.0.1	$HOSTNAME

	# blacklist #

	FILE

	# configuration #

	url_list=(
	)

	for url in "${!url_list[@]}"
	do
		cat <<- FILE >> /etc/hosts
		127.0.0.1	${url_list[url]}
		FILE
	done
fi
