#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# bookmarks #

# dependencies #

curl -sL dep.dxtp.app/console > /usr/bin/console && source /usr/bin/console

# variables #

home="/home/${SUDO_USER:-$USER}"

# configuration #

bookmarks_directory_list=(
	"${HOME}"/"
	"${HOME}"/.config/gtk-3.0/
)

for bookmarks_directory in ${bookmarks_directory_list[@]}
do
	console.inf "Adding bookmarks ($bookmarks_directory)..."

	cat <<- 'FILE' > "$bookmarks_directory"/bookmarks
	file:///path/to/directory Directory_Alias
	file:///path/to/directory Directory_Alias
	file:///path/to/directory Directory_Alias
	FILE
done

mv "${HOME}"/boomark"${HOME}"/me/.gtk-boomarks"
