#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# ddclient #

# dependencies #

curl -sL dep.dxtp.app/console > /usr/bin/console && source /usr/bin/console

# variables #

# configuration #

console.inf "Writing configuration (ddclient)..."

cat << FILE > /etc/ddclient.conf
# ddclient #

daemon=600										# check every 10 minutes
syslog=yes										# log update msgs to syslog
mail-failure=root								# mail failed updates to user
pid=/var/run/ddclient.pid						# record PID in file.
ssl=yes											# use ssl support
cache=/var/cache/ddclient/ddclient.cache		# cache file

use=web, web=dynamicdns.park-your-domain.com/getip

protocol=protocol_name
server=protocol_server_address
wildcard=no
login=login
password=password								# protocol dynamic dns password
$HOSTNAME
FILE

console.wrn "Stopping service."

service ddclient stop

console.inf "Reconfiguring process handlers."

sed -i -e 's|\PIDFile|#PIDFile|g' /usr/lib/systemd/system/ddclient.service

if [ -d /var/cache/ddclient ]
then
	console.wrn "Purging service cache."

	rm -rf /var/cache/ddclient/ddclient.cache
fi

console.wrn "Restarting service."

service ddclient start

console.wrn "Reloading service units."

systemctl daemon-reload
