#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# files #

# dependencies #

# dependencies #  curl -sL dep.dxtp.app/console > /usr/bin/console && source /usr/bin/console

# variables #

home="/home/${SUDO_USER:-$USER}"

local_applications_directory="$home/.local/share/applications"
system_applications_directory="/usr/share/applications"

local_icons_directory="$home/.icons"
system_icons_directory="/usr/share/icons"

system_backgrounds_directory=""
system_backgrounds_directory="/usr/share/backgrounds"

local_themes_directory="$home/.themes"
system_themes_directory="/usr/share/themes"

# configuration #

console.inf "Removing unwanted files and folders..."

# home #

cd "$home" || :

removal_list=(
	file
	file
	file
)

for item in ${removal_list[@]}
do
	rm -rf "$item"
done

# applications directory #

cd "$system_applications_directory" || :

removal_list=(
	file
	file
	file
)

for item in ${removal_list[@]}
do
	rm -rf "$item"
done

# backgrounds directory #

cd "$system_backgrounds_directory" || :

removal_list=(
	file
	file
	file
)

for item in ${removal_list[@]}
do
	rm -rf "$item"
done

# themes directory #

cd "$system_themes_directory" || :

removal_list=(
	file
	file
	file
)

for item in ${removal_list[@]}
do
	rm -rf "$item"
done
