#!/bin/bash

unset password

echo -n "Enter password: "

while IFS= read -p "$prompt" -r -s -n 1 character
do
    # Enter - accept password
    if [[ $character == $'\0' ]]
    then
        break
    fi
    
    # Backspace
    
    if [[ $character == $'\177' ]]
    then
        prompt=$'\b \b'
        password="${password%?}"
    else
        prompt='*'
        password+="$character"
    fi
done
