#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# git #

# dependencies #

# dependencies #  curl -sL dep.dxtp.app/console > /usr/bin/console && source /usr/bin/console

# variables #

home="/home/${SUDO_USER:-$USER}"
git_configuration="$home/.gitconfig"

# configuration #

console.inf "Writing configuration (git)..."

cat << FILE > "$git_configuration"
[user]
email = email
name = username
[credential]
helper = store
FILE
