#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# gnome-settings #

# dependencies #

source ./console

# variables #

font="Sans 9"
monospace_font="Monospace 9"

get_terminal_profile=$(gsettings get org.gnome.Terminal.ProfilesList default)
terminal_profile=${get_terminal_profile:1:-1} # Remove leading and trailing single quotes

# configuration #

console.info "Setting application parameters (gsettings)..."

# gconf #

# user #

gconftool-2 --type=string -s /desktop/gnome/interface/icon_theme "Numix-Circle"

# gsettings #

# user #

user_settings_list=(
	org.freedesktop.Tracker.Miner.Files crawling-interval "-1"
	org.freedesktop.Tracker.Miner.Files enable-monitors true
	org.freedesktop.Tracker.Miner.Files index-on-battery false
	org.freedesktop.Tracker.Miner.Files index-recursive-directories "['&DESKTOP', '&DOCUMENTS', '&DOWNLOAD', '&MUSIC', '&PICTURES', '&VIDEOS', '/media/Disk/Dropbox']"
	org.freedesktop.Tracker.Miner.Files index-removable-devices true
	org.freedesktop.Tracker.Miner.Files low-disk-space-limit "10"
	org.freedesktop.Tracker.Miner.Files removable-days-threshold "1"
	org.gnome.builder.editor draw-spaces "['space', 'tab']"
	org.gnome.builder.editor font-name "$monospace_font"
	org.gnome.builder.editor highlight-current-line true
	org.gnome.builder.editor highlight-matching-brackets true
	org.gnome.builder.editor show-map true
	org.gnome.builder.editor style-scheme-name "oblivion"
	org.gnome.builder.project-tree show true
	org.gnome.desktop.a11y.applications screen-keyboard-enabled false
	org.gnome.desktop.app-folders folder-children "[]"
	org.gnome.desktop.background picture-options "zoom"
	org.gnome.desktop.background picture-uri ""
	org.gnome.desktop.background primary-color "#546e7a"
	org.gnome.desktop.background secondary-color "#546e7a"
	org.gnome.desktop.background show-desktop-icons false
	org.gnome.desktop.file-sharing require-password always
	org.gnome.desktop.interface clock-format 12h
	org.gnome.desktop.interface clock-show-date true
	org.gnome.desktop.interface clock-show-seconds true
	org.gnome.desktop.interface document-font-name "$font"
	org.gnome.desktop.interface font-name "$font"
	org.gnome.desktop.interface gtk-theme "Flat-Plat"
	org.gnome.desktop.interface icon-theme "Numix-Circle"
	org.gnome.desktop.interface monospace-font-name "$monospace_font"
	org.gnome.desktop.interface scaling-factor "1"
	org.gnome.desktop.media-handling automount-open false
	org.gnome.desktop.media-handling autorun-never true
	org.gnome.desktop.peripherals.touchpad tap-to-click true
	org.gnome.desktop.privacy hide-identity true
	org.gnome.desktop.privacy old-files-age 7
	org.gnome.desktop.privacy remember-recent-files false
	org.gnome.desktop.privacy remove-old-temp-files true
	org.gnome.desktop.privacy remove-old-trash-files true
	org.gnome.desktop.privacy show-full-name-in-top-bar false
	org.gnome.desktop.screensaver picture-options "wallpaper"
	org.gnome.desktop.screensaver picture-uri "file:////usr/share/gnome-control-center/pixmaps/noise-texture-light.png"
	org.gnome.desktop.screensaver primary-color "#2e3436"
	org.gnome.desktop.screensaver secondary-color "#2e3436"
	org.gnome.desktop.screensaver show-full-name-in-top-bar false
	org.gnome.desktop.search-providers disable-external false
	org.gnome.desktop.search-providers disabled "['gnome-contacts.desktop', 'org.gnome.Photos.desktop', 'seahorse.desktop', 'bijiben.desktop', 'org.gnome.Documents.desktop', 'gnome-boxes.desktop']"
	org.gnome.desktop.session idle-delay 0
	org.gnome.desktop.sound event-sounds false
	org.gnome.desktop.wm.keybindings maximize-horizontally "['<Super><Shift>h']"
	org.gnome.desktop.wm.keybindings maximize-vertically "['<Super><Shift>v']"
	org.gnome.desktop.wm.keybindings minimize "['<Super>x']"
	org.gnome.desktop.wm.keybindings move-to-center "['<Super>KP_5']"
	org.gnome.desktop.wm.keybindings move-to-corner-ne "['<Super>KP_9']"
	org.gnome.desktop.wm.keybindings move-to-corner-nw "['<Super>KP_7']"
	org.gnome.desktop.wm.keybindings move-to-corner-se "['<Super>KP_3']"
	org.gnome.desktop.wm.keybindings move-to-corner-sw "['<Super>KP_1']"
	org.gnome.desktop.wm.keybindings move-to-side-e "['<Super>KP_6']"
	org.gnome.desktop.wm.keybindings move-to-side-n "['<Super>KP_8']"
	org.gnome.desktop.wm.keybindings move-to-side-s "['<Super>KP_2']"
	org.gnome.desktop.wm.keybindings move-to-side-w "['<Super>KP_4']"
	org.gnome.desktop.wm.keybindings move-to-workspace-1 "['<Control><Shift>KP_1']"
	org.gnome.desktop.wm.keybindings move-to-workspace-2 "['<Control><Shift>KP_2']"
	org.gnome.desktop.wm.keybindings move-to-workspace-3 "['<Control><Shift>KP_3']"
	org.gnome.desktop.wm.keybindings move-to-workspace-4 "['<Control><Shift>KP_4']"
	org.gnome.desktop.wm.keybindings move-to-workspace-5 "['<Control><Shift>KP_5']"
	org.gnome.desktop.wm.keybindings move-to-workspace-6 "['<Control><Shift>KP_6']"
	org.gnome.desktop.wm.keybindings move-to-workspace-7 "['<Control><Shift>KP_7']"
	org.gnome.desktop.wm.keybindings move-to-workspace-8 "['<Control><Shift>KP_8']"
	org.gnome.desktop.wm.keybindings move-to-workspace-9 "['<Control><Shift>KP_9']"
	org.gnome.desktop.wm.keybindings switch-to-workspace-1 "['<Control><Alt>KP_1']"
	org.gnome.desktop.wm.keybindings switch-to-workspace-2 "['<Control><Alt>KP_2']"
	org.gnome.desktop.wm.keybindings switch-to-workspace-3 "['<Control><Alt>KP_3']"
	org.gnome.desktop.wm.keybindings switch-to-workspace-4 "['<Control><Alt>KP_4']"
	org.gnome.desktop.wm.keybindings switch-to-workspace-5 "['<Control><Alt>KP_5']"
	org.gnome.desktop.wm.keybindings switch-to-workspace-6 "['<Control><Alt>KP_6']"
	org.gnome.desktop.wm.keybindings switch-to-workspace-7 "['<Control><Alt>KP_7']"
	org.gnome.desktop.wm.keybindings switch-to-workspace-8 "['<Control><Alt>KP_8']"
	org.gnome.desktop.wm.keybindings switch-to-workspace-9 "['<Control><Alt>KP_9']"
	org.gnome.desktop.wm.keybindings panel-run-dialog "['<Super>r']"
	org.gnome.desktop.wm.keybindings show-desktop "['<Super>d']"
	org.gnome.desktop.wm.keybindings switch-input-source "['<Super>space']"
	org.gnome.desktop.wm.keybindings toggle-fullscreen "['<Alt>F11']"
	org.gnome.desktop.wm.keybindings toggle-shaded "['<Alt><Super>space']"
	org.gnome.desktop.wm.preferences action-double-click-titlebar "toggle-maximize"
	org.gnome.desktop.wm.preferences action-middle-click-titlebar "toggle-maximize-vertically"
	org.gnome.desktop.wm.preferences action-right-click-titlebar "menu"
	org.gnome.desktop.wm.preferences focus-mode mouse
	org.gnome.desktop.wm.preferences mouse-button-modifier '<Super>'
	org.gnome.desktop.wm.preferences theme "Flat-Plat"
	org.gnome.desktop.wm.preferences titlebar-font "$font"
	org.gnome.Epiphany keyword-search-url "https://google.com/search?q=%s"
	org.gnome.Epiphany restore-session-policy "crashed"
	org.gnome.eog.view background-color "#000000"
	org.gnome.eog.view trans-color "#000000"
	org.gnome.eog.view transparency color
	org.gnome.eog.view use-background-color true
	org.gnome.GWeather distance-unit km
	org.gnome.GWeather pressure-unit kpa
	org.gnome.GWeather speed-unit kph
	org.gnome.GWeather temperature-unit centigrade
	org.gnome.gedit.plugins active-plugins "['bookmarks', 'bracketcompletion', 'charmap', 'codecomment', 'colorpicker', 'dashboard', 'docinfo', 'drawspaces', 'filebrowser', 'findinfiles', 'joinlines', 'modelines', 'multiedit', 'sort', 'spell', 'terminal', 'textsize', 'time', 'wordcompletion', 'zeitgeist']"
	org.gnome.gedit.plugins.filebrowser filter-mode "['hide-hidden']"
	org.gnome.gedit.plugins.terminal background-color "#333333"
	org.gnome.gedit.plugins.terminal foreground-color "#c5c5c5"
	org.gnome.gedit.plugins.terminal palette "[]"
	org.gnome.gedit.plugins.terminal use-theme-colors false
	org.gnome.gedit.preferences.editor background-pattern "grid"
	org.gnome.gedit.preferences.editor bracket-matching true
	org.gnome.gedit.preferences.editor create-backup-copy false
	org.gnome.gedit.preferences.editor display-line-numbers true
	org.gnome.gedit.preferences.editor display-overview-map true
	org.gnome.gedit.preferences.editor highlight-current-line true
	org.gnome.gedit.preferences.editor scheme oblivion
	org.gnome.gedit.preferences.editor tabs-size 4
	org.gnome.gedit.preferences.ui side-panel-visible true
	org.gnome.gnome-screenshot include-border false
	org.gnome.gnome-screenshot include-pointer false
	org.gnome.gnome-screenshot take-window-shot true
	org.gnome.mutter attach-modal-dialogs true
	org.gnome.nautilus.desktop font "$font"
	org.gnome.nautilus.desktop home-icon-visible false
	org.gnome.nautilus.desktop network-icon-visible false
	org.gnome.nautilus.desktop trash-icon-visible false
	org.gnome.nautilus.desktop volumes-visible false
	org.gnome.nautilus.icon-view default-zoom-level "standard"
	org.gnome.nautilus.list-view default-zoom-level "standard"
	org.gnome.nautilus.list-view use-tree-view true
	org.gnome.nautilus.preferences click-policy single
	org.gnome.nautilus.preferences confirm-trash false
	org.gnome.nautilus.preferences default-folder-viewer "list-view"
	org.gnome.nautilus.preferences default-sort-order type
	org.gnome.nautilus.preferences executable-text-activation ask
	org.gnome.rhythmbox.rhythmdb grace-period 1
	org.gnome.rhythmbox.rhythmdb monitor-library true
	org.gnome.rhythmbox.sources visible-columns "['artist', 'album', 'duration', 'post-time']"
	org.gnome.SessionManager logout-prompt true
	org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom6/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom7/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom8/']"
	org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding '<Super>c'
	org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command gnome-control-center
	org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name "Control Center"
	org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ binding '<Super>e'
	org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ command gedit
	org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ name Editor
	org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/ binding '<Super>f'
	org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/ command nautilus
	org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/ name Files
	org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/ binding '<Super>p'
	org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/ command gnome-photos
	org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/ name Photos
	org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/ binding '<Super>s'
	org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/ command gnome-search-tool
	org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/ name Search
	org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/ binding '<Super>t'
	org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/ command gnome-terminal
	org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/ name Terminal
	org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom6/ binding '<Super>v'
	org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom6/ command totem
	org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom6/ name Videos
	org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom7/ binding '<Super>w'
	org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom7/ command x-www-browser
	org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom7/ name Web
	org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom8/ binding '<Primary><Shift>x'
	org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom8/ command xkill
	org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom8/ name Kill
	org.gnome.settings-daemon.plugins.power active true
	org.gnome.settings-daemon.plugins.power ambient-enabled false
	org.gnome.settings-daemon.plugins.power power-button-action shutdown
	org.gnome.settings-daemon.plugins.power idle-dim false
	org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout 0
	org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type blank
	org.gnome.settings-daemon.plugins.power sleep-inactive-battery-timeout 0
	org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type blank
	org.gnome.settings-daemon.plugins.xrandr default-monitors-setup do-nothing
	org.gnome.settings-daemon.plugins.xrandr priority 0
	org.gnome.settings-daemon.plugins.xsettings antialiasing rgba
	org.gnome.settings-daemon.plugins.xsettings hinting full
	org.gnome.shell command-history "[]"
	org.gnome.shell disable-extension-
	org.gnome.shell enabled-extensions "['gTile@vibou', 'hidetopbar@mathieu.bidon.ca', 'mediaplayer@patapon.info', 'user-theme@gnome-shell-extensions.gcampax.github.com']"
	org.gnome.shell favorite-apps "[]"
	org.gnome.shell.keybindings focus-active-notification "['<Super>n']"
	org.gnome.shell.keybindings open-application-menu "['<Super>F10']"
	org.gnome.shell.keybindings pause-resume-tweens "[]"
	org.gnome.shell.keybindings toggle-application-view "['<Super>a']"
	org.gnome.shell.keybindings toggle-message-tray "['<Super>m']"
	org.gnome.shell.keybindings toggle-overview "['<Super>s']"
	org.gnome.shell.overrides workspaces-only-on-primary false
	org.gnome.totem subtitle-font 'Sans 10'
	org.gtk.Settings.FileChooser clock-format 12h
)

# gnome-terminal #

gnome_terminal_settings_list=(
	"org.gnome.Terminal.Legacy.Settings default-show-menubar" false
	"org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$terminal_profile/" background-color 'rgb(84,110,122)' #546e7a
	"org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$terminal_profile/" foreground-color 'rgb(255,255,255)' #ffffff
	"org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$terminal_profile/" scroll-on-output true
	"org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$terminal_profile/" scrollbar-policy "never"
	"org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$terminal_profile/" use-theme-colors false
	"org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$terminal_profile/" visible-name 'Terminal'
)

for setting in ${gnome_terminal_settings_list[@]}
do
	gsettings set ${setting}
done

# gdm #

xhost + > /dev/null

sudo su gdm -s /bin/bash << FILE

gdm_settings_list=(
	org.gnome.desktop.background picture-options "zoom"
	org.gnome.desktop.background picture-uri ""
	org.gnome.desktop.background primary-color "#546e7a"
	org.gnome.desktop.background secondary-color "#546e7a"
	org.gnome.desktop.interface icon-theme "Numix-Circle"
	org.gnome.desktop.interface scaling-factor "1"
)

for setting in ${gdm_settings_list[@]}
do
	gsettings set ${setting}
done
FILE

xhost - > /dev/null
