#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# identifiy #

# dependencies #

curl -sL dep.dxtp.app/console > /usr/bin/console && source /usr/bin/console

# configuration #

console.inf "Current user name is: "${SUDO_USER:-$USER}"..."

sleep 3
