#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# identifiy #

# dependencies #

source ./console

# configuration #

console.info "Current user name is: "${SUDO_USER:-$USER}"..."

sleep 3
