#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# install local #

# dependencies #

curl -sL dep.dxtp.app/console > /usr/bin/console && source /usr/bin/console

# variables #

# Enable quiet package install

export DEBIAN_FRONTEND=noninteractive

# install local #

console.inf "Installing local packages..."

if [ -d ./deb ]
then
	for package in ./deb/*.deb
	do
		echo yes | apt install "${package}"
	done
else
	console.wrn "No local packages to install. Continuing..."
fi