#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# lxd qt #

# dependencies #

curl -sL dep.dxtp.app/console > /usr/bin/console && source /usr/bin/console

# variables #

# configuration #

console.inf "Setting additional environment variables."

cat << 'FILE' >> /etc/environment

# fix memory segment allocation in lxd containers for qt applications #

export QT_X11_NO_MITSHM=1
export QT_GRAPHICSSYSTEM=native
FILE
