#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# lxd qt #

# dependencies #

source ./console

# variables #

home="/home/${SUDO_USER:-$USER}"
environment_directory="/etc/environment"

# configuration #

console.info "Setting additional environment variables..."

cat << 'FILE' >> "$environment_directory"

# fix memory segment allocation in lxd containers for qt applications #

export QT_X11_NO_MITSHM=1
export QT_GRAPHICSSYSTEM=native
FILE
