#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# mount #

# dependencies #

# variables #

mount_file="/etc/fstab"
mount_root="/media"

# defaults #

# configuration #

# verify attached devices and generate mount entries

for device in /dev/sd[a-z][1-9]
do
	mount=$(df -H "$device" | awk 'END{print $6}')
	release=$(cat /etc/os-release | awk -F '=' '{if (NR==1) print $2}')

	type=$(blkid -s TYPE -o value "$device")
	label=$(blkid -s LABEL -o value "$device")
	uuid=$(blkid -s UUID -o value "$device")

	# efi #

	if [[ "$label" == [eE][fF][iI] || "$type" = [vV][fF][aA][tT] || "$type" = [eE][fF][iI] ]]
	then
		continue
	fi

	# os #

	if [[ "$label" == [uU][bB][uU][nN][tT][uU] ]]
	then
		e2label "$mount_directory" "$release"

		continue
	fi

	# os #

	if [[ "$label" == [wW][iI][nN][dD][oO][wW][sS] ]]
	then
		: # pass
	fi

	# external #

	if [[ "$label" == [bB][aA][cK][uU][pP] ]]
	then
		: # pass
	fi

	# create mount directories

	for directory in "$label"
	do
		if [[ ! -d "$mount_root/$label" ]]
		then
			mkdir -p "$mount_root/$label"
		fi
	done

	# create mount entries

	if [[ "$type" = ext[2-4] ]]
	then
		echo "UUID="$uuid" $mount_root/${label//[[:blank:]]/_} "$type" rw,defaults 0 2"
	fi
done >> "$mount_file"

# fix fstab entries formatting

sed -i				\
	-e 's/  */ /g'	\
	-e '/#.*/d' 	\
					"$mount_file"

# mount partitions

sudo mount -a
