#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# permissions #

# dependencies #

curl -sL dep.dxtp.app/console > /usr/bin/console && source /usr/bin/console

# configuration #

directory_list=(

)

for directory in ${directory_list[@]}
do
	console.inf "Setting permissions ($directory)..."

	cd "$directory" || exit

	chmod -R 777 *
done
