#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# purge #

# dependencies #

source ./console

# variables #

# Enable quiet package install

export DEBIAN_FRONTEND=noninteractive

# purge #

console.info "Purging unwanted packages from system..."

purge_list=(

)

for package in ${purge_list[@]}
do
	console.info "Purging ${package} and applicable dependencies..."

	echo yes | apt purge ${package}
done

# remove orphaned items #

console.info "Purging orphaned package items from system..."

echo yes | apt autoremove