#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# purge #

# dependencies #

# dependencies #  curl -sL dep.dxtp.app/console > /usr/bin/console && source /usr/bin/console

# variables #

# Enable quiet package install

export DEBIAN_FRONTEND=noninteractive

# purge #

console.inf "Purging unwanted packages from system..."

purge_list=(

)

for package in ${purge_list[@]}
do
	console.inf "Purging ${package} and applicable dependencies..."

	echo yes | apt purge ${package}
done

# remove orphaned items #

console.inf "Purging orphaned package items from system..."

echo yes | apt autoremove