#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# reboot #

# dependencies #

curl -sL dep.dxtp.app/console > /usr/bin/console && source /usr/bin/console

# configuration #

console.question "Would you like to reboot the system to finalize the setup?"

read reply

if [[ "$reply" = [yY] || "$reply" = [yY][eE][sS] ]]
then
	reboot
fi
