#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# repositories #

# dependencies #

curl -sL get.cnsl.app/console> /usr/bin/console && . /usr/bin/console

# variables #

# enable all repositories

sed -i -e '/#.*/d' /etc/apt/sources.list

# update #

apt update

# upgrade #

apt upgrade