#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# repositories #

# dependencies #

# variables #

# enable all repositories

sed -i -e '/#.*/d' /etc/apt/sources.list

# update #

apt-get update

# upgrade #

apt-get upgrade