#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# root #

# dependencies #

curl -sL dep.dxtp.app/console > /usr/bin/console && source /usr/bin/console

# variables #

user_id=$(id -u)
user_name=$(id -u -n)

# identify #

console.inf "Verifying superuser access rights..."

if [[ "${user_id}" != 0 ]]
then
	console.inf "Please enter ${user_name} password..."

	sudo -s
else
	console.inf "Already ${user_name} on "$HOSTNAME". Proceeding..."

	exit
fi
