#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# sensors #

# dependencies #

# dependencies #  curl -sL dep.dxtp.app/console > /usr/bin/console && source /usr/bin/console

# variables #

# Enable quiet package install

export DEBIAN_FRONTEND=noninteractive

# install #

install_list=(
	lm-sensors
)

for package in ${install_list[@]}
do
	console.inf "Installing ${package} and applicable dependencies..."

	echo yes | apt install ${package}
done

# sensors setup #

console.inf "Writing configuration (${install_list[0]})..."

sensors-detect --auto