#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# setup #

# dependencies #

# dependencies #  curl -sL dep.dxtp.app/console > /usr/bin/console && source /usr/bin/console

# variables #

# configuration #

console.inf "Configuring system..."

scripts_list=(

)

for script in ${scripts_list[@]}
do
	bash ${script}
done

console.success "Setup complete."
echo