#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# storage link #

# dependencies #

# dependencies #  curl -sL dep.dxtp.app/console > /usr/bin/console && source /usr/bin/console

# configuration #

console.inf "Linking storage devices..."

ln -s -f /media/${SUDO_USER:-$USER}/SD/MEGA /media/Internal/MEGA