#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# style qt4 #

# dependencies #

curl -sL dep.dxtp.app/console > /usr/bin/console && source /usr/bin/console

# variables #

# configuration #

if [ ! -e "${HOME}"/.config ]
then
	mkdir "${HOME}"/.config
fi

# configuration #

console.inf "Adding style configuration parameters."

cat << 'FILE' > "${HOME}"/.config/Trolltech.conf
[Qt]

style=GTK+
FILE

# link configuration file for GTK 3+ setup

ln -s -f "${HOME}"/.config/Trolltech.conf "${HOME}"/.config/gtk-3.0/Trolltech.conf
