#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# qt5 style #

# dependencies #

# variables #

# install required packages

install_list=(
	qt5-style-plugins
)

for package in  ${install_list[@]}
do
	yes | apt-get install --no-install-recommends "${package}"
done

# write configuration

cat << 'FILE' >> /etc/environment

# fix themeing compliance for qt5 applications #

QT_QPA_PLATFORMTHEME=gtk2
FILE
