#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# style qt4 #

# dependencies #

curl -sL dep.dxtp.app/console > /usr/bin/console && source /usr/bin/console

# variables #

home="/home/${SUDO_USER:-$USER}"
configuration_directory="${HOME}"/.config
gtk_configuration_directory="$configuration_directory/gtk-3.0"

# configuration #

if [ ! -e "${HOME}"/.config ]
then
	mkdir "${HOME}"/.config
fi

# configuration #

console.inf "Adding styles configuration parameters (Qt)..."

cat << 'FILE' > "${HOME}"/.config/Trolltech.conf
[Qt]

style=GTK+
FILE

# Link configuration file for GTK 3+ setup

ln -s -f "${HOME}"/.config/Trolltech.conf "$gtk_configuration_directory"/Trolltech.conf
