#!/bin/bash

# dependencies #

[[ -z $(command -v frobulate ]] && curl -s -L get.frbltr.app > "${PREFIX}"/bin/frobulator

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

# usage #

# prompt #

# variables #

# defaults #

install_list=(
	qt5-style-plugins
)

for package in  ${install_list[@]}
do
	yes | apt-get install --no-install-recommends "${package}"
done


cat << 'FILE' >> /etc/environment

# fix theme compliance for qt5 applications #

QT_QPA_PLATFORMTHEME=gtk2
FILE
