#!/bin/bash

# dependencies #

curl -sL get.trmnl.me/frobulate.console > "${PREFIX}"/bin/console && . "${PREFIX}"/bin/console

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

# usage #

# prompt #

# variables #

# defaults #

if [ ! -e "${HOME}"/.config ]
then
	mkdir "${HOME}"/.config
fi

cat << 'FILE' > "${HOME}"/.config/Trolltech.conf
[Qt]

style=GTK+
FILE

ln -s -f "${HOME}"/.config/Trolltech.conf "${HOME}"/.config/gtk-3.0/Trolltech.conf
