#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# qt5 style #

# dependencies #

curl -sL dep.dxtp.app/console > /usr/bin/console && source /usr/bin/console

# variables #

# install #

console.inf "Installing required packages and utilities..."

install_list=(
	qt5-style-plugins
)

console.install ${install_list[@]}

# create configuration #

console.inf "Adding style configuration parameter."

cat << 'FILE' >> /etc/environment

# fix themeing compliance for qt5 applications #

QT_QPA_PLATFORMTHEME=gtk2
FILE
