#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# upgrade #

# dependencies #

# dependencies #  curl -sL dep.dxtp.app/console > /usr/bin/console && source /usr/bin/console

# variables #

# Enable quiet package install

export DEBIAN_FRONTEND=noninteractive

# Enable all repositories

console.inf "Editing sources list..."

sed -i -e '/#.*/d' /etc/apt/sources.list

# upgrade #

console.inf "Updating package list..."

apt update

console.inf "Upgrading installed packages..."

echo yes | apt upgrade