#!/bin/bash

# uncomment if using 'dbus-launch'

# unset DBUS_SESSION_BUS_ADDRESS
# unset SESSION_MANAGER

if [ ! -z "${APPLICATION}" ]
then
	"${SETTINGS_MANAGER}" &
	"${WINDOW_MANAGER}" &
	"${APPLICATION}" &
else
	"${SESSION_LOADER}" &
	"${WINDOW_MANAGER}" &
fi

if [ -z $(pgrep -x "${RUNNER}") ]
then
	"${RUNNER}" -d &
fi