#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# dependencies #

curl -sL dep.dxtp.app/console > /usr/bin/console && source /usr/bin/console

# variables #

home="/home/${SUDO_USER:-$USER}"

console.info "Setting up openbox window manager."

install_list=(
	feh
	obconf
	obmenu
	openbox
	synapse
	tint2
	volumeicon
	xcompmgr
)

console.install ${install_list[@]}

# configuration #

'./openbox-configuration'
'./openbox-icons'
'./openbox-panel'
'./openbox-startup'
'./openbox-theme-dark'
'./openbox-theme-light'
'./openbox-volume'

# pipe menu #

console.info "Adding pipe menu entries."

if [ ! -d "${HOME}"/.config/pipe ]
then
	mkdir -p "${HOME}"/.config/pipe
fi

pipes_list=(
	openbox-background
	openbox-calendar
	openbox-theme
)

for pipe in ${pipes_list[@]}
do
	cp -r -f "$pipe" "${HOME}"/.config/pipe

	cd "${HOME}"/.config/pipe || exit

	sudo chmod +x "$pipe"
done

# disable gnome shell execution rights

sudo chmod -x /usr/bin/gnome-shell

