#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com - Copyright 2014

# openbox #

home="/home/${SUDO_USER:-$USER}"

echo "${cyan}Would you like to install the Openbox window manager (openbox)? [ Yes | No ]${reset}"

read reply

if [[ "$reply" = [yY] || "$reply" = [yY][eE][sS] ]]
then
	# openbox packages #

	for package in \
	feh \
	obconf \
	obmenu \
	openbox \
	synapse \
	tint2 \
	volumeicon \
	xcompmgr
	do
		dnf -y install "$package"
	done

	# configuration #

	'./openbox-configuration'
	'./openbox-icons'
	'./openbox-panel'
	'./openbox-startup'
	'./openbox-theme-dark'
	'./openbox-theme-light'
	'./openbox-volume'

	# pipe menu #

	echo "${cyan}Adding pipe menu entries...${reset}"

	if [ ! -d "${HOME}"/.config/pipe ]
	then
		mkdir -p "${HOME}"/.config/pipe
	fi

	for file in \
	openbox-background \
	openbox-calendar \
	openbox-theme
	do
		cp -r -f "$file" "${HOME}"/.config/pipe

		cd "${HOME}"/.config/pipe || exit

		sudo chmod +x "$file"
	done

	sudo chmod -x /usr/bin/gnome-shell
else
	continue
fi
