#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# openbox startup #

home="/home/${SUDO_USER:-$USER}"

if [ ! -d "${HOME}"/.config/autostart ]
then
	mkdir "${HOME}"/.config/autostart
fi

console.inf "Adding Openbox startup items."

cd /etc/xdg/autostart || exit

# background #

cat > /etc/xdg/autostart/feh.desktop << 'FILE'
[Desktop Entry]
Type=Application
Exec=bash -c "eval $(cat $HOME/.fehbg) &"
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name=Background
Comment=Start feh background display
FILE


# compositing #

cat > /etc/xdg/autostart/xcompmgr.desktop << FILE
[Desktop Entry]
Type=Application
Exec=bash -c "sleep 5 && xcompmgr &"
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name=Compositing
Comment=Start xcompmgr desktop compositor
FILE

# openbox #

cat > /etc/xdg/autostart/openbox.desktop << FILE
[Desktop Entry]
Type=Application
Exec=openbox --replace
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name=Openbox
Comment=Start Openbox window manager
FILE

# panel #

cat > /etc/xdg/autostart/tint.desktop << FILE
[Desktop Entry]
Type=Application
Exec=tint2 -c /home/"${SUDO_USER:-$USER}"/.config/tint2/tint2rc
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name=Panel
Comment=Openbox panel and notification area
FILE

# volume #

cat > /etc/xdg/autostart/volumeicon.desktop << FILE
[Desktop Entry]
Type=Application
Exec=volumeicon
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name=Volume
Comment=Openbox volume control
FILE
