#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# dependencies #

curl -sL dep.dxtp.app/console > /usr/bin/console && source /usr/bin/console

# variables #

# functions #

function row() {
	cal | gawk -v row=$1 '{ if (NR==row) { print $0 } }'
}

# show calendar

cat << MENU
<openbox_pipe_menu>
<separator label="`date +%A\ %I\:%M\ %p`" />
<item label="[ `date +%B\ %d,\ %Y` ]" />
<separator />
<item label="`row 2`" />
<item label="`row 3`" />
<item label="`row 4`" />
<item label="`row 5`" />
<item label="`row 6`" />
<item label="`row 7`" />
<item label="`row 8`" />
</openbox_pipe_menu>
MENU
