#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# dependencies #

curl -sL dep.dxtp.app/console > /usr/bin/console && source /usr/bin/console

# variables #

console.inf "Generating Openbox volume configuration file."

if [ ! -d "${HOME}"/.config/openbox/volumeicon ]
then
	mkdir -p "${HOME}"/.config/openbox/volumeicon
fi

cd "${HOME}"/.config/openbox/volumeicon || exit

cat << 'FILE' > "${HOME}"/.config/openbox/volumeicon/volumeicon
[StatusIcon]
stepsize=5
lmb_slider=true
mmb_mute=false
use_horizontal_slider=false
show_sound_level=false
onclick=gnome-control-center sound
theme=Default

[Hotkeys]
up_enabled=true
down_enabled=true
mute_enabled=true
up=XF86AudioRaiseVolume
down=XF86AudioLowerVolume
mute=XF86AudioMute

[Alsa]
card=default
FILE
