#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# dependencies #

curl -sL dep.dxtp.app/console > /usr/bin/console && source /usr/bin/console

# variables #

home="/home/${SUDO_USER:-$USER}"

if [ ! -d "${HOME}"/.config/openbox ]
then
	mkdir -p "${HOME}"/.config/openbox
fi

cd "${HOME}"/.config/openbox || exit

console.inf "Generating Openbox 'autostart' file."

cat << 'FILE' > "${HOME}"/.config/openbox/autostart
# autostart #

# background color #

background=""

if which hsetroot > /dev/null
then
	background=hsetroot
else
	if which esetroot >/dev/null
	then
		background=esetroot
	else
		if which xsetroot >/dev/null
		then
			background=xsetroot
		fi
	fi
fi

test -z "$background" || "$background" -solid "#202020"

# gnome settings daemon #

if test -x /usr/libexec/gnome-settings-daemon > /dev/null
then
	/usr/libexec/gnome-settings-daemon &

elif which gnome-settings-daemon > /dev/null
then
	gnome-settings-daemon &
fi
FILE

# menu #

console.inf "Generating Openbox 'menu' file."

catl << 'FILE' > "${HOME}"/.config/openbox/menu.xml
<?xml version="1.0" encoding="utf-8"?>
<openbox_menu xmlns="http://openbox.org/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://openbox.org/ file:///usr/share/openbox/menu.xsd">
<menu id="root-menu" label="Openbox 3">
<item label="Files">
<action name="Execute">
<execute>nautilus</execute>
</action>
</item>
<menu id="root-menu-112526" label="Folders">
<item label="Desktop">
<action name="Execute">
<execute>nautilus Desktop</execute>
</action>
</item>
<item label="Documents">
<action name="Execute">
<execute>nautilus Documents</execute>
</action>
</item>
<item label="Downloads">
<action name="Execute">
<execute>nautilus Downloads</execute>
</action>
</item>
<item label="Music">
<action name="Execute">
<execute>nautilus Music</execute>
</action>
</item>
<item label="Pictures">
<action name="Execute">
<execute>nautilus Pictures</execute>
</action>
</item>
<item label="Public">
<action name="Execute">
<execute>nautilus Public</execute>
</action>
</item>
<item label="Templates">
<action name="Execute">
<execute>nautilus Templates</execute>
</action>
</item>
<item label="Videos">
<action name="Execute">
<execute>nautilus Videos</execute>
</action>
</item>
<separator/>
<item label="Dropbox">
<action name="Execute">
<execute>nautilus /media/Disk/Dropbox</execute>
</action>
</item>
<item label="Infinity [ FTP ]">
<action name="Execute">
<execute>nautilus ftp://192.168.2.20:2121/</execute>
</action>
</item>
<item label="Mako [ FTP ]">
<action name="Execute">
<execute>nautilus ftp://192.168.2.21:2121/</execute>
</action>
</item>
</menu>
<item label="Index">
<action name="Execute">
<execute>synapse</execute>
</action>
</item>
<item label="IRC">
<action name="Execute">
<execute>gnome-terminal --command 'irssi -c irc.freenode.net -n nathaneltitane -w PASSWORD'</execute>
</action>
</item>
<menu id="root-menu-773347" label="Lego">
<item label="LDView [ Intel ]">
<action name="Execute">
<execute>/usr/bin/LDView</execute>
</action>
</item>
<item label="LDView [ Nvidia ]">
<action name="Execute">
<execute>optirun /usr/bin/LDView</execute>
</action>
</item>
<item label="MLCad">
<action name="Execute">
<execute>wine /media/Disk/Dropbox/Lego/MLCAD/MLCAD.exe</execute>
</action>
</item>
</menu>
<item label="Messaging">
<action name="Execute">
<execute>empathy</execute>
</action>
</item>
<item label="Music">
<action name="Execute">
<execute>rhythmbox</execute>
</action>
</item>
<item label="Pictures">
<action name="Execute">
<execute>eog</execute>
</action>
</item>
<item label="Terminal">
<action name="Execute">
<execute>gnome-terminal</execute>
</action>
</item>
<item label="Text">
<action name="Execute">
<execute>gedit</execute>
</action>
</item>
<item label="Video">
<action name="Execute">
<execute>totem</execute>
</action>
</item>
<menu id="root-menu-972624" label="Web">
<menu id="root-menu-972624-422629" label="Firefox">
<item label="Firefox [ Intel ]">
<action name="Execute">
<execute>firefox</execute>
</action>
</item>
<item label="Firefox [ Nvidia ]">
<action name="Execute">
<execute>optirun firefox</execute>
</action>
</item>
</menu>
<menu id="root-menu-972624-952627" label="Google Chrome">
<item label="Google Chrome [ Intel ]">
<action name="Execute">
<execute>google-chrome</execute>
</action>
</item>
<item label="Google Chrome [ Nvidia ]">
<action name="Execute">
<execute>optirun google-chrome</execute>
</action>
</item>
</menu>
</menu>
<separator/>
<menu execute="sh /home/nathanel/.config/openbox/pipe/openbox-calendar" id="pipe-01" label="Calendar"/>
<!-- This requires the presence of the 'menu' package to work -->
<separator/>
<menu id="client-list-menu"/>
<separator/>
<menu id="system" label="System">
<menu id="system-61231" label="CPU Governors">
<item label="Conservative">
<action name="Execute">
<execute>/usr/bin/conservative</execute>
</action>
</item>
<item label="Ondemand">
<action name="Execute">
<execute>/usr/bin/ondemand</execute>
</action>
</item>
<item label="Performance">
<action name="Execute">
<execute>/usr/bin/performance</execute>
</action>
</item>
<item label="Powersave">
<action name="Execute">
<execute>/usr/bin/powersave</execute>
</action>
</item>
</menu>
<separator/>
<item label="Control Center">
<action name="Execute">
<execute>sudo gnome-control-center</execute>
</action>
</item>
<item label="Firewall">
<action name="Execute">
<execute>sudo firewall-config</execute>
</action>
</item>
<item label="Software">
<action name="Execute">
<execute>sudo gpk-application</execute>
</action>
</item>
<separator/>
<item label="Background">
<action name="Execute">
<execute>sh /home/nathanel/.config/openbox/pipe/openbox-background</execute>
</action>
</item>
<menu execute="sh /home/nathanel/.config/openbox/pipe/openbox-theme" id="pipe-02" label="Theme"/>
<separator/>
<item label="Configuration">
<action name="Execute">
<execute>obconf</execute>
</action>
</item>
<item label="Menu">
<action name="Execute">
<execute>obmenu</execute>
</action>
</item>
<separator/>
<item label="Update">
<action name="Execute">
<execute>gnome-terminal --command 'sudo yum check-update'</execute>
</action>
</item>
<item label="Upgrade">
<action name="Execute">
<execute>gnome-terminal --command 'sudo yum -y upgrade'</execute>
</action>
</item>
</menu>
<separator/>
<item label="Reconfigure">
<action name="Reconfigure"/>
</item>
<item label="Reload">
<action name="Restart"/>
</item>
<separator/>
<item label="Kill">
<action name="Execute">
<execute>xkill</execute>
</action>
</item>
<separator/>
<item label="Log Out">
<action name="Execute">
<execute>gnome-session-quit --logout</execute>
</action>
</item>
<item label="Power Off">
<action name="Execute">
<execute>gnome-session-quit --power-off</execute>
</action>
</item>
<item label="Restart">
<action name="Execute">
<execute>gnome-session-quit --reboot</execute>
</action>
</item>
</menu>
</openbox_menu>
FILE

# configuration #

console.inf "Generating Openbox configuration 'rc' file."

cat << 'FILE' > "${HOME}"/.config/openbox/rc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Do not edit this file, it will be overwritten on install.
Copy the file to $HOME/.config/openbox/ instead. -->
<openbox_config xmlns="http://openbox.org/3.4/rc" xmlns:xi="http://www.w3.org/2001/XInclude">
<resistance>
<strength>50</strength>
<screen_edge_strength>50</screen_edge_strength>
</resistance>
<focus>
<focusNew>yes</focusNew>
<!-- always try to focus new windows when they appear. other rules do
apply -->
<followMouse>yes</followMouse>
<!-- move focus to a window when you move the mouse into it -->
<focusLast>yes</focusLast>
<!-- focus the last used window when changing desktops, instead of the one
under the mouse pointer. when followMouse is enabled -->
<underMouse>no</underMouse>
<!-- move focus under the mouse, even when the mouse is not moving -->
<focusDelay>200</focusDelay>
<!-- when followMouse is enabled, the mouse must be inside the window for
this many milliseconds (1000 = 1 sec) before moving focus to it -->
<raiseOnFocus>no</raiseOnFocus>
<!-- when followMouse is enabled, and a window is given focus by moving the
mouse into it, also raise the window -->
</focus>
<placement>
<policy>Smart</policy>
<!-- 'Smart' or 'UnderMouse' -->
<center>yes</center>
<!-- whether to place windows in the center of the free area found or
the top left corner -->
<monitor>Any</monitor>
<!-- with Smart placement on a multi-monitor system, try to place new windows
on: 'Any' - any monitor, 'Mouse' - where the mouse is, 'Active' - where
the active window is, 'Primary' - only on the primary monitor -->
<primaryMonitor>1</primaryMonitor>
<!-- The monitor where Openbox should place popup dialogs such as the
focus cycling popup, or the desktop switch popup.It can be an index
from 1, specifying a particular monitor.Or it can be one of the
following: 'Mouse' - where the mouse is, or
'Active' - where the active window is -->
</placement>
<theme>
<name>Light</name>
<titleLayout>CMILSD</titleLayout>
<!--
available characters are NDSLIMC, each can occur at most once.
N: window icon
L: window label (AKA title).
I: iconify
M: maximize
C: close
S: shade (roll up/down)
D: omnipresent (on all desktops).
-->
<keepBorder>yes</keepBorder>
<animateIconify>no</animateIconify>
<font place="ActiveWindow">
<name>Liberation Sans</name>
<size>9</size>
<!-- font size in points -->
<weight>normal</weight>
<!-- 'normal' or 'normal' -->
<slant>normal</slant>
<!-- 'italic' or 'normal' -->
</font>
<font place="InactiveWindow">
<name>Liberation Sans</name>
<size>9</size>
<!-- font size in points -->
<weight>normal</weight>
<!-- 'normal' or 'normal' -->
<slant>normal</slant>
<!-- 'italic' or 'normal' -->
</font>
<font place="MenuHeader">
<name>Liberation Sans</name>
<size>9</size>
<!-- font size in points -->
<weight>normal</weight>
<!-- 'normal' or 'normal' -->
<slant>normal</slant>
<!-- 'italic' or 'normal' -->
</font>
<font place="MenuItem">
<name>Liberation Sans</name>
<size>9</size>
<!-- font size in points -->
<weight>normal</weight>
<!-- 'normal' or 'normal' -->
<slant>normal</slant>
<!-- 'italic' or 'normal' -->
</font>
<font place="ActiveOnScreenDisplay">
<name>Liberation Sans</name>
<size>9</size>
<!-- font size in points -->
<weight>normal</weight>
<!-- 'normal' or 'normal' -->
<slant>normal</slant>
<!-- 'italic' or 'normal' -->
</font>
<font place="InactiveOnScreenDisplay">
<name>Liberation Sans</name>
<size>9</size>
<!-- font size in points -->
<weight>normal</weight>
<!-- 'normal' or 'normal' -->
<slant>normal</slant>
<!-- 'italic' or 'normal' -->
</font>
</theme>
<desktops>
<!-- this stuff is only used at startup, pagers allow you to change them
during a session

these are default values to use when other ones are not already set
by other applications, or saved in your session

use obconf if you want to change these without having to log out
and back in -->
<number>8</number>
<firstdesk>1</firstdesk>
<names>
<name>[ 1 ]</name>
<name>[ 2 ]</name>
<name>[ 3 ]</name>
<name>[ 4 ]</name>
<name>[ 5 ]</name>
<name>[ 6 ]</name>
<name>[ 7 ]</name>
<name>[ 8 ]</name>
</names>
<popupTime>0</popupTime>
<!-- The number of milliseconds to show the popup for when switching
desktops.Set this to 0 to disable the popup. -->
</desktops>
<resize>
<drawContents>yes</drawContents>
<popupShow>Nonpixel</popupShow>
<!-- 'Always', 'Never', or 'Nonpixel' (xterms and such) -->
<popupPosition>Center</popupPosition>
<!-- 'Center', 'Top', or 'Fixed' -->
<popupFixedPosition>
<!-- these are used if popupPosition is set to 'Fixed' -->
<x>10</x>
<!-- positive number for distance from left edge, negative number for
 distance from right edge, or 'Center' -->
<y>10</y>
<!-- positive number for distance from top edge, negative number for
 distance from bottom edge, or 'Center' -->
</popupFixedPosition>
</resize>
<!-- You can reserve a portion of your screen where windows will not cover when
 they are maximized, or when they are initially placed.
 Many programs reserve space automatically, but you can use this in other
 cases. -->
<margins>
<top>0</top>
<bottom>0</bottom>
<left>0</left>
<right>0</right>
</margins>
<dock>
<position>TopLeft</position>
<!-- (Top|Bottom)(Left|Right|)|Top|Bottom|Left|Right|Floating -->
<floatingX>0</floatingX>
<floatingY>0</floatingY>
<noStrut>yes</noStrut>
<stacking>Below</stacking>
<!-- 'Above', 'Normal', or 'Below' -->
<direction>Vertical</direction>
<!-- 'Vertical' or 'Horizontal' -->
<autoHide>no</autoHide>
<hideDelay>300</hideDelay>
<!-- in milliseconds (1000 = 1 second) -->
<showDelay>300</showDelay>
<!-- in milliseconds (1000 = 1 second) -->
<moveButton>Middle</moveButton>
<!-- 'Left', 'Middle', 'Right' -->
</dock>
<keyboard>
<chainQuitKey>C-g</chainQuitKey>
<!-- Keybindings for desktop switching -->
<keybind key="C-A-Left">
<action name="GoToDesktop">
<to>left</to>
<wrap>no</wrap>
</action>
</keybind>
<keybind key="C-A-Right">
<action name="GoToDesktop">
<to>right</to>
<wrap>no</wrap>
</action>
</keybind>
<keybind key="C-A-Up">
<action name="GoToDesktop">
<to>up</to>
<wrap>no</wrap>
</action>
</keybind>
<keybind key="C-A-Down">
<action name="GoToDesktop">
<to>down</to>
<wrap>no</wrap>
</action>
</keybind>
<keybind key="C-S-Left">
<action name="GrowToEdge">
<direction>west</direction>
</action>
</keybind>
<keybind key="C-S-Right">
<action name="GrowToEdge">
<direction>east</direction>
</action>
</keybind>
<keybind key="C-S-Up">
<action name="GrowToEdge">
<direction>north</direction>
</action>
</keybind>
<keybind key="C-S-Down">
<action name="GrowToEdge">
<direction>south</direction>
</action>
</keybind>
<keybind key="S-A-Left">
<action name="SendToDesktop">
<to>left</to>
<wrap>no</wrap>
</action>
</keybind>
<keybind key="S-A-Right">
<action name="SendToDesktop">
<to>right</to>
<wrap>no</wrap>
</action>
</keybind>
<keybind key="S-A-Up">
<action name="SendToDesktop">
<to>up</to>
<wrap>no</wrap>
</action>
</keybind>
<keybind key="S-A-Down">
<action name="SendToDesktop">
<to>down</to>
<wrap>no</wrap>
</action>
</keybind>
<keybind key="W-F1">
<action name="GoToDesktop">
<to>1</to>
</action>
</keybind>
<keybind key="W-F2">
<action name="GoToDesktop">
<to>2</to>
</action>
</keybind>
<keybind key="W-F3">
<action name="GoToDesktop">
<to>3</to>
</action>
</keybind>
<keybind key="W-F4">
<action name="GoToDesktop">
<to>4</to>
</action>
</keybind>
<keybind key="W-d">
<action name="ToggleShowDesktop"/>
</keybind>
<!-- Keybindings for window tiling -->
<keybind key="A-F4">
<action name="Close"/>
</keybind>
<keybind key="A-Escape">
<action name="Lower"/>
<action name="FocusToBottom"/>
<action name="Unfocus"/>
</keybind>
<keybind key="A-space">
<action name="ShowMenu">
<menu>client-menu</menu>
</action>
</keybind>
<keybind key="W-Down">
<action name="Unmaximize"/>
</keybind>
<keybind key="W-Up">
<action name="Maximize"/>
</keybind>
<keybind key="W-Left">
<action name="UnmaximizeFull"/>
<action name="MaximizeVert"/>
<action name="MoveResizeTo">
<x>0</x>
<y>0</y>
<width>50%</width>
</action>
</keybind>
<keybind key="W-Right">
<action name="UnmaximizeFull"/>
<action name="MaximizeVert"/>
<action name="MoveResizeTo">
<x>-0</x>
<y>0</y>
<width>50%</width>
</action>
</keybind>
<keybind key="W-numbersign">
<action name="MoveResizeTo">
<width>800</width>
<height>600</height>
</action>
</keybind>
<keybind key="W-8">
<action name="UnmaximizeFull"/>
<action name="MoveResizeTo">
<x>0</x>
<y>0</y>
<width>100%</width>
<height>50%</height>
</action>
</keybind>
<keybind key="W-5">
<action name="UnmaximizeFull"/>
<action name="MoveResizeTo">
<x>center</x>
<y>center</y>
<width>50%</width>
<height>50%</height>
</action>
</keybind>
<keybind key="W-2">
<action name="UnmaximizeFull"/>
<action name="MoveResizeTo">
<x>0</x>
<y>-0</y>
<width>100%</width>
<height>50%</height>
</action>
</keybind>
<keybind key="W-1">
<action name="UnmaximizeFull"/>
<action name="MoveResizeTo">
<x>0</x>
<y>-0</y>
<width>50%</width>
<height>50%</height>
</action>
</keybind>
<keybind key="W-4">
<action name="UnmaximizeFull"/>
<action name="MoveResizeTo">
<x>0</x>
<y>center</y>
<width>50%</width>
<height>50%</height>
</action>
</keybind>
<keybind key="W-7">
<action name="UnmaximizeFull"/>
<action name="MoveResizeTo">
<x>0</x>
<y>0</y>
<width>50%</width>
<height>50%</height>
</action>
</keybind>
<keybind key="W-9">
<action name="UnmaximizeFull"/>
<action name="MoveResizeTo">
<x>-0</x>
<y>0</y>
<width>50%</width>
<height>50%</height>
</action>
</keybind>
<keybind key="W-6">
<action name="UnmaximizeFull"/>
<action name="MoveResizeTo">
<x>-0</x>
<y>center</y>
<width>50%</width>
<height>50%</height>
</action>
</keybind>
<keybind key="W-3">
<action name="UnmaximizeFull"/>
<action name="MoveResizeTo">
<x>-0</x>
<y>-0</y>
<width>50%</width>
<height>50%</height>
</action>
</keybind>
<keybind key="W-KP_8">
<action name="UnmaximizeFull"/>
<action name="MoveResizeTo">
<x>0</x>
<y>0</y>
<width>100%</width>
<height>50%</height>
</action>
</keybind>
<keybind key="W-KP_5">
<action name="UnmaximizeFull"/>
<action name="MoveResizeTo">
<x>center</x>
<y>center</y>
<width>50%</width>
<height>50%</height>
</action>
</keybind>
<keybind key="W-KP_2">
<action name="UnmaximizeFull"/>
<action name="MoveResizeTo">
<x>0</x>
<y>-0</y>
<width>100%</width>
<height>50%</height>
</action>
</keybind>
<keybind key="W-KP_1">
<action name="UnmaximizeFull"/>
<action name="MoveResizeTo">
<x>0</x>
<y>-0</y>
<width>50%</width>
<height>50%</height>
</action>
</keybind>
<keybind key="W-KP_4">
<action name="UnmaximizeFull"/>
<action name="MoveResizeTo">
<x>0</x>
<y>center</y>
<width>50%</width>
<height>50%</height>
</action>
</keybind>
<keybind key="W-KP_7">
<action name="UnmaximizeFull"/>
<action name="MoveResizeTo">
<x>0</x>
<y>0</y>
<width>50%</width>
<height>50%</height>
</action>
</keybind>
<keybind key="W-KP_9">
<action name="UnmaximizeFull"/>
<action name="MoveResizeTo">
<x>-0</x>
<y>0</y>
<width>50%</width>
<height>50%</height>
</action>
</keybind>
<keybind key="W-KP_6">
<action name="UnmaximizeFull"/>
<action name="MoveResizeTo">
<x>-0</x>
<y>center</y>
<width>50%</width>
<height>50%</height>
</action>
</keybind>
<keybind key="W-KP_3">
<action name="UnmaximizeFull"/>
<action name="MoveResizeTo">
<x>-0</x>
<y>-0</y>
<width>50%</width>
<height>50%</height>
</action>
</keybind>
<!-- Take a screenshot of the current window with gnome-screenshot when Alt+Print are pressed -->
<keybind key="A-Print">
<action name="Execute">
<command>gnome-screenshot -w</command>
</action>
</keybind>
<!-- Keybindings for window switching -->
<keybind key="A-Tab">
<action name="NextWindow">
<dialog>icons</dialog>
<finalactions>
<action name="Focus"/>
<action name="Raise"/>
<action name="Unshade"/>
</finalactions>
</action>
</keybind>
<keybind key="A-S-Tab">
<action name="PreviousWindow">
<dialog>icons</dialog>
<finalactions>
<action name="Focus"/>
<action name="Raise"/>
<action name="Unshade"/>
</finalactions>
</action>
</keybind>
<keybind key="C-A-Tab">
<action name="NextWindow">
<dialog>icons</dialog>
<panels>yes</panels>
<desktop>yes</desktop>
<finalactions>
<action name="Focus"/>
<action name="Raise"/>
<action name="Unshade"/>
</finalactions>
</action>
</keybind>
<keybind key="W-Tab">
<action name="NextWindow">
<dialog>icons</dialog>
<allDesktops>yes</allDesktops>
</action>
</keybind>
<keybind key="W-S-Tab">
<action name="PreviousWindow">
<dialog>icons</dialog>
<allDesktops>yes</allDesktops>
</action>
</keybind>
<!-- Keybindings for window switching with the arrow keys -->
<keybind key="W-S-Right">
<action name="DirectionalCycleWindows">
<direction>right</direction>
</action>
</keybind>
<keybind key="W-S-Left">
<action name="DirectionalCycleWindows">
<direction>left</direction>
</action>
</keybind>
<keybind key="W-S-Up">
<action name="DirectionalCycleWindows">
<direction>up</direction>
</action>
</keybind>
<keybind key="W-S-Down">
<action name="DirectionalCycleWindows">
<direction>down</direction>
</action>
</keybind>
<!-- Keybindings for window decorations -->
<keybind key="W-A-z">
<action name="Decorate">
</action>
</keybind>
<keybind key="W-A-x">
<action name="Undecorate">
</action>
</keybind>
<!-- Keybindings for running applications -->
<keybind key="W-c">
<action name="Execute">
<startupnotify>
<enabled>true</enabled>
<name>Control Center</name>
</startupnotify>
<command>gnome-control-center</command>
</action>
</keybind>
<keybind key="W-S-c">
<action name="Execute">
<startupnotify>
<enabled>true</enabled>
<name>Control Center</name>
</startupnotify>
<command>sudo gnome-control-center</command>
</action>
</keybind>
<keybind key="W-e">
<action name="Execute">
<startupnotify>
<enabled>true</enabled>
<name>Text Editor</name>
</startupnotify>
<command>gedit</command>
</action>
</keybind>
<keybind key="W-f">
<action name="Execute">
<startupnotify>
<enabled>true</enabled>
<name>Files</name>
</startupnotify>
<command>nautilus</command>
</action>
</keybind>
<keybind key="W-m">
<action name="Execute">
<startupnotify>
<enabled>true</enabled>
<name>Music</name>
</startupnotify>
<command>rhythmbox</command>
</action>
</keybind>
<keybind key="W-s">
<action name="Execute">
<startupnotify>
<enabled>true</enabled>
<name>Search</name>
</startupnotify>
<command>gnome-search-tool</command>
</action>
</keybind>
<keybind key="W-t">
<action name="Execute">
<startupnotify>
<enabled>true</enabled>
<name>Terminal</name>
</startupnotify>
<command>gnome-terminal</command>
</action>
</keybind>
<keybind key="W-S-t">
<action name="Execute">
<startupnotify>
<enabled>true</enabled>
<name>Root Terminal</name>
</startupnotify>
<command>sudo gnome-terminal</command>
</action>
</keybind>
<keybind key="W-v">
<action name="Execute">
<startupnotify>
<enabled>true</enabled>
<name>Video</name>
</startupnotify>
<command>totem</command>
</action>
</keybind>
<keybind key="W-w">
<action name="Execute">
<startupnotify>
<enabled>true</enabled>
<name>Web</name>
</startupnotify>
<command>google-chrome</command>
</action>
</keybind>
<keybind key="S-W-w">
<action name="Execute">
<startupnotify>
<enabled>true</enabled>
<name>Web</name>
</startupnotify>
<command>optirun google-chrome</command>
</action>
</keybind>
<keybind key="C-S-x">
<action name="Execute">
<startupnotify>
<enabled>true</enabled>
<name>Kill</name>
</startupnotify>
<command>xkill</command>
</action>
</keybind>
<!-- Launch gnome-screenshot when Print is pressed -->
<keybind key="Print">
<action name="Execute">
<command>gnome-screenshot</command>
</action>
</keybind>
</keyboard>
<mouse>
<dragThreshold>10</dragThreshold>
<!-- number of pixels the mouse must move before a drag begins -->
<doubleClickTime>200</doubleClickTime>
<!-- in milliseconds (1000 = 1 second) -->
<screenEdgeWarpTime>0</screenEdgeWarpTime>
<!-- Time before changing desktops when the pointer touches the edge of the
screen while moving a window, in milliseconds (1000 = 1 second).
Set this to 0 to disable warping -->
<screenEdgeWarpMouse>false</screenEdgeWarpMouse>
<!-- Set this to TRUE to move the mouse pointer across the desktop when
switching due to hitting the edge of the screen -->
<context name="Frame">
<mousebind button="A-Left" action="Press">
<action name="Focus"/>
<action name="Raise"/>
</mousebind>
<mousebind button="A-Left" action="Click">
<action name="Unshade"/>
</mousebind>
<mousebind button="A-Left" action="Drag">
<action name="Move"/>
</mousebind>
<mousebind button="A-Right" action="Press">
<action name="Focus"/>
<action name="Raise"/>
<action name="Unshade"/>
</mousebind>
<mousebind button="A-Right" action="Drag">
<action name="Resize"/>
</mousebind>
<mousebind button="A-Middle" action="Press">
<action name="Lower"/>
<action name="FocusToBottom"/>
<action name="Unfocus"/>
</mousebind>
<mousebind button="A-Up" action="Click">
<action name="GoToDesktop">
<to>previous</to>
</action>
</mousebind>
<mousebind button="A-Down" action="Click">
<action name="GoToDesktop">
<to>next</to>
</action>
</mousebind>
<mousebind button="C-A-Up" action="Click">
<action name="GoToDesktop">
<to>previous</to>
</action>
</mousebind>
<mousebind button="C-A-Down" action="Click">
<action name="GoToDesktop">
<to>next</to>
</action>
</mousebind>
<mousebind button="A-S-Up" action="Click">
<action name="SendToDesktop">
<to>previous</to>
</action>
</mousebind>
<mousebind button="A-S-Down" action="Click">
<action name="SendToDesktop">
<to>next</to>
</action>
</mousebind>
</context>
<context name="Titlebar">
<mousebind button="Left" action="Drag">
<action name="if">
<maximized>true</maximized>
<then>
<action name="UnmaximizeFull"/>
<action name="Move"/>
<edge>top</edge>
</then>
</action>
</mousebind>
<mousebind button="Left" action="Drag">
<action name="Move"/>
</mousebind>
<mousebind button="Left" action="DoubleClick">
<action name="ToggleMaximizeFull"/>
</mousebind>
<mousebind button="Up" action="Click">
<action name="if">
<shaded>no</shaded>
<then>
<action name="Shade"/>
<action name="FocusToBottom"/>
<action name="Unfocus"/>
<action name="Lower"/>
</then>
</action>
</mousebind>
<mousebind button="Down" action="Click">
<action name="if">
<shaded>yes</shaded>
<then>
<action name="Unshade"/>
<action name="Raise"/>
</then>
</action>
</mousebind>
</context>
<context name="Titlebar Top Right Bottom Left TLCorner TRCorner BRCorner BLCorner">
<mousebind button="Left" action="Press">
<action name="Focus"/>
<action name="Raise"/>
<action name="Unshade"/>
</mousebind>
<mousebind button="Middle" action="Press">
<action name="Lower"/>
<action name="FocusToBottom"/>
<action name="Unfocus"/>
</mousebind>
<mousebind button="Right" action="Press">
<action name="Focus"/>
<action name="Raise"/>
<action name="ShowMenu">
<menu>client-menu</menu>
</action>
</mousebind>
</context>
<context name="Top">
<mousebind button="Left" action="Drag">
<action name="Resize">
<edge>top</edge>
</action>
</mousebind>
</context>
<context name="Left">
<mousebind button="Left" action="Drag">
<action name="Resize">
<edge>left</edge>
</action>
</mousebind>
</context>
<context name="Right">
<mousebind button="Left" action="Drag">
<action name="Resize">
<edge>right</edge>
</action>
</mousebind>
</context>
<context name="Bottom">
<mousebind button="Left" action="Drag">
<action name="Resize">
<edge>bottom</edge>
</action>
</mousebind>
<mousebind button="Right" action="Press">
<action name="Focus"/>
<action name="Raise"/>
<action name="ShowMenu">
<menu>client-menu</menu>
</action>
</mousebind>
</context>
<context name="TRCorner BRCorner TLCorner BLCorner">
<mousebind button="Left" action="Press">
<action name="Focus"/>
<action name="Raise"/>
<action name="Unshade"/>
</mousebind>
<mousebind button="Left" action="Drag">
<action name="Resize"/>
</mousebind>
</context>
<context name="Client">
<mousebind button="Left" action="Press">
<action name="Focus"/>
<action name="Raise"/>
</mousebind>
<mousebind button="Middle" action="Press">
<action name="Focus"/>
<action name="Raise"/>
</mousebind>
<mousebind button="Right" action="Press">
<action name="Focus"/>
<action name="Raise"/>
</mousebind>
</context>
<context name="Icon">
<mousebind button="Left" action="Press">
<action name="Focus"/>
<action name="Raise"/>
<action name="Unshade"/>
<action name="ShowMenu">
<menu>client-menu</menu>
</action>
</mousebind>
<mousebind button="Right" action="Press">
<action name="Focus"/>
<action name="Raise"/>
<action name="ShowMenu">
<menu>client-menu</menu>
</action>
</mousebind>
</context>
<context name="AllDesktops">
<mousebind button="Left" action="Press">
<action name="Focus"/>
<action name="Raise"/>
<action name="Unshade"/>
</mousebind>
<mousebind button="Left" action="Click">
<action name="ToggleOmnipresent"/>
</mousebind>
</context>
<context name="Shade">
<mousebind button="Left" action="Press">
<action name="Focus"/>
<action name="Raise"/>
</mousebind>
<mousebind button="Left" action="Click">
<action name="ToggleShade"/>
</mousebind>
</context>
<context name="Iconify">
<mousebind button="Left" action="Press">
<action name="Focus"/>
<action name="Raise"/>
</mousebind>
<mousebind button="Left" action="Click">
<action name="Iconify"/>
</mousebind>
</context>
<context name="Maximize">
<mousebind button="Left" action="Press">
<action name="Focus"/>
<action name="Raise"/>
<action name="Unshade"/>
</mousebind>
<mousebind button="Middle" action="Press">
<action name="Focus"/>
<action name="Raise"/>
<action name="Unshade"/>
</mousebind>
<mousebind button="Right" action="Press">
<action name="Focus"/>
<action name="Raise"/>
<action name="Unshade"/>
</mousebind>
<mousebind button="Left" action="Click">
<action name="ToggleMaximize"/>
</mousebind>
<mousebind button="Middle" action="Click">
<action name="ToggleMaximize">
<direction>vertical</direction>
</action>
</mousebind>
<mousebind button="Right" action="Click">
<action name="ToggleMaximize">
<direction>horizontal</direction>
</action>
</mousebind>
</context>
<context name="Close">
<mousebind button="Left" action="Press">
<action name="Focus"/>
<action name="Raise"/>
<action name="Unshade"/>
</mousebind>
<mousebind button="Left" action="Click">
<action name="Close"/>
</mousebind>
</context>
<context name="Desktop">
<mousebind button="Up" action="Click">
<action name="GoToDesktop">
<to>previous</to>
</action>
</mousebind>
<mousebind button="Down" action="Click">
<action name="GoToDesktop">
<to>next</to>
</action>
</mousebind>
<mousebind button="A-Up" action="Click">
<action name="GoToDesktop">
<to>previous</to>
</action>
</mousebind>
<mousebind button="A-Down" action="Click">
<action name="GoToDesktop">
<to>next</to>
</action>
</mousebind>
<mousebind button="C-A-Up" action="Click">
<action name="GoToDesktop">
<to>previous</to>
</action>
</mousebind>
<mousebind button="C-A-Down" action="Click">
<action name="GoToDesktop">
<to>next</to>
</action>
</mousebind>
<mousebind button="Left" action="Press">
<action name="Focus"/>
<action name="Raise"/>
</mousebind>
<mousebind button="Right" action="Press">
<action name="Focus"/>
<action name="Raise"/>
</mousebind>
</context>
<context name="Root">
<!-- Menus -->
<mousebind button="Middle" action="Press">
<action name="ShowMenu">
<menu>client-list-combined-menu</menu>
</action>
</mousebind>
<mousebind button="Right" action="Press">
<action name="ShowMenu">
<menu>root-menu</menu>
</action>
</mousebind>
</context>
<context name="MoveResize">
<mousebind button="Up" action="Click">
<action name="GoToDesktop">
<to>previous</to>
</action>
</mousebind>
<mousebind button="Down" action="Click">
<action name="GoToDesktop">
<to>next</to>
</action>
</mousebind>
<mousebind button="A-Up" action="Click">
<action name="GoToDesktop">
<to>previous</to>
</action>
</mousebind>
<mousebind button="A-Down" action="Click">
<action name="GoToDesktop">
<to>next</to>
</action>
</mousebind>
</context>
</mouse>
<menu>
<!-- You can specify more than one menu file in here and they are all loaded,
just don't make menu ids clash or, well, it'll be kind of pointless -->
<!-- default menu file (or custom one in $HOME/.config/openbox/) -->
<!-- system menu files on Debian systems -->
<file>/var/lib/openbox/debian-menu.xml</file>
<file>menu.xml</file>
<hideDelay>200</hideDelay>
<!-- if a press-release lasts longer than this setting (in milliseconds), the
menu is hidden again -->
<middle>no</middle>
<!-- center submenus vertically about the parent entry -->
<submenuShowDelay>100</submenuShowDelay>
<!-- time to delay before showing a submenu after hovering over the parent
entry.
if this is a negative value, then the delay is infinite and the
submenu will not be shown until it is clicked on -->
<submenuHideDelay>400</submenuHideDelay>
<!-- time to delay before hiding a submenu when selecting another
entry in parent menu
if this is a negative value, then the delay is infinite and the
submenu will not be hidden until a different submenu is opened -->
<applicationIcons>yes</applicationIcons>
<!-- controls if icons appear in the client-list-(combined-)menu -->
<manageDesktops>yes</manageDesktops>
<!-- show the manage desktops section in the client-list-(combined-)menu -->
</menu>
<applications>
<!--
# this is an example with comments through out. use these to make your
# own rules, but without the comments of course.
# you may use one or more of the name/class/role/title/type rules to specify
# windows to match

<application name="the window's _OB_APP_NAME property (see obxprop)"
class="the window's _OB_APP_CLASS property (see obxprop)"
role="the window's _OB_APP_ROLE property (see obxprop)"
title="the window's _OB_APP_TITLE property (see obxprop)"
type="the window's _OB_APP_TYPE property (see obxprob)..
(if unspecified, then it is 'dialog' for child windows)">
# you may set only one of name/class/role/title/type, or you may use more
# than one together to restrict your matches.

# the name, class, role, and title use simple wildcard matching such as those
# used by a shell. you can use * to match any characters and ? to match
# any single character.

# the type is one of: normal, dialog, splash, utility, menu, toolbar, dock,
#or desktop

# when multiple rules match a window, they will all be applied, in the
# order that they appear in this list


# each rule element can be left out or set to 'default' to specify to not 
# change that attribute of the window

<decor>yes</decor>
# enable or disable window decorations

<shade>no</shade>
# make the window shaded when it appears, or not

<position force="no">
# the position is only used if both an x and y coordinate are provided
# (and not set to 'default')
# when force is "yes", then the window will be placed here even if it
# says you want it placed elsewhere.this is to override buggy
# applications who refuse to behave
<x>center</x>
# a number like 50, or 'center' to center on screen. use a negative number
# to start from the right (or bottom for <y>), ie -50 is 50 pixels from the
# right edge (or bottom).
<y>200</y>
<monitor>1</monitor>
# specifies the monitor in a xinerama setup.
# 1 is the first head, or 'mouse' for wherever the mouse is
</position>

<focus>yes</focus>
# if the window should try be given focus when it appears. if this is set
# to yes it doesn't guarantee the window will be given focus. some
# restrictions may apply, but Openbox will try to

<desktop>1</desktop>
# 1 is the first desktop, 'all' for all desktops

<layer>normal</layer>
# 'above', 'normal', or 'below'

<iconic>no</iconic>
# make the window iconified when it appears, or not

<skip_pager>no</skip_pager>
# asks to not be shown in pagers

<skip_taskbar>no</skip_taskbar>
# asks to not be shown in taskbars. window cycling actions will also
# skip past such windows

<fullscreen>yes</fullscreen>
# make the window in fullscreen mode when it appears

<maximized>true</maximized>
# 'Horizontal', 'Vertical' or boolean (yes/no)
</application>

# end of the example
-->
</applications>
</openbox_config>
FILE
