#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com - Copyright 2014

# openbox icons #

black= red= green= yellow= blue= magenta= cyan= white= reset=

if [[ -t 1 ]]
then
	black=$(tput setaf 0)
	red=$(tput setaf 1)
	green=$(tput setaf 2)
	yellow=$(tput setaf 3)
	blue=$(tput setaf 4)
	magenta=$(tput setaf 5)
	cyan=$(tput setaf 6)
	white=$(tput setaf 7)
	reset=
$(tput sgr0);
fi

version="22"

icons_directory="/usr/share/icons/"
actions_directory="/usr/share/icons/Faenza/actions/scalable"
applications_directory="/usr/share/icons/Faenza/apps/scalable"
categories_directory="/usr/share/icons/Faenza/categories/scalable"
devices_directory="/usr/share/icons/Faenza/devices/scalable"
emblems_directory="/usr/share/icons/Faenza/emblems/scalable"
mimetypes_directory="/usr/share/icons/Faenza/mimetypes/scalable"
places_directory="/usr/share/icons/Faenza/places/scalable"
status_directory="/usr/share/icons/Faenza/status/scalable"
stock_directory="/usr/share/icons/Faenza/sock/scalable"
theme_directory="/usr/share/icons/Faenza"
pixmaps_directory="/usr/share/pixmaps"
shell_directory="/usr/share/gnome-shell/theme"

echo "${cyan}Customizing (icons)...${reset}"

# openbox #

ln -s -f "$applications_directory"/gnome-display-properties.svg /usr/share/obconf/video-display.png
ln -s -f "$applications_directory"/menu-editor.svg /usr/share/obmenu/mnu16.png
ln -s -f "$applications_directory"/menu-editor.svg /usr/share/obmenu/mnu48.png

# icon cache update #

echo "${cyan}Forcing icon cache update (gtk-update-icon-cache)...${reset}"

find /usr/share/icons -mindepth 1 -maxdepth 1 -type d | while read -r theme
do
	if [ -f "$theme/index.theme" ]
	then
		gtk-update-icon-cache -f -q "$theme"
	fi
done
