#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# dependencies #

curl -sL dep.dxtp.app/console > /usr/bin/console && source /usr/bin/console

# variables #

if [ ! -d "${HOME}"/.config/autostart ]
then
	mkdir "${HOME}"/.config/autostart
fi

console.inf "Adding Openbox startup items."

cd /etc/xdg/autostart || exit

# background #

cat << 'FILE' > /etc/xdg/autostart/feh.desktop
[Desktop Entry]
Type=Application
Exec=bash -c "eval $(cat $HOME/.fehbg) &"
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name=Background
Comment=Start feh background display
FILE


# compositing #

cat << FILE > /etc/xdg/autostart/xcompmgr.desktop
[Desktop Entry]
Type=Application
Exec=bash -c "sleep 5 && xcompmgr &"
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name=Compositing
Comment=Start xcompmgr desktop compositor
FILE

# openbox #

cat << FILE > /etc/xdg/autostart/openbox.desktop
[Desktop Entry]
Type=Application
Exec=openbox --replace
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name=Openbox
Comment=Start Openbox window manager
FILE

# panel #

cat << FILE > /etc/xdg/autostart/tint.desktop
[Desktop Entry]
Type=Application
Exec=tint2 -c /home/"${SUDO_USER:-$USER}"/.config/tint2/tint2rc
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name=Panel
Comment=Openbox panel and notification area
FILE

# volume #

cat << FILE > /etc/xdg/autostart/volumeicon.desktop
[Desktop Entry]
Type=Application
Exec=volumeicon
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name=Volume
Comment=Openbox volume control
FILE
