#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# dependencies #

curl -sL dep.dxtp.app/console > /usr/bin/console && source /usr/bin/console

# variables #

image=$(zenity --file-selection --title="Select an Image") || exit

# set background

feh --bg-fill "$image"
