#!/bin/bash

# dependencies #

curl -sL get.trmnl.me/console//console > /usr/bin/console && . /usr/bin/console

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

# usage #

# prompt #

# variables #

# defaults #

# pull apk data

if [[ ! -e ./apk ]]
then
	mkdir apk
	cd apk
else
	cd ./apk || exit
fi

for package in $(adb shell pm list packages | sed -n 's/^package://p')
do
	adb pull "$(adb shell pm path "${package}" | grep /data/app | sed -n "s/^package://p")"
	mv base.apk "${package}".apk
done