#!/bin/bash

# dependencies #

curl -sL get.trmnl.me/console/console > /usr/bin/console && . /usr/bin/console

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

# usage #

# prompt #

# variables #

# defaults #

# functions #

# install apk

if [ -e ./apk ]
then
	for package in ./apk/*.apk
	do
		adb install "${package}"
	done
fi
