#!/bin/bash

# dependencies #

curl -sL get.trmnl.me/console//console > /usr/bin/console && . /usr/bin/console

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

# usage #

# prompt #

# variables #

parse=$(cat "${directory}"/adb_usb.ini)

# defaults #

# functions #

# write vendors list

console.directory ${HOME}"/.android

for i in {0..65535}
do
	printf '0x%04x\n' "$i"
done >> "{HOME}"/.android/adb_usb.ini

chmod -R 777 ${HOME}"/.android

# udev #

if [ -d /etc/udev ]
then
	while read -r vendor_id
	do
		echo SUBSYSTEM=='"usb"', SYSFS{idVendor}=="\"${vendor_id:2}\"", MODE='"0666"';
	done <<< "${parse}" >> /etc/udev/rules.d/51-android.rules
fi
