#!/bin/bash

# dependencies #

curl -sL get.trmnl.me/console//console > /usr/bin/console && . /usr/bin/console

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

# usage #

# prompt #

# variables #

# write settings

commands_list+=(
	system hw_hide_font_style false
	global policy_control immersive.navigation=com.sec.android.app.desktoplauncher
	)

for command in ${commands_list[@]}
do
	sudo adb shell settings put "${command}"
done