#!/bin/bash

# dependencies #

curl -sL get.trmnl.me/console/console > /usr/bin/console && . /usr/bin/console

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="12-24-2021"

# usage #

# prompt #

console.script "Setting up ${script#*-}"
echo

# variables #

# link configuration

console.inf "Linking configuration."
echo

if [ -f /media/internal/Lego/leocad/leocad.conf ]
then
	mkdir -p "$ROOT_DIRECTORY"/home/"${USER}"/.config/"LeoCAD Software"

	ln -s -f																	\
	/media/internal/Lego/leocad/leocad.conf										\
	"$ROOT_DIRECTORY"/home/"${USER}"/.config/"LeoCAD Software"/LeoCAD.conf
fi