#!/bin/bash

# dependencies #

curl -sL get.trmnl.me/console/console > /usr/bin/console && . /usr/bin/console

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="12-24-2021"

# usage #

# prompt #

console.script "Setting up ${script#*-}"
echo

# variables #

application="leocad"
architecture="arm64"

archive=$(curl -sL https://api.github.com/repos/leozide/leocad/releases/latest | grep -o [aA0-zZ9-]*${architecture}.zip | head -n 1)

archive_url="https://github.com/leozide/leocad/releases/download/continuous/${archive}"

extract_command=$(unzip -qq -d /usr/bin -o ./*.zip)

# clean #

rm -rf "${TMPDIR}"/${archive}

# get #

cd "${TMPDIR}" || exit 1

console.dwl "Downloading ${application}..."
echo

curl						\
	--silent				\
	--location				\
	--remote-header-name	\
	--remote-name			\
							"${archive_url}"

# extract #

console.fwd "Extracting..."
echo

console.silence "${extract_command}"