#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/dextop

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# configuration #

# link configuration

console.inf "Linking configuration."
echo

if [ -f /media/internal/Lego/leocad/leocad.conf ]
then
	mkdir -p "$ROOT_DIRECTORY"/home/"${USER}"/.config/"LeoCAD Software"

	ln -s -f																	\
	/media/internal/Lego/leocad/leocad.conf										\
	"$ROOT_DIRECTORY"/home/"${USER}"/.config/"LeoCAD Software"/LeoCAD.conf
fi