#!/bin/bash

# dependencies #

curl -sL get.trmnl.me/console/console > /usr/bin/console && . /usr/bin/console

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="12-24-2021"

# usage #

# prompt #

console.script "Setting up ${script#*-}"
echo

# variables #

scripts_list=(
	leocad-build
)

# run scripts

for script in ${scripts_list[@]}
do
	bash ${script}
done

# update binary

cp /usr/bin/leocad ./leocad

# upload changes

git add *

git commit -a -m "Build update"

git push