#!/bin/bash

# dependencies #

curl -sL get.trmnl.me/console//console > /usr/bin/console && . /usr/bin/console

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

# usage #

# prompt #

# variables #

TEMPORARY=$(mktemp -d -t TEMPORARY.XXXXXX) || exit 1

trap 'rm -f "${TEMPORARY}"' EXIT

build_directory="${TEMPORARY}"

application="leocad"
source="https://github.com/leozide/leocad.git"

[[ $(id -u -n) = "root" ]] && home=/home/"${SUDO_USER:-$USER}" || home=/home/"${USER}"

# defaults #

# packages #

install_list=(
	git
	hub
	g++
	make
	zip
	zlib1g-dev
	libqt5concurrent5
	libqt5opengl5
	libqt5opengl5-dev
	libqt5printsupport5
	libqt5xml5
	qt5-default
	qtbase5-dev
	qttools5-dev
	qttools5-dev-tools
)

# install #

console.install ${install_list[@]}

# build #

git clone "${source}" "${build_directory}"

cd "${build_directory}" || exit 1

# compile project

qmake "${application}".pro

# compile binary

make -j$(nproc)

# update binary

cp "${build_directory}"/build/release/"${application}" /usr/bin/"${application}"

# launcher #

cat <<- 'FILE' > /usr/share/applications/leocad.desktop
[Desktop Entry]
Encoding=UTF-8
Name=LeoCAD
GenericName=LDraw Model Editor
Comment=LDraw Model Editor
Exec=/usr/bin/leocad
Icon=leocad
Terminal=false
Type=Application
MimeType=application/x-ldraw;application/x-multipart-ldraw;
Categories=Graphics;2DGraphics;3DGraphics;Editor;
FILE