#!/bin/bash

# dependencies #

curl -sL get.trmnl.me/frobulate.console > /usr/bin/console && . /usr/bin/console

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="12-24-2021"

# usage #

# prompt #

frobulate.script "Setting up ${script#*-}"
echo

# variables #

TEMPORARY=$(mktemp -d -t TEMPORARY.XXXXXX) || exit 1

trap 'rm -rf "${TEMPORARY}"' EXIT

download_directory="${TEMPORARY}"

application="leocad"
architecture="arm64"

archive=$(curl -s -L https://api.github.com/repos/leozide/leocad/releases/latest | grep -o [aA0-zZ9-]*${architecture}.zip | head -n 1)

archive_url="https://github.com/leozide/leocad/releases/download/continuous/${archive}"

extract_command=$(unzip -qq -d /usr/bin -o ./*.zip)

# defaults #

# packages #

install_list=(
	curl
	zip
	unzip
)

# install #

frobulate.install ${install_list[@]}

# get #

cd "${download_directory}" || exit 1

frobulate.dwl "Downloading" "[ ${application} ]"
echo

	curl						\
		--silent				\
		--location				\
		--remote-header-name	\
		--remote-name			\
								"${archive_url}"

# extract #

frobulate.silence "${extract_command}" &

frobulate.progress "Extracting..."

frobulate.scs "Done."
